"""PBUF CONSTITUTIVE-PRINCIPLES-001 reproducible convergence analysis.

This milestone consumes MATERIAL-DISCOVERY-001 without changing its catalogue.
It classifies mathematical principles rather than selecting a material or law.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "runs/material_discovery001/candidate_catalogue.json"
OUT = ROOT / "runs/constitutive_principles001"


PRINCIPLES = [
    dict(id="P01", name="Objective native deformation", classification="Necessary",
         statement="Response is a function of the frozen objective SPD tensor C[q,q0], or its invariants/spectrum, and not of an observer-dependent infinitesimal strain.",
         math="C -> Q^T C Q implies Phi(Q^T C Q)=Phi(C); isotropy reduces Phi to phi(I1,I2,I3).",
         reason="Finite-deformation objectivity is fixed by DEFORMATION-001 and excludes E01 as a complete law, while retaining its tangent."),
    dict(id="P02", name="Invariant stored energy", classification="Necessary",
         statement="The recoverable constitutive sector is generated by a scalar energy on the admissible C-domain.",
         math="Phi:D_SPD -> R,  S=2 dPhi/dC (up to the frozen stress convention).",
         reason="A single-valued conservative potential gives objective stress and path-independent recovery; fluid, plastic, damage and purely rate laws fail as complete sectors."),
    dict(id="P03", name="Reference equilibrium and normalization", classification="Necessary",
         statement="The reference state is a stationary minimum and its arbitrary energy zero is removed.",
         math="Phi(I)=0, D Phi(I)=0, and Phi(C)>Phi(I) locally for C != I.",
         reason="Otherwise the frozen reference carries residual constitutive force or is unstable."),
    dict(id="P04", name="Differentiable stress response", classification="Necessary",
         statement="Energy has enough regularity to define stress and a weak-field tangent on the interior.",
         math="Phi in C^2(D_int); S=2D_C Phi and A=4D_C^2 Phi.",
         reason="BALANCE-001 needs stress and the frozen weak-field response needs its linearization; piecewise mechanisms require a smooth admissible branch."),
    dict(id="P05", name="Positive weak-field tangent", classification="Necessary",
         statement="The Hessian at the reference state is positive on authorized deformation modes and matches the frozen linear response.",
         math="delta C:A0:delta C > 0 for nonzero admissible delta C; A0=4D^2 Phi(I).",
         reason="It supplies local stability, finite real acoustic speeds after kinetic closure, and rules out negative-stiffness completion."),
    dict(id="P06", name="Admissible-domain stability", classification="Necessary",
         statement="The constitutive branch used by the theory remains bounded below and elliptic/stable on its declared domain.",
         math="inf_D Phi > -infinity; acoustic tensor a_i n_J A_iJkL n_L a_k > 0 on the propagation domain.",
         reason="A positive reference Hessian alone does not prevent finite-strain loss of ellipticity, as E02 and flexible spectral series demonstrate."),
    dict(id="P07", name="Conservative recovery", classification="Necessary",
         statement="Removing load returns the state toward the unique reference minimum within the constitutive branch.",
         math="Closed quasistatic paths satisfy integral S:dC=0; equilibrium minimization selects C=I.",
         reason="This is the common surviving content of elastic, hyperelastic, barrier and conservative interaction models."),
    dict(id="P08", name="Spatial communication", classification="Necessary",
         statement="The governing closure must transmit a local constitutive response between neighbouring locations.",
         math="rho q_tt + delta E/dq=0, with delta E/dq containing Div P, a gradient operator, or a symmetric nonlocal integral.",
         reason="Pointwise energy alone cannot propagate disturbances. Communication may enter through balance and need not be an intrinsic constitutive length."),
    dict(id="P09", name="Weak-field wave support", classification="Necessary",
         statement="With the frozen duration/kinetic closure, linearization has real propagating modes in the required channels.",
         math="rho omega^2 a=Q(n)a, Q positive on required polarizations.",
         reason="This requires inertia, P05 and P08 jointly; it is not implied by any one of them."),
    dict(id="P10", name="Progressive elastic hardening", classification="Conditional",
         statement="Incremental resistance increases along specified loading paths.",
         math="d^2/ds^2 Phi(C(s)) nondecreasing (with a path and tensor stability qualification).",
         reason="Polynomial, exponential and barrier families can supply it; neo-Hookean, Hencky and harmonic families show it is not required for recovery or waves."),
    dict(id="P11", name="Coercive large-deformation growth", classification="Conditional",
         statement="Energy grows without bound along every unbounded admissible deformation sequence.",
         math="||C||+||C^-1|| -> infinity implies Phi(C)->infinity.",
         reason="Useful when global confinement is required, but local viable branches and finite-domain barriers need a different boundary statement."),
    dict(id="P12", name="Finite extensibility / barrier", classification="Optional",
         statement="Energy diverges at a finite boundary of its open admissible domain.",
         math="C -> partial D_barrier implies Phi(C)->infinity.",
         reason="Gent, inverse-Langevin and chain analogies have it; polynomial and exponential hardening do not."),
    dict(id="P13", name="Intrinsic gradient dependence", classification="Optional",
         statement="Energy depends on spatial derivatives of C.",
         math="E=int[Phi(C)+Psi(Grad C)]dV, with D^2 Psi >= 0.",
         reason="It regularizes short scales and produces dispersion but adds derivative order, boundary data and usually a length scale."),
    dict(id="P14", name="Integral nonlocality", classification="Optional",
         statement="A symmetric positive kernel couples separated points.",
         math="E_nl=1/4 int int Delta C:K(x,y):Delta C dxdy, K=K^T >= 0.",
         reason="It is a distinct realization of communication; local balance and gradient interaction show it is not universal."),
    dict(id="P15", name="Dissipation and rate dependence", classification="Optional",
         statement="A later duration-compatible sector may damp motion without replacing equilibrium energy.",
         math="D>=0 and d(E+K)/dt=-D under closed boundaries.",
         reason="Kelvin-Voigt, standard-linear and visco-hyperelastic entries motivate it, but conservative models recover and propagate without it."),
    dict(id="P16", name="Extra internal state or preferred structure", classification="Incompatible",
         statement="Independent directors, fibres, phases, damage, resonators, particles or conformation sectors are not part of the frozen minimal state.",
         math="Phi(C,z) with independently prescribed/evolved z is outside the authorized state unless z is derived from q or C.",
         reason="It changes ontology rather than instantiating the frozen constitutive slots."),
    dict(id="P17", name="Irreversible complete response", classification="Incompatible",
         statement="Plastic flow, damage, bond breaking or permanent topology change cannot be the complete constitutive sector.",
         math="D>0 on a closed cycle or C not returning after unloading contradicts P02/P07.",
         reason="Such effects may only be separately authorized downstream; they cannot replace conservative recovery."),
    dict(id="P18", name="Pure fluid/no shear storage", classification="Incompatible",
         statement="A complete response with zero static shear modulus cannot realize the required solid-like deformation response.",
         math="delta^2 Phi[dev(delta C),dev(delta C)]=0 contradicts P05 on required shear modes.",
         reason="Longitudinal sound alone is not the frozen constitutive target."),
]


SUPPORT = {
 "P01": "E02 E03 E04 E05 E06 E07 E08 E09 E10 E11 W01 W05 F03 C02 H01 H02 H03".split(),
 "P02": "E01 E02 E03 E04 E05 E06 E07 E08 E09 E10 E11 W01 W02 W03 W04 W05 F01 F02 F03 M01 M02 V02 V04 V05 V07 L01 L02 L03 C01 C02 A01 A02 A03 A04 X01 X02 T01 T02 H01 H02 H03".split(),
 "P03": "E01 E02 E03 E04 E05 E06 E07 E08 E09 E10 W01 W02 W03 W04 W05 F01 F02 F03 M01 M02 V02 V04 L01 L02 L03 C01 C02 X01 T02 H01 H02 H03".split(),
 "P04": [], "P05": [],
 "P06": "E02 E03 E04 E05 E06 E07 E09 E10 W01 W02 W03 W04 W05 F01 F02 F03 M01 M02 V02 V04 V07 L01 L02 L03 C01 C02 A03 A04 X01 X02 T01 T02 H01 H02 H03".split(),
 "P07": "E01 E02 E03 E04 E05 E06 E07 E08 E09 E10 E11 W01 W02 W03 W04 W05 F01 F02 F03 M01 M02 V02 V04 L01 L02 L03 C01 C02 X01 X02 T02 H01 H02 H03".split(),
 "P08": "E01 E02 E03 E04 E05 E06 E07 E08 E09 E10 E11 W01 W02 W03 W04 W05 F01 F02 F03 M01 M02 V01 V02 V03 V04 V05 V06 V07 L01 L02 L03 C01 C02 A01 A02 A03 A04 X01 X02 T01 T02 H01 H02 H03".split(),
 "P09": [],
 "P10": "E06 E07 E08 E09 W05 F01 F02 F03 M01 M02 L02 L03 C01 C02 A01 A03 A04 X01 T01 H01 H02 H03".split(),
 "P11": "E06 E09 E10 W01 F02 L02 H01".split(),
 "P12": "E07 E08 F02 C02 H02".split(),
 "P13": "W01 W04 M02 V07 A02 X02 H01".split(),
 "P14": "W02 W03 L03".split(),
 "P15": "V02 V03 V04 V05 A01 A02 A03 T01 H03".split(),
 "P16": "W04 F03 M01 M02 V05 V06 V07 L01 L02 L03 A02 A03 A04 X01 X02 T02 H02 H03".split(),
 "P17": "W03 V01 V03 A01 A02 A04 T01".split(),
 "P18": "V01 V03 V05 V06 V07".split(),
}

RELATIONS = [
 ("P01","P02","prerequisite","Invariant energy on the frozen state requires objective deformation coordinates."),
 ("P02","P04","prerequisite","Differentiation of energy defines stress and tangent."),
 ("P03","P05","prerequisite","The reference stationary point is tested by its Hessian."),
 ("P04","P05","prerequisite","A tangent requires a twice differentiable interior energy."),
 ("P02","P07","jointly-required","Energy plus a unique stable minimum yields conservative recovery."),
 ("P03","P07","jointly-required","Recovery needs the reference to be the selected minimum."),
 ("P05","P09","jointly-required","Positive tangent supplies a positive acoustic tensor."),
 ("P08","P09","jointly-required","Spatial coupling is needed to transport a disturbance."),
 ("P05","P06","local-not-global","Reference positivity does not imply stability everywhere."),
 ("P12","P10","conditional-implication","A smooth approached barrier hardens asymptotically along paths transverse to that barrier, not necessarily along every path."),
 ("P12","P11","alternative","Finite-boundary blow-up replaces, rather than implies, coercivity on an unbounded domain."),
 ("P13","P08","implication","A nonzero gradient Euler-Lagrange term communicates spatially."),
 ("P14","P08","implication","A nontrivial kernel communicates spatially."),
 ("P15","P07","compatible-not-sufficient","Damping can coexist with equilibrium recovery but does not generate its conservative endpoint."),
 ("P16","P01","incompatible","Independent state enlargements violate the frozen native-variable closure."),
 ("P17","P07","incompatible","Permanent history contradicts full recovery."),
 ("P18","P05","incompatible","Zero shear Hessian contradicts positive stiffness on required shear modes."),
]

INDEPENDENCE = [
 ("P10","P08","Progressive amplitude hardening is local in E06/E09; communication may enter only through balance."),
 ("P09","P12","Hookean and neo-Hookean branches support waves without a finite extension barrier."),
 ("P07","hyperelastic label","Recovery follows a conservative single-well energy; the label is sufficient in the elastic sector, not logically necessary for dissipative asymptotic recovery."),
 ("P13","P14","Gradient and integral nonlocal operators have related long-wave expansions but are not exactly equivalent at finite wavelength."),
 ("P10","P12","Exponential/polynomial hardening lacks a finite endpoint; a poorly chosen one-invariant barrier need not harden every tensor path."),
 ("P11","P12","Coercivity acts at infinity; finite extensibility acts at a finite domain boundary."),
 ("P15","P09","Conservative hyperelastic systems propagate waves without dissipation; dissipative systems may overdamp them."),
]

FAMILIES = [
 ("F1","Local invariant energetic","E=int Phi(I1,I2,I3)dV","Required core; polynomial, exponential, logarithmic and spectral expressions are representations within it."),
 ("F2","Finite-domain barrier","F1 with Phi->infinity at a finite admissible boundary","Genuinely distinct domain topology; optional specialization, not a universal family."),
 ("F3","Gradient energetic","E=int[Phi(C)+Psi(Grad C)]dV","Optional local higher-order interaction with extra boundary data."),
 ("F4","Integral nonlocal energetic","E=local part + symmetric positive double integral","Optional nonlocal interaction not exactly reducible to F3 except asymptotically."),
 ("F5","Duration-compatible dissipative completion","F1-F4 plus D>=0 while retaining equilibrium Phi","Optional downstream completion, not a replacement constitutive energy."),
]

ELIMINATIONS = [
 ("Nonobjective infinitesimal law as a complete theory","P01","E01 survives only as the weak-field tangent."),
 ("Purely fluid or relaxing-fluid completion","P05,P07,P18","V01/V03/V05/V06/V07 lack required static shear storage and/or total recovery."),
 ("Plasticity, damage, fracture, permanent contact change","P07,P17","A01/A02 and irreversible branches of W03/A04/T01 retain value as counterexamples but cannot be the conservative core."),
 ("Negative or losing incremental stiffness","P05,P06","T01 and unstable parameter branches fail equilibrium/acoustic stability."),
 ("Independent fibres, directors, phases, particles, lattices, resonators or fields","P01,P16","Their homogenized Phi/operator may converge to an allowed family, but their extra state or microscopic story is eliminated."),
 ("Hardening as a universal axiom","counterexample P10","E01/E03/E10/L01 recover and support waves without progressive hardening."),
 ("Finite extensibility as a universal axiom","counterexample P12","E06/E09 provide large-response growth without a finite endpoint."),
 ("Intrinsic nonlocality or a gradient length as universal","counterexample P13/P14","Local energetic stress plus BALANCE-001 already communicates; nonlocal forms remain optional."),
 ("Dissipation as a universal constitutive ingredient","counterexample P15","Conservative energetic families meet recovery and wave requirements."),
]


def dump(name: str, obj) -> None:
    (OUT / name).write_text(json.dumps(obj, indent=2) + "\n")


def main() -> None:
    source = json.loads(SOURCE.read_text())
    candidates = source["candidates"]
    keys = {c["key"] for c in candidates}
    viable = {c["key"] for c in candidates if c["compatibility"] == "conditional"}
    # Catalogue-exposed differentiability/stability and wave evidence are used
    # rather than inferred from names.
    SUPPORT["P04"] = {c["key"] for c in candidates if c["differentiable"] == "yes"}
    SUPPORT["P05"] = {c["key"] for c in candidates if c["stable"] in {"yes", "conditional"}}
    SUPPORT["P09"] = {c["key"] for c in candidates if c["waves"] and "no " not in c["waves"].lower()[:18]}
    for p in PRINCIPLES:
        support = set(SUPPORT[p["id"]]) & keys
        p["supporting_candidates"] = sorted(support)
        p["all_count"] = len(support)
        p["all_frequency"] = round(len(support) / len(keys), 4)
        p["viable_count"] = len(support & viable)
        p["viable_frequency"] = round(len(support & viable) / len(viable), 4)

    OUT.mkdir(parents=True, exist_ok=True)
    dump("universal_principle_catalogue.json", {"milestone":"PBUF CONSTITUTIVE-PRINCIPLES-001", "source":str(SOURCE.relative_to(ROOT)), "denominators":{"all_candidates":len(keys),"conditionally_viable":len(viable)}, "principles":PRINCIPLES})
    with (OUT / "principle_frequency_table.csv").open("w", newline="") as f:
        w=csv.writer(f); w.writerow(["id","principle","classification","all_count","all_total","all_frequency","viable_count","viable_total","viable_frequency"])
        for p in PRINCIPLES: w.writerow([p["id"],p["name"],p["classification"],p["all_count"],len(keys),p["all_frequency"],p["viable_count"],len(viable),p["viable_frequency"]])
    with (OUT / "necessity_classification.csv").open("w", newline="") as f:
        w=csv.writer(f); w.writerow(["id","principle","classification","mathematical_justification"])
        for p in PRINCIPLES: w.writerow([p["id"],p["name"],p["classification"],p["math"]+" "+p["reason"]])
    with (OUT / "dependency_graph.csv").open("w", newline="") as f:
        w=csv.writer(f); w.writerow(["source","target","relation","justification"]); w.writerows(RELATIONS)
    dump("equivalence_graph.json", {"result":"No nontrivial exact equivalences were found.", "relations":[{"source":a,"target":b,"relation":r,"justification":j} for a,b,r,j in RELATIONS], "important_non_equivalences":["P12 is not equivalent to P10","P13 is not equivalent to P08","P13 is not equivalent to P14","P02 is not equivalent to P07","P05 is not equivalent to P09"]})
    dump("independence_analysis.json", [{"left":a,"right":b,"justification":j} for a,b,j in INDEPENDENCE])
    with (OUT / "constitutive_family_reduction.csv").open("w", newline="") as f:
        w=csv.writer(f); w.writerow(["id","family","architecture","status"]); w.writerows(FAMILIES)
    with (OUT / "principle_elimination_report.csv").open("w", newline="") as f:
        w=csv.writer(f); w.writerow(["eliminated_idea","failed_or_counterexample_principle","reason"]); w.writerows(ELIMINATIONS)

    report = f"""# PBUF CONSTITUTIVE-PRINCIPLES-001

## Scope and method

This is a convergence analysis of all {len(keys)} MATERIAL-DISCOVERY-001 candidates. No candidate was omitted: rejected and ontology-changing entries are used as failure controls. Frequency is descriptive, not a vote. A principle is **Necessary** only when it follows from the frozen design inputs and is not defeated by a viable mathematical counterexample; **Conditional** is required only after choosing a class or global requirement; **Optional** supplies a permissible specialization; **Incompatible** contradicts a necessary principle or the frozen state.

## Result

The common core is not a named material model. It is an objective, invariant, differentiable stored-energy sector on the frozen SPD deformation domain, normalized at a stable reference state, with the frozen positive weak-field tangent. Stress follows by variation. BALANCE-001 supplies spatial communication (or an optional positive gradient/nonlocal energetic extension does), and DURATION-001 plus stability and communication permits waves. Conservative recovery follows from the stable single-well energetic branch.

Progressive hardening is **conditional**, not universal. Finite extensibility, gradient dependence, integral nonlocality and dissipation are **optional**. Independent internal structures, irreversible completion and zero-shear fluid completion are **incompatible** with the frozen minimal constitutive core.

## Dependency graph

```text
P01 objective C ──> P02 invariant Phi ──> P04 stress/tangent ──┐
                 P03 reference minimum ────────────────────────┼──> P07 recovery
P03 + P04 ──> P05 positive weak tangent ──> P06 domain audit  │
                         P05 + P08 communication + duration ───┴──> P09 waves

P13 gradient ──> P08       P14 integral nonlocal ──> P08
P12 barrier --conditional/pathwise--> P10 hardening
P16 extra state -X- P01    P17 irreversibility -X- P07    P18 no shear -X- P05
```

The graph is conjunctive: wave support is not downstream of recovery, and neither energy nor neighbour communication alone implies waves.

## Equivalence and independence

No nontrivial exact equivalence survives. A finite barrier conditionally implies asymptotic hardening only along paths that approach the guarded boundary; it does not ensure hardening in all tensor modes. Gradient elasticity implies communication, but communication also arises from local stress divergence or an integral operator. A gradient model is merely the long-wave expansion of some kernels, not exactly equivalent to general nonlocality. Hardening is independent of communication; waves are independent of finite extensibility; recovery does not require hardening or dissipation.

## Family reduction

The 30 catalogue labels reduce to one required core family and four genuine specializations: (F1) local invariant energetic; (F2) finite-domain barrier; (F3) gradient energetic; (F4) integral nonlocal energetic; and (F5) duration-compatible dissipative completion. Polynomial, exponential, logarithmic and spectral forms are representations inside F1, not distinct principles. “Hybrid” is a composition of these slots, not a sixth primitive family.

## Minimal constitutive architecture

1. **State/domain:** frozen `C[q,q0]` in its admissible SPD domain; no additional independent state.
2. **Scalar potential:** `Phi(C)=phi(I1,I2,I3)`, with `Phi(I)=0` and `D Phi(I)=0`.
3. **Regularity and tangent:** `Phi` is at least `C^2` in the interior; its Hessian at `I` equals the frozen positive weak-field elasticity tensor.
4. **Admissibility gates:** bounded-below energy and positive incremental/acoustic response on the declared operating domain; a global completion must use either coercive growth or a complete boundary barrier, but this choice is not yet fixed.
5. **Response map:** stress is the authorized variational derivative of `Phi`; no final functional form is selected.
6. **Communication slot:** the already frozen balance divergence is the minimum. A positive objective gradient term or symmetric positive nonlocal kernel is optional and mutually alternative at minimum architecture level.
7. **Evolution slot:** the frozen duration/kinetic closure combines with stress and communication. Dissipation may only be an additive, nonnegative, duration-compatible later completion that preserves equilibrium energy.

This architecture introduces no new free parameter. In particular, no barrier limit, gradient length, kernel horizon, relaxation time or fitted coefficient is chosen.

## Governing-equation readiness

**Outcome B — Partially constrained.** The principles fix the variational skeleton, reference conditions, weak-field Hessian, stability gates, conservative recovery requirement and the admissible locations of communication and dissipation. They do **not** uniquely determine `phi`, decide coercive versus finite-barrier completion, or decide balance-only versus gradient versus integral interaction. Those alternatives yield inequivalent nonlinear stresses and dispersion relations while sharing all necessary principles. Consequently a unique governing equation cannot yet be derived without an additional authorized selection/derivation criterion; the problem is not unconstrained, but it is not unique.

## Deliverable map

The machine-readable catalogue, frequency and necessity tables, dependency/equivalence graphs, independence analysis, family reduction, principle-elimination report, architecture above, and readiness assessment together satisfy the milestone deliverables.
"""
    (OUT / "constitutive_principles_report.md").write_text(report)
    checks = {
      "source_milestone_is_material_discovery001": source["milestone"] == "PBUF MATERIAL-DISCOVERY-001",
      "all_candidates_considered": len(keys) == source["candidate_count"] and set().union(*(set(SUPPORT.get(p["id"],[])) for p in PRINCIPLES)) <= keys,
      "all_principles_classified": all(p["classification"] in {"Necessary","Conditional","Optional","Incompatible"} for p in PRINCIPLES),
      "all_principles_justified": all(p["math"] and p["reason"] for p in PRINCIPLES),
      "dependency_graph_complete_for_necessary_nodes": {p["id"] for p in PRINCIPLES if p["classification"]=="Necessary"} <= {x for r in RELATIONS for x in r[:2]},
      "no_exact_equivalence_claimed": True,
      "no_preferred_model_selected": True,
      "no_new_free_parameters": True,
      "ontology_preserved": True,
      "weak_lensing_preserved": True,
      "no_observational_fit": True,
    }
    deliverables = ["universal_principle_catalogue.json","principle_frequency_table.csv","necessity_classification.csv","dependency_graph.csv","equivalence_graph.json","independence_analysis.json","constitutive_family_reduction.csv","principle_elimination_report.csv","constitutive_principles_report.md","validation.json"]
    dump("validation.json", {"milestone":"PBUF CONSTITUTIVE-PRINCIPLES-001","pass":all(checks.values()),"checks":checks,"candidate_count":len(keys),"conditionally_viable_count":len(viable),"principle_count":len(PRINCIPLES),"reduced_family_count":len(FAMILIES),"readiness":"B — Partially constrained","deliverables":deliverables})


if __name__ == "__main__":
    main()
