#!/usr/bin/env python3
"""Dev154 read-only reconstruction of the implemented native working system."""
from __future__ import annotations
import hashlib,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]; sys.path.insert(0,str(ROOT)); RUN=ROOT/"runs/native_microphysics_reconstruction001"
from pbuf.audit.native_system_inventory import domains,variables
from pbuf.audit.native_equation_registry import equations
from pbuf.audit.native_dependency_graph import graph
from pbuf.audit.native_provenance_map import provenance
from pbuf.audit.native_duplicate_mechanism_audit import duplicates

def dump(n,v): (RUN/f"{n}.json").write_text(json.dumps(v,indent=2,sort_keys=True)+"\n")
def baseline():
 names={145:"mass_loading_excitation_propagation001",146:"loaded_excitation_native_dispersion001",147:"existing_excitation_propagation_provenance001",148:"em_constrained_native_excitation001",149:"quantum_constrained_native_excitation001",150:"source_interaction_quantization001",151:"unified_native_neighbor_state001",152:"mixed_state_neighbor_law_discrimination001",153:"loaded_link_transverse_response001"}
 checks={f"DEV{k}_AUDIT_COMPLETE":f"DEV{k}_AUDIT_COMPLETE" in (ROOT/"runs"/v/"report.txt").read_text() for k,v in names.items()}
 if not all(checks.values()): raise RuntimeError("DEV154_BASELINE_MISMATCH")
 return checks
def source_hashes():
 paths=list((ROOT/"pbuf/foundation").glob("*.py"))+list((ROOT/"pbuf/excitation").glob("*.py"))+[ROOT/"pbuf/models/a8_state.py",ROOT/"pbuf/wl/native_incremental_elastic_energy.py"]
 return {str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}
def markdown(ds,eqs,gaps,params,discrepancies):
 lines=["# PBUF Native Microphysics Working System","","## What exists today","","The implemented system has two adjacent but uncoupled lanes. Static source arrays initialize frozen fast/slow scalar fields, whose mean `c_state` drives a nonlinear six-neighbor bounded-strain equilibrium solve for accumulated deformation `u`. Dynamic excitation is a signed two-component array on a one-dimensional periodic support. A progression step moves every two-vector to exactly one neighbor; the frame-aware form orthogonally changes its two coordinates. No neighbor branching, ray solver, renormalization, or loaded-state transfer factor participates.","","Packet density is the squared two-component magnitude. Its density-weighted index is the centroid, and the centroid history is the diagnostic native packet trajectory. The current excitation observer does not compute direction or curvature. Dev151 unifies an audit longitudinal array `L` and the two excitation components as `(L,X1,X2)`, but `L` is not derived from production `c_state` in that path. Dev153 establishes no loaded/unloaded cross-effect.","","## One-page equations",""]
 lines += [f"- **{e['equation_id']} {e['name']}:** ${e['latex']}$ — `{e['code_location']}`" for e in eqs]
 lines += ["","## The system without equations","","Imagine two ledgers for the same conceptual medium. The static ledger spreads and balances persistent loading across six-faced grid neighbors, while enforcing a strain barrier. The dynamic ledger stores two signed disturbance numbers and shifts each pair one site per progression step. When local link frames differ, those two numbers are rotated without changing their combined squared size. Afterward, an observer squares them, locates their center, and records how that center changes. The code does not currently let the static ledger modify the dynamic update.","","CARPET_FIBER_ANALOGY: A link's longitudinal entry can be pictured as fiber condition and its two transverse entries as sideways disturbance. The implementation supports the bookkeeping analogy; it does not prove a literal carpet-fiber ontology.","","## Definitive flowcharts","","```text","STATIC: rho -> u_slow/u_fast N6 updates -> c_state -> embed -> bounded N6 equilibrium -> accumulated u -> bond epsilon -> sigma/W/Ktan","DYNAMIC: packet controls -> X(N,2) -> one-neighbor periodic permutation -> optional orthogonal frame map -> X history -> rho_X -> centroid history (trajectory)","COMBINED: (static L, dynamic X1,X2) share rank-3 records; [NO ESTABLISHED L -> X UPDATE EDGE]","```","","## ONE EXCITATION PROGRESSION STEP","","1. Read `old[i]`, a two-number signed vector, and source frame `E_i`.","2. Select exactly `j=(i+1) mod N` (or the opposite direction in the basic transfer). There is no candidate list, branching, or weight.","3. Form raw transverse overlap `B=E_perp,j E_perp,i^T`; take its SVD `B=U Sigma V^T`; set `R=UV^T`.","4. Write `next[j]=R old[i]`. Each destination has exactly one writer.","5. Replace the whole transverse array with `next`; leave `L` unchanged; append a copy to history.","6. No renormalization, clipping, averaging, timestep, or ray update occurs.","","## ONE STATIC EQUILIBRIUM UPDATE","","For current `u`, calculate positive-axis bond differences divided by `DX`. Form secant bond weights `K/(1-(|epsilon|/epsilon_max)^2)`. Assemble the six-neighbor divergence operator `A(u)`, solve `A(candidate)=c_state` by conjugate gradient with zero boundary values, then damp: `u_new=0.65 candidate+0.35 u`. Stop when relative RMS change is at most `2e-7`, or after 30 Picard iterations.","","## FROM EXCITATION STATE TO TRAJECTORY POINT","","At every site, calculate `rho=X1^2+X2^2`. Calculate `rbar=sum(a*rho)/sum(rho)`. Repeating that observer operation for each stored state produces the centroid sequence. There is no current excitation function implementing `rbar_n,rbar_(n+1)->direction` or `direction->curvature`.","","## D01–D30 domain reconstruction",""]
 fields=["Name","Status","Purpose","Physical meaning","Stored variables","Units/dimensional status","Mathematical definition","Update/evolution equation","Inputs","Outputs","Code implementation","Upstream dependencies","Downstream consumers","Conservation/invariants","Known controls/tests","What it DOES establish","What it DOES NOT establish"]
 for d in ds:
  lines += [f"### {d['id']} — {d['Name']}",""]
  for f in fields: lines += [f"#### {f}","",str(d[f]),""]
  lines += ["PLAIN_LANGUAGE:","",d["PLAIN_LANGUAGE"],"","CARPET_FIBER_ANALOGY:","",d["CARPET_FIBER_ANALOGY"],""]
 lines += ["## Historical trajectory distinction","","| System | What evolves | Driver | Physical excitation? | Path imposed/extracted | Consumer |","|---|---|---|---|---|---|","| Historical trajectory state | positions/directions | geometric propagation | No | imposed/evolved geometry | receiver diagnostics |","| Dev148/149 excitation | signed `X(N,2)` | periodic permutation | Yes, native candidate | centroid extracted | excitation audits |","| Dev153 packet path | centroid history | same excitation history | diagnostic of X | extracted | loaded/unloaded comparison |","| Weak-lensing 3D rays | ray position/direction/bundle | frozen WL field | optical tracer, separate | solver-evolved | shear/receiver stack |","","## User-supplied Dev153 statement verification",""]
 for x in discrepancies: lines += [f"- `{x['statement']}` — **{x['classification']}**: {x['exact_difference']}"]
 lines += ["","## Parameters and hidden numerical operations","",f"The machine-readable register contains {len(params)} active/historical constants. Important hidden operations are the N6 factor `1/6`, fast/slow mean `1/2`, polarization normalization, SVD orthogonalization, periodic modulo indexing, centroid denominator guard, FFT exclusion of DC, static clipping, Picard damping, strain barrier guard, and solver tolerances.","","## What we must stop re-deriving","","- Native signed two-component excitation state and its two transverse modes.","- Source-free periodic permutation and exact quadratic-norm conservation.","- FFT-bin wavelength diagnostic, polarization covariance, and handedness fixtures.","- Rank-3 `(L,X1,X2)` representation and orthogonal F02–F06 frame transport.","- Excitation-density centroid trajectory extraction.","- Static N6 fast/slow response and bounded-strain accumulation.","","## Real remaining gaps",""]
 lines += [f"- **{g['classification']}** — {g['missing_relation']}: {g['why_current_equations_are_insufficient']}" for g in gaps]
 lines += ["","## Retired mechanisms","","Do not revive `Rmax`, historical `strength=0.18`, trajectory-as-physical-excitation, fundamental native time/`T0`, reflective boundaries as conservative zero flux, or fitted loading-to-excitation transfer factors.",""]
 return "\n".join(lines)
def main():
 RUN.mkdir(parents=True,exist_ok=True); base=baseline(); before=source_hashes(); ds=domains(); eqs=equations(); dep=graph(); prov=provenance(); dup=duplicates()
 gaps=[{"missing_relation":"loaded longitudinal state -> transverse evolution operator","upstream_known_quantities":["L","epsilon","sigma","W","K_tangent","geometry"],"downstream_required_quantity":"C_ij(L)","why_current_equations_are_insufficient":"No mixed Hessian, metric, allocation, or conservative exchange map is implemented.","dev_that_established_gap":153,"classification":"ACTUAL_MISSING_PHYSICS"},{"missing_relation":"excitation centroid history -> direction","upstream_known_quantities":["rbar history"],"downstream_required_quantity":"native direction","why_current_equations_are_insufficient":"No excitation observer implements the finite difference or zero-step rule.","dev_that_established_gap":154,"classification":"IMPLEMENTED_BUT_POORLY_DOCUMENTED" if False else "ACTUAL_MISSING_PHYSICS"},{"missing_relation":"excitation direction -> curvature","upstream_known_quantities":["direction history"],"downstream_required_quantity":"native curvature","why_current_equations_are_insufficient":"Curvature exists only in separate geometric WL trajectory code.","dev_that_established_gap":154,"classification":"IMPLEMENTED_UNDER_DIFFERENT_NAME"},{"missing_relation":"FFT wavelength -> native k","upstream_known_quantities":["lambda_n"],"downstream_required_quantity":"k_n","why_current_equations_are_insufficient":"The canonical observer emits wavelength but not k.","dev_that_established_gap":154,"classification":"ACTUAL_MISSING_PHYSICS"}]
 params=[{"name":"A8_INIT_DT","value":.03,"code_location":"pbuf/models/a8_state.py:28","origin":"frozen historical","classification":"numerical","status":"active"},{"name":"A8_INIT_OMEGA","value":1.,"code_location":"pbuf/models/a8_state.py:29","origin":"frozen historical","classification":"structural normalization","status":"active"},{"name":"A8_INIT_K","value":1.,"code_location":"pbuf/models/a8_state.py:30","origin":"frozen historical","classification":"structural normalization","status":"active"},{"name":"A8_INIT_STEPS","value":160,"code_location":"pbuf/models/a8_state.py:31","origin":"frozen historical","classification":"numerical","status":"active"},{"name":"A8_INIT_COUP_F2S/S2F","value":.5,"code_location":"pbuf/models/a8_state.py:33-34","origin":"frozen historical","classification":"fitted/history unresolved","status":"active"},{"name":"A8_INIT_FAST/SLOW_TIMESCALE","value":[1.,.1],"code_location":"pbuf/models/a8_state.py:35-36","origin":"frozen historical","classification":"numerical/model","status":"active"},{"name":"A8_INIT_CLIP","value":5.,"code_location":"pbuf/models/a8_state.py:37","origin":"frozen historical","classification":"numerical guard","status":"active"},{"name":"K0/epsilon_max","value":[1.,1.],"code_location":"pbuf/labs/foundation/c_state_bounded_strain_bridge001.py:51-52","origin":"normalization","classification":"structural normalization","status":"active"},{"name":"Picard tol/max/damp","value":[2e-7,30,.65],"code_location":"pbuf/labs/foundation/c_state_bounded_strain_bridge001.py:53-55","origin":"solver","classification":"numerical","status":"active"},{"name":"CG rel tol/max","value":[2e-9,700],"code_location":"pbuf/labs/foundation/c_state_bounded_strain_bridge001.py:56-57","origin":"solver","classification":"numerical","status":"active"},{"name":"strength","value":.18,"code_location":"pbuf/models/a8_state.py:144","origin":"historical self-test","classification":"historical","status":"retired from native bridge"}]
 discrepancies=[{"statement":"X_j = R_ij X_i","classification":"EXACT","exact_difference":"Exact for frame-aware one-neighbor progression."},{"statement":"R_ij^T R_ij = I","classification":"EXACT","exact_difference":"SVD polar factor enforces this numerically."},{"statement":"|X_j|^2 = |X_i|^2","classification":"EXACT","exact_difference":"Follows per transported vector."},{"statement":"C_ij = I in established Dev153 result","classification":"APPROXIMATE_DESCRIPTION","exact_difference":"Dev153 establishes absence of a derived nontrivial C; identity is the null control, not a separately discovered constitutive law."},{"statement":"rho_a = X1_a^2 + X2_a^2","classification":"EXACT","exact_difference":"Named amp in observer."},{"statement":"centroid is density-weighted spatial mean","classification":"EQUIVALENT","exact_difference":"It is a 1D index-weighted linear mean, not a general spatial vector or circular mean."},{"statement":"trajectory is centroid sequence","classification":"EQUIVALENT","exact_difference":"The code returns centroid history; packet_path artifacts interpret it as trajectory."},{"statement":"direction comes from centroid differences","classification":"INCORRECT","exact_difference":"No excitation direction estimator exists."},{"statement":"curvature comes from tangent differences","classification":"INCORRECT","exact_difference":"No excitation curvature estimator exists; separate WL geometry code has curvature."},{"statement":"loaded and unloaded packet paths are identical in Dev153","classification":"EXACT","exact_difference":"Dev153 execute applies the same fixed rotation irrespective of load."}]
 existing=[{"mechanism":e["name"],"status":e["status"],"canonical_implementation":e["code_location"],"canonical_equation":e["latex"],"what_it_already_solves":e["name"],"what_it_does_not_solve":"loaded-state cross-effect or absolute physical interpretation","superseded_implementations":[]} for e in eqs]
 retired=[{"mechanism":"Rmax","status":"RETIRED"},{"mechanism":"historical strength=0.18","status":"HISTORICAL_SELF_TEST_ONLY"},{"mechanism":"trajectory-as-physical-excitation","status":"RETIRED"},{"mechanism":"fundamental native time/T0","status":"RETIRED"},{"mechanism":"reflect padding interpreted as zero flux","status":"RETIRED_INTERPRETATION"}]
 hidden_weights=[{"operation":"N6 average","value":"1/6","location":"a8_state.py:57,77"},{"operation":"fast/slow mean","value":"1/2","location":"a8_state.py:90,112"},{"operation":"channel couplings","value":"0.5 each","location":"a8_state.py:104-109"},{"operation":"Picard damping","value":"0.65/0.35","location":"c_state_bounded_strain_bridge001.py:206"},{"operation":"excitation allocation","value":"one destination, weight 1","location":"native_neighbor_mixed_state.py:23-27"}]
 hidden_norm=[{"operation":"polarization unit normalization","location":"native_excitation_state.py:28-32"},{"operation":"SVD frame orthogonalization","location":"native_neighbor_state.py:48-52"},{"operation":"centroid denominator guard 1e-30","location":"native_neighbor_mixed_observer.py:9"},{"operation":"no excitation renormalization","location":"native_excitation_transfer.py:31-37"}]
 hidden_geom=[{"geometry":"periodic 1D index adjacency","effect":"selects sole recipient","location":"native_excitation_transfer.py:24-29"},{"geometry":"link relation normalized to e_parallel","effect":"builds local frame","location":"native_neighbor_state.py:26-32"},{"geometry":"transverse frame overlap","effect":"rotates X","location":"native_neighbor_state.py:48-52"},{"geometry":"loading gradient fixture","effect":"constructs link frames in Dev152 audit only","location":"native_neighbor_loaded_excitation.py:23-24"}]
 contract={"contract":"PBUF_NATIVE_WORKING_SYSTEM_V1","native_topology":"3D Cartesian N6 static; 1D periodic dynamic audit","static_state_definition":"c_state=(u_slow+u_fast)/2","static_update_equation":"E02,E03,E09","bounded_strain_definition":"E06-E08","accumulated_response_definition":"nonlinear N6 equilibrium u","dynamic_state_definition":"X in R^(N x 2)","dynamic_state_rank":2,"dynamic_update_equation":"E11/E12","transverse_mode_count":2,"frame_transport_definition":"E13","excitation_norm_definition":"E14","wavelength_definition":"E17","k_definition":"UNRESOLVED","excitation_density_definition":"E15","centroid_definition":"E16","trajectory_definition":"centroid sequence (diagnostic)","direction_definition":"UNRESOLVED","curvature_definition":"UNRESOLVED","unified_rank3_state_definition":"E18","loaded_unloaded_cross_effect_present":False,"trajectory_imposed_or_extracted":"extracted centroid diagnostic","historical_ray_relation":"distinct implementation","active_parameters":[p["name"] for p in params if p["status"]=="active"],"retired_parameters":["Rmax","strength=0.18 as physical input","T0"],"established_mechanisms":[e["name"] for e in eqs],"unresolved_mechanisms":[g["missing_relation"] for g in gaps],"physics_changes":0}
 artifacts={"native_variable_inventory":variables(),"native_equation_registry":eqs,"native_dependency_graph":dep,"native_provenance_map":prov,"static_system_reconstruction":{"domains":ds[:7],"equations":[e for e in eqs if e["equation_id"]<="E09"]},"dynamic_system_reconstruction":{"domains":ds[7:17],"equations":[e for e in eqs if "excitation" in e["name"] or "progression" in e["name"]]},"trajectory_reconstruction":{"domains":ds[22:28],"direction_implemented":False,"curvature_implemented":False},"unified_state_reconstruction":{"domains":ds[17:22]},"historical_trajectory_distinction":{"rows":["historical geometric tracer","Dev148/149 X evolution","Dev153 centroid path","weak-lensing ray"]},"duplicate_mechanism_map":dup,"existing_mechanisms":existing,"established_equations":eqs,"unresolved_equations":gaps,"parameter_inventory":params,"hidden_weight_inventory":hidden_weights,"hidden_normalization_inventory":hidden_norm,"hidden_geometry_inventory":hidden_geom,"remaining_gap_inventory":gaps,"retired_mechanism_inventory":retired,"code_doc_discrepancies":discrepancies,"final_native_system_contract":contract}
 for n,v in artifacts.items(): dump(n,v)
 report=markdown(ds,eqs,gaps,params,discrepancies); (ROOT/"PBUF_NATIVE_MICROPHYSICS_WORKING_SYSTEM.md").write_text(report); (RUN/"PBUF_NATIVE_MICROPHYSICS_WORKING_SYSTEM.md").write_text(report)
 import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
 figs={"native_system_overview":"static N6 lane | dynamic 1D lane","static_loading_pipeline":"rho -> fast/slow -> c_state -> bounded equilibrium -> u","dynamic_excitation_pipeline":"X -> shift -> frame rotation -> history","rank3_neighbor_state":"S = (L, X1, X2)","frame_transport":"Xj = R_ij Xi; R^T R = I","excitation_density_to_trajectory":"X -> rho_X -> centroid -> centroid sequence","static_dynamic_combined_architecture":"static lane  [NO CROSS EDGE]  dynamic lane","dependency_graph":"real edges only; conceptual edges excluded","historical_trajectory_comparison":"centroid diagnostic != geometric tracer != WL ray","remaining_gap_map":"missing: L->X, direction, curvature, k"}
 for n,text in figs.items():
  fig,ax=plt.subplots(figsize=(8,3)); ax.axis("off"); ax.text(.5,.5,text,ha="center",va="center",wrap=True,fontsize=14,bbox={"boxstyle":"round","facecolor":"#eef5ff"}); fig.tight_layout(); fig.savefig(RUN/f"{n}.png",dpi=130); plt.close(fig)
 after=source_hashes(); assert before==after
 guards={"PHYSICS_CHANGES":0,"SOURCE_BEHAVIOR_CHANGES":0,"NUMERICAL_BEHAVIOR_CHANGES":0,"NEW_INTERACTION_COEFFICIENTS":0,"NEW_PHYSICAL_ASSUMPTIONS":0,"RENORMALIZATION_USED":False,"NATIVE_PACKET_TRAJECTORY_IS_DERIVED_FROM_EXCITATION_DENSITY":True,"TRAJECTORY_SOLVER_USED_TO_MOVE_EXCITATION":False}
 outcomes=["DEV154_AUDIT_COMPLETE","PBUF_NATIVE_WORKING_SYSTEM_RECONSTRUCTED","PBUF_NATIVE_EQUATION_REGISTRY_ESTABLISHED","PBUF_NATIVE_DEPENDENCY_GRAPH_ESTABLISHED","PBUF_EXISTING_MECHANISM_REGISTER_ESTABLISHED"]
 dump("result",{"status":outcomes[0],"outcomes":outcomes,"baseline":base,"source_hashes_unchanged":True}); dump("structural_result",{"domains":30,"equations":len(eqs),"variables":len(variables()),"guards":guards,"source_hashes":after})
 (RUN/"baseline_git.txt").write_text(subprocess.run(["git","status","--short"],cwd=ROOT,text=True,capture_output=True).stdout)
 (RUN/"report.txt").write_text("\n".join(outcomes+[f"{k}={str(v).lower() if isinstance(v,bool) else v}" for k,v in guards.items()])+"\n"); print("\n".join(outcomes))
if __name__=="__main__": main()
