def dominates(a,b):
    rank={"SURVIVES":3,"PARTIAL":2,"UNDERDETERMINED":1,"REJECTED":0}
    ca=(a["NEW_SCALAR_STATE_COUNT"]+a["NEW_VECTOR_STATE_COUNT"]+a["NEW_BOND_STATE_COUNT"])
    cb=(b["NEW_SCALAR_STATE_COUNT"]+b["NEW_VECTOR_STATE_COUNT"]+b["NEW_BOND_STATE_COUNT"])
    return rank[a["STATUS"]]>=rank[b["STATUS"]] and ca<=cb and a["NEW_FREE_COEFFICIENT_COUNT"]<=b["NEW_FREE_COEFFICIENT_COUNT"]
