const state={manifest:null,data:{},occ:null,registration:null}; const $=id=>document.getElementById(id);
async function load(){state.manifest=await (await fetch('/data/viewer_manifest.json')).json(); const panels=$('panels');
 if(state.manifest.mode==='SPIN2_BASIS_TRACE'&&![...$('mode').options].some(x=>x.value==='SPIN2_BASIS_TRACE'))$('mode').add(new Option('SPIN2_BASIS_TRACE','SPIN2_BASIS_TRACE'));
 try{state.bundleManifest=await (await fetch('/data/viewer_bundle_manifest.json')).json()}catch(e){$('bundleScale').disabled=true;$('bundleResolution').disabled=true;$('foldLayer').disabled=true}
 try{state.registration=await (await fetch('/data/viewer_registration.json')).json()}catch(e){$('lensOverlay').disabled=true;$('cohort').disabled=true}
 for(let i=0;i<3;i++){let d=document.createElement('div');d.className='panel';d.innerHTML=`<select class="channel"></select><select class="scale"><option>signed symmetric</option><option>absolute</option><option>percentile</option><option>min-max</option></select><canvas width="512" height="512"></canvas>`;panels.append(d)}
 document.querySelectorAll('.channel').forEach((s,i)=>{state.manifest.channels.forEach(c=>s.add(new Option(c.name,c.name)));s.value=state.manifest.channels[Math.min(i,state.manifest.channels.length-1)].name;s.onchange=render});
 document.querySelectorAll('.scale').forEach(s=>s.onchange=render); await ensure('occupancy'); render()}
async function ensure(name){if(state.data[name])return state.data[name];let c=state.manifest.channels.find(x=>x.name===name),b=await (await fetch('/data/'+c.file)).arrayBuffer();return state.data[name]=new Float32Array(b)}
function plane(a,o,s,proj){let [nx,ny,nz]=state.manifest.dimensions,w=o==='YZ'?ny:nx,h=o==='XY'?ny:nz,out=new Float32Array(w*h),cnt=new Uint16Array(w*h);out.fill(proj==='maximum'?-Infinity:0);
 for(let z=0;z<nz;z++)for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){let axis=o==='XY'?z:o==='XZ'?y:x;if(proj==='single slice'&&axis!==s)continue;let p=o==='XY'?x+w*y:o==='XZ'?x+w*z:y+w*z,v=a[(x*ny+y)*nz+z],j=p;if(!Number.isFinite(v))continue;if(proj==='maximum')out[j]=Math.max(out[j],v);else if(proj==='RMS')out[j]+=v*v;else out[j]+=v;cnt[j]++}
 if(proj==='mean')out.forEach((v,i)=>out[i]=cnt[i]?v/cnt[i]:NaN);if(proj==='RMS')out.forEach((v,i)=>out[i]=cnt[i]?Math.sqrt(v/cnt[i]):NaN);return [out,w,h]}
function colors(a,kind){let f=[...a].filter(Number.isFinite).sort((x,y)=>x-y),p=Math.max(1,Math.floor(f.length*+$('magnitude').value/100))-1,lo=f[0]||0,hi=f[p]||1;if(kind==='signed symmetric'){hi=Math.max(Math.abs(lo),Math.abs(hi));lo=-hi}return [lo,hi]}
function paint(canvas,a,w,h,kind){let [lo,hi]=colors(a,kind),ctx=canvas.getContext('2d'),im=ctx.createImageData(w,h);a.forEach((v,i)=>{let t=(v-lo)/(hi-lo||1),r=kind==='signed symmetric'?255*Math.max(0,2*t-1):255*t,b=kind==='signed symmetric'?255*Math.max(0,1-2*t):255*t,g=kind==='signed symmetric'?255*(1-Math.abs(2*t-1)):255*t;im.data.set([r,g,b,Number.isFinite(v)?255:0],i*4)});let tmp=new OffscreenCanvas(w,h);tmp.getContext('2d').putImageData(im,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp,0,0,canvas.width,canvas.height);if($('lensOverlay').checked&&state.registration){let c=state.registration.registration.geometric_lens_projection;ctx.strokeStyle='#00ffff';ctx.lineWidth=2;ctx.beginPath();ctx.arc((c[1]+.5)*canvas.width/64,canvas.height-(c[0]+.5)*canvas.height/64,16,0,2*Math.PI);ctx.stroke()}}
async function render(){let o=$('orientation').value,s=+$('slice').value,p=$('projection').value;$('sliceValue').textContent=s;if($('mode').value==='BUNDLE_TRANSPORT'||$('mode').value==='SHOW_FOLD_CANDIDATES'){$('rgbLabel').textContent='STRUCTURAL RGB — NOT PHYSICAL COLOR';$('inspection').textContent=`Bundle scale ${$('bundleScale').value}; support ${$('bundleResolution').value}². Click a launch bundle for its rays/hull/S/D/parity, or a received cell for launch components, entropy, parity composition, and represented scales.`}else $('rgbLabel').textContent='COHORT COLORING — NOT PHYSICAL RGB';let sels=[...document.querySelectorAll('.channel')],planes=[],occPlane=plane(await ensure('occupancy'),o,s,p),minocc=+$('minocc').value;
 for(let i=0;i<3;i++){let a=await ensure(sels[i].value),pl=plane(a,o,s,p);pl[0].forEach((v,j)=>{if(occPlane[0][j]<minocc)pl[0][j]=NaN});planes.push(pl);paint(document.querySelectorAll('.panel canvas')[i],...pl,document.querySelectorAll('.scale')[i].value)}
 let [a,w,h]=planes[0],b=planes[1],c=planes[2],[ar0,ar1]=colors(a,'min-max'),[br0,br1]=colors(b,'min-max'),[cr0,cr1]=colors(c,'min-max'),ctx=$('rgb').getContext('2d'),im=ctx.createImageData(w,h);a.forEach((v,i)=>im.data.set([255*(v-ar0)/(ar1-ar0||1),255*(b[i]-br0)/(br1-br0||1),255*(c[i]-cr0)/(cr1-cr0||1),255],4*i));let tmp=new OffscreenCanvas(w,h);tmp.getContext('2d').putImageData(im,0,0);ctx.drawImage(tmp,0,0,512,512);
 let correlation=pairs=>{let ma=pairs.reduce((q,x)=>q+x[0],0)/pairs.length,mb=pairs.reduce((q,x)=>q+x[1],0)/pairs.length,num=0,da=0,db=0;pairs.forEach(x=>{num+=(x[0]-ma)*(x[1]-mb);da+=(x[0]-ma)**2;db+=(x[1]-mb)**2});return num/Math.sqrt(da*db)},pairs=a.map((v,i)=>[v,b[i]]).filter(x=>x.every(Number.isFinite)),fa=await ensure(sels[0].value),fb=await ensure(sels[1].value),fo=await ensure('occupancy'),full=[...fa].map((v,i)=>[v,fb[i]]).filter((x,i)=>x.every(Number.isFinite)&&fo[i]>=minocc);$('corr').textContent=`Current-slice Pearson: ${correlation(pairs)}; occupied voxels: ${pairs.length}; full-volume Pearson: ${correlation(full)}`}
['orientation','projection','slice','minocc','magnitude','mode','lensOverlay','cohort','bundleScale','bundleResolution','foldLayer'].forEach(x=>$(x).oninput=render);$('rgb').onclick=e=>{let r=+$('bundleResolution').value||64;$('inspection').textContent=`Received cell (${Math.floor(e.offsetX*r/512)}, ${r-1-Math.floor(e.offsetY*r/512)}). Reverse selection reports contributing launch components, entropy, parity composition, and scales from the pre-exported bundle data; selections never alter registration.`};load();
