"""Human-readable registry renderers."""
from __future__ import annotations

from collections import defaultdict


def render_registry(registry: dict, commit: str, date: str) -> str:
    attempts = {a["attempt_id"]: a for a in registry["attempts"]}
    domains = defaultdict(list)
    for target in registry["targets"]: domains[target["domain"]].append(target)
    out = ["# PBUF Mechanism Registry", "", "Registry source: `docs/PBUF_MECHANISM_REGISTRY.json`", f"Built at commit: `{commit}`", f"Generated: `{date}`", "Do not edit this file directly; edit the canonical JSON and run `python tools/pbuf_registry.py render`.", "", "`MECHANISM_REGISTRY_JSON_CANONICAL=true`", "`MECHANISM_REGISTRY_MD_GENERATED=true`", "`REGISTRY_SCOPE=FULL_REACHABLE_PBUF_HISTORY`", "", "## Domain index", ""]
    for domain in sorted(domains): out.append(f"- [{domain}](#{domain.lower().replace(' / ', '-').replace(' ', '-')})")
    for domain in sorted(domains):
        out += ["", f"## {domain}", ""]
        for target in domains[domain]:
            out += [f"### {target['canonical_name']}", "", f"Question: {target['plain_language_question']}", "", f"Status: `{target['current_status']}`", "", "| Date | Dev / PR | Mechanism | Result | Current status |", "|---|---|---|---|---|"]
            for aid in target.get("attempt_ids", []):
                a = attempts[aid]; label = ", ".join(filter(None, [a.get("dev"), a.get("pr")])) or "Pre-ledger"
                out.append(f"| {a.get('date_completed') or 'UNKNOWN'} | {label} | {a['name']} | {a['result']} | {a['current_status']} |")
            canonical = target.get("canonical_solution_ids", [])
            if canonical: out += ["", "Canonical answer: " + ", ".join(attempts[x].get("dev") or x for x in canonical) + "."]
            out += ["", f"Do not rederive: `{str(target['do_not_rederive']).lower()}` — {target.get('reopen_condition', 'UNKNOWN')}"]
    out += ["", "## Confirmed equivalences", ""]
    for e in registry.get("equivalences", []): out.append(f"- `{e['relation']}`: {e['source']} ↔ {e['target']} — {e['reason']}")
    return "\n".join(out) + "\n"


def render_timeline(registry: dict) -> str:
    rows = sorted(registry["attempts"], key=lambda a: (a.get("date_completed") or "9999-99-99", a["attempt_id"]))
    out = ["# PBUF Development Timeline", "", "Generated from `docs/PBUF_MECHANISM_REGISTRY.json`; do not edit directly.", "", "| Date | Dev / PR | Target | Mechanism | Result | Current status |", "|---|---|---|---|---|---|"]
    targets = {t['target_id']: t['canonical_name'] for t in registry['targets']}
    for a in rows:
        out.append(f"| {a.get('date_completed') or 'UNKNOWN'} | {', '.join(filter(None,[a.get('dev'),a.get('pr')])) or 'Pre-ledger'} | {targets[a['target_id']]} | {a['name']} | {a['result']} | {a['current_status']} |")
    return "\n".join(out) + "\n"
