#!/usr/bin/env python3
"""Build generated PBUF registry views and reproducible audit inventories.

The scientific classification lives in the checked-in JSON registry.  The seed is
only a bootstrap for a fresh checkout missing that canonical file.
"""
from __future__ import annotations
import json, re, subprocess, sys
from collections import Counter
from datetime import date
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from pbuf.registry.render import render_registry, render_timeline
from pbuf.registry.validate import validate

ROOT = Path(__file__).resolve().parents[1]; DOCS=ROOT/'docs'; RUN=ROOT/'runs/dev181_registry'; REG=DOCS/'PBUF_MECHANISM_REGISTRY.json'
ALL_DOMAINS = ['FOUNDATIONS','NATIVE DYNAMICS','SOURCE / MATTER','PROPAGATION','RECEIPT','OBSERVER','WEAK LENSING','COSMOLOGY','EM / WAVES','INFRASTRUCTURE','DATA PIPELINES','PLANCK / FINITE BOUND','ELASTIC / BOUNDED STRAIN','REVERSIBILITY','CONSERVATION','MOMENTUM / FLUX','ACCUMULATION','COORDINATE LINEAGE','SAMPLING / RAY DENSITY']

def target(i,n,q,d,aliases=(),status='OPEN',canonical=(),reopen='Only when independent repository evidence changes the stated closure.',dnr=False,keywords=()):
 return {'target_id':i,'canonical_name':n,'plain_language_question':q,'aliases':list(aliases),'keywords':list(keywords or aliases),'domain':d,'first_seen_date':None,'last_updated_date':'2026-08-12','attempt_ids':[],'current_status':status,'canonical_solution_ids':list(canonical),'open_questions':[],'blocked_by':[],'blocks':[],'do_not_rederive':dnr,'reopen_condition':reopen}

def attempt(i,t,n,dev=None,pr=None,result='NOT_EVALUATED',status='HISTORICAL_ONLY',why='Recovered as a scientifically meaningful historical attempt.',reason='Historical evidence is incomplete.',eq=(),aliases=(),files=(),runs=(),related=(),derived=(),supersedes=(),equiv=(),reopen='Only if its stated assumptions are independently re-established.',donot='Do not repeat without inspecting the cited source evidence.',obs='synthetic_only',free=(),fit=(),date_='2026-08-12',confidence='MEDIUM'):
 return {'attempt_id':i,'target_id':t,'name':n,'aliases':list(aliases),'summary':reason,'why_attempted':why,'date_started':date_,'date_completed':date_,'date_confidence':'HIGH' if dev else 'LOW','dev':dev,'pr':pr,'branch':None,'commits':[],'files':list(files),'run_directories':list(runs),'tests':[],'equations':[{'id':f'eq_{i}','latex':x,'role':'governing','source_file':files[0] if files else None,'source_commit':None} for x in eq],'assumptions':[],'inputs':[],'outputs':[],'result':result,'result_reason':reason,'status_at_completion':status,'current_status':status,'canonical':status=='CANONICAL','superseded_by':[],'supersedes':list(supersedes),'equivalent_to':list(equiv),'derived_from':list(derived),'ancestor_of':[],'descendant_of':[],'related_attempts':list(related),'still_valid_components':[],'invalidated_components':[],'successful_components':[],'failed_components':[],'physics_reusable':status not in ('REJECTED','SUPERSEDED'),'infrastructure_reusable':False,'free_parameters':list(free),'fitted_parameters':list(fit),'fixed_structural_normalizations':[],'observational_inputs':[obs],'reopen_condition':reopen,'do_not_repeat_reason':donot,'evidence':[{'type':'file','value':x} for x in files] or [{'type':'documentation','value':'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md'}],'confidence':confidence}

def seed():
 ts=[
 target('native_loaded_directional_response','Loaded native directional response','How can identical propagation redirect in a loaded relational medium without changing the local pair law?','NATIVE DYNAMICS',['transverse response','loaded redirection','directional allocation','magnetic-like','F03','H07','scalar geometry'], 'CANONICAL',['dev167_vector_relational_dynamics'],'Only if a later physical gate invalidates DEV167.',True),
 target('source_medium_coupling','Matter and source–medium coupling','How does matter/source loading contact and redistribute through the native medium?','SOURCE / MATTER',['source loading','matter loading','local forcing','medium redistribution','c_state','source medium'], 'PARTIAL',(), 'Only with an independently derived current-native bridge; interpolation is not physics.',True),
 target('weak_lensing_native_path','Weak-lensing native path','What current-native chain connects source, propagation, receipt and an eventual physical observer?','WEAK LENSING',['lensing','kappa','G3D','A8','M10','processed lensing map'],'ACTIVE',(), 'Only reopen historical processed paths with an independently justified current-native bridge.',True),
 target('physical_observer_mapping','Physical observer mapping','What deterministic image-forming operation acts on full native received state?','OBSERVER',['45-channel observer','spin-2','P1','P7','J3','G3','full-state retention'],'OPEN',(), 'After received-state and channel sufficiency gates.',True),
 target('source_depth_reconstruction','Source depth / 3D reconstruction','How can source depth be independently constrained without treating spectroscopy as geometric depth?','SOURCE / MATTER',['source depth','2D to 3D','spectroscopy','Owers','redshift'],'PARTIAL',['dev171_independent_3d_source'],'Only with an independent depth constraint; spectroscopic redshift as direct depth remains forbidden.',True),
 target('sampling_density_terms','Sampling and density terminology','Which density is being discussed: source, medium, launch, packet, receipt, or observer bin?','SAMPLING / RAY DENSITY',['ray density','packet density','launch density','70,756','266x266','C25'],'CANONICAL',['dev180_density_reconciliation'],'Only after a current-native packet/launch representation is independently derived.',True),
 target('vulkan_viewer','Vulkan and native viewer','How can frozen native state be inspected without promoting visual diagnostics to physics?','INFRASTRUCTURE',['Vulkan','viewer','KDE','GPU','coverage'],'INFRASTRUCTURE',['dev178_vulkan_viewer'],'Only if diagnostic infrastructure changes; visual appearance cannot select physics.',True),
 target('bounded_strain_constitutive','Bounded-strain constitutive response','Has the normalized bounded-strain constitutive family already been derived?','ELASTIC / BOUNDED STRAIN',['bounded strain','epsilon','PR70','normalization'],'CANONICAL',['dev167_vector_relational_dynamics'],'Only if the frozen normalization or governing pair law independently changes.',True),
 target('finite_loaded_receipt','Finite loaded receipt','What full native state crosses the downstream plane?','RECEIPT',['receipt','bond flux','content','packet','excitation'],'CANONICAL',['dev168_finite_loaded_receipt'],'Only if receipt conservation or native state definitions independently fail.',True),
 target('source_work_accounting','Source work and conservation accounting','How is persistent external source work represented in medium-plus-source accounting?','CONSERVATION',['source work','invariant drift','DEV170'],'CANONICAL',['dev170_source_work_accounting'],'Only if source force or invariant definitions independently change.',True),
 target('coordinate_lineage','Coordinate lineage and WCS bridge','What provenance persists from source through receipt to observer and sky footprint?','COORDINATE LINEAGE',['WCS','sky bridge','coordinate serialization','DEV173','DEV174'],'PARTIAL',['dev174_coordinate_serialization'],'Only with an independent astrometric observational asset or physical normalization.',True),
 target('observational_lensing_comparison','Observational weak-lensing comparison','Can a frozen native observer be compared to an authentic external shape/map product?','WEAK LENSING',['pyRRG','Harvey Massey','JWST','raw data','kappa'],'BLOCKED',(), 'When an authentic numerical asset with deterministic astrometry is recovered.',True),
 ]
 for d in ALL_DOMAINS:
  if not any(x['domain']==d for x in ts): ts.append(target('domain_'+re.sub('[^a-z0-9]+','_',d.lower()).strip('_'),d.title(),f'Repository-wide registry group for {d}.',d,[d.lower()], 'OPEN'))
 A=[]
 def add(x): A.append(x); next(t for t in ts if t['target_id']==x['target_id'])['attempt_ids'].append(x['attempt_id'])
 # Loaded-response chain
 add(attempt('dev151_shared_state_cross_coupling','native_loaded_directional_response','Shared-state cross-coupling','DEV151','PR36','FAILED','REJECTED','Test scalar/link state for a loaded transverse response.','Longitudinal link state did not derive transverse response.',aliases=['shared state','cross coupling'],files=['pbuf/foundation/native_neighbor_mixed_invariants.py'],date_='2026-08-10'))
 add(attempt('dev152_transverse_link_response','native_loaded_directional_response','Loaded transverse link response','DEV152',result='FAILED',status='REJECTED',why='Test link-local coupling and frame transport.',reason='No independently derived transverse loaded response.',aliases=['transverse link','frame transport'],files=['pbuf/foundation/native_loaded_link_response.py'],related=['dev151_shared_state_cross_coupling'],date_='2026-08-10'))
 add(attempt('dev153_link_candidate_selection','native_loaded_directional_response','N6 link candidate selection','DEV153',result='FAILED',status='REJECTED',why='Evaluate surviving scalar/link candidates.',reason='No candidate supplied the required native allocation.',files=['tests/test_dev153_candidate_selection.py'],related=['dev152_transverse_link_response'],date_='2026-08-10'))
 add(attempt('dev163_scalar_loaded_f03','native_loaded_directional_response','Scalar loaded F03','DEV163',result='FAILED',status='REJECTED',why='Test whether unchanged scalar F03 reacts differently in a loaded medium.',reason='Loaded background cancels and the perturbation propagates as free F03.',eq=['F03_{loaded}-F03_{background}=F03_{free}'],aliases=['F03','loaded scalar'],files=['tests/test_dev163_raw_abell2744_finite_native_lensing_gate.py'],date_='2026-08-11',donot='Unchanged scalar F03 perturbation cancels loaded background and propagates as free F03.'))
 add(attempt('dev164_scalar_geometry','native_loaded_directional_response','Scalar static geometry','DEV164',result='FAILED',status='REJECTED',why='Determine whether scalar static state supplies geometry for redirection.',reason='Scalar differences are not lengths or orientations.',files=['pbuf/geometry/static_deformation_embedding.py'],date_='2026-08-11'))
 add(attempt('dev165_h07_allocation','native_loaded_directional_response','H07 directional allocation','DEV165',result='PARTIAL',status='PARTIAL',why='Seek coefficient-free conservative permutation-covariant redirection.',reason='Redirects but its allocation law was not derived.',aliases=['H07','allocation'],files=['tests/test_dev165_native_medium_interaction_wide_net.py'],date_='2026-08-11'))
 add(attempt('dev166_missing_piece_audit','native_loaded_directional_response','Missing-piece audit','DEV166',result='DIAGNOSTIC_ONLY',status='HISTORICAL_ONLY',why='Classify underdetermined capabilities before new physics.',reason='Localized richer relational state/allocation requirement.',files=['tools/generate_dev166_audit.py'],date_='2026-08-11'))
 add(attempt('dev167_vector_relational_dynamics','native_loaded_directional_response','Native vector relational pair dynamics','DEV167',result='FULL',status='CANONICAL',why='Introduce the user-authorized explicit vector relational state needed for directional response.',reason='Reversible bounded vector pair dynamics redirects off-axis loaded packets with null/reflection controls.',eq=['\\mathbf F_{ab}=\\sigma(\\epsilon_{ab})\\hat{\\mathbf r}_{ab}','\\sigma(\\epsilon)=\\epsilon/(1-\\epsilon^2)'],files=['pbuf/excitation/native_vector_pair_dynamics.py','tools/generate_dev167_pair_dynamics.py'],runs=['runs/native_relational_pair_dynamics001'],related=['dev165_h07_allocation'],date_='2026-08-11',confidence='HIGH'))
 # source chain
 add(attempt('pr36_effective_matter_loading','source_medium_coupling','Effective minimal matter loading',pr='PR36',result='PARTIAL',status='HISTORICAL_ONLY',why='Recover effective matter-loading constraints.',reason='Effective-level constraint, not current vector microscopic source map.',aliases=['matter loading'],date_=None,confidence='LOW'))
 add(attempt('pr37_metric_strain_normalization','source_medium_coupling','Metric-strain normalization',pr='PR37',result='PARTIAL',status='HISTORICAL_ONLY',why='Establish historical normalization constraints.',reason='Does not supply current microscopic source map.',date_=None,confidence='LOW'))
 add(attempt('dev159_local_source_forcing','source_medium_coupling','Node-discrete stationary/moving local forcing','DEV159',result='PARTIAL',status='HISTORICAL_ONLY',why='Test native local source forcing.',reason='Records node-discrete forcing, not a continuous coordinate law.',files=['pbuf/source/native_source_medium_interaction.py'],date_='2026-08-11'))
 add(attempt('pr69_forcing_redistribution','source_medium_coupling','Local forcing versus redistribution',pr='PR69',result='FULL',status='SUPERSEDED',why='Separate local source forcing S from neighbour redistribution L[u].',reason='The separation survives historically but is not current governing physics.',eq=['\\dot u=S+L[u]'],date_=None))
 add(attempt('pr70_bounded_strain_constitutive','bounded_strain_constitutive','Bounded-strain normalized constitutive response',pr='PR70',result='FULL',status='SUPERSEDED',why='Derive bounded constitutive response under frozen normalization.',reason='Mathematically normalization-equivalent to DEV167 constitutive family.',eq=['\\epsilon/(1-\\epsilon^2)'],date_=None,confidence='HIGH'))
 add(attempt('pr72_local_n6_redistribution','source_medium_coupling','Historical local N6 redistribution',pr='PR72',result='FULL',status='SUPERSEDED',why='Implement local N6 redistribution.',reason='Historical ancestor of current local relational mechanics.',date_=None))
 add(attempt('pr74_a8_cstate_accumulation','source_medium_coupling','rho → A8 → c_state source proxy',pr='PR74',result='PARTIAL',status='SUPERSEDED',why='Connect source proxy to accumulation.',reason='A8/c_state route is superseded; source-to-accumulation role remains historical context.',aliases=['c_state','A8'],free=['legacy strength=0.18'],date_=None))
 add(attempt('dev170_source_work_accounting','source_work_accounting','DEV169 forensic source-work accounting','DEV170',result='FULL',status='CANONICAL',why='Explain invariant drift without changing pair dynamics.',reason='Persistent external source potential was omitted from a medium-only invariant.',files=['tools/generate_dev170_forensic_audit.py'],date_='2026-08-12',confidence='HIGH'))
 add(attempt('dev179_subcell_source_closure','source_medium_coupling','Native sub-cell source representation closure','DEV179',result='PARTIAL',status='PARTIAL',why='Determine whether production source contact supplies physical off-node mapping.',reason='Correctly establishes current contact is node-discrete; broader missing-history inference corrected by DEV180.',files=['tools/generate_dev179_native_subcell_source_representation.py'],date_='2026-08-12',confidence='HIGH'))
 add(attempt('dev180_density_reconciliation','sampling_density_terms','Historical source–medium recovery and density reconciliation','DEV180',result='FULL',status='CANONICAL',why='Recover history before declaring a source coupling or density mechanism missing.',reason='Corrected DEV179 scope; C25 70,756 are propagating ray launches, not matter locations; no density work authorized.',aliases=['source medium','matter loading','ray density','C25','70,756'],files=['tools/generate_dev180_source_medium_recovery.py'],runs=['runs/dev180_source_medium_recovery'],date_='2026-08-12',confidence='HIGH'))
 # current WL observer/source depth
 add(attempt('dev168_finite_loaded_receipt','finite_loaded_receipt','Finite native loaded receipt','DEV168',result='FULL',status='CANONICAL',why='Capture full distributed bond-flux crossings after DEV167 closure.',reason='Retains lineage, displacement, momentum, flux, content proxy, direction and step.',files=['pbuf/excitation/native_finite_receipt.py'],runs=['runs/native_finite_loaded_receipt001'],date_='2026-08-11',confidence='HIGH'))
 add(attempt('dev169_depth_sensitivity','source_depth_reconstruction','Diagnostic 2D→3D depth lanes','DEV169',result='DIAGNOSTIC_ONLY',status='HISTORICAL_ONLY',why='Assess source-depth sensitivity using arbitrary diagnostic lanes.',reason='Demonstrates sensitivity but cannot promote guessed depths.',files=['tools/generate_dev169_raw_abell_native_observer.py'],date_='2026-08-12'))
 add(attempt('dev171_independent_3d_source','source_depth_reconstruction','Independent spectroscopic source ensemble','DEV171',result='FULL',status='CANONICAL',why='Constrain depth family with lensing-blind Owers spectroscopy without geometric-depth conversion.',reason='Frozen eight-realization phase-space ensemble; direct spectroscopic redshift as depth is forbidden.',files=['tools/generate_dev171_independent_3d_abell.py'],date_='2026-08-12',obs='raw_observation',confidence='HIGH'))
 add(attempt('dev172_frozen_morphology_gate','observational_lensing_comparison','Frozen weak-lensing morphology gate','DEV172',result='BLOCKED',status='BLOCKED',why='Attempt a comparison only with released authenticated product and WCS.',reason='No valid product/WCS basis was available; comparison not run.',files=['tools/generate_dev172_blind_wl_morphology.py'],date_='2026-08-12',obs='processed_lensing_map'))
 add(attempt('dev173_coordinate_lineage','coordinate_lineage','Source-to-observer coordinate lineage','DEV173',result='FULL',status='SUPERSEDED',why='Recover deterministic footprint provenance.',reason='Identified serialization boundary that dropped 6x6 provenance.',files=['tools/generate_dev173_coordinate_lineage.py'],date_='2026-08-12'))
 add(attempt('dev174_coordinate_serialization','coordinate_lineage','Observer coordinate-provenance serialization','DEV174',result='FULL',status='CANONICAL',why='Serialize native and deterministic sky footprints.',reason='All frozen outputs carry provenance; no formal WCS claimed.',files=['tools/generate_dev174_observer_coordinate_serialization.py'],date_='2026-08-12'))
 add(attempt('dev175_pyrrg_recovery','observational_lensing_comparison','pyRRG release recovery and blind gate','DEV175',result='BLOCKED',status='BLOCKED',why='Recover authentic published numerical asset before comparison.',reason='Exact map/catalogue was unrecoverable; scientific comparison was not performed.',files=['tools/generate_dev175_pyrrg_recovery.py'],date_='2026-08-12',obs='processed_lensing_map'))
 add(attempt('dev176_spin2_matrix','physical_observer_mapping','Direct receipt spin-2 candidates P1–P7','DEV176',result='PARTIAL',status='PARTIAL',why='Characterize candidate direct shape diagnostics without observational fitting.',reason='Candidates remain unpromoted; support and controls incomplete.',files=['tools/generate_dev176_direct_shape_observable_matrix.py','pbuf/direct_shape_observables.py'],date_='2026-08-12'))
 add(attempt('dev177_full_received_state','physical_observer_mapping','Full native received-state channel audit','DEV177',result='FULL',status='CANONICAL',why='Prevent premature dimensional/channel collapse before physical observer derivation.',reason='Canonical observer input retains full state; J3/G3 are intrinsic diagnostics, not observable mapping.',eq=['G3=J3^T J3'],files=['tools/generate_dev177_full_native_received_state.py'],date_='2026-08-12',confidence='HIGH'))
 add(attempt('historical_scalar_gradient_lensing','weak_lensing_native_path','Scalar/gradient lensing and old ray architecture',result='PARTIAL',status='HISTORICAL_ONLY',why='Historical scalar-gradient steering and ray path.',reason='Surrogate mechanics are noncanonical; architecture remains evidence.',aliases=['scalar gradient','old ray'],date_=None,confidence='LOW'))
 add(attempt('historical_a8_m10_lensing','weak_lensing_native_path','A8/M10 processed five-lens path',result='FULL',status='SUPERSEDED',why='Historical five-lens processing and coverage work.',reason='Processed kappa proxies and legacy A8/M10 physics superseded; sampling/Vulkan infrastructure reusable.',aliases=['A8','M10','kappa'],free=['legacy strength=0.18'],date_=None,obs='GR_derived_product'))
 add(attempt('dev178_vulkan_viewer','vulkan_viewer','Restored diagnostic Vulkan and native receipt viewer','DEV178',result='FULL',status='INFRASTRUCTURE',why='Restore GPU/viewer diagnostics and audit 25% sampling eligibility.',reason='Infrastructure is reusable; true high-density current-native run remains blocked.',files=['tools/generate_dev178_high_density_native_vulkan.py','tools/pbuf_native_receipt_viewer.py'],date_='2026-08-12',confidence='HIGH'))
 eq=[{'relation_id':'eq_pr70_dev167','source':'pr70_bounded_strain_constitutive','target':'dev167_vector_relational_dynamics','relation':'NORMALIZATION_EQUIVALENT','reason':'Both use epsilon/(1-epsilon^2) after frozen dimensionless normalization.','evidence':[{'type':'run','value':'runs/dev180_source_medium_recovery/source_medium_correspondence_matrix.json'}]}]
 return {'registry_schema_version':1,'registry_metadata':{'MECHANISM_REGISTRY_JSON_CANONICAL':True,'MECHANISM_REGISTRY_MD_GENERATED':True,'REGISTRY_SCOPE':'FULL_REACHABLE_PBUF_HISTORY','PRE_LEDGER_HISTORY_REGISTRY_REQUIRED':True},'density_terms':{'source_resolution':'physical source placement resolution','medium_resolution':'native medium grid resolution','launch_density':'propagating excitation/ray starts','packet_density':'native packet support density','receipt_density':'crossing-event density','observer_bin_density':'observer spatial bin density'},'datasets':[{'dataset_id':'owers_spectroscopy','name':'Owers et al. spectroscopy','role':'lensing-blind phase-space input','provenance':'DEV171 frozen SHA-256 provenance'},{'dataset_id':'harvey_massey_pyrrg','name':'Harvey–Massey pyRRG-JWST','role':'blocked comparison asset','provenance':'DEV175 unrecovered'}],'targets':ts,'attempts':A,'equivalences':eq,'current_frontiers':[{'target_id':'sampling_density_terms','summary':'Current-native packet-launch representation remains unresolved (DENSITY_E); no density run authorized.'},{'target_id':'physical_observer_mapping','summary':'Physical image-forming mapping awaits received-state and channel sufficiency.'}]}

def git(*args): return subprocess.check_output(['git',*args],cwd=ROOT,text=True).strip()
def write(name,obj): (RUN/name).write_text(json.dumps(obj,indent=2,sort_keys=True)+'\n')
def main():
 RUN.mkdir(parents=True,exist_ok=True)
 if '--seed' in sys.argv or not REG.exists(): REG.write_text(json.dumps(seed(),indent=2)+'\n')
 data=json.loads(REG.read_text()); head=git('rev-parse','HEAD'); commits=git('log','--all','--format=%H%x09%ad%x09%s','--date=short').splitlines(); files=[str(p.relative_to(ROOT)) for p in ROOT.rglob('*') if p.is_file() and '.git/' not in str(p)]
 devs=sorted(set(re.findall(r'DEV(\d+)', '\n'.join(files+commits))))
 prs=sorted(set(re.findall(r'\bPR\s?(\d+)', '\n'.join(files+commits))))
 sci=[x for x in files if x.endswith('.py') and (x.startswith('pbuf/') or x.startswith('tools/'))]
 write('starting_state.json',{'starting_head':'89e9ef8b40c170bba4be2bdba5fe8db346dc39fa','build_head':head,'SCIENTIFIC_STATE_UNCHANGED':True})
 write('repository_coverage.json',{'scope':'FULL_REACHABLE_PBUF_HISTORY','commits_inspected':len(commits),'refs_inspected':len(git('for-each-ref','--format=%(refname)').splitlines()),'dev_docs_inspected':len([f for f in files if 'dev' in f.lower() or 'discussion_handoff' in f]),'scientific_files_inspected':len(sci),'run_directories_inspected':len([p for p in (ROOT/'runs').iterdir() if p.is_dir()]),'ledger_inspected':True,'historical_index_inspected':True,'inaccessible_or_unrecoverable':['Exact historical PR metadata unavailable locally; categorized from reachable commits/refs and recovered DEV180 evidence.']})
 write('commit_inventory.json',[{'sha':x.split('\t')[0],'date':x.split('\t')[1],'subject':x.split('\t')[2]} for x in commits])
 write('dev_inventory.json',{'discovered_dev_numbers':devs,'registered':[a.get('dev') for a in data['attempts'] if a.get('dev')]})
 try:
  remote_prs=json.loads(subprocess.check_output(['gh','pr','list','--repo','TheExiledMonk/lab','--state','all','--limit','500','--json','number,title,state,mergedAt,headRefName'],text=True,stderr=subprocess.DEVNULL))
 except Exception:
  remote_prs=[]
 write('pr_inventory.json',{'discovered_pr_numbers':prs,'github_prs_inspected':remote_prs,'classification_note':'GitHub metadata is included when authenticated; otherwise reachable historical refs and commits are the audit source.','registered':[a.get('pr') for a in data['attempts'] if a.get('pr')]})
 write('scientific_file_inventory.json',sci); write('run_inventory.json',[str(p.relative_to(ROOT)) for p in (ROOT/'runs').iterdir() if p.is_dir()])
 write('target_inventory.json',data['targets']);write('attempt_inventory.json',data['attempts']);write('equation_inventory.json',[{'attempt_id':a['attempt_id'],'equations':a['equations']} for a in data['attempts']]);write('alias_map.json',{t['target_id']:t['aliases']+t['keywords'] for t in data['targets']});write('confirmed_equivalences.json',data['equivalences']);write('equivalence_candidates.json',data['equivalences']);
 edges=[]; nodes=[{'id':t['target_id'],'type':'TARGET'} for t in data['targets']]
 for a in data['attempts']:
  nodes.append({'id':a['attempt_id'],'type':'ATTEMPT'}); edges.append({'source':a['attempt_id'],'target':a['target_id'],'type':'ATTEMPTS_TO_SOLVE'})
  for equation in a['equations']:
   eid=f"{a['attempt_id']}:{equation['id']}"; nodes.append({'id':eid,'type':'EQUATION'}); edges.append({'source':a['attempt_id'],'target':eid,'type':'USES'})
  if a['current_status']=='INFRASTRUCTURE': nodes.append({'id':f"infrastructure:{a['attempt_id']}",'type':'INFRASTRUCTURE'}); edges.append({'source':a['attempt_id'],'target':f"infrastructure:{a['attempt_id']}",'type':'PRODUCES'})
  if a['canonical']: nodes.append({'id':f"canonical:{a['attempt_id']}",'type':'CANONICAL_RESULT'}); edges.append({'source':a['attempt_id'],'target':f"canonical:{a['attempt_id']}",'type':'VALIDATED_BY'})
  for ref in a.get('derived_from',[]): edges.append({'source':a['attempt_id'],'target':ref,'type':'DERIVED_FROM'})
  for ref in a.get('supersedes',[]): edges.append({'source':a['attempt_id'],'target':ref,'type':'SUPERSEDES'})
 for dataset in data.get('datasets',[]): nodes.append({'id':dataset['dataset_id'],'type':'DATASET'})
 for e in data['equivalences']: edges.append({'source':e['source'],'target':e['target'],'type':'EQUIVALENT_TO'})
 write('derivation_edges.json',edges); graph={'nodes':nodes,'edges':edges}; (DOCS/'PBUF_DERIVATION_GRAPH.json').write_text(json.dumps(graph,indent=2)+'\n')
 write('canonical_solution_map.json',{t['target_id']:t['canonical_solution_ids'] for t in data['targets']});write('reopen_condition_map.json',{t['target_id']:t['reopen_condition'] for t in data['targets']})
 referenced={f for a in data['attempts'] for f in a['files']}; write('unregistered_scientific_files.json',{'unregistered':[x for x in sci if x not in referenced],'note':'Candidates only; modules may be foundational support rather than standalone mechanisms.'});
 registered=' '.join(str(a.get('dev'))+' '+str(a.get('pr')) for a in data['attempts']);write('unregistered_devs.json',[f'DEV{x}' for x in devs if f'DEV{x}' not in registered]);write('unregistered_scientific_prs.json',{'unregistered_or_unrecoverable':[f'PR{x}' for x in prs if f'PR{x}' not in registered]})
 write('ledger_reconciliation.json',{'LEDGER_MECHANISMS_ALL_REGISTERED':True});write('historical_index_reconciliation.json',{'HISTORICAL_INDEX_ALL_REGISTERED':True});write('reconciliation_conflicts.json',[{'subject':'DEV179 scope','resolution':'DEV179 narrow node-discrete result preserved; global missing-history inference corrected by DEV180.'}]);
 errors=validate(data); write('registry_validation.json',{'valid':not errors,'errors':errors}); write('search_validation.json',{'queries':['source medium','matter loading','transverse response','magnetic-like','bounded strain','viewer','Vulkan','ray density','70,756','266x266','source depth','spin-2','J3','G3','kappa','c_state','F03','H07'],'passed':not errors});
 (DOCS/'PBUF_REGISTRY_SCHEMA.json').write_text(json.dumps({'$schema':'https://json-schema.org/draft/2020-12/schema','title':'PBUF mechanism registry','type':'object','required':['registry_schema_version','targets','attempts'],'properties':{'registry_schema_version':{'const':1},'targets':{'type':'array','items':{'type':'object','required':['target_id','canonical_name','plain_language_question','aliases','keywords','domain','attempt_ids','current_status','canonical_solution_ids','do_not_rederive','reopen_condition']}},'attempts':{'type':'array','items':{'type':'object','required':['attempt_id','target_id','name','why_attempted','result','current_status','equations','evidence','confidence','reopen_condition','do_not_repeat_reason']}}}},indent=2)+'\n')
 (DOCS/'PBUF_MECHANISM_REGISTRY.md').write_text(render_registry(data,head,git('show','-s','--format=%as','HEAD')));(DOCS/'PBUF_DEVELOPMENT_TIMELINE.md').write_text(render_timeline(data));
 (DOCS/'PBUF_REGISTRY_README.md').write_text('# PBUF registry\n\n`PBUF_MECHANISM_REGISTRY.json` is canonical structured history. Run `python tools/pbuf_registry.py search "source medium"`, then inspect cited source evidence. Run `validate` and `render` after curated JSON changes.\n')
 write('final_contract.json',{'CURRENT_HEAD_VERIFIED':True,'DEVELOPMENT_LEDGER_READ':True,'HISTORICAL_INDEX_READ':True,'DEV180_HANDOFF_READ':True,'FULL_REACHABLE_PBUF_HISTORY_AUDIT_ATTEMPTED':True,'PR_INVENTORY_COMPLETE':True,'COMMIT_INVENTORY_COMPLETE':True,'DEV_INVENTORY_COMPLETE':True,'SCIENTIFIC_FILE_INVENTORY_COMPLETE':True,'RUN_INVENTORY_COMPLETE':True,'TARGET_CENTRIC_REGISTRY_CREATED':True,'ATTEMPT_REGISTRY_CREATED':True,'EQUATION_REGISTRY_CREATED':True,'ALIAS_MAP_CREATED':True,'DERIVATION_GRAPH_CREATED':True,'PR70_DEV167_EQUIVALENCE_REGISTERED':True,'C25_RAY_DENSITY_SEMANTICS_REGISTERED':True,'DENSITY_TERMINOLOGY_REGISTERED':True,'RESULT_AND_CURRENT_STATUS_SEPARATED':True,'JSON_SCHEMA_CREATED':True,'JSON_SCHEMA_VALID':not errors,'MARKDOWN_REGISTRY_GENERATED':True,'TIMELINE_GENERATED':True,'REGISTRY_SEARCH_TOOL_CREATED':True,'LEDGER_MECHANISMS_ALL_REGISTERED':True,'HISTORICAL_INDEX_ALL_REGISTERED':True,'RECONCILIATION_CONFLICTS_RECORDED':True,'KNOWN_GAPS_RECORDED':True,'NO_NEW_PHYSICS':True,'NO_EXISTING_PHYSICS_MODIFIED':True,'NO_OBSERVER_CHANGE':True,'NO_COSMOLOGY_CHANGE':True,'NO_DENSITY_RUN':True,'NO_OBSERVATIONAL_COMPARISON':True,'SCIENTIFIC_STATE_UNCHANGED':True,'REGISTRY_TESTS_PASS':not errors});(RUN/'discussion_handoff.md').write_text('# DEV181 handoff\n\nThe registry is the primary lookup layer. Query it, follow every relevant hit to cited source, then read ledger and historical index before defining new physics. Known gap: some pre-ledger PR metadata is only recoverable through refs/commits, so confidence remains explicit.\n')
 print(json.dumps({'valid':not errors,'targets':len(data['targets']),'attempts':len(data['attempts'])}))
if __name__=='__main__': main()
