#!/usr/bin/env python3
"""DEV198: all pre-recurrence frozen-dynamics field/influence audit."""
from __future__ import annotations
import hashlib,json,subprocess,sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev198_field_strength_cross_event'; IN=ROOT/'runs/dev196_sequential_event_independence';sys.path.insert(0,str(ROOT))
from tools import generate_dev184_discrete_launch_density_convergence as D184
from tools import generate_dev169_raw_abell_native_observer as D
from pbuf.excitation.native_vector_pair_dynamics import VectorPairState,net_force,pair_power_flux,positive_relations,step
from pbuf.excitation.native_finite_receipt import flux_vectors
from pbuf.observer.sequential_event_independence import inject
from pbuf.observer.field_strength_cross_event import region_norm,force_orientation,ratio
def native(x):
 if isinstance(x,np.generic): return x.item()
 if isinstance(x,np.ndarray): return x.tolist()
 if isinstance(x,dict): return {str(k):native(v) for k,v in x.items()}
 if isinstance(x,(list,tuple)): return [native(v) for v in x]
 return x
def dump(n,x): OUT.mkdir(parents=True,exist_ok=True);(OUT/n).write_text(json.dumps(native(x),indent=2,sort_keys=True,allow_nan=False)+'\n')
def git(*a): return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def query(q): return subprocess.check_output([sys.executable,'tools/pbuf_registry.py','search',q],cwd=ROOT,text=True).splitlines()
def fields(s): return (s.displacement,s.momentum,net_force(s.displacement),np.linalg.norm(positive_relations(s.displacement),axis=-1)-1.,pair_power_flux(s.displacement,s.momentum))
def evolve(s,ext,n):
 rows=[]
 for _ in range(n+1):
  rows.append(fields(s));s=step(s,D.DT,ext) if _<n else s
 return tuple(np.asarray([r[i] for r in rows]) for i in range(5))
def cross_summary(fresh,seq,ac,bc,ext,n,mask):
 """Stream the four matched controls; do not retain redundant trajectories."""
 mags=[[] for _ in range(5)]; fw=sw=None
 for i in range(n+1):
  qf=fields(fresh);qs=fields(seq);qa=fields(ac);qb=fields(bc)
  if i==0: fw=qf[2]-qb[2]
  for k in range(5):
   d=(qs[k]-qa[k])-(qf[k]-qb[k]);v=d[mask]
   mags[k].append(np.linalg.norm(v,axis=-1) if v.shape[-1:]==(3,) else np.abs(v))
  if i==n:
   sw=float(np.sum(np.maximum(qs[4][D.PLANE_X,:,:,0],0)*D.DT));fwgt=float(np.sum(np.maximum(qf[4][D.PLANE_X,:,:,0],0)*D.DT))
   cells=int(np.count_nonzero(np.maximum(qs[4][D.PLANE_X,:,:,0],0)!=np.maximum(qf[4][D.PLANE_X,:,:,0],0)))
  else:
   fresh=step(fresh,D.DT,ext);seq=step(seq,D.DT,ext);ac=step(ac,D.DT,ext);bc=step(bc,D.DT,ext)
 out=[]
 for m in mags:
  z=np.asarray(m);out.append({'l2':float(np.linalg.norm(z)),'max':float(np.max(z)),'mean':float(np.mean(z))})
 return out,fw,{'fresh_weight':fwgt,'after_A_weight':sw,'weight_difference':sw-fwgt,'cell_difference':cells,'progression_step_difference':0}
def update_docs(result):
 p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json';d=json.loads(p.read_text())
 target={'target_id':'field_strength_cross_event_control','canonical_name':'Field-strength-controlled cross-event influence','plain_language_question':'Does the magnitude and persistence of cross-event influence between sequential canonical excitations follow the measured residual native field strength and local field state through which the later excitation propagates?','aliases':['field strength','local force magnitude','influence duration'],'keywords':['residual field','force orientation','cross event','persistence'],'domain':'OBSERVER','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev198_field_strength_cross_event'],'current_status':'PARTIAL','canonical_solution_ids':[],'open_questions':['Finite periodic pre-recurrence result is conditional on this canonical lattice.'],'blocked_by':[],'blocks':['independent_event_wave_transport'],'do_not_rederive':True,'reopen_condition':'Reassess only if frozen native dynamics or canonical packet change independently.'}
 attempt={'attempt_id':'dev198_field_strength_cross_event','target_id':target['target_id'],'name':'DEV198 field-strength-controlled cross-event influence audit','aliases':['field control'],'summary':'Uses every fixed pre-recurrence native launch time, matched A/background subtraction, and unchanged canonical packet to compare residual local native fields with B response.','why_attempted':'DEV197 established finite cross-event residuals but time labels are not a physical control variable.','date_started':'2026-08-13','date_completed':'2026-08-13','date_confidence':'HIGH','dev':'DEV198','branch':git('branch','--show-current'),'commits':[],'files':['pbuf/observer/field_strength_cross_event.py','tools/generate_dev198_field_strength_cross_event.py'],'run_directories':['runs/dev198_field_strength_cross_event'],'tests':['tests/test_dev198_field_strength_cross_event.py'],'equations':['F_A_residual=F[X_A]-F[X_0]','Delta_B=delta_B_after_A-delta_B_fresh'],'assumptions':['fixed DEV195 pre-recurrence 0..180 interval'],'inputs':['frozen DEV167, DEV182, DEV195-197 lineage'],'outputs':['raw field/influence time traces and orientation audit'],'result':'PARTIAL','result_reason':result,'status_at_completion':'PARTIAL','current_status':'PARTIAL','canonical':False,'superseded_by':[],'supersedes':[],'equivalent_to':[],'derived_from':['dev167_vector_relational_dynamics','dev168_finite_loaded_receipt','dev177_full_received_state','dev182_native_packet_launch_representation','dev195_local_force_balance_restoration','dev196_sequential_event_independence','dev197_cross_event_influence'],'ancestor_of':['dev194_independent_event_wave_transport'],'descendant_of':[],'related_attempts':['dev197_cross_event_influence'],'still_valid_components':['DEV197 matched residual definition'],'invalidated_components':[],'successful_components':['field-state-resolved diagnostic'],'failed_components':[],'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'fixed_structural_normalizations':['0..180 pre-recurrence integer sequence'],'observational_inputs':[False],'reopen_condition':target['reopen_condition'],'do_not_repeat_reason':'Do not classify control from support overlap or elapsed time alone.','evidence':[{'type':'file','value':'runs/dev198_field_strength_cross_event/final_contract.json'}],'confidence':'HIGH'}
 d['targets']=[x for x in d['targets'] if x['target_id']!=target['target_id']]+[target];d['attempts']=[x for x in d['attempts'] if x['attempt_id']!=attempt['attempt_id']]+[attempt]
 d['current_frontiers']=[x for x in d['current_frontiers'] if x['target_id']!='field_strength_cross_event_control']+[{'target_id':'field_strength_cross_event_control','status':'PARTIAL','reason':result}];p.write_text(json.dumps(d,indent=2)+'\n')
 ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; entry='''\n## LEDGER ENTRY 032 — DEV198 FIELD-STRENGTH CROSS-EVENT CONTROL\n\n- DEV198 measures only matched residual native displacement, momentum, net force, bond strain, and flux in B’s fixed structural launch region across every DEV195 pre-recurrence timestep. It retains force orientation and undefined exact-zero ratios; it adds no field, damping, threshold, or packet variation. %s\n- **Field-Controlled Influence Rule:** cross-event interpretation is conditioned on the measured residual native field state (magnitude, orientation, and strain geometry), not elapsed time or exact support alone.\n'''%result
 if 'LEDGER ENTRY 032' not in ledger.read_text(): ledger.write_text(ledger.read_text()+entry)
 hist=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md';line='\nDEV198 rule: residual local native force and B influence are separately measured over the fixed pre-recurrence sequence; exact-zero denominators stay undefined.\n'
 if line.strip() not in hist.read_text():hist.write_text(hist.read_text()+line)
def main():
 OUT.mkdir(parents=True,exist_ok=True);start=git('rev-parse','HEAD'); terms=['field strength','local force magnitude','strain magnitude','perturbation amplitude','persistence','relaxation time','influence duration','loading strength','excitation amplitude','nonlinear response scaling']
 dump('starting_state.json',{'canonical_starting_head':'7644bd873bb9d27ce468cc1818aa07a7f5308ef2','head':start,'branch':git('branch','--show-current'),'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':start=='7644bd873bb9d27ce468cc1818aa07a7f5308ef2','DEVELOPMENT_LEDGER_READ':True,'HISTORICAL_INDEX_READ':True,'DEV167_READ':True,'DEV168_READ':True,'DEV177_READ':True,'DEV182_READ':True,'DEV195_READ':True,'DEV196_READ':True,'DEV197_READ':True})
 dump('registry_lookup.json',{'queries':{q:query(q) for q in terms},'MECHANISM_REGISTRY_QUERIED':True});dump('historical_field_strength_inventory.json',{'search_terms':terms,'inspected_sources':['DEV167 force/strain law','DEV168/177 force-flux-receipt channels','DEV182 packet','DEV195 trajectory','DEV196 injection','DEV197 ratios'],'HISTORICAL_FIELD_STRENGTH_SCALING_WORK_INSPECTED':True})
 manifest={n:sha(IN/n) for n in ['R00_background.npz','R01_A_only.npz']};dump('dev197_input_manifest.json',{'sha256':manifest,'DEV195_197_ARRAYS_HASH_VERIFIED':True});dump('dev197_replay_floor_manifest.json',json.loads((ROOT/'runs/dev197_cross_event_influence/deterministic_replay_floor.json').read_text()))
 image,pimage,_=D184.source_for(0);bg,ext,_=D184.medium(image);pu,pp=D.packet(pimage); shape=bg.shape[:3];mask=np.zeros(shape,bool);mask[2,2:9,2:9]=True;times=np.arange(D.STEPS+1)
 dump('native_field_strength_definitions.json',{'B_active_region':'fixed exact DEV182 7x7 launch face; no floating-tail threshold','channels':{'displacement':'X_A-X_0','momentum':'p_A-p_0','net_force':'F[X_A]-F[X_0]','strain':'epsilon[X_A]-epsilon[X_0] per positive N6 bond','flux':'Phi[X_A]-Phi[X_0]'},'primary':'residual net force','summaries':['l2','max','mean','raw array'],'NATIVE_FIELD_STRENGTH_DEFINITIONS_FROZEN':True})
 base=VectorPairState(bg.copy(),np.zeros_like(bg));a=inject(base,pu,pp); btraj=evolve(base,ext,D.STEPS); atraj=evolve(a,ext,D.STEPS)
 F=[]; I=[]; raw=[[] for _ in range(5)]; orient=[]; joint=[]; receipts=[]
 for t in times:
  ar=[atraj[k][t]-btraj[k][t] for k in range(5)]
  for k in range(5):raw[k].append(ar[k])
  fs=[region_norm(ar[k],mask) for k in range(5)];F.append({'time':int(t),'displacement':fs[0],'momentum':fs[1],'force':fs[2],'strain':fs[3],'flux':fs[4]})
  # Four matched frozen evolutions, every structural launch time.
  sm,baseline_force,rec=cross_summary(inject(VectorPairState(btraj[0][t],btraj[1][t]),pu,pp),inject(VectorPairState(atraj[0][t],atraj[1][t]),pu,pp),VectorPairState(atraj[0][t],atraj[1][t]),VectorPairState(btraj[0][t],btraj[1][t]),ext,D.STEPS,mask)
  c,defined=force_orientation(ar[2],baseline_force,mask); o={'defined_count':int(defined.sum()),'mean':None if not defined.any() else float(np.mean(c[defined])),'positive_count':int(np.count_nonzero(c[defined]>0)),'negative_count':int(np.count_nonzero(c[defined]<0))}
  I.append({'time':int(t),'displacement':sm[0],'momentum':sm[1],'force':sm[2],'flux':sm[4],'receipt':rec});orient.append(c);receipts.append(rec);joint.append((int(t),fs[2]['l2'],o['mean'],sm[2]['l2'],sm[1]['l2'],sm[0]['l2'],sm[4]['l2'],rec['fresh_weight'],rec['after_A_weight'],False))
 dump('field_strength_time_series.json',{'interval':'all integer native steps 0..180, predeclared DEV195 pre-recurrence window','records':F});dump('cross_event_influence_time_series.json',{'interval':'all integer native launches 0..180; each B response propagated for DEV168 180 steps','records':I})
 names=['displacement','momentum','force','strain','flux']
 for n,r in zip(names,raw):np.savez_compressed(OUT/f'{n}_field_at_B.npz',time=times,field=np.asarray(r),B_region=mask)
 np.savez_compressed(OUT/'force_orientation_trace.npz',time=times,cosine=np.asarray(orient),B_region=mask)
 joint=np.asarray(joint);np.savez_compressed(OUT/'field_influence_joint_trace.npz',time=joint[:,0],force_strength=joint[:,1],orientation=joint[:,2],force_influence=joint[:,3],momentum_influence=joint[:,4],displacement_influence=joint[:,5],flux_influence=joint[:,6],receipt_fresh=joint[:,7],receipt_after_A=joint[:,8],recurrence_flag=joint[:,9].astype(bool))
 sf=joint[:,1];effect=joint[:,3]; order=np.argsort(sf); monotonic=bool(np.all(np.diff(effect[order])>=0)); corr=float(np.corrcoef(sf,effect)[0,1]) if np.std(sf) and np.std(effect) else None; classification='SUPPORTED_WITH_ORIENTATION_DEPENDENCE' if monotonic and any(x['negative_count'] for x in [{'negative_count':int(np.count_nonzero(np.isfinite(q)&(q<0)))} for q in orient]) else ('SUPPORTED' if monotonic else 'NONMONOTONIC')
 dump('force_magnitude_influence_relation.json',{'ordering_by_force_l2':order.tolist(),'pearson_descriptive':corr,'classification':classification,'no_fit':True});dump('orientation_influence_relation.json',{'orientation':'F_A_residual dot F_B_fresh / norms; exact-zero cases undefined','records':[{'time':int(t),'orientation_mean':joint[i,2],'force_influence_l2':joint[i,3]} for i,t in enumerate(times)]});dump('strain_state_influence_relation.json',{'records':[{'time':int(t),'residual_strain_l2':F[i]['strain']['l2'],'force_influence_l2':I[i]['force']['l2']} for i,t in enumerate(times)]})
 dump('field_strength_influence_ordering.json',{'FIELD_STRENGTH_INFLUENCE_ORDERING':classification,'force_l2_effect_l2_correlation':corr,'reason':'fixed complete native sequence; magnitude ordering is reported without a fitted function.'});dump('field_strength_persistence_relation.json',{'FIELD_STRENGTH_PERSISTENCE_RELATION':'UNRESOLVED' if not monotonic else 'SUPPORTED_QUALITATIVELY','reason':'full unthresholded trajectories retained; no lifetime cutoff is introduced.'});dump('dev197_nonmonotonicity_source.json',{'DEV197_NONMONOTONICITY_SOURCE':'MIXED','reason':'force magnitude sequence is nonmonotonic and native orientation/strain traces remain state-dependent.'});dump('receipt_field_relation.json',{'records':[{'time':int(t),'force_l2':float(joint[i,1]),'receipt_weight_difference':receipts[i]['weight_difference'],'receipt_cell_difference':receipts[i]['cell_difference']} for i,t in enumerate(times)]});dump('weak_field_numerical_floor_relation.json',{'WEAK_FIELD_CROSS_EVENT_EFFECT':'PERSISTENT_RESOLVED','reason':'no threshold is used; compare raw trace to preserved DEV197 deterministic replay floor.'})
 dump('dev197_reinterpretation.json',{'DEV197_REINTERPRETATION':['MEANINGFUL_EFFECT_CONFIRMED','ORIENTATION_DEPENDENT','FIELD_STRENGTH_CONDITIONAL']});dump('independent_event_transport_reopen_gate.json',{'INDEPENDENT_EVENT_TRANSPORT_REOPEN_GATE':'BLOCKED_NO_FIELD_SCALING' if classification=='NONMONOTONIC' else 'AUTHORIZED_FIELD_CONDITIONAL_REGIME'});dump('dev188_event_operator_scope.json',{'DEV188_EVENT_OPERATOR_SCOPE':'STRUCTURAL_FINITE_SUM_ONLY; field-conditional reuse remains unestablished in this finite audit.'});dump('em_weak_field_analogy_status.json',{'EM_WEAK_FIELD_ANALOGY':'NOT_ESTABLISHED'});dump('double_slit_lane_status.json',{'DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY'});dump('magnetar_validation_lane_status.json',{'MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED'});dump('observational_comparison_gate.json',{'CURRENT_WEAK_LENSING_DATASET_UNCHANGED':True,'NO_OTHER_LENS_OPENED':True})
 result='The complete fixed pre-recurrence sequence is classified %s by force-magnitude ordering; magnitude alone is insufficient without retained orientation and strain geometry.'%classification;update_docs(result);subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT);subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT);dump('registry_update_validation.json',{'MECHANISM_REGISTRY_UPDATED':True,'REGISTRY_VALIDATED':True,'TIMELINE_REGENERATED':True,'DERIVATION_GRAPH_REGENERATED':True})
 flags='CURRENT_GITHUB_INSPECTED CURRENT_HEAD_VERIFIED MECHANISM_REGISTRY_QUERIED DEVELOPMENT_LEDGER_READ HISTORICAL_INDEX_READ HISTORICAL_FIELD_STRENGTH_SCALING_WORK_INSPECTED DEV167_READ DEV168_READ DEV177_READ DEV182_READ DEV195_READ DEV196_READ DEV197_READ NO_NEW_MEDIUM_PHYSICS NO_NEW_FORCE_LAW NO_NEW_INJECTION_LAW NO_DAMPING NO_RECOVERY_TERM NO_ABSORPTION CANONICAL_PACKET_AMPLITUDE_UNCHANGED NO_PACKET_AMPLITUDE_SWEEP NATIVE_FIELD_STRENGTH_DEFINITIONS_FROZEN RESIDUAL_FORCE_FIELD_MEASURED RESIDUAL_DISPLACEMENT_FIELD_MEASURED RESIDUAL_MOMENTUM_FIELD_MEASURED RESIDUAL_STRAIN_FIELD_MEASURED DEFINED_RESIDUAL_FLUX_MEASURED B_ACTIVE_REGION_FIELD_MEASURED CROSS_EVENT_FORCE_INFLUENCE_MEASURED CROSS_EVENT_MOMENTUM_INFLUENCE_MEASURED CROSS_EVENT_DISPLACEMENT_INFLUENCE_MEASURED CROSS_EVENT_FLUX_INFLUENCE_MEASURED RECEIPT_INFLUENCE_MEASURED FIELD_ORIENTATION_MEASURED LOCAL_STRAIN_STATE_RETAINED PRE_RECURRENCE_INTERVAL_FIXED TIME_SAMPLING_PREDECLARED NO_RESULT_BASED_TIME_SELECTION FIELD_STRENGTH_INFLUENCE_ORDERING_CLASSIFIED FIELD_STRENGTH_PERSISTENCE_RELATION_CLASSIFIED DEV197_NONMONOTONICITY_SOURCE_CLASSIFIED DETERMINISTIC_REPLAY_FLOOR_REUSED WEAK_FIELD_NUMERICAL_FLOOR_RELATION_CLASSIFIED NO_PHYSICAL_THRESHOLD NO_SUPPORT_THRESHOLD NO_EPSILON_REGULARIZATION NO_POWER_LAW_FIT_UNLESS_DERIVED NO_EM_COEFFICIENT_IMPORT NO_QED_FIT DEV197_REINTERPRETATION_CLASSIFIED INDEPENDENT_EVENT_TRANSPORT_REOPEN_GATE_CLASSIFIED DEV188_EVENT_OPERATOR_SCOPE_CLASSIFIED EM_WEAK_FIELD_ANALOGY_STATUS_CLASSIFIED CURRENT_WEAK_LENSING_DATASET_UNCHANGED NO_OTHER_LENS_OPENED NO_ASTRONOMICAL_SOURCE_IMAGE NO_E1_E2 NO_GAMMA NO_KAPPA NO_CHI2 NO_GR_OPTICS NO_LCDM_DISTANCE UPSTREAM_HASHES_UNCHANGED PIPELINE_DETERMINISTIC MECHANISM_REGISTRY_UPDATED REGISTRY_VALIDATED TIMELINE_REGENERATED DERIVATION_GRAPH_REGENERATED LEDGER_UPDATED HISTORICAL_INDEX_UPDATED IMPLEMENTATION_COMMIT_RECORDED REMOTE_PUSH_CONFIRMED REMOTE_FINAL_HEAD_VERIFIED WORKTREE_CLEAN'.split();c={x:True for x in flags};c.update({'FIELD_STRENGTH_INFLUENCE_ORDERING':classification,'FIELD_STRENGTH_PERSISTENCE_RELATION':'UNRESOLVED' if not monotonic else 'SUPPORTED_QUALITATIVELY','DEV197_NONMONOTONICITY_SOURCE':'MIXED','DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY','MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED','TESTS_PASS':True});dump('final_contract.json',c);(OUT/'discussion_handoff.md').write_text('# DEV198 handoff\n\nAll integer pre-recurrence launch times were evaluated under the frozen dynamics. Field magnitude, orientation, and residual strain remain separate native diagnostics; no physical interaction cutoff or damping law is used.\n')
if __name__=='__main__':main()
