#!/usr/bin/env python3
"""DEV201: exact tangent normal modes of frozen DEV167 unloaded N6 dynamics."""
from __future__ import annotations
import hashlib, json, subprocess, sys
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev201_native_linear_modes'; sys.path.insert(0,str(ROOT))
from pbuf.excitation.native_vector_pair_dynamics import net_force, step, VectorPairState
from pbuf.foundation.native_linear_modes import allowed_wavevectors, tangent_symbol, update_matrix, oscillatory_frequency, small_k_continuum_statement
from pbuf.observer.native_mode_classification import longitudinal_transverse, transverse_rank

SHAPE=(11,11,11); H=0.04
def git(*a): return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def native(x):
 if isinstance(x,np.generic): return x.item()
 if isinstance(x,np.ndarray): return x.tolist()
 if isinstance(x,dict): return {k:native(v) for k,v in x.items()}
 if isinstance(x,(list,tuple)): return [native(v) for v in x]
 return x
def dump(n,x): OUT.mkdir(parents=True,exist_ok=True);(OUT/n).write_text(json.dumps(native(x),indent=2,sort_keys=True,allow_nan=False)+'\n')
def save(n,**x): np.savez_compressed(OUT/n,**x)

def update_docs():
 p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json'; d=json.loads(p.read_text())
 targets=[
  {'target_id':'native_linear_mode_spectrum','canonical_name':'Native linear mode spectrum','plain_language_question':'What normal-mode spectrum follows from the tangent-linear evolution of the canonical N6 bond-state plus momentum field under frozen DEV167 dynamics?','aliases':['DEV201','normal modes','tangent spectrum'],'keywords':['dispersion','eigenmode','wavevector','dynamical matrix','transverse'],'domain':'NATIVE DYNAMICS','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev201_native_linear_modes'],'current_status':'CANONICAL','canonical_solution_ids':['dev201_native_linear_modes'],'open_questions':['Loaded backgrounds require a separate non-homogeneous tangent analysis.'],'blocked_by':[],'blocks':[],'do_not_rederive':True,'reopen_condition':'Only if frozen DEV167 force law or background choice changes independently.'},
  {'target_id':'em_like_transverse_wave_sector','canonical_name':'EM-like transverse wave sector','plain_language_question':'Does the native tangent-linear spectrum contain an emergent long-wavelength wave sector with the transverse degree-of-freedom, degeneracy, isotropy, and dispersion structure required for an EM-like interpretation?','aliases':['EM-like wave sector','native transverse waves'],'keywords':['transverse','degeneracy','isotropy','linear dispersion'],'domain':'NATIVE DYNAMICS','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev201_native_linear_modes'],'current_status':'BLOCKED','canonical_solution_ids':[],'open_questions':['The unloaded central-force N6 tangent has no robust transverse propagating sector.'],'blocked_by':['native_linear_mode_spectrum'],'blocks':[],'do_not_rederive':True,'reopen_condition':'Only if frozen native dynamics acquire an independently derived transverse tangent stiffness.'}]
 d['targets']=[x for x in d['targets'] if x['target_id'] not in {t['target_id'] for t in targets}]+targets
 attempt={'attempt_id':'dev201_native_linear_modes','target_id':'native_linear_mode_spectrum','name':'DEV201 native linearized N6 mode spectrum','aliases':['DEV201'],'summary':'Analytically assembles the unloaded DEV167 tangent kick-drift symbol and diagonalizes every exact periodic wavevector.','why_attempted':'DEV200 made the N6 bond-state plus momentum representation canonical.','date_started':'2026-08-13','date_completed':'2026-08-13','date_confidence':'HIGH','dev':'DEV201','branch':git('branch','--show-current'),'commits':[],'files':['pbuf/foundation/native_linear_modes.py','pbuf/observer/native_mode_classification.py','tools/generate_dev201_native_linear_modes.py'],'run_directories':['runs/dev201_native_linear_modes'],'tests':['tests/test_dev201_native_linear_modes.py','tests/test_dev201_mode_classification.py'],'equations':['L(k)=diag(-4 sin^2(k_i/2))','M(k)=[[I+h^2L,hI],[hL,I]]'],'assumptions':['unloaded homogeneous DEV167 equilibrium; h=0.04 frozen numerical step'],'inputs':['DEV151 historical guardrail','DEV155/156 history','DEV167 dynamics','DEV182 initialization only','DEV199/DEV200 tangent work'],'outputs':['exact periodic dynamical matrices and discrete eigenpairs'],'result':'FULL','result_reason':'Longitudinal coordinate branches propagate; robust transverse radiative modes do not.','status_at_completion':'FULL','current_status':'CANONICAL','canonical':True,'superseded_by':[],'supersedes':[],'equivalent_to':[],'derived_from':['dev167_vector_relational_dynamics','dev200_native_n6_field'],'ancestor_of':[],'descendant_of':[],'related_attempts':['historical_scalar_gradient_lensing'],'still_valid_components':['DEV200 N6 canonical state'],'invalidated_components':[],'successful_components':['Exact discrete tangent spectrum'],'failed_components':['EM-like transverse wave sector'],'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'fixed_structural_normalizations':['N6 unit bond length','DEV167 h=0.04'],'observational_inputs':[False],'reopen_condition':'Only independent change to DEV167 dynamics or background.','do_not_repeat_reason':'No Maxwell input, continuum import, or transverse-link representation is admissible.','evidence':[{'type':'file','value':'runs/dev201_native_linear_modes/final_contract.json'}],'confidence':'HIGH'}
 d['attempts']=[x for x in d['attempts'] if x['attempt_id']!=attempt['attempt_id']]+[attempt]
 d['current_frontiers']=[x for x in d['current_frontiers'] if x.get('target_id') not in {t['target_id'] for t in targets}]+[{'target_id':'native_linear_mode_spectrum','status':'CANONICAL','reason':'Exact unloaded discrete spectrum is diagonal coordinatewise.'},{'target_id':'em_like_transverse_wave_sector','status':'BLOCKED','reason':'No robust two-transverse propagating branch follows from frozen tangent dynamics.'}]
 p.write_text(json.dumps(d,indent=2)+'\n')
 ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; entry='''\n## LEDGER ENTRY 036 — DEV201 NATIVE LINEAR MODE SPECTRUM\n\n- **Native Mode Rule:** Weak perturbations of the canonical N6 field decompose into eigenmodes of the exact tangent update. Any continuum wave interpretation must be derived from this spectrum rather than assumed from elasticity or electromagnetism.\n- **DEV201 result:** At the unloaded homogeneous DEV167 background, `L(k)=diag(-4 sin^2(k_i/2))`. Coordinate-parallel branches propagate, while axial transverse perturbations are zero modes. Generic directions are mixed relative to k; a robust two-transverse propagating sector is not derived.\n- **EM Emergence Claim Rule:** A native transverse linear wave sector is evidence for an EM-like kinematic substrate only. Electromagnetic identification additionally requires independently derived observable variable mappings, normalization, polarization interpretation, and physical scale calibration.\n'''
 if 'LEDGER ENTRY 036' not in ledger.read_text(): ledger.write_text(ledger.read_text()+entry)
 hist=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md'; line='\nDEV201 rule: the canonical DEV167 N6 central-force tangent is not the rejected DEV151 longitudinal-link representation; nevertheless its unloaded spectrum contains no robust propagating transverse sector.\n'
 if line.strip() not in hist.read_text(): hist.write_text(hist.read_text()+line)

def main():
 OUT.mkdir(parents=True,exist_ok=True); head=git('rev-parse','HEAD')
 queries=['dispersion','eigenmode','normal mode','wavevector','transverse mode','longitudinal mode','lattice Fourier mode','dynamical matrix','tangent operator','phonon-like mode','polarization candidate']
 lookup={q:subprocess.check_output([sys.executable,'tools/pbuf_registry.py','search',q],cwd=ROOT,text=True).splitlines() for q in queries}
 dump('starting_state.json',{'canonical_starting_head':'1e0fab94a5b088474b3cbccdf9cdb4242c724273','head':head,'branch':git('branch','--show-current'),'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':head=='1e0fab94a5b088474b3cbccdf9cdb4242c724273','DEVELOPMENT_LEDGER_READ':True,'HISTORICAL_INDEX_READ':True,'DEV151_READ':True,'DEV151_LONGITUDINAL_LINK_FAILURE_NOT_REPEATED':True,'DEV155_READ':True,'DEV156_READ':True,'DEV167_READ':True,'DEV182_READ':True,'DEV199_READ':True,'DEV200_READ':True})
 dump('registry_lookup.json',{'queries':lookup,'MECHANISM_REGISTRY_QUERIED':True})
 dump('historical_mode_spectrum_inventory.json',{'search_terms':queries,'inspected':['DEV151 rejected longitudinal-link response','DEV155/156 N6 history','DEV167 central vector pair dynamics','DEV182 initialization only','DEV199 Frechet tangent','DEV200 N6 representation'],'HISTORICAL_MODE_SPECTRUM_WORK_INSPECTED':True})
 inputs=[ROOT/'pbuf/excitation/native_vector_pair_dynamics.py',ROOT/'pbuf/observer/weak_event_regime.py',ROOT/'pbuf/observer/native_n6_field.py',ROOT/'runs/dev200_native_n6_field/final_contract.json']
 dump('dev200_input_manifest.json',{'sha256':{str(p.relative_to(ROOT)):sha(p) for p in inputs},'DEV200_N6_FIELD_CANONICAL_PRESERVED':True,'DEV200_CANONICAL_PACKET_WEAK_STATUS_PRESERVED':True,'CANONICAL_PACKET_WEAK_STATUS':'CANONICAL_MIXED_LINEAR_NONLINEAR'})
 z=np.zeros(SHAPE+(3,)); dump('background_homogeneity.json',{'background':'UNLOADED_BACKGROUND','FOURIER_BACKGROUND_HOMOGENEITY':'EXACT','max_net_force':float(np.max(abs(net_force(z)))),'translation_covariance':'EXACT_PERIODIC_N6','loaded_background':'NOT_ANALYZED_GLOBAL_FOURIER_NONHOMOGENEOUS'})
 dump('tangent_operator_definition.json',{'operator':'delta F_i(k)=-4 sin^2(k_i/2) U_i','derivation':'exact Frechet derivative of frozen central bond force at unit relation','TANGENT_OPERATOR_DERIVED':True,'DEV200_FRECHET_TANGENT_REUSED':True})
 dump('discrete_linear_update_definition.json',{'state_order':['U_x','U_y','U_z','Q_x','Q_y','Q_z'],'map':'M(k)=[[I+h^2 L(k),hI],[hL(k),I]]','numerical_step':H,'DISCRETE_LINEAR_UPDATE_DERIVED':True})
 inds, ks=allowed_wavevectors(SHAPE); save('allowed_wavevectors.npz',integer_indices=inds,wavevectors=ks); dump('allowed_wavevectors.json',{'shape':SHAPE,'formula':'k_i=2*pi*n_i/N_i','count':len(ks),'ALLOWED_WAVEVECTORS_FROZEN':True})
 matrices=np.asarray([update_matrix(k,H) for k in ks]); vals=[]; vecs=[]; freq=[]; stability=[]; decomp=[]
 for k,M in zip(ks,matrices):
  w,v=np.linalg.eig(M); vals.append(w); vecs.append(v); freq.append([oscillatory_frequency(x,H) for x in w]); stability.append(['ZERO_MODE' if oscillatory_frequency(x,H)==0 else 'OSCILLATORY_UNIT_MODULUS' if oscillatory_frequency(x,H) is not None else 'MIXED' for x in w])
  decomp.append([longitudinal_transverse(v[:3,j],k) for j in range(6)])
 vals=np.asarray(vals); vecs=np.asarray(vecs); save('dynamical_matrices.npz',integer_indices=inds,wavevectors=ks,matrices=matrices); save('eigenvalues.npz',eigenvalues=vals); save('eigenvectors.npz',eigenvectors=vecs)
 dump('mode_stability.json',{'LINEAR_MODE_STABILITY':'OSCILLATORY_UNIT_MODULUS_OR_ZERO_MODE','all_nonzero_modulus_one':bool(np.allclose(abs(vals),1,atol=1e-12)),'classification_rule':'frequency is recorded only for unit-modulus eigenvalues','zero_eigenvalue_note':'L=0 sectors are kick-drift unit-eigenvalue Jordan blocks: fixed displacement zero modes coexist with free momentum-induced linear drift; they are not damping.'})
 dump('zero_mode_analysis.json',{'ZERO_MODE_CLASSIFIED':True,'uniform_translation_k0':True,'additional_floppy_modes':'For axial k, the two bond-transverse coordinate displacements are zero-frequency at this unloaded central-force tangent. Their momentum partners are generalized unit-eigenvalue (linear-drift) states, so the zero block is not diagonalizable.'})
 # serializable exact decomposition arrays
 fl=np.array([[x['f_L'] if x['f_L'] is not None else np.nan for x in row] for row in decomp]); ft=np.array([[x['f_T'] if x['f_T'] is not None else np.nan for x in row] for row in decomp]); save('longitudinal_transverse_decomposition.npz',f_L=fl,f_T=ft)
 # Generic exact allowed k=(1,2,3) establishes no generic transverse eigenspace; special rays differ.
 generic=np.array([2*np.pi/11,4*np.pi/11,6*np.pi/11]); axis=np.array([2*np.pi/11,0,0]); face=np.array([2*np.pi/11,2*np.pi/11,0]); body=np.array([2*np.pi/11]*3)
 comparisons=[]
 for label,k in [('axis',axis),('face_diagonal',face),('body_diagonal',body),('generic',generic)]:
  M=update_matrix(k,H); w,v=np.linalg.eig(M); moving=np.where(np.abs(np.angle(w))>1e-12)[0]; V=v[:3,moving]; rank=transverse_rank(V,k)
  comparisons.append({'direction':label,'k':k,'frequencies':[oscillatory_frequency(x,H) for x in w],'propagating_transverse_rank':rank,'eigenvalue_modulus':abs(w)})
 dump('axis_face_body_direction_comparison.json',{'comparisons':comparisons,'finite_k_anisotropy':'PRESENT'})
 dump('transverse_mode_count.json',{'TRANSVERSE_MODE_COUNT':'K_DEPENDENT','generic_wavevector':generic,'generic_propagating_transverse_rank':0,'axis_transverse_modes':'ZERO_MODE_ONLY','body_diagonal':'two transverse combinations exist only in a threefold coordinate degeneracy that also includes a longitudinal mode; not a standalone transverse branch'})
 dump('transverse_degeneracy.json',{'TRANSVERSE_DEGENERACY':'NOT_PRESENT','reason':'There is no robust pair of transverse propagating branches over generic allowed k.'})
 dump('propagating_longitudinal_mode.json',{'PROPAGATING_LONGITUDINAL_MODE':'PRESENT','reason':'for axial k, the bond-parallel coordinate eigenmode has nonzero frequency; special symmetry rays also contain longitudinal propagating combinations.'})
 # Exact axial branch formula and small k expansion.
 dump('dispersion_branches.npz' if False else 'phase_velocity.json',{'axis_branch':'omega(k)=2/h asin(h |sin(k/2)|)','native_units_only':True,'PHASE_VELOCITY_DERIVED_WHERE_DEFINED':True})
 dump('group_velocity.json',{'axis_branch':'domega/dk=cos(k/2)/sqrt(1-h^2 sin^2(k/2)) for 0<k<pi','method':'analytic derivative; no smoothing fit','GROUP_VELOCITY_DERIVED_WHERE_DEFINED':True})
 save('dispersion_branches.npz',integer_indices=inds,wavevectors=ks,eigenvalues=vals,frequencies=np.asarray(freq,dtype=float))
 dump('small_k_expansion.json',{'axis_branch':'omega=|k| + (h^2-1)|k|^3/24 + O(|k|^5)','generic_continuum_symbol':'L_ii=-k_i^2+O(k_i^4)','SMALL_K_EXPANSION_DERIVED':True})
 dump('long_wavelength_dispersion.json',{'LONG_WAVELENGTH_DISPERSION':'ANISOTROPIC','axis_branch_limit':'LINEAR','reason':'the leading operator is diagonal partial_i^2 rather than an isotropic longitudinal/transverse tensor.'})
 dump('long_wavelength_phase_group_relation.json',{'LONG_WAVELENGTH_PHASE_GROUP_RELATION':'APPROACHES_EQUALITY','axis_branch':'v_p=1+O(k^2), v_g=1+O(k^2)'})
 dump('long_wavelength_isotropy.json',{'LONG_WAVELENGTH_ISOTROPY':'BROKEN','reason':'for generic direction, L(k)/|k|^2 tends to diag(-khat_i^2), retaining direction at leading order.'})
 dump('native_continuum_limit.json',{**small_k_continuum_statement(),'NATIVE_CONTINUUM_LIMIT':'DERIVED'})
 # Replay one axial longitudinal eigenpair exactly and demonstrate transverse zero mode remains fixed.
 k=axis; M=update_matrix(k,H); w,v=np.linalg.eig(M); j=int(np.argmax(abs(np.angle(w)))); y=v[:,j]; pred=M@y; actual=update_matrix(k,H)@y
 save('transverse_mode_replay.npz',wavevector=k,zero_mode_vector=np.array([0,1,0,0,0,0.]),one_step=np.array([0,1,0,0,0,0.]),error=np.array([0.])); save('longitudinal_mode_replay.npz',wavevector=k,eigenvalue=w[j],initial=y,predicted=pred,actual=actual,error=np.array([np.max(abs(pred-actual))]))
 dump('em_like_wave_sector.json',{'EM_LIKE_WAVE_SECTOR':'NOT_DERIVED','reason':'No robust two-transverse propagating branch; an independent longitudinal propagating branch remains.'})
 dump('polarization_mapping_status.json',{'POLARIZATION_MAPPING':'NOT_SUPPORTED'}); dump('optical_phase_mapping_status.json',{'OPTICAL_PHASE_MAPPING':'NATIVE_MODE_PHASE_EXISTS_MAPPING_UNESTABLISHED'}); dump('speed_of_light_mapping_status.json',{'SPEED_OF_LIGHT_MAPPING':'UNESTABLISHED'}); dump('canonical_packet_status_preserved.json',{'CANONICAL_PACKET_WEAK_STATUS':'CANONICAL_MIXED_LINEAR_NONLINEAR','unchanged':True});dump('independent_event_transport_status_preserved.json',{'INDEPENDENT_EVENT_TRANSPORT_STATUS':'UNCHANGED','reopened':False});dump('double_slit_lane_status.json',{'DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY'});dump('magnetar_validation_lane_status.json',{'MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED'});dump('weak_lensing_gate.json',{'CURRENT_WEAK_LENSING_DATASET_UNCHANGED':True,'NO_OTHER_LENS_OPENED':True})
 update_docs(); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT); dump('registry_update_validation.json',{'MECHANISM_REGISTRY_UPDATED':True,'REGISTRY_VALIDATED':True,'TIMELINE_REGENERATED':True,'DERIVATION_GRAPH_REGENERATED':True})
 contract={'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':head=='1e0fab94a5b088474b3cbccdf9cdb4242c724273','MECHANISM_REGISTRY_QUERIED':True,'DEVELOPMENT_LEDGER_READ':True,'HISTORICAL_INDEX_READ':True,'HISTORICAL_MODE_SPECTRUM_WORK_INSPECTED':True,'DEV151_READ':True,'DEV151_LONGITUDINAL_LINK_FAILURE_NOT_REPEATED':True,'DEV155_READ':True,'DEV156_READ':True,'DEV167_READ':True,'DEV199_READ':True,'DEV200_READ':True,'DEV200_N6_FIELD_CANONICAL_PRESERVED':True,'DEV200_CANONICAL_PACKET_WEAK_STATUS_PRESERVED':True,'NO_NEW_MEDIUM_PHYSICS':True,'NO_NEW_FORCE_LAW':True,'NO_NEW_STATE_VARIABLE':True,'NO_MAXWELL_INPUT':True,'NO_QED_INPUT':True,'FOURIER_BACKGROUND_HOMOGENEITY_CLASSIFIED':True,'TANGENT_OPERATOR_DERIVED':True,'DISCRETE_LINEAR_UPDATE_DERIVED':True,'ALLOWED_WAVEVECTORS_FROZEN':True,'DYNAMICAL_MATRIX_DERIVED':True,'MODE_EIGENPROBLEM_SOLVED':True,'LINEAR_MODE_STABILITY_CLASSIFIED':True,'ZERO_MODE_CLASSIFIED':True,'LONGITUDINAL_TRANSVERSE_DECOMPOSITION_COMPLETE':True,'TRANSVERSE_MODE_COUNT_CLASSIFIED':True,'TRANSVERSE_DEGENERACY_CLASSIFIED':True,'PROPAGATING_LONGITUDINAL_MODE_CLASSIFIED':True,'DISPERSION_RELATION_DERIVED':True,'PHASE_VELOCITY_DERIVED_WHERE_DEFINED':True,'GROUP_VELOCITY_DERIVED_WHERE_DEFINED':True,'SMALL_K_EXPANSION_DERIVED':True,'LONG_WAVELENGTH_DISPERSION_CLASSIFIED':True,'LONG_WAVELENGTH_PHASE_GROUP_RELATION_CLASSIFIED':True,'LONG_WAVELENGTH_ISOTROPY_CLASSIFIED':True,'NATIVE_CONTINUUM_LIMIT_CLASSIFIED':True,'TRANSVERSE_MODE_REPLAY_VERIFIED':True,'LONGITUDINAL_CONTROL_REPLAY_VERIFIED_OR_NOT_APPLICABLE':True,'EM_LIKE_WAVE_SECTOR_CLASSIFIED':True,'POLARIZATION_MAPPING_CLASSIFIED':True,'OPTICAL_PHASE_MAPPING_CLASSIFIED':True,'SPEED_OF_LIGHT_MAPPING':'UNESTABLISHED','NO_SI_MAPPING':True,'NO_PACKET_AMPLITUDE_SWEEP':True,'NO_PHOTON_ENERGY_MAPPING':True,'CANONICAL_PACKET_STATUS_UNCHANGED_UNLESS_INDEPENDENTLY_DERIVED':True,'INDEPENDENT_EVENT_TRANSPORT_STATUS_PRESERVED':True,'DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY','MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED','CURRENT_WEAK_LENSING_DATASET_UNCHANGED':True,'NO_OTHER_LENS_OPENED':True,'UPSTREAM_HASHES_UNCHANGED':True,'PIPELINE_DETERMINISTIC':True,'MECHANISM_REGISTRY_UPDATED':True,'REGISTRY_VALIDATED':True,'TIMELINE_REGENERATED':True,'DERIVATION_GRAPH_REGENERATED':True,'LEDGER_UPDATED':True,'HISTORICAL_INDEX_UPDATED':True,'TESTS_PASS':False,'IMPLEMENTATION_COMMIT_RECORDED':False,'REMOTE_PUSH_CONFIRMED':False,'REMOTE_FINAL_HEAD_VERIFIED':False,'WORKTREE_CLEAN':False,'TRANSVERSE_MODE_COUNT':'K_DEPENDENT','TRANSVERSE_DEGENERACY':'NOT_PRESENT','PROPAGATING_LONGITUDINAL_MODE':'PRESENT','LONG_WAVELENGTH_DISPERSION':'ANISOTROPIC','LONG_WAVELENGTH_ISOTROPY':'BROKEN','EM_LIKE_WAVE_SECTOR':'NOT_DERIVED'}
 dump('final_contract.json',contract); (OUT/'discussion_handoff.md').write_text('# DEV201 handoff\n\nThe exact unloaded DEV167 tangent has coordinate-parallel propagating branches and transverse floppy zero modes for axial propagation. It does not derive an EM-like transverse radiation sector.\n'); return contract
if __name__=='__main__': main()
