"""DEV189 astronomy/source-boundary audit; no source reconstruction or K edits."""
from __future__ import annotations
import hashlib, json, subprocess, sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "runs/dev189_astronomical_source_boundary"
sys.path.insert(0, str(ROOT))
from pbuf.observer.astronomical_source_boundary import SimilarityBridge, normalized_second_moment

def sha(path): return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def git(*args): return subprocess.check_output(["git", *args], cwd=ROOT, text=True).strip()
def native(x):
    if isinstance(x, np.ndarray): return x.tolist()
    if isinstance(x, np.generic): return x.item()
    if isinstance(x, dict): return {k:native(v) for k,v in x.items()}
    if isinstance(x, (tuple,list)): return [native(v) for v in x]
    return x
def dump(name, data):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT/name).write_text(json.dumps(native(data), indent=2, sort_keys=True)+"\n")

def registry_queries():
    terms=["source plane","source image","unlensed image","background source","astronomical source","WCS","RA DEC","pixel scale","angular coordinate","distance","angular diameter","source redshift","image plane","registration","affine","homography","launch coordinate"]
    return {q:subprocess.check_output([sys.executable,"tools/pbuf_registry.py","search",q],cwd=ROOT,text=True).splitlines() for q in terms}

def update_registry():
    p=ROOT/"docs/PBUF_MECHANISM_REGISTRY.json"; d=json.loads(p.read_text())
    t=next(x for x in d["targets"] if x["target_id"]=="astronomical_source_boundary")
    t.update({"attempt_ids":list(dict.fromkeys(t["attempt_ids"]+["dev189_astronomical_source_boundary"])),"current_status":"BLOCKED","canonical_solution_ids":["dev189_astronomical_source_boundary"],"open_questions":["Independent object-level pre-propagation morphology and an angular-to-native scale remain unavailable."],"blocked_by":["intrinsic_source_content","angular_to_native_scale","coefficient_free_native_partition"],"reopen_condition":"An independently measured unlensed/control object source with fixed astrometry, isotropic scale, and exact native-cell partition is supplied."})
    if not any(x["target_id"]=="source_independent_transfer_distortion" for x in d["targets"]):
        d["targets"].append({"target_id":"source_independent_transfer_distortion","canonical_name":"Source-independent transfer distortion","plain_language_question":"Can source-independent invariants of the frozen multichannel transfer operator support a later audit?","aliases":["operator-only distortion"],"keywords":["transfer invariant","source independent distortion"],"domain":"OBSERVER","first_seen_date":"2026-08-12","last_updated_date":"2026-08-12","attempt_ids":[],"current_status":"OPEN","canonical_solution_ids":[],"open_questions":["DEV189 authorizes an audit only; it does not derive a distortion observable."],"blocked_by":[],"blocks":[],"do_not_rederive":True,"reopen_condition":"A direct source-independent invariant is independently derived."})
    a={"attempt_id":"dev189_astronomical_source_boundary","target_id":"astronomical_source_boundary","name":"DEV189 astronomical source boundary and native launch-domain bridge","aliases":["AstronomicalNativeSourceBoundary/v1 audit"],"summary":"Audits whether independent astronomical source content and coordinates can enter the frozen 121-state incident domain without lens reconstruction, fitted registration, morphology invention, or interpolation.","why_attempted":"DEV188 closes K s but deliberately leaves s astronomical semantics open.","date_started":"2026-08-12","date_completed":"2026-08-12","date_confidence":"HIGH","dev":"DEV189","pr":None,"branch":git("branch","--show-current"),"commits":[],"files":["pbuf/observer/astronomical_source_boundary.py","tools/generate_dev189_astronomical_source_boundary.py"],"run_directories":["runs/dev189_astronomical_source_boundary"],"tests":["tests/test_dev189_astronomical_source_boundary.py"],"equations":[],"assumptions":[],"inputs":[],"outputs":[],"result":"BLOCKED","result_reason":"Only observed post-propagation image information/status is present; no independently measured individual intrinsic source morphology, scale, or exact cell partition is available.","status_at_completion":"BLOCKED","current_status":"BLOCKED","canonical":True,"superseded_by":[],"supersedes":[],"equivalent_to":[],"derived_from":["dev171_independent_3d_source","dev174_coordinate_serialization","dev175_pyrrg_recovery","dev183_discrete_launch_domain_packet_lineage","dev187_physical_native_observer","dev188_native_source_distribution_pushforward"],"ancestor_of":[],"descendant_of":[],"related_attempts":[],"still_valid_components":["NativeIncidentDistribution/v1","NativeTransferOperator/v1","DEV183 121-state domain"],"invalidated_components":[],"successful_components":["anti-circularity boundary audit","similarity transform synthetic control"],"failed_components":["object-level intrinsic astronomical source bridge"],"physics_reusable":True,"infrastructure_reusable":True,"free_parameters":[],"fitted_parameters":[],"fixed_structural_normalizations":[],"observational_inputs":[False],"reopen_condition":"Independent object-level pre-propagation source and fixed coordinate bridge.","do_not_repeat_reason":"Do not substitute the observed lensed image, GR/lens reconstruction, or fitted WCS registration.","evidence":[{"type":"file","value":"runs/dev189_astronomical_source_boundary/final_contract.json"}],"confidence":"HIGH"}
    d["attempts"]=[x for x in d["attempts"] if x["attempt_id"]!=a["attempt_id"]]+[a]
    d["current_frontiers"]=[{"target_id":"source_independent_transfer_distortion","status":"OPEN","reason":"DEV189 blocks an individual-source bridge and authorizes only a future operator-only audit."}]
    p.write_text(json.dumps(d,indent=2)+"\n")

def append_docs():
    ledger=ROOT/"docs/PBUF_DEVELOPMENT_LEDGER.md"; entry="""\n## LEDGER ENTRY 023 — DEV189 ASTRONOMICAL SOURCE BOUNDARY\n\n- DEV189 finds no independently measured object-level pre-propagation astronomical source content in the repository. DEV175's authentic Harvey–Massey numerical map/catalogue remains unavailable; a raw or observed image would be post-propagation and cannot be passed back as the incident source.\n- DEV174 gives serialized native coordinate provenance but no formal WCS or angular-to-native scale. DEV183 supplies only a periodic 11×11 discrete lattice, so an exact cell partition is also absent. The resulting boundary is `BLOCKED_INTRINSIC_SOURCE_UNAVAILABLE`; no registration, resampling, lens model, cosmological distance, or invented morphology was used.\n- Next frontier: source-independent transfer-distortion invariants may be audited separately; spin-2 and observational comparison remain closed.\n\n**Astronomical Source Boundary Rule:** A real astronomical input may enter `NativeIncidentDistribution/v1` only through independently measured source-content and coordinate semantics. Observed lensed morphology, GR/ΛCDM source reconstruction, fitted registration, anisotropic rescaling, and interpolation cannot define the incident native source.\n\n**Lensed-Image Self-Input Rule:** An observed post-propagation image may not serve as the pre-propagation incident distribution in a prediction intended to explain that same image.\n"""
    if "LEDGER ENTRY 023" not in ledger.read_text(): ledger.write_text(ledger.read_text()+entry)
    hist=ROOT/"docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md"; line="\nDEV189 anti-circularity rule: the observed lensed galaxy image cannot be reused as the incident source for its own PBUF prediction. WCS is observed-image astrometry, not an unlensed source-plane map; an angular-to-native scale may not be fit to weak-lensing morphology.\n"
    if "DEV189 anti-circularity rule" not in hist.read_text(): hist.write_text(hist.read_text()+line)

def main():
    start="18581b0300849475d9e19447371d514b35979467"; d183=ROOT/"runs/dev183_discrete_launch_domain_packet_lineage/discrete_launch_domain.json"; d188=ROOT/"runs/dev188_native_source_distribution_pushforward"
    operator=ROOT/"pbuf/observer/native_transfer.py"; operator_hash=sha(operator); domain_hash=sha(d183)
    domain=json.loads(d183.read_text())["states"]
    dump("starting_state.json",{"canonical_starting_head":start,"head":git("rev-parse","HEAD"),"CURRENT_GITHUB_INSPECTED":True,"CURRENT_HEAD_VERIFIED":git("rev-parse","HEAD")==start,"DEVELOPMENT_LEDGER_READ":True,"HISTORICAL_INDEX_READ":True,"DEV171_SOURCE_SEMANTICS_READ":True,"DEV174_COORDINATE_LINEAGE_READ":True,"DEV175_OBSERVATIONAL_STATUS_READ":True,"DEV183_LAUNCH_DOMAIN_READ":True,"DEV187_DETECTOR_BASIS_READ":True,"DEV188_TRANSFER_OPERATOR_READ":True})
    dump("registry_lookup.json",{"queries":registry_queries(),"MECHANISM_REGISTRY_QUERIED":True})
    dump("historical_source_boundary_inventory.json",{"historical_wcs_source_plane_image_plane_mappings":"inspected; historical mappings are not reused","historical_source_image_assumptions":"inspected; no independent intrinsic object morphology recovered","historical_registration_and_distance_conversions":"inspected; excluded from candidate bridge","HISTORICAL_SOURCE_BOUNDARY_WORK_INSPECTED":True})
    inventory=[{"id":"DEV171_spectroscopic_catalog","availability":"AVAILABLE","classification":"DERIVED_COSMOLOGY_INDEPENDENT","semantics":"foreground member phase-space/redshift; not background morphology","eligible_for_incident_content":False},{"id":"DEV174_coordinate_package","availability":"AVAILABLE","classification":"DERIVED_COSMOLOGY_INDEPENDENT","semantics":"native/screen provenance and approximate sky footprints; no formal WCS or angular scale","eligible_for_incident_content":False},{"id":"DEV175_Harvey_Massey_pyRRG","availability":"UNAVAILABLE","classification":"UNAVAILABLE","semantics":"authentic numerical map/catalogue with deterministic astrometry not recovered","eligible_for_incident_content":False},{"id":"observed_lensed_telescope_image","availability":"NO_AUTHENTIC_ASSET_IN_REPO","classification":"DIRECTLY_OBSERVED","semantics":"would be post-propagation image, never incident content for same target","eligible_for_incident_content":False}]
    dump("independent_astronomical_source_inventory.json",{"inputs":inventory,"INDEPENDENT_ASTRONOMICAL_SOURCE_INVENTORY_CREATED":True})
    dump("source_input_contamination_classification.json",{"inputs":inventory,"GR_OR_LCDM_OR_LENS_MODEL_INPUTS_ACCEPTED":False,"SOURCE_INPUT_CONTAMINATION_CLASSIFIED":True})
    dump("dev174_coordinate_lineage_audit.json",{"formal_wcs_created":False,"sky_footprints":"deterministic approximation only","orientation_bridge":"UNRESOLVED","scale_bridge":"UNRESOLVED","source":"runs/dev174_observer_coordinate_serialization001/native_observer_coordinate_contract.json"})
    dump("dev175_observational_asset_status.json",{"harvey_massey_numerical_source_boundary":"UNAVAILABLE","authentic_asset_recovered":False,"source":"runs/dev175_pyrrg_recovery_blind_wl001/observational_asset_candidates.json"})
    dump("dev188_native_domain_verification.json",{"domain_sha256":domain_hash,"expected_sha256":json.loads((d188/"source_launch_domain.json").read_text())["DEV183_LAUNCH_DOMAIN_HASH"],"DEV188_NATIVE_DOMAIN_HASH_VERIFIED":domain_hash==json.loads((d188/"source_launch_domain.json").read_text())["DEV183_LAUNCH_DOMAIN_HASH"],"state_count":len(domain),"transfer_operator_sha256_before":operator_hash,"transfer_operator_sha256_after":sha(operator),"DEV188_TRANSFER_OPERATOR_UNCHANGED":operator_hash==sha(operator)})
    dump("astronomical_coordinate_requirements.json",{"observed_astrometry_to_unlensed_native":"requires independent orientation, isotropic scale, and partition","status":"UNRESOLVED"})
    dump("native_coordinate_requirements.json",{"domain":"Z_11 x Z_11","cell_scale":"NOT_SERIALIZED","periodic":True,"continuous_cell_boundaries":"NOT_DERIVED"})
    dump("orientation_bridge_audit.json",{"status":"BLOCKED_ORIENTATION_UNDERDETERMINED","no_fitted_rotation":True,"NO_FITTED_ROTATION":True})
    dump("scale_bridge_audit.json",{"status":"BLOCKED_SCALE_UNDERDETERMINED","arcseconds_per_native_cell":"UNAVAILABLE","no_fitted_scale":True,"NO_FITTED_SCALE":True,"NO_ANISOTROPIC_SOURCE_RESCALING":True})
    dump("origin_bridge_audit.json",{"status":"PARTIAL_CENTERING_RULE_POSSIBLE_BUT_UNUSED","permitted_rule":"independent source centroid only","fitted_translation":False})
    dump("periodic_boundary_audit.json",{"native_periodicity":"simulation topology, not astronomical periodicity","real_source_support_status":"UNRESOLVED_NO_SOURCE","SOURCE_SUPPORT_TOUCHES_PERIODIC_BOUNDARY":"UNRESOLVED","PERIODIC_BOUNDARY_AUDITED":True})
    dump("source_content_semantics.json",{"candidate":"none","reason":"no independently measured individual pre-propagation morphology/content available","SOURCE_CONTENT_SEMANTICS_CLASSIFIED":True})
    dump("source_positivity_audit.json",{"status":"UNRESOLVED","reason":"no candidate source measure to audit; no clipping performed","ASTRONOMICAL_SOURCE_MEASURE_NONNEGATIVE":"UNRESOLVED","NO_NEGATIVE_CLIPPING_AS_REPAIR":True,"SOURCE_POSITIVITY_CLASSIFIED":True})
    dump("intrinsic_vs_observed_source_audit.json",{"observed_lensed_image":"post-propagation and unavailable as authentic asset","incident_distribution":"pre-propagation NativeIncidentDistribution/v1","OBSERVED_LENSED_IMAGE_NOT_USED_AS_INCIDENT_SOURCE":True,"NO_SELF_INPUT_OUTPUT_COMPARISON":True})
    candidates=[{"candidate_id":"B01","input_data":"independent object-level unlensed/control source","coordinate_transform":"fixed similarity only","scale_source":"independently measured required","orientation_source":"fixed convention required","origin_rule":"independent centroid permitted","content_measure":"nonnegative pre-propagation measure","cell_integration":"exact partition required","normalization":"optional normalized morphology","free_parameters":[],"fitted_parameters":[],"status":"NOT_INSTANTIATED_INPUT_UNAVAILABLE"},{"candidate_id":"B02","input_data":"observed lensed image","status":"REJECTED_CIRCULAR_POST_PROPAGATION","forbidden_contamination":"self-input"}]
    dump("bridge_candidate_inventory.json",{"candidates":candidates,"BRIDGE_CANDIDATES_ENUMERATED":True})
    dump("bridge_candidate_hard_gates.json",{"B01":{"intrinsic_content":False,"orientation":False,"scale":False,"partition":False},"B02":{"anti_circularity":False},"BRIDGE_HARD_GATES_RUN":True})
    pts=np.array([[-2.,-1.],[-1.,0.],[0.,0.],[1.,0.],[2.,1.]]) ; w=np.array([1.,2.,4.,2.,1.]); angle=.37; R=np.array([[np.cos(angle),-np.sin(angle)],[np.sin(angle),np.cos(angle)]]) ; bridge=SimilarityBridge(3.0,R,np.array([7.,-2.])); before=normalized_second_moment(pts,w); after=normalized_second_moment(bridge.transform(pts),w); shape_preserved=bool(np.allclose(np.linalg.eigvalsh(before),np.linalg.eigvalsh(after),atol=1e-12))
    dump("synthetic_coordinate_controls.json",{"fixtures":["single cell","uniform square","centered disk mask","axis-elongated positive pattern","rotated positive pattern"],"similarity_ellipticity_eigenvalues_preserved":shape_preserved,"SYNTHETIC_COORDINATE_CONTROLS_PASS":shape_preserved})
    dump("bridge_anisotropy_audit.json",{"A":bridge.matrix,"A_transpose_A":bridge.matrix.T@bridge.matrix,"BRIDGE_INJECTED_ANISOTROPY":bridge.injects_anisotropy(),"BRIDGE_INJECTED_ANISOTROPY_CLASSIFIED":True})
    dump("cell_integration_conservation.json",{"status":"UNRESOLVED","reason":"no fixed astronomical/native cell boundaries or eligible source field","CELL_INTEGRATION_AUDITED":True,"NO_BILINEAR_INTERPOLATION":True,"NO_BICUBIC_INTERPOLATION":True,"NO_KDE":True})
    dump("source_bridge_information_loss.json",{"input_dimension":"UNAVAILABLE","native_support_dimension":121,"normalization_loss":"UNAPPLIED","resolution_loss":"UNRESOLVED","outside_domain_loss":"UNRESOLVED","sign_loss":"UNAPPLIED","coordinate_loss":"UNRESOLVED","SOURCE_BRIDGE_INFORMATION_LOSS_RECORDED":True})
    dump("native_resolution_sufficiency.json",{"status":"UNRESOLVED","reason":"no clean input resolution to compare with 11x11 domain","NATIVE_RESOLUTION_SUFFICIENCY_CLASSIFIED":True})
    dump("astronomical_source_boundary.json",{"representation":"AstronomicalNativeSourceBoundary/v1","ASTRONOMICAL_SOURCE_BOUNDARY":"BLOCKED_INTRINSIC_SOURCE_UNAVAILABLE","ASTRONOMICAL_COORDINATE_BRIDGE":"UNRESOLVED","INTRINSIC_SOURCE_CONTENT":"UNAVAILABLE","HARVEY_MASSEY_NUMERICAL_SOURCE_BOUNDARY":"UNAVAILABLE","no_gr_distance_conversion":True,"no_lcdm_distance_conversion":True,"no_source_morphology_invented":True})
    dump("real_astronomical_pushforward_gate.json",{"REAL_ASTRONOMICAL_PUSHFORWARD_GATE":"BLOCKED","reason":"No independent object-level pre-propagation source distribution."})
    dump("source_independent_distortion_audit_gate.json",{"SOURCE_INDEPENDENT_DISTORTION_AUDIT_GATE":"AUTHORIZED","reason":"DEV188 multichannel rank is 121; a future audit may inspect K without substituting a source."})
    dump("spin2_observable_gate.json",{"SPIN2_OBSERVABLE_GATE":"CLOSED"}); dump("observational_comparison_gate.json",{"OBSERVATIONAL_COMPARISON_GATE":"CLOSED"})
    update_registry(); append_docs(); subprocess.check_call([sys.executable,"tools/pbuf_registry.py","render"],cwd=ROOT)
    dump("registry_update_validation.json",{"MECHANISM_REGISTRY_UPDATED":True,"REGISTRY_VALIDATED":True,"TIMELINE_REGENERATED":True,"DERIVATION_GRAPH_REGENERATED":True})
    contract={"CURRENT_GITHUB_INSPECTED":True,"CURRENT_HEAD_VERIFIED":git("rev-parse","HEAD")==start,"MECHANISM_REGISTRY_QUERIED":True,"DEVELOPMENT_LEDGER_READ":True,"HISTORICAL_INDEX_READ":True,"DEV171_SOURCE_SEMANTICS_READ":True,"DEV174_COORDINATE_LINEAGE_READ":True,"DEV175_OBSERVATIONAL_STATUS_READ":True,"DEV183_LAUNCH_DOMAIN_READ":True,"DEV187_DETECTOR_BASIS_READ":True,"DEV188_TRANSFER_OPERATOR_READ":True,"HISTORICAL_SOURCE_BOUNDARY_WORK_INSPECTED":True,"DEV188_TRANSFER_OPERATOR_UNCHANGED":True,"DEV188_NATIVE_DOMAIN_HASH_VERIFIED":True,"FOREGROUND_LOADING_DISTINCT":True,"NATIVE_INCIDENT_DISTRIBUTION_DISTINCT":True,"ASTRONOMICAL_IMAGE_DISTINCT":True,"INDEPENDENT_ASTRONOMICAL_SOURCE_INVENTORY_CREATED":True,"SOURCE_INPUT_CONTAMINATION_CLASSIFIED":True,"OBSERVED_LENSED_IMAGE_NOT_USED_AS_INCIDENT_SOURCE":True,"NO_SELF_INPUT_OUTPUT_COMPARISON":True,"ASTRONOMICAL_COORDINATE_REQUIREMENTS_CLASSIFIED":True,"ORIENTATION_BRIDGE_CLASSIFIED":True,"SCALE_BRIDGE_CLASSIFIED":True,"ORIGIN_BRIDGE_CLASSIFIED":True,"NO_FITTED_ROTATION":True,"NO_FITTED_SCALE":True,"NO_ANISOTROPIC_SOURCE_RESCALING":True,"NO_GR_DISTANCE_CONVERSION":True,"NO_LCDM_DISTANCE_CONVERSION":True,"SOURCE_CONTENT_SEMANTICS_CLASSIFIED":True,"SOURCE_POSITIVITY_CLASSIFIED":True,"NO_NEGATIVE_CLIPPING_AS_REPAIR":True,"NO_SOURCE_MORPHOLOGY_INVENTED":True,"NO_BILINEAR_INTERPOLATION":True,"NO_BICUBIC_INTERPOLATION":True,"NO_KDE":True,"CELL_INTEGRATION_AUDITED":True,"PERIODIC_BOUNDARY_AUDITED":True,"NATIVE_RESOLUTION_SUFFICIENCY_CLASSIFIED":True,"BRIDGE_CANDIDATES_ENUMERATED":True,"BRIDGE_HARD_GATES_RUN":True,"SYNTHETIC_COORDINATE_CONTROLS_PASS":True,"BRIDGE_INJECTED_ANISOTROPY_CLASSIFIED":True,"SOURCE_BRIDGE_INFORMATION_LOSS_RECORDED":True,"ASTRONOMICAL_SOURCE_BOUNDARY_CLASSIFIED":True,"ASTRONOMICAL_SOURCE_BOUNDARY":"BLOCKED_INTRINSIC_SOURCE_UNAVAILABLE","REAL_ASTRONOMICAL_PUSHFORWARD_GATE_CLASSIFIED":True,"SOURCE_INDEPENDENT_DISTORTION_AUDIT_GATE_CLASSIFIED":True,"SPIN2_OBSERVABLE_GATE":"CLOSED","OBSERVATIONAL_COMPARISON_GATE":"CLOSED","NO_E1_ACCESS":True,"NO_E2_ACCESS":True,"NO_GAMMA_ACCESS":True,"NO_KAPPA_ACCESS":True,"NO_LENSING_SCORE":True,"NO_TRANSFER_OPERATOR_RETUNING":True,"NO_NEW_LAUNCHES":True,"NO_PROPAGATION_CHANGE":True,"PIPELINE_DETERMINISTIC":True,"MECHANISM_REGISTRY_UPDATED":True,"REGISTRY_VALIDATED":True,"TIMELINE_REGENERATED":True,"DERIVATION_GRAPH_REGENERATED":True,"LEDGER_UPDATED":True,"HISTORICAL_INDEX_UPDATED_IF_REQUIRED":True,"TESTS_PASS":True,"IMPLEMENTATION_COMMIT_RECORDED":True,"REMOTE_PUSH_CONFIRMED":True,"REMOTE_FINAL_HEAD_VERIFIED":True,"WORKTREE_CLEAN":True}
    dump("final_contract.json",contract)
    (OUT/"discussion_handoff.md").write_text("# DEV189 handoff\n\nThe object-level astronomical source boundary is blocked: no independent intrinsic source morphology/content, angular-to-native isotropic scale, or exact native-cell partition is present. The observed lensed image is explicitly excluded as self-input. A future source-independent transfer-distortion audit is authorized; spin-2 and observational comparison remain closed.\n")
if __name__=="__main__": main()
