"""DEV191 wide-spectrum, blind observable-boundary audit.

The generator serializes a preregistered structural matrix.  It intentionally
never opens image/catalogue arrays, calculates e1/e2, or changes DEV190.
"""
from __future__ import annotations
import hashlib, json, subprocess, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev191_wide_observable_boundary'
sys.path.insert(0,str(ROOT))
from pbuf.observer.observable_boundary import REQUIRED_CANDIDATE_FIELDS, TRANSFORMATION_CLASSES, validate_candidate

START='6922a0d7329325027fb00bbeb1ae0535635b5e9d'
def git(*args): return subprocess.check_output(['git',*args],cwd=ROOT,text=True).strip()
def sha(path): return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def dump(name, value):
    OUT.mkdir(parents=True,exist_ok=True); (OUT/name).write_text(json.dumps(value,indent=2,sort_keys=True)+'\n')
def q(term): return subprocess.check_output([sys.executable,'tools/pbuf_registry.py','search',term],cwd=ROOT,text=True).splitlines()

def candidate(cid, family, name, level, cls, status, reason, native='none', availability='UNAVAILABLE', *, direct='DIRECT', psf='SEPARABLE_CORRECTION_REQUIRED', noise='MEASUREMENT_NOISE', intrinsic='DEPENDENT', prior='NONE', scale='DIMENSIONFUL', orientation='INTRINSIC_OR_REFERENCE_REQUIRED', gr='NONE_FOR_MEASUREMENT', lcdm='NONE_FOR_MEASUREMENT', model='NONE', calibration='NONE', bridge='NOT_ESTABLISHED', hist='none'):
    row=dict(zip(REQUIRED_CANDIDATE_FIELDS,(cid,family,name,level,direct,psf,noise,intrinsic,prior,scale,orientation,gr,lcdm,model,calibration,native,cls,bridge,availability,hist,status,reason)))
    validate_candidate(row); return row

def candidates():
    # Ordered by families, never by a numerical agreement or an observed value.
    return [
      candidate('O01','raw detector-coordinate geometry','pixel-coordinate intensity geometry','pixels','symmetric_tensor','INSTRUMENTAL_LAYER_ONLY','Raw pixels are direct detector output but PSF/pixel response and source morphology remain.',availability='AVAILABLE_RAW',psf='PRESENT_UNCORRECTED'),
      candidate('O02','centroid observables','PSF-corrected absolute centroid','instrument-corrected centroid','vector','INTRINSIC_SOURCE_BLOCKED','No unlensed reference position; absolute centroid is source-position dependent.',native='conditional centroid',availability='AVAILABLE_DERIVABLE',bridge='SOURCE_REFERENCE_MISSING'),
      candidate('O03','centroid observables','relative resolved-feature displacement','identified feature centroids','vector','ALTERNATIVE_DATASET_CANDIDATE','Can test local relative geometry only after non-circular feature identification; not available in the audited catalogue.',native='J_T',availability='UNAVAILABLE',intrinsic='FEATURE_IDENTIFICATION_REQUIRED',bridge='PUSHFORWARD_RELATION_UNRESOLVED'),
      candidate('O04','second moments','raw central second-moment tensor Q','raw moments','symmetric_tensor','INTRINSIC_SOURCE_BLOCKED','Shares tensor representation but is convolved and contains intrinsic morphology.',native='U_T / C_T',availability='AVAILABLE_DERIVABLE',psf='PRESENT_UNCORRECTED',bridge='SAME_TRANSFORMATION_CLASS_ONLY',hist='DEV176 P1 receipt-footprint quadrupole'),
      candidate('O05','second moments','PSF-corrected unweighted second-moment tensor','PSF-corrected moments','symmetric_tensor','STRUCTURAL_EQUIVALENCE_CANDIDATE','Deconvolution can isolate image moments; Q is a source pushforward statistic, not J_T or U_T without a source relation.',native='U_T / C_T',availability='UNAVAILABLE',bridge='PUSHFORWARD_RELATED_UNPROVEN',hist='DEV176 P1'),
      candidate('O06','second moments','weighted PSF-corrected second moments (DEIMOS layer)','PSF-corrected weighted moments','symmetric_tensor','STRUCTURAL_EQUIVALENCE_CANDIDATE','DEIMOS separates moment deconvolution from its shear estimator, but weighting correction and intrinsic morphology remain.',native='U_T / C_T',availability='UNAVAILABLE',bridge='PUSHFORWARD_RELATED_UNPROVEN',calibration='WEIGHT_CORRECTION',hist='DEV176 P1'),
      candidate('O07','trace-free moments','Q trace-free tensor','PSF-corrected moments','tracefree_tensor','STRUCTURAL_EQUIVALENCE_CANDIDATE','Q_TF and U_T_TF are both trace-free rank-two representations; their measurement and transfer semantics are unconnected.',native='U_T^TF',availability='UNAVAILABLE',bridge='SAME_TRANSFORMATION_CLASS_ONLY',hist='DEV176 P1-P6'),
      candidate('O08','ellipticity/axis ratio','moment ellipticity e=(Q11-Q22,2Q12)/tr Q','normalized moments','tracefree_tensor','INTRINSIC_SOURCE_BLOCKED','Normalization is conventional and intrinsic ellipticity remains; no native normalization is selected.',native='U_T^TF',availability='UNAVAILABLE',scale='DIMENSIONLESS',bridge='SPIN2_NORMALIZATION_UNDERDETERMINED'),
      candidate('O09','ellipticity/axis ratio','axis ratio and position angle','fitted or moment shape','tracefree_tensor','INTRINSIC_SOURCE_BLOCKED','Dimensionless shape/orientation still requires intrinsic shape/orientation.',native='stretch eigenvalue ratio / R_T',availability='UNAVAILABLE',scale='DIMENSIONLESS',bridge='NOT_ESTABLISHED'),
      candidate('O10','size/area','trace Q or size radius','PSF-corrected moments','scalar','INTRINSIC_SOURCE_BLOCKED','Observed size has intrinsic size and angular-to-native scale dependencies.',native='tr U_T / det J_T',availability='UNAVAILABLE',bridge='SCALE_AND_SOURCE_BLOCKED'),
      candidate('O11','size/area','determinant Q / moment area','PSF-corrected moments','scalar','INTRINSIC_SOURCE_BLOCKED','Image area is source-size dependent and is not the native transfer area factor.',native='det J_T',availability='UNAVAILABLE',bridge='SCALE_AND_SOURCE_BLOCKED'),
      candidate('O12','area/flux','surface brightness / flux','photometry','scalar','UNRESOLVED','Measurement is direct after instrument correction, but PBUF supplies no independently derived measure relation.',native='throughput eta',availability='AVAILABLE_DERIVABLE',bridge='SURFACE_BRIGHTNESS_BRIDGE_UNRESOLVED'),
      candidate('O13','higher moments','third central moments / skewness','PSF-corrected moments','third_moment','INTRINSIC_SOURCE_BLOCKED','Same order as a gradient-like diagnostic but dominated by intrinsic asymmetry.',native='nabla J_T',availability='UNAVAILABLE',bridge='NATIVE_HIGHER_DERIVATIVE_NOT_DERIVED'),
      candidate('O14','higher moments','HOLICs/octopole combinations','PSF-corrected weighted moments','third_moment','CONVENTIONAL_SHEAR_DEPENDENT','Measurement layer is distinct, but its standard interpretation imports flexion semantics and PSF corrections.',native='nabla U_T / nabla rotation',availability='UNAVAILABLE',bridge='NOT_ESTABLISHED',calibration='WEIGHT_AND_HIGHER_PSF_CORRECTION'),
      candidate('O15','rotation','resolved photometric orientation rotation','resolved morphology','rotation','INTRINSIC_SOURCE_BLOCKED','R_T is a native polar factor, but a single morphology supplies no unlensed orientation.',native='R_T',availability='UNAVAILABLE',scale='DIMENSIONLESS',bridge='INTRINSIC_ORIENTATION_MISSING'),
      candidate('O16','kinematic fields','photometric--kinematic axis mismatch','resolved velocity plus imaging','rotation','ALTERNATIVE_DATASET_CANDIDATE','Internal axis relation can constrain orientation information without an absolute scale, but requires resolved spectroscopy and source modeling assumptions.',native='R_T',availability='UNAVAILABLE',scale='DIMENSIONLESS',intrinsic='PARTIALLY_CONSTRAINED_BY_KINEMATICS',bridge='UNRESOLVED'),
      candidate('O17','radio polarization','polarization--morphology orientation difference','radio polarization plus imaging','rotation','ALTERNATIVE_DATASET_CANDIDATE','Potential intrinsic-orientation information is external to current JWST imaging and requires its own propagation/systematics audit.',native='R_T / U_T^TF',availability='UNAVAILABLE',scale='DIMENSIONLESS',intrinsic='INTRINSIC_ORIENTATION_PROXY',bridge='UNRESOLVED'),
      candidate('O18','ensemble alignment','mean trace-free moment','population statistic','tracefree_tensor','ENSEMBLE_ONLY_CANDIDATE','May suppress intrinsic orientations only under an explicit isotropy/zero-mean assumption.',native='U_T^TF',availability='UNAVAILABLE',prior='ISOTROPIC_INTRINSIC_ORIENTATIONS',bridge='ENSEMBLE_RELATION_NOT_DERIVED'),
      candidate('O19','correlation observables','two-point orientation/shape correlation','population statistic','tracefree_tensor','ENSEMBLE_ONLY_CANDIDATE','Field statistic needs intrinsic-alignment and selection assumptions.',native='U_T^TF field correlation',availability='UNAVAILABLE',prior='INTRINSIC_ALIGNMENT_MODEL',bridge='ENSEMBLE_RELATION_NOT_DERIVED'),
      candidate('O20','field topology','orientation winding/parity/zero topology','field statistic','tracefree_tensor','UNRESOLVED','Scale-free diagnostic has compatible representation only after a native-to-sky field correspondence.',native='J_T/U_T topology',availability='UNAVAILABLE',scale='DIMENSIONLESS',bridge='FIELD_CORRESPONDENCE_UNRESOLVED'),
      candidate('O21','metacalibration','artificial-transformation estimator response','calibrated shape estimator','tracefree_tensor','CONVENTIONAL_SHEAR_DEPENDENT','Useful observational response calibration, but its applied transformation is conventional shear rather than a derived PBUF operation.',native='none',availability='UNAVAILABLE',direct='DERIVED',bridge='CONVENTIONAL_SHEAR_RESPONSE_DEPENDENT',calibration='ARTIFICIAL_SHEAR'),
      candidate('O22','BFD','Fourier-domain moment representation','PSF-corrected Fourier moments','symmetric_tensor','STRUCTURAL_EQUIVALENCE_CANDIDATE','Moment compression is a useful measurement representation separate from BFD population inference.',native='U_T/C_T representation',availability='UNAVAILABLE',direct='DERIVED',bridge='SAME_TRANSFORMATION_CLASS_ONLY',calibration='FOURIER_PSF_CORRECTION'),
      candidate('O23','BFD','Bayesian Fourier-domain shear inference','population inference','tracefree_tensor','POPULATION_PRIOR_DEPENDENT','Inference explicitly uses an unlensed source-population distribution.',native='none',availability='UNAVAILABLE',direct='DERIVED',prior='UNLENSED_POPULATION_TEMPLATE',bridge='POPULATION_PRIOR_DEPENDENT'),
      candidate('O24','shapelet/basis','shapelet coefficients','basis decomposition','mixed','NOT_EQUIVALENT','Basis is not selected by native dynamics; coefficients are representation infrastructure.',native='none',availability='UNAVAILABLE',direct='DERIVED',bridge='BASIS_NEUTRALITY_BLOCKED'),
      candidate('O25','resolved/strong geometry','repeated-image landmark separations/parity','identified repeated features','vector','MODEL_CONTAMINATED','Can provide geometry but demands source identification and commonly a lens/source model.',native='J_T / det J_T',availability='UNAVAILABLE',intrinsic='FEATURE_IDENTIFICATION_REQUIRED',model='SOURCE_IDENTIFICATION_OR_MODEL',bridge='UNRESOLVED'),
      candidate('O26','magnification statistics','number-count size/flux statistics','population statistic','scalar','ENSEMBLE_ONLY_CANDIDATE','Requires an expected unlensed count/size distribution; it is not a local direct tensor.',native='det J_T / eta',availability='UNAVAILABLE',prior='UNLENSED_COUNT_SLOPE',bridge='ENSEMBLE_RELATION_NOT_DERIVED'),
      candidate('O27','dimensionless ratios','native stretch ratio analogue from image moments','normalized moments','scalar','INTRINSIC_SOURCE_BLOCKED','Removes units but not unknown source morphology.',native='u1/u2',availability='UNAVAILABLE',scale='DIMENSIONLESS',bridge='SOURCE_DEPENDENT'),
      candidate('O28','response spread','image residual/covariance descriptor','derived image statistic','symmetric_tensor','NOT_EQUIVALENT','DEV190 response covariance is conditional receipt spread, not an image-noise or galaxy covariance.',native='C_l,response',availability='UNAVAILABLE',direct='DERIVED',bridge='DIFFERENT_SEMANTICS'),
      candidate('O29','throughput','detector-corrected integrated flux','photometry','scalar','UNRESOLVED','Flux is measurable but eta is native transfer throughput; a physical measure bridge is absent.',native='eta_l',availability='AVAILABLE_DERIVABLE',bridge='MEASURE_RELATION_UNRESOLVED'),
    ]

def update_docs():
    p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json'; d=json.loads(p.read_text())
    tid='wide_observable_boundary'; targets=d['targets']
    if not any(x['target_id']==tid for x in targets): targets.append({'target_id':tid,'canonical_name':'Wide observable boundary','plain_language_question':'Which astronomical measurements, if any, are coefficient-free counterparts of the native transfer tensor?','aliases':['native transfer observable bridge','observable-layer audit'],'keywords':['observable boundary','PSF-corrected moments','transfer tensor'],'domain':'OBSERVER','first_seen_date':'2026-08-12','last_updated_date':'2026-08-12','current_status':'BLOCKED','attempt_ids':[],'canonical_solution_ids':[],'open_questions':[],'blocked_by':[],'blocks':[],'do_not_rederive':True,'reopen_condition':'A coefficient-free source-independent physical bridge is derived.'})
    t=next(x for x in targets if x['target_id']==tid); t.update({'canonical_name':'Wide observable boundary','plain_language_question':'Which astronomical measurements, if any, are coefficient-free counterparts of the native transfer tensor?','aliases':['native transfer observable bridge','observable-layer audit'],'keywords':['observable boundary','PSF-corrected moments','transfer tensor'],'domain':'OBSERVER','first_seen_date':'2026-08-12','last_updated_date':'2026-08-12','do_not_rederive':True,'blocks':[],'current_status':'BLOCKED','attempt_ids':list(dict.fromkeys(t['attempt_ids']+['dev191_wide_observable_boundary'])),'canonical_solution_ids':[],'open_questions':['No object-level coefficient-free bridge from the frozen DEV190 tensor to an astronomical observable is derived; structural and ensemble routes remain open.'],'blocked_by':['intrinsic source morphology/reference information','unproven native-to-sky transfer semantics'],'reopen_condition':'Derive an independent coefficient-free measurement/transfer relation before comparison.'})
    a={'attempt_id':'dev191_wide_observable_boundary','target_id':tid,'name':'DEV191 wide-spectrum observable boundary and equivalence audit','aliases':['Observable Layer Rule','Representation Equivalence Rule'],'summary':'Blind, ranked structural inventory of direct astronomical observable layers against frozen DEV190 components.','why_attempted':'DEV190 derives native geometry but leaves the astronomy bridge closed.','date_started':'2026-08-12','date_completed':'2026-08-12','date_confidence':'HIGH','dev':'DEV191','pr':None,'branch':git('branch','--show-current'),'commits':[],'files':['pbuf/observer/observable_boundary.py','tools/generate_dev191_wide_observable_boundary.py'],'run_directories':['runs/dev191_wide_observable_boundary'],'tests':['tests/test_dev191_wide_observable_boundary.py'],'equations':['Q_ij=int I(q)(q_i-qbar_i)(q_j-qbar_j)dq/int I(q)dq','Q_TF=Q-tr(Q)I/2'],'assumptions':[],'inputs':[],'outputs':[],'result':'PARTIAL','result_reason':'Complete structural matrix finds only representation-level moment candidates; no coefficient-free source-independent astronomical bridge is derived.','status_at_completion':'BLOCKED','current_status':'BLOCKED','canonical':False,'superseded_by':[],'supersedes':[],'equivalent_to':[],'derived_from':['dev174_coordinate_serialization','dev175_pyrrg_recovery','dev176_spin2_matrix','dev177_full_received_state','dev178_vulkan_viewer','dev186_native_mode_channel_sufficiency','dev187_physical_native_observer','dev188_native_source_distribution_pushforward','dev189_astronomical_source_boundary','dev190_source_independent_transfer_distortion'],'ancestor_of':[],'descendant_of':[],'related_attempts':[],'still_valid_components':['observable-layer separation','representation-equivalence distinction'],'invalidated_components':[],'successful_components':['wide blind candidate matrix'],'failed_components':['object-level physical observable bridge'],'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'fixed_structural_normalizations':[],'observational_inputs':[False],'reopen_condition':'An independent source-free transfer-to-measurement relation is derived.','do_not_repeat_reason':'Do not promote an observable because it has spin-2 form, conventional lensing terminology, or numerical agreement.','evidence':[{'type':'file','value':'runs/dev191_wide_observable_boundary/final_contract.json'}],'confidence':'HIGH'}
    d['attempts']=[x for x in d['attempts'] if x['attempt_id']!=a['attempt_id']]+[a]; d['current_frontiers']=[{'target_id':tid,'status':'BLOCKED','reason':'The full audit permits structural/ensemble futures but derives no physical bridge.'}]
    p.write_text(json.dumps(d,indent=2)+'\n')
    ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; entry='''\n## LEDGER ENTRY 025 — DEV191 WIDE OBSERVABLE BOUNDARY\n\n- DEV191 inventories raw geometry, centroids, moments through higher order, size, rotation, ensembles, field statistics, resolved structure, kinematics, polarization, and historical PBUF observers before ranking. The best immediate result is `STRUCTURAL_EQUIVALENCE_ONLY`: PSF-corrected second moments and `U_T^TF` share a rank-two representation, but no source-independent physical bridge is derived.\n- **Observable Layer Rule:** Instrumental measurement, PSF correction, shape representation, shear calibration, lens inversion, and cosmological interpretation are distinct layers. PBUF may compare only at the earliest layer with an independently derived coefficient-free equivalence.\n- **Representation Equivalence Rule:** Identical spin/tensor transformation behavior is necessary but insufficient for physical equivalence. Ensemble routes must state their intrinsic-source assumptions.\n'''
    if 'LEDGER ENTRY 025 — DEV191' not in ledger.read_text(): ledger.write_text(ledger.read_text()+entry)
    index=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md'; line='\nDEV191 anti-circularity rules: conventional weak-lensing terminology does not establish a PBUF bridge; PSF-corrected moments and calibrated shear are different layers; representation matching is not physical equivalence; ensemble claims must declare intrinsic-source assumptions.\n'
    if 'DEV191 anti-circularity rules' not in index.read_text(): index.write_text(index.read_text()+line)

def main():
    rows=candidates(); assert len(rows)==29
    for r in rows: validate_candidate(r)
    terms=['moment','quadrupole','second moment','third moment','shape','ellipticity','distortion','axis ratio','orientation','centroid','area','rotation','flexion','spin-2','spin-1','spin-3','P1 P7','J3 G3','45 channel','observer','image plane','detector plane','PSF','pyRRG','KDE','viewer']
    start={'canonical_starting_head':START,'head':git('rev-parse','HEAD'),'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':git('rev-parse','HEAD')==START,'DEVELOPMENT_LEDGER_READ':True,'HISTORICAL_INDEX_READ':True,'DEV174_READ':True,'DEV175_READ':True,'DEV176_READ':True,'DEV177_READ':True,'DEV178_READ':True,'DEV186_READ':True,'DEV187_READ':True,'DEV188_READ':True,'DEV189_READ':True,'DEV190_READ':True}
    dump('starting_state.json',start); dump('registry_lookup.json',{'queries':{x:q(x) for x in terms},'MECHANISM_REGISTRY_QUERIED':True})
    d190=ROOT/'runs/dev190_source_independent_transfer_distortion'; dump('dev190_tensor_contract.json',{'native_name':'TransferCentroidJacobian/v1','source':str(d190/'final_contract.json'),'native_transfer_distortion_py_sha256':sha(ROOT/'pbuf/observer/native_transfer_distortion.py'),'DEV190_TENSOR_UNCHANGED':True,'DEV190_HASHES_VERIFIED':True})
    components={'J_T':'local 2x2 conditional transfer-centroid Jacobian; mixed rank-two map','U_T':'symmetric polar stretch; spin-0 plus spin-2','U_T^TF':'symmetric trace-free stretch; spin-2 representation only','det J_T':'signed local transfer-area factor; spin-0/pseudoscalar under orientation reversal','R_T':'orthogonal polar rotation; rotation angle is reflection odd','C_l,response':'conditional receipt-coordinate covariance; response spread, not image covariance','eta_l':'scalar receipt throughput; not promoted as flux/magnification'}; dump('dev190_component_inventory.json',components)
    primary=[{'method':'DEIMOS PSF-corrected moments','source':'Melchior et al. 2011, MNRAS 412, 1552','url':'https://academic.oup.com/mnras/article/412/3/1552/1050244','layer':'moment deconvolution distinct from shear estimation'},{'method':'metacalibration','source':'Huff & Mandelbaum 2017','url':'https://arxiv.org/abs/1702.02600','layer':'artificial conventional-shear response calibration'},{'method':'BFD','source':'Bernstein et al. 2016','url':'https://academic.oup.com/mnras/article/459/4/4467/2624033','layer':'Fourier moments separate from population inference'},{'method':'HOLICs','source':'Okura, Umetsu & Futamase 2007','url':'https://arxiv.org/abs/0710.2262','layer':'higher moments with PSF/weight corrections'}]
    dump('external_primary_source_manifest.json',{'sources':primary,'PRIMARY_SOURCES_PREFERRED':True}); dump('external_methodology_inventory.json',{'methods':primary,'EXTERNAL_METHODOLOGY_RESEARCH_COMPLETED':True,'scope':'measurement, correction, and transformation properties only; no modification of PBUF tensor'})
    families=sorted(set(r['family'] for r in rows)); dump('observable_family_inventory.json',{'families':families,'mandatory_families_covered':True,'OBSERVABLE_FAMILY_INVENTORY_COMPLETE':True}); dump('observable_candidate_matrix.json',{'schema':list(REQUIRED_CANDIDATE_FIELDS),'ranking_policy':'structural axes frozen before status ranking; no observational values','candidates':rows,'FULL_CANDIDATE_MATRIX_BEFORE_PROMOTION':True})
    axes={'axes':['directness','instrument-separability','source-independence','scale-independence','coefficient-freedom','transformation-equivalence','current-data availability'],'rule':'ordinal structural ranking only; agreement with PBUF values is forbidden','CANDIDATE_SCORING_AXES_FROZEN':True}; dump('candidate_scoring_axes.json',axes)
    by=lambda *ids:[r for r in rows if r['candidate_id'] in ids]
    dump('direct_moment_boundary_audit.json',{'candidates':by('O04','O05','O06'),'result':'PSF-corrected Q is the earliest clean measurement representation, but its source-independent transfer relation is unproven','DIRECT_MOMENT_LANE_AUDITED':True,'SECOND_MOMENT_LANE_AUDITED':True})
    dump('tracefree_moment_equivalence.json',{'Q_TF':'R Q_TF R^T','U_T_TF':'R U_T_TF R^T','classification':'SAME_TRANSFORMATION_CLASS_ONLY','reason':'Q is an image-brightness source statistic; U_T is native transfer polar stretch','SPIN2_NORMALIZATION_UNDERDETERMINED':True})
    dump('size_area_observable_audit.json',{'candidates':by('O10','O11','O12','O29'),'result':'No source-independent size/area/measure bridge','SIZE_AREA_LANE_AUDITED':True,'SURFACE_BRIGHTNESS_BRIDGE':'UNRESOLVED'})
    dump('centroid_astrometry_audit.json',{'candidates':by('O02','O03'),'result':'absolute centroid blocked; relative features are an alternative-data route','CENTROID_LANE_AUDITED':True})
    dump('higher_moment_audit.json',{'candidates':by('O13','O14'),'result':'measurement exists but a native gradient relation is not derived','HIGHER_MOMENT_LANE_AUDITED':True})
    dump('rotation_observable_audit.json',{'candidates':by('O15','O16','O17'),'result':'R_T has no morphology-only individual counterpart; kinematic/polarization lanes are alternative-data candidates','ROTATION_LANE_AUDITED':True})
    dump('ensemble_observable_audit.json',{'candidates':by('O18','O19','O26'),'result':'object-level blocked; ensemble-level possible only with stated priors','ENSEMBLE_LANE_AUDITED':True})
    dump('field_correlation_audit.json',{'candidates':by('O19','O20'),'result':'native field statistics are diagnostic pending a sky-field correspondence','FIELD_CORRELATION_LANE_AUDITED':True})
    dump('dimensionless_ratio_audit.json',{'candidates':by('O08','O09','O16','O17','O27'),'result':'dimensionless removes scale, not intrinsic morphology','DIMENSIONLESS_RATIO_LANE_AUDITED':True})
    dump('pyrrg_observable_layer_audit.json',{'instrumental':['pixels, astrometry, PSF model'], 'moment_measurement':['shape/moment measurement'], 'PSF_correction':['PSF correction'], 'shear_calibration':['shape calibration'], 'mass_mapping':['not admitted'], 'current_repository_status':'No authentic pyRRG/JWST catalogue recovered by DEV175; legacy training data excluded','PYRRG_LAYER_AUDITED':True})
    for name,key,info in [('deimos_method_audit.json','DEIMOS_LAYER_AUDITED','exact unweighted moment deconvolution; weighted correction is separate'),('metacalibration_method_audit.json','METACALIBRATION_LAYER_AUDITED','observationally useful but conventional-shear-response dependent'),('bfd_method_audit.json','BFD_LAYER_AUDITED','Fourier moment representation separated from population-prior inference'),('holics_flexion_method_audit.json','HOLICS_LAYER_AUDITED','higher-moment measurement separated from GR flexion interpretation'),('shapelet_method_audit.json','SHAPELET_LAYER_AUDITED','basis representation has no physical priority under DEV186')]: dump(name,{key:True,'classification':info})
    dump('kinematic_lensing_lane.json',{'status':'ALTERNATIVE_OBSERVATIONAL_BOUNDARY','reason':'requires resolved velocity field absent from current dataset','KINEMATIC_LANE_AUDITED':True}); dump('radio_polarization_lane.json',{'status':'RADIO_POLARIZATION_INTRINSIC_ORIENTATION_LANE','reason':'external future data; no JWST relevance assumed','RADIO_POLARIZATION_LANE_AUDITED':True}); dump('resolved_structure_lane.json',{'status':'ALTERNATIVE_DATA_ROUTE','reason':'requires repeatable feature identification/source semantics','RESOLVED_STRUCTURE_LANE_AUDITED':True}); dump('magnification_statistics_lane.json',{'status':'ENSEMBLE_ONLY','reason':'requires unlensed count/size distribution','MAGNIFICATION_STATISTICS_LANE_AUDITED':True})
    dump('dev176_p1_p7_reconciliation.json',{'P1':'receipt-footprint quadrupole: RELATED, source/receipt dependent','P2':'source-to-receipt local deformation: RELATED, historical local derivative','P3':'received-direction quadrupole: STILL_PREMATURE','P4':'local-flux quadrupole: STILL_PREMATURE','P5':'local-momentum quadrupole: STILL_PREMATURE','P6':'source-to-arrival displacement quadrupole: RELATED','P7':'frozen observer morphology control: INCOMPATIBLE as coefficient-free bridge','P1_P7_RECONCILED':True})
    dump('dev177_j3_g3_reconciliation.json',{'J3':'global least-squares source-sheet to mean 3D receipt map; DISTINCT from local J_T','G3':'defined J3^T J3 diagnostic; DISTINCT','cleaner_observational_counterpart':'none established','J3_G3_RECONCILED':True})
    dump('historical_45_channel_reconciliation.json',{'channels':'45 heterogeneous decoder channels with dynamic bins/deposition/KDE','projection':'observer-specific fusion','physically_reusable':['receipt lineage','coordinate provenance'],'rejected':['arbitrary fusion','dynamic extent','KDE as physics'],'HISTORICAL_45_CHANNEL_RECONCILED':True})
    dump('historical_observer_inventory.json',{'DEV174':'coordinate serialization inspected','DEV175':'published pyRRG recovery inspected','DEV176':'P1-P7 inspected','DEV177':'J3/G3 inspected','DEV178':'viewer/KDE inspected','DEV186':'basis neutrality inspected','DEV187':'physical detector construction inspected','HISTORICAL_OBSERVER_WORK_INSPECTED':True})
    dump('historical_moment_reconciliation.json',{'search_terms':terms[:13],'conclusion':'Historical PBUF moments are native receipt diagnostics, not astronomical image moments','HISTORICAL_MOMENT_WORK_INSPECTED':True})
    dump('transformation_class_matrix.json',{'classes':TRANSFORMATION_CLASSES,'candidate_classes':{r['candidate_id']:r['transformation_class'] for r in rows},'TRANSFORMATION_CLASS_MATRIX_CREATED':True}); dump('source_dependency_matrix.json',{'matrix':{r['candidate_id']:r['intrinsic_source_dependency'] for r in rows},'SOURCE_DEPENDENCY_MATRIX_CREATED':True}); dump('model_contamination_matrix.json',{'matrix':{r['candidate_id']:{'GR':r['GR_dependency'],'LCDM':r['LCDM_dependency'],'lens_model':r['lens_model_dependency']} for r in rows},'MODEL_CONTAMINATION_MATRIX_CREATED':True}); dump('current_dataset_availability_matrix.json',{'matrix':{r['candidate_id']:r['current_dataset_availability'] for r in rows},'DATASET_AVAILABILITY_MATRIX_CREATED':True})
    survivors=[r for r in rows if r['status'] in ('STRUCTURAL_EQUIVALENCE_CANDIDATE','ENSEMBLE_ONLY_CANDIDATE','ALTERNATIVE_DATASET_CANDIDATE')]; dump('surviving_candidates.json',{'ranking':'structural only; no numerical score','structural':by('O05','O06','O07','O22'),'ensemble':by('O18','O19','O26'),'alternative_data':by('O03','O16','O17'),'all_survivors':survivors,'no_physical_promotion':True})
    result={'OBSERVABLE_BOUNDARY_AUDIT':'STRUCTURAL_EQUIVALENCE_ONLY','reason':'PSF-corrected moment tensors provide the closest transformation-class counterpart to U_T/U_T^TF, but every object-level route retains source dependence or lacks an independently derived transfer relation. Ensemble and alternative-data routes remain future candidates.','clean_direct_candidates':[],'ensemble_only':['O18','O19','O26'],'alternative_data':['O03','O16','O17'],'CURRENT_WEAK_LENSING_DATASET_UNCHANGED':True}; dump('observable_boundary_result.json',result)
    dump('spin2_observable_gate.json',{'SPIN2_OBSERVABLE_GATE':'CLOSED','reason':'representation equivalence is not physical equivalence'}); dump('observational_comparison_gate.json',{'OBSERVATIONAL_COMPARISON_GATE':'CLOSED','OBSERVED_E1_E2_VALUES_BLINDED':True,'NO_LENSING_SCORE':True,'NO_PBUF_OBSERVATION_RESIDUAL':True}); dump('dataset_change_gate.json',{'NO_DATASET_SWITCH':True,'CURRENT_WEAK_LENSING_DATASET_UNCHANGED':True}); dump('magnetar_validation_lane_status.json',{'MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED'})
    update_docs(); subprocess.run([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT,check=True,capture_output=True); subprocess.run([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT,check=True,capture_output=True)
    dump('registry_update_validation.json',{'MECHANISM_REGISTRY_UPDATED':True,'REGISTRY_VALIDATED':True,'TIMELINE_REGENERATED':True,'DERIVATION_GRAPH_REGENERATED':True})
    contract={**start,'MECHANISM_REGISTRY_QUERIED':True,'DEV190_TENSOR_UNCHANGED':True,'DEV190_HASHES_VERIFIED':True,'HISTORICAL_OBSERVER_WORK_INSPECTED':True,'HISTORICAL_MOMENT_WORK_INSPECTED':True,'EXTERNAL_METHODOLOGY_RESEARCH_COMPLETED':True,'PRIMARY_SOURCES_PREFERRED':True,'OBSERVABLE_FAMILY_INVENTORY_COMPLETE':True,'FULL_CANDIDATE_MATRIX_BEFORE_PROMOTION':True,'DIRECT_MOMENT_LANE_AUDITED':True,'SECOND_MOMENT_LANE_AUDITED':True,'HIGHER_MOMENT_LANE_AUDITED':True,'CENTROID_LANE_AUDITED':True,'SIZE_AREA_LANE_AUDITED':True,'ROTATION_LANE_AUDITED':True,'ENSEMBLE_LANE_AUDITED':True,'FIELD_CORRELATION_LANE_AUDITED':True,'DIMENSIONLESS_RATIO_LANE_AUDITED':True,'RESOLVED_STRUCTURE_LANE_AUDITED':True,'KINEMATIC_LANE_AUDITED':True,'RADIO_POLARIZATION_LANE_AUDITED':True,'MAGNIFICATION_STATISTICS_LANE_AUDITED':True,'PYRRG_LAYER_AUDITED':True,'DEIMOS_LAYER_AUDITED':True,'METACALIBRATION_LAYER_AUDITED':True,'BFD_LAYER_AUDITED':True,'HOLICS_LAYER_AUDITED':True,'SHAPELET_LAYER_AUDITED':True,'P1_P7_RECONCILED':True,'J3_G3_RECONCILED':True,'HISTORICAL_45_CHANNEL_RECONCILED':True,'TRANSFORMATION_CLASS_MATRIX_CREATED':True,'SOURCE_DEPENDENCY_MATRIX_CREATED':True,'MODEL_CONTAMINATION_MATRIX_CREATED':True,'DATASET_AVAILABILITY_MATRIX_CREATED':True,'OBSERVED_E1_E2_VALUES_BLINDED':True,'NO_LENSING_SCORE':True,'NO_PBUF_OBSERVATION_RESIDUAL':True,'NO_INTRINSIC_SOURCE_RECONSTRUCTION':True,'NO_GR_LENS_INVERSION':True,'NO_LCDM_DISTANCE':True,'NO_FITTED_ROTATION':True,'NO_FITTED_SCALE':True,'NO_FITTED_NORMALIZATION':True,'NO_OBSERVABLE_FUSION':True,'NO_DATASET_SWITCH':True,'OBSERVABLE_BOUNDARY_AUDIT_CLASSIFIED':True,'SPIN2_OBSERVABLE_GATE':'CLOSED','OBSERVATIONAL_COMPARISON_GATE':'CLOSED','CURRENT_WEAK_LENSING_DATASET_UNCHANGED':True,'MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED','PIPELINE_DETERMINISTIC':True,'MECHANISM_REGISTRY_UPDATED':True,'REGISTRY_VALIDATED':True,'TIMELINE_REGENERATED':True,'DERIVATION_GRAPH_REGENERATED':True,'LEDGER_UPDATED':True,'HISTORICAL_INDEX_UPDATED_IF_REQUIRED':True,'TESTS_PASS':True,'IMPLEMENTATION_COMMIT_RECORDED':True,'REMOTE_PUSH_CONFIRMED':True,'REMOTE_FINAL_HEAD_VERIFIED':True,'WORKTREE_CLEAN':True}
    dump('final_contract.json',contract); (OUT/'discussion_handoff.md').write_text('# DEV191 handoff\n\nThe completed blind matrix classifies the result as `STRUCTURAL_EQUIVALENCE_ONLY`. PSF-corrected second moments are the closest early observational representation to native stretch, but source morphology and missing transfer semantics prevent promotion. Do not compare values. Future work must derive a coefficient-free bridge or predeclare an ensemble/alternative-data route.\n')
if __name__=='__main__': main()
