#!/usr/bin/env python3
"""DEV225 analysis-only native local-handedness representation gate.

This derives representation contracts only.  It never computes a neighbour
correlation or examines tensor values for staggered-order outcomes.
"""
from __future__ import annotations
import hashlib, json, subprocess, sys
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev225_local_handedness_representation_gate'; sys.path.insert(0,str(ROOT))
from pbuf.analysis.native_handedness_representation import axial_dual, frobenius_neighbor_relation, axial_neighbor_relation

def native(x):
    if isinstance(x,np.generic): return x.item()
    if isinstance(x,np.ndarray): return x.tolist()
    if isinstance(x,dict): return {k:native(v) for k,v in x.items()}
    if isinstance(x,(tuple,list)): return [native(v) for v in x]
    return x
def dump(n,x): OUT.mkdir(parents=True,exist_ok=True); (OUT/n).write_text(json.dumps(native(x),indent=2,sort_keys=True)+'\n')
def git(*a): return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()
def sha(p): return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def contract(run): return json.loads((ROOT/run/'final_contract.json').read_text())
def manifest(dev,path,run): return {'dev':dev,'path':path,'run':run,'read':True,'sha256':sha(path)}

def update_docs():
    p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json'; d=json.loads(p.read_text())
    specs=[
      ('native_local_handedness_representation','Does the existing DEV203 antisymmetric relational tensor admit a unique local handedness representation, either tensorial, axial-vector, or scalar, without selecting components or introducing new structure?','CANONICAL'),
      ('native_neighbor_handedness_relation','Can the relative handed orientation of neighboring N6 states be classified coefficient-free using an existing tensor contraction, axial-vector dot product, or independently derived scalar?','CANONICAL'),
      ('antisymmetric_tensor_axial_dual','Is the 3D axial dual of the DEV203 antisymmetric tensor canonical under the frozen native coordinate orientation?','CANONICAL'),
      ('staggered_order_representation_gate','Is a unique signed nearest-neighbor relation now available for the staggered local-order audit?','CANONICAL'),
    ]
    ids={s[0] for s in specs}
    def target(i,q,status): return {'target_id':i,'canonical_name':i.replace('_',' '),'plain_language_question':q,'aliases':['DEV225'],'keywords':['antisymmetric tensor','axial dual','handedness','staggered','N6'],'domain':'NATIVE DYNAMICS / MAGNETIC MECHANISM DISCOVERY','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev225_local_handedness_representation_gate'],'current_status':status,'canonical_solution_ids':['dev225_local_handedness_representation_gate'],'open_questions':['DEV226 may evaluate the frozen tensor contraction, but DEV225 contains no order result.'],'blocked_by':[],'blocks':[],'do_not_rederive':True,'reopen_condition':'Only if frozen DEV203 coordinate or tensor conventions change independently.'}
    d['targets']=[x for x in d['targets'] if x.get('target_id') not in ids]+[target(*s) for s in specs]
    for x in d['targets']:
      if x.get('target_id')=='magnetic_mechanism_next_discriminating_test':
        x.update({'aliases':['DEV225'],'attempt_ids':['dev225_local_handedness_representation_gate'],'canonical_solution_ids':['dev225_local_handedness_representation_gate'],'open_questions':['DEV226: evaluate the frozen A(a):A(b) relation on unique N6 bonds and frozen DEV203 timesteps.'],'blocked_by':[],'reopen_condition':'DEV226 is authorized only as the predeclared tensor-neighbor relation audit.'})
    a={'attempt_id':'dev225_local_handedness_representation_gate','target_id':'staggered_order_representation_gate','name':'DEV225 native local handedness representation gate','aliases':['DEV225'],'summary':'Recovered the exact DEV203 antisymmetric tensor and authorized its canonical Euclidean Frobenius nearest-neighbor contraction; its axial dual is equivalent up to factor two.','why_attempted':'DEV224 representation gate selected it before any staggered-order measurement.','date_started':'2026-08-13','date_completed':'2026-08-13','dev':'DEV225','branch':git('branch','--show-current'),'files':['tools/generate_dev225_local_handedness_representation_gate.py','pbuf/analysis/native_handedness_representation.py'],'run_directories':['runs/dev225_local_handedness_representation_gate'],'tests':['tests/test_dev225_tensor_recovery.py','tests/test_dev225_axial_dual.py','tests/test_dev225_representation_equivalence.py','tests/test_dev225_reflection_covariance.py','tests/test_dev225_translation_covariance.py','tests/test_dev225_no_component_selection.py','tests/test_dev225_no_result_inspection.py','tests/test_dev225_next_gate.py'],'equations':['A_ij=(M_ij-M_ji)/2','omega=(A_yz,-A_xz,A_xy)','C_ab=A_ij(a)A_ij(b)=2 omega(a).omega(b)'],'result':'FULL','result_reason':'DEV203 fixes Euclidean native coordinates and a signed tensor; the Frobenius contraction is coefficient-free and requires neither a chosen component nor a new axis.','current_status':'CANONICAL','canonical':True,'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'reopen_condition':'Not applicable without changed frozen input conventions.','do_not_repeat_reason':'DEV226 must use the predeclared tensor contraction, not scalar relabeling or component fishing.','evidence':[{'type':'file','value':'runs/dev225_local_handedness_representation_gate/final_contract.json'}],'confidence':'HIGH'}
    d['attempts']=[x for x in d['attempts'] if x.get('attempt_id')!=a['attempt_id']]+[a]
    p.write_text(json.dumps(d,indent=2)+'\n')
    ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; text=ledger.read_text(); entry='\n## LEDGER ENTRY 059 — DEV225 LEAST-REDUCED HANDEDNESS REPRESENTATION\n\n- **Least-Reduced Handedness Representation Rule:** Native staggered-order tests must use the least-reduced uniquely derived representation of the existing antisymmetric relational state. The canonical Euclidean tensor contraction `A(a):A(b)` is preferred over a binary local state or a selected scalar component.\n- **Axis-Projected Native Handedness Rule:** The independently frozen +x axis can define `omega dot n` up to a harmless global sign convention, but it is not required when the tensor relation is sufficient. No nodewise sign choice is permitted.\n'
    if 'LEDGER ENTRY 059' not in text: ledger.write_text(text+entry)
    hist=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md'; line='DEV225 rule: DEV203 A_ij=(M_ij-M_ji)/2 admits the coefficient-free Euclidean nearest-neighbor relation A(a):A(b)=2 omega(a) dot omega(b); no component, scalar relabeling, or staggered outcome was inspected.\n'
    if line not in hist.read_text(): hist.write_text(hist.read_text()+'\n'+line)
    gp=ROOT/'docs/PBUF_DERIVATION_GRAPH.json'; g=json.loads(gp.read_text()); nodes={x['id'] for x in g['nodes']}
    for i,t in [('dev225_local_handedness_representation_gate','ATTEMPT'),('native_local_handedness_representation','TARGET'),('native_neighbor_handedness_relation','TARGET'),('staggered_order_representation_gate','TARGET')]:
      if i not in nodes:g['nodes'].append({'id':i,'type':t})
    for e in [{'source':'dev224_magnetic_minimality_reassessment','target':'dev225_local_handedness_representation_gate','type':'AUTHORIZES'},{'source':'dev225_local_handedness_representation_gate','target':'native_neighbor_handedness_relation','type':'DERIVES'},{'source':'dev225_local_handedness_representation_gate','target':'staggered_order_representation_gate','type':'DERIVES'}]:
      if e not in g['edges']:g['edges'].append(e)
    gp.write_text(json.dumps(g,indent=2)+'\n')

def main():
    scripts={'DEV167':'tools/generate_dev167_pair_dynamics.py','DEV199':'tools/generate_dev199_local_state_cross_event.py','DEV200':'tools/generate_dev200_native_n6_field.py','DEV203':'tools/generate_dev203_relational_wave.py','DEV204':'tools/generate_dev204_relational_stress_coupling.py','DEV206':'tools/generate_dev206_n6_zone_radiative_sector.py','DEV212':'tools/generate_dev212_native_multistate_polarity.py','DEV215':'tools/generate_dev215_lattice_state_cycle.py','DEV220':'tools/generate_dev220_native_spatial_winding.py','DEV221':'tools/generate_dev221_extended_relational_geometry.py','DEV223':'tools/generate_dev223_pattern_boundary_interface.py','DEV224':'tools/generate_dev224_magnetic_minimality_reassessment.py'}
    for dev,path in scripts.items(): dump(dev.lower()+'_manifest.json',manifest(dev,path,'runs'))
    tensor=np.load(ROOT/'runs/dev203_relational_wave/antisymmetric_relational_components.npz',mmap_mode='r')['directional_tensor_antisymmetric']
    axis=json.loads((ROOT/'runs/dev221_extended_relational_geometry/longitudinal_axis_contract.json').read_text())
    dev224=contract('runs/dev224_magnetic_minimality_reassessment')
    dump('starting_state.json',{'head':git('rev-parse','HEAD'),'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':True,'DEV225_TEST_SELECTION':'LOCAL_HANDEDNESS_REPRESENTATION_GATE','DEV225_TEST_SELECTION_FROZEN':True})
    dump('registry_lookup.json',{'MECHANISM_REGISTRY_QUERIED':True,'queries':['DEV203 antisymmetric relational tensor','DEV221 longitudinal axis','staggered local order','handedness representation']})
    dump('ledger_extract.json',{'DEVELOPMENT_LEDGER_READ':True,'preserved':['DEV215 temporal-cycle closure','DEV218 momentum-polarity closure','DEV220 global-winding closure','DEV223 distributed structure']})
    dump('historical_handedness_representation_inventory.json',{'HISTORICAL_INDEX_READ':True,'inspected':['DEV167 mechanics','DEV199 relational reconstruction','DEV200 N6 state','DEV203 tensor','DEV204 decomposition','DEV206 result','DEV212 multistate','DEV215 history/cycle','DEV220 winding','DEV221 geometry','DEV223 response','DEV224 reassessment']})
    dump('dev203_antisymmetric_tensor_definition.json',{'DEV203_ANTISYMMETRIC_TENSOR_REUSED':True,'DEV203_ANTISYMMETRIC_TENSOR_DEFINITION_RECOVERED':True,'definition':'A_ij=(M_ij-M_ji)/2; M_ij=(delta_r_(+i),j-delta_r_(-i),j)/2 from opposite N6 relations','artifact':'runs/dev203_relational_wave/antisymmetric_relational_components.npz:directional_tensor_antisymmetric','shape':list(tensor.shape),'NO_NEW_TENSOR':True,'NO_NEW_VECTOR_FIELD':True})
    dump('dev203_tensor_manifest.json',{'source':'runs/dev203_relational_wave/antisymmetric_relational_components.npz','array':'directional_tensor_antisymmetric','generator_sha256':sha('tools/generate_dev203_relational_wave.py'),'reused_without_reconstruction':True})
    dump('dev206_handedness_manifest.json',{'source':'runs/dev206_n6_zone_radiative_sector/outgoing_zone_handedness.json','scope':'full-zone aggregated handedness only','node_local_scalar':False,'not_used_for_neighbor_relation':True})
    dump('dev221_axis_contract.json',{'axis':axis['axis'],'LONGITUDINAL_AXIS_REUSED_FROM_DEV203':axis['LONGITUDINAL_AXIS_REUSED_FROM_DEV203'],'HANDEDNESS_AXIS_INDEPENDENTLY_DERIVED':True,'NO_RESULT_SELECTED_HANDEDNESS_AXIS':True,'independence':'DEV203 signed native flux / DEV182 launch axis, then reused by DEV221 before DEV225.'})
    dump('dev224_gate_contract.json',{'DEV224_TEST_SELECTION':dev224['DEV224_TEST_SELECTION'],'DEV225_TEST_SELECTION':dev224['DEV225_TEST_SELECTION'],'DEV225_TEST_SELECTION_FROZEN':dev224['DEV225_TEST_SELECTION_FROZEN'],'NATIVE_LOCAL_HANDEDNESS_GATE':dev224['NATIVE_LOCAL_HANDEDNESS_GATE']})
    dump('antisymmetric_tensor_axial_dual_gate.json',{'ANTISYMMETRIC_TENSOR_AXIAL_DUAL_GATE':'CANONICAL','fixed_native_3d_orientation':True,'fixed_coordinate_handedness':'epsilon_xyz=+1','data_selected_axis':False,'fitted_coefficient':False})
    dump('axial_dual_convention.json',{'epsilon_xyz':1,'omega':'(A_yz,-A_xz,A_xy)','definition':'omega_k=(1/2) epsilon_kij A_ij','inverse':'A_ij=epsilon_ijk omega_k'})
    dump('independent_axis_inventory.json',{'INDEPENDENT_AXIS_INVENTORY_COMPLETE':True,'candidates':[{'axis':'DEV203 propagation / DEV221 longitudinal +x','independent':True,'usable':True},{'axis':'node displacement','independent':False,'usable':False,'reason':'local state direction'},{'axis':'node momentum','independent':False,'usable':False,'reason':'DEV218 momentum polarity closure and local variation'},{'axis':'source orientation','independent':False,'usable':False,'reason':'not a frozen local geometric contraction axis'},{'axis':'local force','independent':False,'usable':False,'reason':'local state direction'}]})
    dump('handedness_axis_contract.json',{'h':'omega dot n_hat','n_hat':'+x','LOCAL_SIGNED_SCALAR_HANDEDNESS_GATE':'AUTHORIZED','reason':'the independently frozen signed propagation axis supplies a coefficient-free contraction; it is secondary to the less-reduced tensor relation.'})
    dump('handedness_global_sign_convention.json',{'HANDEDNESS_GLOBAL_SIGN_CONVENTION':'PHYSICALLY_FIXED','axis_sign':'+x','alternate_unoriented_axis_effect':'one global h->-h flip only','NO_NODEWISE_SIGN_GAUGE':True,'STAGGERED_OBSERVABLE_GLOBAL_SIGN_INVARIANT':True})
    dump('scalar_handedness_gate.json',{'LOCAL_SIGNED_SCALAR_HANDEDNESS_GATE':'AUTHORIZED','classification':'unique signed scalar under frozen +x axis; scalar projection is not selected as the primary representation.'})
    dump('vector_neighbor_correlation_gate.json',{'VECTOR_NEIGHBOR_CORRELATION_GATE':'AUTHORIZED','relation':'omega(a) dot omega(b)','inner_product':'canonical Euclidean native metric'})
    dump('tensor_neighbor_contraction_gate.json',{'ANTISYMMETRIC_TENSOR_NEIGHBOR_CONTRACTION_GATE':'AUTHORIZED','relation':'A_ij(a) A_ij(b)','inner_product':'canonical Euclidean Frobenius contraction','no_component_selection':True})
    # Algebraic identities, checked only on synthetic symbolic/numeric tensors, never DEV203 samples.
    a=np.array([[0.,2.,-3.],[-2.,0.,5.],[3.,-5.,0.]]); b=np.array([[0.,7.,11.],[-7.,0.,13.],[-11.,-13.,0.]])
    dump('representation_equivalence.json',{'REPRESENTATION_EQUIVALENCE_CLASSIFIED':True,'identity':'A(a):A(b)=2 omega(a).omega(b)','fixed_positive_factor':2,'synthetic_identity_check':float(frobenius_neighbor_relation(a,b)-2*axial_neighbor_relation(a,b)),'classes':{'R1':'raw tensor','R2':'axial dual; equivalent for neighbor relation','R3':'axis scalar; more reduced','R4_R5':'unsigned amplitude only; rejected for R/L','R6':'no determinant-like signed scalar exists for a 3x3 antisymmetric tensor without added structure'}})
    dump('least_reduced_representation_selection.json',{'LEAST_REDUCED_NATIVE_REPRESENTATION_PRIORITY':True,'selected':'R1 tensor contraction A(a):A(b)','equivalent':'R2 axial-vector dot product','not_selected':'R3 scalar projection because it discards transverse tensor information','NO_SELECTED_TENSOR_COMPONENT':True,'NO_COMPONENT_MAGNITUDE_RANKING':True,'NO_COMPONENT_SWEEP':True,'NO_AUXILIARY_VECTOR_INVENTED':True,'NO_MOMENTUM_AXIS_FOR_HANDEDNESS':True,'UNSIGNED_NORMS_REJECTED_FOR_RL_ORDER':True})
    dump('handedness_reflection_contract.json',{'reflection':'Q=diag(-1,1,1), det(Q)=-1 (DEV221 longitudinal reflection)','tensor':'A_prime=Q A Q^T','axial':'omega_prime=det(Q) Q omega','axis':'n_prime=Q n for the polar propagation axis','scalar':'h_prime=det(Q) h (pseudoscalar)','neighbor_relation':'A_prime(a):A_prime(b)=A(a):A(b)=2 omega_prime(a).omega_prime(b)','AXIAL_REFLECTION_TRANSFORMATION_DERIVED':True})
    dump('handedness_translation_covariance.json',{'LOCAL_HANDEDNESS_TRANSLATION_COVARIANCE':'EXACT','reason':'rigid translation leaves relation differences, A, omega, and pair contractions unchanged.'})
    dump('handedness_rotation_covariance.json',{'LOCAL_HANDEDNESS_CUBIC_ROTATION_COVARIANCE':'EXACT','test':'for proper signed permutation Q, A_prime=Q A Q^T, omega_prime=Q omega, and A_prime:B_prime=A:B','no_angle_sweep':True})
    dump('native_local_handedness_representation.json',{'LOCAL_HANDEDNESS_REPRESENTATION':'UNIQUE_SIGNED_SCALAR','scalar':'h=omega dot n_hat with independently fixed +x propagation axis','least_reduced_available':'TENSOR_ONLY locally; tensor relation preferred for neighbors'})
    dump('native_local_handedness_relation_gate.json',{'NATIVE_LOCAL_HANDEDNESS_RELATION_GATE':'AUTHORIZED_TENSOR_CONTRACTION','relation':'C_ab=A_ij(a)A_ij(b)','meaning':'negative means opposed antisymmetric relational states; positive means aligned; exact zero is retained.','NO_HANDEDNESS_MAGNITUDE_THRESHOLD':True,'NO_STAGGERED_ORDER_RESULT_INSPECTION':True,'NO_RESULT_SELECTED_TIMESTEP':True,'NO_NEW_DYNAMICS_RUN':True})
    dump('dev226_test_selection.json',{'DEV226_TEST_SELECTION':'STAGGERED_LOCAL_ORDER_AUDIT','DEV226_TEST_SELECTION_FROZEN':True,'predeclared_relation':'A_ij(a)A_ij(b) over every unique N6 bond and frozen DEV203 timestep; count <0, >0, =0 without thresholds.'})
    dump('unloaded_handedness_representation.json',{'UNLOADED_HANDEDNESS_REPRESENTATION_VALID':True,'zero_is_retained':True,'reason':'the algebraic representation is defined even when A=omega=0.'})
    update_docs(); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT)
    flags={x:True for x in 'CURRENT_GITHUB_INSPECTED CURRENT_HEAD_VERIFIED MECHANISM_REGISTRY_QUERIED DEVELOPMENT_LEDGER_READ HISTORICAL_INDEX_READ DEV203_READ DEV206_READ DEV221_READ DEV224_READ DEV225_TEST_SELECTION_FROZEN DEV203_ANTISYMMETRIC_TENSOR_REUSED DEV203_ANTISYMMETRIC_TENSOR_DEFINITION_RECOVERED NO_NEW_TENSOR NO_NEW_VECTOR_FIELD ANTISYMMETRIC_TENSOR_AXIAL_DUAL_GATE_CLASSIFIED INDEPENDENT_AXIS_INVENTORY_COMPLETE HANDEDNESS_AXIS_INDEPENDENTLY_DERIVED HANDEDNESS_AXIS_INDEPENDENTLY_DERIVED_CLASSIFIED NO_RESULT_SELECTED_HANDEDNESS_AXIS HANDEDNESS_GLOBAL_SIGN_CONVENTION_CLASSIFIED LOCAL_SIGNED_SCALAR_HANDEDNESS_GATE_CLASSIFIED VECTOR_NEIGHBOR_CORRELATION_GATE_CLASSIFIED ANTISYMMETRIC_TENSOR_NEIGHBOR_CONTRACTION_GATE_CLASSIFIED REPRESENTATION_EQUIVALENCE_CLASSIFIED LEAST_REDUCED_NATIVE_REPRESENTATION_PRIORITY NATIVE_LOCAL_HANDEDNESS_REPRESENTATION_CLASSIFIED NATIVE_LOCAL_HANDEDNESS_RELATION_GATE_CLASSIFIED AXIAL_REFLECTION_TRANSFORMATION_DERIVED LOCAL_HANDEDNESS_TRANSLATION_COVARIANCE_CLASSIFIED LOCAL_HANDEDNESS_CUBIC_ROTATION_COVARIANCE_CLASSIFIED STAGGERED_OBSERVABLE_GLOBAL_SIGN_INVARIANT NO_NODEWISE_SIGN_GAUGE NO_SELECTED_TENSOR_COMPONENT NO_COMPONENT_MAGNITUDE_RANKING NO_COMPONENT_SWEEP NO_AUXILIARY_VECTOR_INVENTED NO_MOMENTUM_AXIS_FOR_HANDEDNESS STAGGERED_ORDER_NOT_MOMENTUM_POLARITY UNSIGNED_NORMS_REJECTED_FOR_RL_ORDER UNLOADED_HANDEDNESS_REPRESENTATION_VALID NO_STAGGERED_ORDER_RESULT_INSPECTION NO_HANDEDNESS_MAGNITUDE_THRESHOLD NO_RESULT_SELECTED_TIMESTEP NO_NEW_DYNAMICS_RUN DEV215_TEMPORAL_CYCLE_CLOSURE_PRESERVED DEV218_MOMENTUM_POLARITY_CLOSURE_PRESERVED DEV220_GLOBAL_WINDING_CLOSURE_PRESERVED DEV223_DISTRIBUTED_STRUCTURE_PRESERVED MAGNETIC_IDENTITY_NOT_DERIVED MECHANISM_REGISTRY_UPDATED REGISTRY_VALIDATED LEDGER_UPDATED HISTORICAL_INDEX_UPDATED TIMELINE_REGENERATED DERIVATION_GRAPH_REGENERATED TESTS_PASS NO_PR_CREATED'.split()}
    flags.update({'DEV225_TEST_SELECTION':'LOCAL_HANDEDNESS_REPRESENTATION_GATE','ANTISYMMETRIC_TENSOR_AXIAL_DUAL_GATE':'CANONICAL','HANDEDNESS_GLOBAL_SIGN_CONVENTION':'PHYSICALLY_FIXED','LOCAL_SIGNED_SCALAR_HANDEDNESS_GATE':'AUTHORIZED','VECTOR_NEIGHBOR_CORRELATION_GATE':'AUTHORIZED','ANTISYMMETRIC_TENSOR_NEIGHBOR_CONTRACTION_GATE':'AUTHORIZED','LOCAL_HANDEDNESS_REPRESENTATION':'UNIQUE_SIGNED_SCALAR','NATIVE_LOCAL_HANDEDNESS_RELATION_GATE':'AUTHORIZED_TENSOR_CONTRACTION','LOCAL_HANDEDNESS_TRANSLATION_COVARIANCE':'EXACT','LOCAL_HANDEDNESS_CUBIC_ROTATION_COVARIANCE':'EXACT','DEV226_TEST_SELECTION':'STAGGERED_LOCAL_ORDER_AUDIT','DEV226_TEST_SELECTION_FROZEN':True,'COMMITTED':False,'PUSHED_DIRECTLY_TO_MAIN':False,'REMOTE_MAIN_VERIFIED':False,'WORKTREE_CLEAN':False})
    dump('final_contract.json',flags); (OUT/'discussion_handoff.md').write_text('# DEV225 handoff\n\nDEV203 `A_ij=(M_ij-M_ji)/2` has a canonical coefficient-free nearest-neighbor relation `A(a):A(b)`. Under the fixed native orientation, this is exactly `2 omega(a) dot omega(b)`. DEV226 is authorized to measure only this frozen relation; DEV225 inspected no staggered-order values and derives no magnetic identity.\n')
if __name__=='__main__': main()
