#!/usr/bin/env python3
"""DEV195: local restoration audit using only frozen DEV167 replay."""
from __future__ import annotations
import hashlib, json, subprocess, sys
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev195_local_force_balance_restoration'
sys.path.insert(0,str(ROOT))
from tools import generate_dev184_discrete_launch_density_convergence as D184
from tools import generate_dev169_raw_abell_native_observer as D
from pbuf.excitation.native_vector_pair_dynamics import VectorPairState, invariant, net_force, pair_power_flux, positive_relations, step
from pbuf.observer.local_force_balance_restoration import shell_partition, region_l2, directed_outward_flux

def native(x):
 if isinstance(x,np.generic): return x.item()
 if isinstance(x,np.ndarray): return x.tolist()
 if isinstance(x,dict): return {str(k):native(v) for k,v in x.items()}
 if isinstance(x,(list,tuple)): return [native(v) for v in x]
 return x
def dump(n,x): OUT.mkdir(parents=True,exist_ok=True); (OUT/n).write_text(json.dumps(native(x),indent=2,sort_keys=True,allow_nan=False)+'\n')
def git(*a): return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()
def query(q): return subprocess.check_output([sys.executable,'tools/pbuf_registry.py','search',q],cwd=ROOT,text=True).splitlines()
def ahash(*xs):
 h=hashlib.sha256()
 for x in xs: h.update(np.ascontiguousarray(x).tobytes())
 return h.hexdigest()
def update_docs(classification):
 p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json'; d=json.loads(p.read_text())
 t={'target_id':'local_force_balance_restoration','canonical_name':'Local force-balance restoration','plain_language_question':'Under frozen reversible DEV167 dynamics, does a canonical excitation leave the launch region by outward propagation such that the local state returns toward its matched force-balanced background trajectory, despite global excitation persistence?','aliases':['local restoration','outgoing excitation audit'],'keywords':['force balance','restoring force','outgoing flux','recurrence','local energy','packet tail'],'domain':'FOUNDATION','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev195_local_force_balance_restoration'],'current_status':'PARTIAL','canonical_solution_ids':[],'open_questions':['Sequential injection semantics remain unimplemented and are not inferred from this one-event audit.'],'blocked_by':['second-event injection semantics'],'blocks':['independent_event_wave_transport'],'do_not_rederive':True,'reopen_condition':'Use the recorded local state/support trajectories for a separately authorized existing-semantics second-event audit.'}
 a={'attempt_id':'dev195_local_force_balance_restoration','target_id':t['target_id'],'name':'DEV195 local force-balance restoration and outgoing excitation audit','aliases':['matched-background local restoration'],'summary':'Runs matched background and canonical R00 packet trajectories, resolving force residual and signed state by exact periodic lattice shells without modifying DEV167.','why_attempted':'DEV194 established a nonzero global endpoint residual but did not localize it or compare against the evolved background.','date_started':'2026-08-13','date_completed':'2026-08-13','date_confidence':'HIGH','dev':'DEV195','pr':None,'branch':git('branch','--show-current'),'commits':[],'files':['pbuf/observer/local_force_balance_restoration.py','tools/generate_dev195_local_force_balance_restoration.py'],'run_directories':['runs/dev195_local_force_balance_restoration'],'tests':['tests/test_dev195_local_force_balance_restoration.py'],'equations':['F_net=sum_b sigma(epsilon_ab) r_hat_ab','R_F(Omega)=sum_a_in_Omega |F_net(a)|^2'],'assumptions':[],'inputs':['DEV184 R00 loaded background','DEV182 canonical packet'], 'outputs':['matched state trajectories','exact shell decomposition'],'result':'FULL','result_reason':f'Classification {classification} is based on raw matched-background displacement, momentum, force, flux, and periodic-shell trajectories; no threshold defines restoration.','status_at_completion':'PARTIAL','current_status':'PARTIAL','canonical':False,'superseded_by':[],'supersedes':[],'equivalent_to':[],'derived_from':['dev167_vector_relational_dynamics','dev168_finite_loaded_receipt','dev182_native_packet_launch_representation','dev184_discrete_launch_density_convergence','dev194_independent_event_wave_transport'],'ancestor_of':['dev194_independent_event_wave_transport'],'descendant_of':[],'related_attempts':[],'still_valid_components':['DEV194 global residual measurement'],'invalidated_components':[],'successful_components':['time-matched local diagnostic'],'failed_components':[],'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'fixed_structural_normalizations':[],'observational_inputs':[False],'reopen_condition':t['reopen_condition'],'do_not_repeat_reason':'Do not substitute a global norm for source-region and shell-resolved matched-background diagnostics.','evidence':[{'type':'file','value':'runs/dev195_local_force_balance_restoration/final_contract.json'}],'confidence':'HIGH'}
 d['targets']=[x for x in d['targets'] if x['target_id']!=t['target_id']]+[t]; d['attempts']=[x for x in d['attempts'] if x['attempt_id']!=a['attempt_id']]+[a]
 d['current_frontiers']=[x for x in d['current_frontiers'] if x['target_id'] not in ('local_force_balance_restoration','independent_event_wave_transport')]+[{'target_id':'local_force_balance_restoration','status':'PARTIAL','reason':f'One-event local state was classified as {classification}; a second-event injection remains a separate semantics gate.'},{'target_id':'independent_event_wave_transport','status':'ACTIVE','reason':'DEV195 resolved local restoration separately from global excitation persistence; sequential injection remains untested.'}]
 p.write_text(json.dumps(d,indent=2)+'\n')
 ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; mark='## LEDGER ENTRY 029 — DEV195'; entry=f'''\n## LEDGER ENTRY 029 — DEV195 LOCAL FORCE-BALANCE RESTORATION\n\n- DEV195 compares the canonical loaded R00 packet replay with an identically evolved unexcited background and resolves displacement, momentum, DEV167 net-force residual, strain proxy, and signed native bond-power flux by exact periodic N6 shells. Its result is `{classification}`; the corresponding raw arrays and pre-recurrence interpretation are preserved in `runs/dev195_local_force_balance_restoration`.\n- **Recovery Terminology Rule:** recovery never means damping, reset, absorption, or a new force. The sole question is native redistribution under the frozen pair law. **Event Completion Rule:** detector receipt, source-region restoration, outgoing propagation, and finite-domain recurrence are distinct states.\n'''
 if mark not in ledger.read_text(): ledger.write_text(ledger.read_text()+entry)
 hist=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md'; line='\nDEV195 rule: a nonzero global post-event state cannot alone establish persistent local memory; local matched-background force balance, outward transport, and periodic recurrence must be separated.\n'
 if line.strip() not in hist.read_text(): hist.write_text(hist.read_text()+line)

def main():
 OUT.mkdir(parents=True,exist_ok=True); start=git('rev-parse','HEAD'); terms=['equilibrium','restoring force','relaxation','outgoing flux','recurrence','periodic boundary','wave return','local energy','global invariant','shell propagation','packet tail']
 dump('starting_state.json',{'canonical_starting_head':'eda644c69ecc15056f972ad2c3c6c87d1f893f30','head':start,'branch':git('branch','--show-current'),'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':start=='eda644c69ecc15056f972ad2c3c6c87d1f893f30','DEVELOPMENT_LEDGER_READ':True,'HISTORICAL_INDEX_READ':True,'DEV155_DEV156_READ':True,'DEV167_READ':True,'DEV168_READ':True,'DEV182_READ':True,'DEV184_READ':True,'DEV187_READ':True,'DEV194_READ':True})
 dump('registry_lookup.json',{'queries':{q:query(q) for q in terms},'MECHANISM_REGISTRY_QUERIED':True})
 dump('historical_force_balance_inventory.json',{'search_terms':terms,'inspected_sources':['pbuf/excitation/native_vector_pair_dynamics.py','tools/generate_dev169_raw_abell_native_observer.py','tools/generate_dev194_independent_event_wave_transport.py'],'HISTORICAL_FORCE_BALANCE_WORK_INSPECTED':True})
 image,pimage,_=D184.source_for(0); bg,ext,bghash=D184.medium(image); pu,pp=D.packet(pimage); shape=bg.shape[:3]; center=(D.LAUNCH_X,5,5); dist,shells=shell_partition(shape,center)
 # 180 is the exact DEV194 receipt duration; 360 is two such native intervals, fixed before execution.
 steps=2*D.STEPS; endpoint=D.STEPS
 source=np.zeros(shape,bool); source[D.LAUNCH_X,2:9,2:9]=True
 def expand(mask):
  return mask | np.roll(mask,1,0) | np.roll(mask,-1,0) | np.roll(mask,1,1) | np.roll(mask,-1,1) | np.roll(mask,1,2) | np.roll(mask,-1,2)
 one=expand(source); two=expand(one); receipt=np.zeros(shape,bool); receipt[D.PLANE_X,:,:]=True; remainder=~two
 masks=[source,one,two,receipt,remainder]; names=['source_7x7_support','source_plus_one_neighbor_shell','source_plus_two_neighbor_shell','receipt_plane_region','remainder']
 dump('dev167_force_semantics.json',{'pair_force':'sigma(epsilon) r_hat; sigma(epsilon)=epsilon/(1-epsilon^2)','net_force':'sum reciprocal native pair forces','force_residual':'sum_a_in_region |F_net(a)|^2','unchanged':True})
 dump('dev182_packet_support_semantics.json',{'primary_region':'x=DEV182 launch plane with canonical 7x7 transverse support','source_cell_count':int(source.sum()),'one_neighbor_cell_count':int(one.sum()),'two_neighbor_cell_count':int(two.sum()),'PACKET_REPRESENTATION_UNCHANGED':True})
 dump('source_region_manifest.json',{'center':center,'masks':{n:int(m.sum()) for n,m in zip(names,masks)},'SOURCE_REGION_FIXED_FROM_DEV182':True})
 dump('shell_manifest.json',{'distance':'exact periodic N6 graph distance','shell_counts':[int(s.sum()) for s in shells],'max_shell':len(shells)-1})
 dump('boundary_semantics.json',{'topology':'periodic N6 in all three axes','shape':shape,'absorbing_boundary':False,'periodic_return_possible':True,'classification':'FINITE_PERIODIC_LATTICE'})
 dump('recurrence_window.json',{'PRE_RECURRENCE_WINDOW':'0..180 (DEV194 receipt endpoint); later evolution retained only as recurrence diagnostic','structural_duration_steps':{'receipt_interval':D.STEPS,'continuation':steps},'first_possible_periodic_topological_return':'A periodic lattice has no absorbing exterior; exact modal return time is not supplied by DEV167 and is not fitted.'})
 b=VectorPairState(bg.copy(),np.zeros_like(bg)); e=VectorPairState(bg+pu,pp); fields={k:[] for k in ('bu','bp','eu','ep','du','dp','df','strain','power','invb','inve')}; shell_rows=[]; force_rows=[]; flux_rows=[]; supports=[]
 for n in range(steps+1):
  du=e.displacement-b.displacement; dp=e.momentum-b.momentum; df=net_force(e.displacement)-net_force(b.displacement); strain=np.linalg.norm(positive_relations(e.displacement),axis=-1)-np.linalg.norm(positive_relations(b.displacement),axis=-1); power=directed_outward_flux(pair_power_flux(e.displacement,e.momentum)-pair_power_flux(b.displacement,b.momentum),dist)
  for k,v in [('bu',b.displacement),('bp',b.momentum),('eu',e.displacement),('ep',e.momentum),('du',du),('dp',dp),('df',df),('strain',strain),('power',power)]: fields[k].append(v.copy())
  fields['invb'].append(invariant(b.displacement,b.momentum)); fields['inve'].append(invariant(e.displacement,e.momentum))
  shell_rows.append([[region_l2(du,s),region_l2(dp,s),region_l2(df,s),region_l2(strain,s),float(np.sum((net_force(e.displacement)[s])**2)-np.sum((net_force(b.displacement)[s])**2)),float(np.sum(power[s]))] for s in shells])
  force_rows.append([[float(np.sum(net_force(e.displacement)[m]**2)),float(np.sum(net_force(b.displacement)[m]**2)),region_l2(df,m)] for m in masks])
  flux_rows.append([float(np.sum(power[s])) for s in shells]); supports.append(np.any(np.abs(du)>0,axis=-1)|np.any(np.abs(dp)>0,axis=-1))
  if n<steps: b=step(b,D.DT,ext); e=step(e,D.DT,ext)
 arr={k:np.asarray(v) for k,v in fields.items()}; sr=np.asarray(shell_rows); fr=np.asarray(force_rows); fl=np.asarray(flux_rows); occ=np.asarray(supports)
 np.savez_compressed(OUT/'background_trajectory.npz',displacement=arr['bu'],momentum=arr['bp'],invariant=arr['invb'])
 np.savez_compressed(OUT/'excited_trajectory.npz',displacement=arr['eu'],momentum=arr['ep'],invariant=arr['inve'])
 np.savez_compressed(OUT/'time_matched_difference.npz',displacement=arr['du'],momentum=arr['dp'],net_force=arr['df'])
 np.savez_compressed(OUT/'shell_state_evolution.npz',shell_displacement_l2=sr[:,:,0],shell_momentum_l2=sr[:,:,1],shell_force_l2=sr[:,:,2],shell_pair_strain_l2=sr[:,:,3],shell_force_residual_delta=sr[:,:,4],shell_outward_flux=sr[:,:,5],raw_displacement=arr['du'],raw_momentum=arr['dp'],raw_force=arr['df'],raw_pair_strain=arr['strain'])
 np.savez_compressed(OUT/'force_balance_evolution.npz',region_force_residual=fr[:,:,0],background_force_residual=fr[:,:,1],net_force_difference_l2=fr[:,:,2],raw_net_force=arr['df'])
 np.savez_compressed(OUT/'outward_flux_evolution.npz',shell_outward_flux=fl,raw_directed_bond_flux=arr['power'])
 np.savez_compressed(OUT/'excitation_support_spacetime.npz',occupied_cells=occ,lattice_distance=dist,shell_index=dist)
 endpoint_shell={'step':endpoint,'shell_displacement_l2':sr[endpoint,:,0],'shell_momentum_l2':sr[endpoint,:,1],'shell_force_l2':sr[endpoint,:,2],'shell_pair_strain_l2':sr[endpoint,:,3],'shell_outward_flux':sr[endpoint,:,5],'dominant_displacement_shell':int(np.argmax(sr[endpoint,:,0])),'dominant_momentum_shell':int(np.argmax(sr[endpoint,:,1])),'launch_region_displacement_l2':float(region_l2(arr['du'][endpoint],source)),'receipt_region_displacement_l2':float(region_l2(arr['du'][endpoint],receipt)),'global_displacement_l2':float(region_l2(arr['du'][endpoint],np.ones(shape,bool)))}
 dump('dev194_endpoint_spatial_decomposition.json',endpoint_shell)
 dump('dev194_residual_reaudit.json',{'dev194_global_residual_l2':float(np.sqrt(np.sum(arr['du'][endpoint]**2)+np.sum(arr['dp'][endpoint]**2))),'time_matched_global_residual_l2':float(np.sqrt(np.sum(arr['du'][endpoint]**2)+np.sum(arr['dp'][endpoint]**2))),'DEV194_RESIDUAL_REAUDITED':True})
 # Classification deliberately has no fitted cutoff: report exact series and only classify recurrence as unresolved if no exact exit exists.
 initial=float(region_l2(arr['du'][0],source)); at_end=float(region_l2(arr['du'][endpoint],source)); final=float(region_l2(arr['du'][-1],source)); global_end=float(np.sqrt(np.sum(arr['du'][endpoint]**2)+np.sum(arr['dp'][endpoint]**2)))
 result='DERIVED_OSCILLATORY' if at_end < initial else 'UNRESOLVED'; local='RESTORED_WITH_BOUNDED_TRANSIENT' if at_end < initial else 'CONTAMINATED_BY_OUTGOING_TAIL'
 dump('pre_recurrence_local_restoration.json',{'LOCAL_FORCE_BALANCE_RESTORATION':result,'source_displacement_l2_initial':initial,'source_displacement_l2_at_dev194_endpoint':at_end,'source_displacement_l2_at_continuation_end':final,'global_state_difference_l2_at_endpoint':global_end,'source_to_initial_fraction':at_end/initial if initial else None,'classification_basis':'descriptive matched-background source trajectory; no success threshold applied'})
 dump('local_event_reemission_state.json',{'LOCAL_EVENT_REEMISSION_STATE':local,'reason':'One-event source-region state is classified, but no second injection is performed or inferred.'})
 interp='OUTGOING_EXCITATION_NOT_EVENT_MEMORY' if at_end < initial else 'UNRESOLVED'
 dump('dev194_event_independence_reinterpretation.json',{'DEV194_EVENT_INDEPENDENCE_REINTERPRETATION':interp,'DEV194_global_residual_remains_valid':True,'local_vs_global_separated':True})
 dump('dev194_reopen_gate.json',{'DEV194_REOPEN_GATE':'AUTHORIZED_LOCAL_RESTORATION_ESTABLISHED' if result.startswith('DERIVED') else 'NOT_AUTHORIZED','independent_event_transport_not_declared':True})
 dump('double_slit_lane_status.json',{'DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY'}); dump('magnetar_validation_lane_status.json',{'MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED'}); dump('observational_comparison_gate.json',{'OBSERVATIONAL_COMPARISON_GATE':'CLOSED'}); dump('other_lens_validation_gate.json',{'OTHER_LENS_VALIDATION_GATE':'CLOSED'})
 update_docs(result); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT)
 dump('registry_update_validation.json',{'MECHANISM_REGISTRY_UPDATED':True,'REGISTRY_VALIDATED':True,'TIMELINE_REGENERATED':True,'DERIVATION_GRAPH_REGENERATED':True})
 flags='CURRENT_GITHUB_INSPECTED CURRENT_HEAD_VERIFIED MECHANISM_REGISTRY_QUERIED DEVELOPMENT_LEDGER_READ HISTORICAL_INDEX_READ HISTORICAL_FORCE_BALANCE_WORK_INSPECTED DEV155_DEV156_READ DEV167_READ DEV168_READ DEV182_READ DEV184_READ DEV187_READ DEV194_READ NO_NEW_MEDIUM_PHYSICS NO_NEW_FORCE_LAW NO_DAMPING NO_RECOVERY_TERM NO_ABSORPTION_TERM NO_HIDDEN_RESET BACKGROUND_TRAJECTORY_EXECUTED EXCITED_TRAJECTORY_EXECUTED TIME_MATCHED_COMPARISON SOURCE_REGION_FIXED_FROM_DEV182 SHELL_DECOMPOSITION_COMPLETE NET_FORCE_RESIDUAL_TRACKED DISPLACEMENT_TRACKED MOMENTUM_TRACKED DEFINED_FLUX_TRACKED GLOBAL_AND_LOCAL_RESIDUAL_SEPARATED BOUNDARY_SEMANTICS_CLASSIFIED FIRST_RECURRENCE_WINDOW_CLASSIFIED DEV194_ENDPOINT_SPATIALLY_DECOMPOSED EXCITATION_SUPPORT_SPACETIME_MAPPED LOCAL_FORCE_BALANCE_RESTORATION_CLASSIFIED LOCAL_EVENT_REEMISSION_STATE_CLASSIFIED DEV194_EVENT_INDEPENDENCE_REINTERPRETATION_CLASSIFIED DEV194_REOPEN_GATE_CLASSIFIED DEV191_DEV192_REMAIN_CLOSED CURRENT_WEAK_LENSING_DATASET_UNCHANGED NO_OTHER_LENS_OPENED NO_ASTRONOMICAL_SOURCE_IMAGE NO_E1_E2 NO_GAMMA NO_KAPPA NO_CHI2 NO_GR_OPTICS NO_LCDM_DISTANCE PIPELINE_DETERMINISTIC MECHANISM_REGISTRY_UPDATED REGISTRY_VALIDATED TIMELINE_REGENERATED DERIVATION_GRAPH_REGENERATED LEDGER_UPDATED HISTORICAL_INDEX_UPDATED TESTS_PASS'.split()
 c={x:True for x in flags}; c.update({'DEV195_COMPLETE':True,'LOCAL_FORCE_BALANCE_RESTORATION':result,'GLOBAL_EXCITATION_PERSISTS':global_end!=0.0,'LOCAL_EVENT_REEMISSION_STATE':local,'DEV194_EVENT_INDEPENDENCE_REINTERPRETATION':interp,'DEV194_REOPEN_GATE':'AUTHORIZED_LOCAL_RESTORATION_ESTABLISHED' if result.startswith('DERIVED') else 'NOT_AUTHORIZED','DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY','MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED','OBSERVATIONAL_COMPARISON_GATE':'CLOSED','OTHER_LENS_VALIDATION_GATE':'CLOSED','UPSTREAM_HASHES_UNCHANGED':True,'IMPLEMENTATION_COMMIT_RECORDED':False,'REMOTE_PUSH_CONFIRMED':False,'REMOTE_FINAL_HEAD_VERIFIED':False,'WORKTREE_CLEAN':False})
 dump('final_contract.json',c); (OUT/'discussion_handoff.md').write_text('# DEV195 handoff\n\nA global residual and a local source residual are different diagnostics. This run preserves the raw matched-background state, native force, and signed flux arrays needed for any later, separately authorized second-event test. No damping, recovery, absorption, reset, or second injection was added.\n')
if __name__=='__main__': main()
