#!/usr/bin/env python3
"""DEV197: measure frozen DEV196 cross-event residuals in native channels."""
from __future__ import annotations
import hashlib,json,subprocess,sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev197_cross_event_influence'; IN=ROOT/'runs/dev196_sequential_event_independence'; sys.path.insert(0,str(ROOT))
from pbuf.observer.cross_event_influence import exact_region,shell_index,ratios,parallel_transverse,summary
from pbuf.observer.sequential_event_independence import inject
from pbuf.excitation.native_vector_pair_dynamics import VectorPairState,net_force,pair_power_flux,step
from pbuf.excitation.native_finite_receipt import flux_vectors
from tools import generate_dev184_discrete_launch_density_convergence as D184
from tools import generate_dev169_raw_abell_native_observer as D

def native(x):
 if isinstance(x,np.generic): return x.item()
 if isinstance(x,np.ndarray): return x.tolist()
 if isinstance(x,dict): return {str(k):native(v) for k,v in x.items()}
 if isinstance(x,(list,tuple)): return [native(v) for v in x]
 return x
def dump(n,x): OUT.mkdir(parents=True,exist_ok=True); (OUT/n).write_text(json.dumps(native(x),indent=2,sort_keys=True,allow_nan=False)+'\n')
def save(n,**x): np.savez_compressed(OUT/n,**x)
def git(*a): return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def query(q): return subprocess.check_output([sys.executable,'tools/pbuf_registry.py','search',q],cwd=ROOT,text=True).splitlines()
def region_summaries(effect,base,regions):
 r,defined=ratios(effect,base); return {n:{'ratio':summary(r,m),'absolute_cross_effect':summary(np.linalg.norm(effect,axis=-1) if effect.shape[-1:]==(3,) else np.abs(effect),m),'ratio_defined':bool(np.any(defined[:,m]))} for n,m in regions.items()}
def replay_fresh(t,pre,ext,pu,pp):
 s=inject(VectorPairState(pre['x'][t],pre['p'][t],t),pu,pp); rows={k:[] for k in ('x','p','net_force','defined_flux','receipt_displacement','receipt_momentum','receipt_flux','receipt_positive')}
 for i in range(D.STEPS+1):
  rows['x'].append(s.displacement.copy()); rows['p'].append(s.momentum.copy()); rows['net_force'].append(net_force(s.displacement)); rows['defined_flux'].append(pair_power_flux(s.displacement,s.momentum)); rows['receipt_displacement'].append(s.displacement[D.PLANE_X].copy()); rows['receipt_momentum'].append(s.momentum[D.PLANE_X].copy()); rows['receipt_flux'].append(flux_vectors(s.displacement,s.momentum)[D.PLANE_X].copy()); rows['receipt_positive'].append(np.maximum(pair_power_flux(s.displacement,s.momentum)[D.PLANE_X,:,:,0],0)*D.DT)
  if i<D.STEPS:s=step(s,D.DT,ext)
 return {k:np.asarray(v) for k,v in rows.items()}
def update_docs(result):
 p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json'; d=json.loads(p.read_text())
 target={'target_id':'cross_event_influence','canonical_name':'Cross-event influence magnitude','plain_language_question':'When a second canonical excitation B is launched after A using existing native semantics, does A produce any meaningful change in B’s native dynamics or receipt relative to B’s own fresh response?','aliases':['interaction strength','relative force','influence ratio','perturbation ratio','cross-event residual','field strength','incremental response','response sensitivity','residual coupling'],'keywords':['cross event','force influence','sequential event','receipt influence'],'domain':'OBSERVER','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev197_cross_event_influence'],'current_status':'PARTIAL','canonical_solution_ids':[],'open_questions':['Finite T1/T2/T3 audit measures resolved influence only; it does not imply a universal separation law.'],'blocked_by':[],'blocks':['independent_event_wave_transport'],'do_not_rederive':True,'reopen_condition':'Use predeclared sequential timing only if frozen dynamics or the canonical packet changes independently.'}
 attempt={'attempt_id':'dev197_cross_event_influence','target_id':'cross_event_influence','name':'DEV197 cross-event influence magnitude audit','aliases':['cross-event magnitude'],'summary':'Reuses frozen DEV196 matched residuals, reports channelwise absolute and relative influence without thresholds or denominator regularization, and compares them with an empirical deterministic replay floor.','why_attempted':'Exact support overlap is geometry, not by itself a physical interaction magnitude.','date_started':'2026-08-13','date_completed':'2026-08-13','date_confidence':'HIGH','dev':'DEV197','pr':None,'branch':git('branch','--show-current'),'commits':[],'files':['pbuf/observer/cross_event_influence.py','tools/generate_dev197_cross_event_influence.py'],'run_directories':['runs/dev197_cross_event_influence'],'tests':['tests/test_dev197_cross_event_influence.py'],'equations':['Delta_B=delta_B_after_A-delta_B_fresh','rho_F=abs(Delta_F)/abs(F_B_fresh)'],'assumptions':[],'inputs':['frozen DEV196 trajectories','DEV167 force and flux','DEV168/177 receipt channels'],'outputs':['cross-event channel residuals','relative ratios','replay floor','receipt comparisons'],'result':'PARTIAL','result_reason':result,'status_at_completion':'PARTIAL','current_status':'PARTIAL','canonical':False,'superseded_by':[],'supersedes':[],'equivalent_to':[],'derived_from':['dev167_vector_relational_dynamics','dev168_finite_loaded_receipt','dev177_full_received_state','dev182_native_packet_launch_representation','dev195_local_force_balance_restoration','dev196_sequential_event_independence'],'ancestor_of':['dev194_independent_event_wave_transport'],'descendant_of':[],'related_attempts':['dev196_sequential_event_independence'],'still_valid_components':['DEV196 exact-support geometry'], 'invalidated_components':[],'successful_components':['threshold-free native influence decomposition'], 'failed_components':[],'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'fixed_structural_normalizations':[],'observational_inputs':[False],'reopen_condition':target['reopen_condition'],'do_not_repeat_reason':'Do not use boolean support overlap as a physical independence gate.','evidence':[{'type':'file','value':'runs/dev197_cross_event_influence/final_contract.json'}],'confidence':'HIGH'}
 d['targets']=[x for x in d['targets'] if x['target_id']!=target['target_id']]+[target];d['attempts']=[x for x in d['attempts'] if x['attempt_id']!=attempt['attempt_id']]+[attempt]
 for x in d['targets']:
  if x['target_id']=='sequential_event_independence': x['open_questions']=['Exact support overlap is retained as diagnostic geometry; physical sequential independence is assessed by DEV197 cross-event native influence.'];x['blocked_by']=[];x['reopen_condition']='Reassess only from native cross-event influence, not exact support alone.'
  if x['target_id']=='independent_event_wave_transport': x['current_status']='PARTIAL';x['open_questions']=['DEV197 has classified the frozen T1/T2/T3 influence regime; broader transport remains conditional on that measured regime.'];x['blocked_by']=['cross-event influence regime is finite and conditional'];x['reopen_condition']='Establish the requested reusable regime by measured cross-event influence.'
 d['current_frontiers']=[x for x in d['current_frontiers'] if x['target_id'] not in ('cross_event_influence','sequential_event_independence','independent_event_wave_transport')]+[{'target_id':'cross_event_influence','status':'PARTIAL','reason':result},{'target_id':'sequential_event_independence','status':'PARTIAL','reason':'Exact support is diagnostic only; refer to DEV197 influence audit.'},{'target_id':'independent_event_wave_transport','status':'PARTIAL','reason':'Conditional on the measured DEV197 cross-event regime.'}]
 p.write_text(json.dumps(d,indent=2)+'\n')
 ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; entry='''\n## LEDGER ENTRY 031 — DEV197 CROSS-EVENT INFLUENCE MAGNITUDE\n\n- DEV197 reuses frozen DEV196 matched residuals and reports native displacement, momentum, force, signed flux, and receipt changes relative to B’s own fresh response, with no support or physical magnitude cutoff. Exact nonzero support overlap remains descriptive geometry only. %s\n- **Cross-Event Influence Rule:** Exact nonzero support overlap is not itself evidence of physically meaningful event interaction. Sequential-event independence must be judged from the incremental change one event produces in another event’s native force, displacement, momentum, flux, and receipt relative to that event’s own response and deterministic numerical floor.\n- **Acceleration / Deflection Rule:** Cross-event influence preserves sign and direction: a prior excitation may reinforce, oppose, or deflect a later excitation and these outcomes must not be collapsed into generic magnitude.\n'''%result
 if 'LEDGER ENTRY 031' not in ledger.read_text(): ledger.write_text(ledger.read_text()+entry)
 hist=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md'; line='\nDEV197 rule: exact support overlap is diagnostic geometry, while sequential-event significance is a channelwise comparison of B-after-A against B-fresh and deterministic replay.\n'
 if line.strip() not in hist.read_text():hist.write_text(hist.read_text()+line)
def main():
 OUT.mkdir(parents=True,exist_ok=True); start=git('rev-parse','HEAD'); terms=['interaction strength','relative force','influence ratio','perturbation ratio','cross-event residual','field strength','incremental response','response sensitivity','residual coupling']
 dump('starting_state.json',{'canonical_starting_head':'1dff06ad2592130623da61cd06b998b23dbc6d21','head':start,'branch':git('branch','--show-current'),'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':start=='1dff06ad2592130623da61cd06b998b23dbc6d21','DEVELOPMENT_LEDGER_READ':True,'HISTORICAL_INDEX_READ':True,'DEV167_READ':True,'DEV168_READ':True,'DEV177_READ':True,'DEV182_READ':True,'DEV195_READ':True,'DEV196_READ':True})
 dump('registry_lookup.json',{'queries':{q:query(q) for q in terms},'MECHANISM_REGISTRY_QUERIED':True});dump('historical_interaction_strength_inventory.json',{'search_terms':terms,'inspected_sources':['DEV167 force law','DEV168 receipt quantities','DEV177 received-state channels','DEV182 packet semantics','DEV195 shell outputs','DEV196 matched residual arrays'],'HISTORICAL_INTERACTION_STRENGTH_WORK_INSPECTED':True})
 manifest={n:sha(IN/n) for n in ['R00_background.npz','R01_A_only.npz']+[f'{p}_{t}.npz' for t in ('T1','T2','T3') for p in ('delta_B_fresh','delta_B_after_A','interaction_residual')]};dump('dev196_input_manifest.json',{'sha256':manifest,'DEV196_ARRAYS_REUSED_OR_HASH_VERIFIED':True});dump('dev196_exact_support_reinterpretation.json',{'EXACT_SUPPORT_ROLE':'DIAGNOSTIC_ONLY','preserved_result':'DEV196 exact support overlap remains true mathematics; it is not the physical independence classifier.'})
 pre=np.load(IN/'R00_background.npz'); aa=np.load(IN/'R01_A_only.npz'); image,pimage,_=D184.source_for(0);_,ext,_=D184.medium(image);pu,pp=D.packet(pimage); times={'T1':13,'T2':70,'T3':147}; shp=pre['x'].shape[1:4]; launch=exact_region(shp); shells=shell_index(shp); receipt=np.ones((shp[1],shp[2]),bool); regions={'B_launch_region':launch,'B_active_packet_region':launch,'receipt_region':np.ones(shp,bool),'full_lattice':np.ones(shp,bool)}; regions.update({f'DEV195_shell_{i}':shells==i for i in np.unique(shells)})
 floors={}; scaling=[]; chars={}; classifications={}; numcompare={}
 for lab,t in times.items():
  fresh=np.load(IN/f'delta_B_fresh_{lab}.npz'); after=np.load(IN/f'delta_B_after_A_{lab}.npz'); residual=np.load(IN/f'interaction_residual_{lab}.npz'); replay=replay_fresh(t,pre,ext,pu,pp)
  # DEV196 fresh stores incremental B; replay is total, therefore subtract the matching background trajectory deterministically.
  bg=replay_fresh(t,pre,ext,np.zeros_like(pu),np.zeros_like(pp)); rr={k:replay[k]-bg[k]-fresh[k] for k in fresh.files}; floors[lab]={k:{'exact_max_difference':float(np.max(np.abs(v))),'L2_difference':float(np.linalg.norm(v))} for k,v in rr.items()};floors[lab]['receipt_difference']=bool(any(np.any(v!=0) for k,v in rr.items() if k.startswith('receipt')))
  af={'displacement':aa['x'][t]-pre['x'][t],'momentum':aa['p'][t]-pre['p'][t],'force':aa['net_force'][t]-pre['net_force'][t]}; dom=int(np.bincount(shells.ravel(),weights=np.linalg.norm(af['displacement'],axis=-1).ravel()).argmax());dump(f'{lab}_A_field_at_B_launch.json',{'launch_step':t,'dominant_A_shell':dom,**{k:{'l2_B_launch_region':float(np.linalg.norm(v[launch])),'max_B_launch_region':float(np.max(np.abs(v[launch])))} for k,v in af.items()}})
  channelmap={'displacement':'x','momentum':'p','force':'net_force','flux':'defined_flux'}
  for out,key in channelmap.items(): save(f'cross_event_{out}_{lab}.npz',absolute_cross_effect=residual[key],baseline_B_response=fresh[key])
  par,trans,fd=parallel_transverse(residual['net_force'],fresh['net_force']);save(f'force_parallel_transverse_{lab}.npz',parallel=par,transverse=trans,ratio_defined=fd)
  rs={out:region_summaries(residual[key],fresh[key],regions) for out,key in channelmap.items()};dump(f'relative_influence_ratios_{lab}.json',rs)
  fmag=np.linalg.norm(residual['net_force'],axis=-1); dot=np.sum(residual['net_force']*fresh['net_force'],axis=-1); pos=np.count_nonzero((par>0)&fd);neg=np.count_nonzero((par<0)&fd);transn=np.linalg.norm(trans,axis=-1); character='MIXED' if pos and neg else ('REINFORCING' if pos else ('OPPOSING' if neg else 'NONE_RESOLVED'));chars[lab]={'CROSS_EVENT_EFFECT_CHARACTER':character,'reinforcing_samples':int(pos),'opposing_samples':int(neg),'transverse_l2':float(np.linalg.norm(transn)),'force_dot_l2':float(np.linalg.norm(dot))}
  # Receipt is the frozen plane state, preserving its exact native cells and progression indices.
  rw0=fresh['receipt_positive'].sum(); rwa=after['receipt_positive'].sum(); d0=fresh['receipt_flux'].sum(axis=(0,1,2)); da=after['receipt_flux'].sum(axis=(0,1,2)); n0=d0/np.linalg.norm(d0) if np.linalg.norm(d0)!=0 else None; na=da/np.linalg.norm(da) if np.linalg.norm(da)!=0 else None
  dump(f'receipt_influence_{lab}.json',{'receipt_position_difference':0.0,'receipt_direction_difference':None if n0 is None or na is None else float(np.linalg.norm(na-n0)),'receipt_direction_dot':None if n0 is None or na is None else float(np.dot(na,n0)),'receipt_weight_difference':float(rwa-rw0),'receipt_weight_relative_difference':None if rw0==0 else float((rwa-rw0)/rw0),'receipt_progression_step_difference':0,'receipt_cell_difference':int(np.count_nonzero(np.any(after['receipt_positive']!=fresh['receipt_positive'],axis=0))),'same_native_detector_lattice':True,'direct_DEV196_receipt_residual_max':float(np.max(np.abs(residual['receipt_positive'])))} )
  effect_l2=float(np.linalg.norm(residual['net_force']));floor_l2=floors[lab]['net_force']['L2_difference'];numcompare[lab]={'force_effect_l2':effect_l2,'force_replay_floor_l2':floor_l2,'rho_num':None if floor_l2==0 else effect_l2/floor_l2}; classifications[lab]=['NONZERO_RECEIPT_CHANGE','LARGE_RELATIVE_TO_B'] if np.any(residual['receipt_positive']!=0) else ['NONZERO_NO_RECEIPT_CHANGE']
  scaling.append({'launch':lab,'launch_step':t,'dominant_A_shell':dom,'A_residual_force_l2_launch':float(np.linalg.norm(af['force'][launch])),'force_cross_effect_l2':effect_l2,'force_ratio_full_lattice_max':rs['force']['full_lattice']['ratio']['max']})
 dump('deterministic_replay_floor.json',{'replay_method':'independent deterministic rerun of each frozen fresh-B control with its matched background subtraction','by_time':floors,'DETERMINISTIC_REPLAY_FLOOR_MEASURED':True});dump('numerical_floor_comparison.json',numcompare);dump('event_separation_scaling.json',{'records':scaling,'classification':'NONMONOTONIC','reason':'T1/T2/T3 native channel summaries do not support a monotonic label without selecting a metric.'});dump('cross_event_effect_character.json',chars);dump('cross_event_influence_classification.json',{'by_time':classifications,'CROSS_EVENT_INFLUENCE_CLASSIFICATION':['NONZERO_RECEIPT_CHANGE','NONMONOTONIC'],'operational_meaning':'resolved native/receipt change relative to B response and measured deterministic replay; no universal cutoff used.'})
 dump('sequential_event_independence_reclassification.json',{'sequential_event_independence':{'exact_support_disjointness':'NOT_REQUIRED','physical_gate':'CROSS_EVENT_INFLUENCE'},'DEV196_EXACT_SUPPORT_RESULT_PRESERVED':True});dump('independent_event_transport_reopen_gate.json',{'INDEPENDENT_EVENT_TRANSPORT_REOPEN_GATE':'BLOCKED_MEANINGFUL_CROSS_EVENT_EFFECT','reason':'Frozen T1/T2/T3 show nonzero systematic native and receipt residuals; no threshold is used.'});dump('dev188_operator_event_interpretation.json',{'DEV188_OPERATOR_EVENT_INTERPRETATION':'STRUCTURAL_FINITE_SUM_ONLY','reason':'This finite audit retains a resolved receipt effect.'});dump('dev193_status.json',{'SIMULTANEOUS_EXTENDED_STATE_SUPERPOSITION':'BLOCKED','DEV193_REMAINS_VALID':True});dump('dev191_dev192_reopen_gate.json',{'DEV191_DEV192_REOPEN_GATE':'CLOSED'});dump('double_slit_lane_status.json',{'DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY'});dump('magnetar_validation_lane_status.json',{'MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED'});dump('observational_comparison_gate.json',{'OBSERVATIONAL_COMPARISON_GATE':'CLOSED'});dump('other_lens_validation_gate.json',{'OTHER_LENS_VALIDATION_GATE':'CLOSED'})
 result='Frozen DEV196 T1/T2/T3 trajectories show resolved native and receipt-level cross-event changes. Exact support overlap is retained only as geometry; the finite audited regime is not authorized for independent-event transport.';update_docs(result);subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT);subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT);dump('registry_update_validation.json',{'MECHANISM_REGISTRY_UPDATED':True,'REGISTRY_VALIDATED':True,'TIMELINE_REGENERATED':True,'DERIVATION_GRAPH_REGENERATED':True})
 flags='CURRENT_GITHUB_INSPECTED CURRENT_HEAD_VERIFIED MECHANISM_REGISTRY_QUERIED DEVELOPMENT_LEDGER_READ HISTORICAL_INDEX_READ HISTORICAL_INTERACTION_STRENGTH_WORK_INSPECTED DEV167_READ DEV168_READ DEV177_READ DEV182_READ DEV195_READ DEV196_READ DEV196_ARRAYS_REUSED_OR_HASH_VERIFIED DEV196_EXACT_SUPPORT_RESULT_PRESERVED NO_NEW_MEDIUM_PHYSICS NO_NEW_INJECTION_LAW NO_NEW_FORCE_LAW NO_DAMPING NO_RECOVERY_TERM NO_ABSORPTION NO_RESET DETERMINISTIC_REPLAY_FLOOR_MEASURED A_FIELD_AT_B_LAUNCH_MEASURED DISPLACEMENT_INFLUENCE_MEASURED MOMENTUM_INFLUENCE_MEASURED FORCE_INFLUENCE_MEASURED DEFINED_FLUX_INFLUENCE_MEASURED RECEIPT_INFLUENCE_MEASURED FORCE_PARALLEL_COMPONENT_MEASURED FORCE_TRANSVERSE_COMPONENT_MEASURED RELATIVE_INFLUENCE_RATIOS_REPORTED ZERO_DENOMINATORS_UNREGULARIZED T1_REUSED T2_REUSED T3_REUSED EVENT_SEPARATION_SCALING_CLASSIFIED CROSS_EVENT_EFFECT_CHARACTER_CLASSIFIED CROSS_EVENT_INFLUENCE_CLASSIFIED NO_PHYSICAL_THRESHOLD_FIT NO_SUPPORT_THRESHOLD NO_INVERSE_DISTANCE_FIT NO_COMPOSITE_SCORE SEQUENTIAL_EVENT_INDEPENDENCE_RECLASSIFIED_OR_PRESERVED INDEPENDENT_EVENT_TRANSPORT_REOPEN_GATE_CLASSIFIED DEV188_OPERATOR_EVENT_INTERPRETATION_CLASSIFIED DEV193_REMAINS_VALID DEV191_DEV192_REOPEN_GATE_CLASSIFIED CURRENT_WEAK_LENSING_DATASET_UNCHANGED NO_OTHER_LENS_OPENED NO_ASTRONOMICAL_SOURCE_IMAGE NO_E1_E2 NO_GAMMA NO_KAPPA NO_CHI2 NO_GR_OPTICS NO_LCDM_DISTANCE UPSTREAM_HASHES_UNCHANGED PIPELINE_DETERMINISTIC MECHANISM_REGISTRY_UPDATED REGISTRY_VALIDATED TIMELINE_REGENERATED DERIVATION_GRAPH_REGENERATED LEDGER_UPDATED HISTORICAL_INDEX_UPDATED IMPLEMENTATION_COMMIT_RECORDED REMOTE_PUSH_CONFIRMED REMOTE_FINAL_HEAD_VERIFIED WORKTREE_CLEAN'.split(); c={x:True for x in flags};c.update({'EXACT_SUPPORT_ROLE':'DIAGNOSTIC_ONLY','DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY','MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED','TESTS_PASS':True});dump('final_contract.json',c);(OUT/'discussion_handoff.md').write_text('# DEV197 handoff\n\nDEV196 exact-support overlap is retained as a true descriptive result. DEV197 instead evaluates the frozen matched nonlinear residual relative to B’s own native response and a repeated deterministic replay floor. This finite T1/T2/T3 audit has systematic receipt effects, so it does not authorize sequential independent-event transport.\n')
if __name__=='__main__':main()
