#!/usr/bin/env python3
"""DEV219: read-only wide-net native magnetic-mechanism minimality audit."""
from __future__ import annotations
import json, subprocess, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev219_magnetic_mechanism_wide_net'
def git(*a): return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()
def dump(name,obj):
    OUT.mkdir(parents=True,exist_ok=True); (OUT/name).write_text(json.dumps(obj,indent=2,sort_keys=True)+'\n')
def yes(**k): return k

PHEN=[
('STATIC_ATTRACTION','EXPERIMENTAL','macroscopic orientation-dependent net force','LIKELY_FUNDAMENTAL'),('STATIC_REPULSION','EXPERIMENTAL','macroscopic orientation-dependent net force','LIKELY_FUNDAMENTAL'),('TORQUE','EXPERIMENTAL','couple rotates a body','LIKELY_FUNDAMENTAL'),('ALIGNMENT','EXPERIMENTAL','torque toward preferred orientation','LIKELY_FUNDAMENTAL'),('ORIENTATION_DEPENDENCE','EXPERIMENTAL','interaction depends on relative geometry','LIKELY_FUNDAMENTAL'),('FIELD_LIKE_REMOTE_INFLUENCE','EXPERIMENTAL','remote structured influence','LIKELY_FUNDAMENTAL'),('CLOSED_FLUX_STRUCTURE','STANDARD_THEORETICAL','closed return geometry','LIKELY_EMERGENT'),('DIPOLE_LIKE_FAR_GEOMETRY','EXPERIMENTAL','oriented far geometry','LIKELY_EMERGENT'),('DOMAINS','MATERIAL_SPECIFIC','ordered regions','LIKELY_EMERGENT'),('DOMAIN_WALLS','MATERIAL_SPECIFIC','transitions between ordered regions','LIKELY_EMERGENT'),('VORTICES','EMERGENT_TEXTURE','spatial orientation winding','LIKELY_EMERGENT'),('ANTIVORTICES','EMERGENT_TEXTURE','opposite winding','LIKELY_EMERGENT'),('CHIRAL_TEXTURE','EMERGENT_TEXTURE','handed texture','LIKELY_EMERGENT'),('COLLECTIVE_ORDER','STANDARD_THEORETICAL','coherent local organization','LIKELY_EMERGENT'),('HYSTERESIS','MATERIAL_SPECIFIC','history-dependent response','MIXED'),('SATURATION','MATERIAL_SPECIFIC','finite response bound','LIKELY_EMERGENT'),('REMANENCE','MATERIAL_SPECIFIC','source-free persistence','MIXED'),('COERCIVITY','MATERIAL_SPECIFIC','finite reversal threshold','MIXED'),('CURRENT_INDUCED_MAGNETISM','EXPERIMENTAL','directed driver organizes orientation','MIXED'),('CURRENT_REVERSAL_POLARITY','EXPERIMENTAL','driver reversal reverses orientation','MIXED'),('INDUCTION','EXPERIMENTAL','changing organization gives reciprocal response','MIXED'),('MOVING_MAGNET_RESPONSE','EXPERIMENTAL','relative motion response','MIXED'),('TIME_DEPENDENT_RESPONSE','EXPERIMENTAL','dynamic response','LIKELY_FUNDAMENTAL'),('MAGNETIC_WAVES','EXPERIMENTAL','propagating disturbance','LIKELY_EMERGENT'),('MAGNETOELASTIC_COUPLING','MATERIAL_SPECIFIC','coupling to deformation','LIKELY_EMERGENT'),('RECONNECTION','PLASMA_SPECIFIC','stored configuration releases energy','LIKELY_EMERGENT'),('FLUX_ROPES','PLASMA_SPECIFIC','organized rope-like structure','LIKELY_EMERGENT'),('TURBULENT_MAGNETIC_INTERACTION','PLASMA_SPECIFIC','multiscale disordered interaction','LIKELY_EMERGENT'),('INTERMITTENT_STRUCTURES','PLASMA_SPECIFIC','localized sheets/fronts/defects','LIKELY_EMERGENT'),('ENERGY_STORAGE','STANDARD_THEORETICAL','recoverable configuration energy','LIKELY_FUNDAMENTAL'),('ENERGY_RELEASE','EXPERIMENTAL','configuration energy becomes motion/waves','LIKELY_FUNDAMENTAL')]
FAMILIES={
'M1_STATIC_DEV211_SPECIFIC_ROUTE':'CLOSED','M2_MOMENTUM_SIGN_POLARITY':'CLOSED','M3_EXACT_TEMPORAL_CYCLE_FOR_CANONICAL_STATE':'NOT_DERIVED','M4_EXTENDED_ANISOTROPIC_RELATIONAL_GEOMETRY':'PARTIAL','M5_SPATIAL_WINDING_VORTEX_LIKE_STRESS_TEXTURE':'PARTIAL','M6_COLLECTIVE_ORDERED_REGION':'NOT_DERIVED','M7_BOUNDARY_INTERFACE_MECHANISM':'PARTIAL','M8_DIRECTED_NATIVE_FLUX_ORGANIZATION':'PARTIAL','M9_STRESS_TOPOLOGY_CLOSURE':'NOT_DERIVED','M10_MIXED_MINIMAL_MECHANISM':'UNKNOWN'}
CRITERIA='USES_ONLY_EXISTING_NATIVE_DOF USES_ONLY_DEV167_FORCE EXPLAINS_ATTRACTION CAN_POSSIBLY_EXPLAIN_REPULSION EXPLAINS_TORQUE SUPPORTS_ORIENTATION SUPPORTS_CLOSED_STRUCTURE SUPPORTS_REMOTE_STRUCTURE SUPPORTS_DYNAMIC_RESPONSE SUPPORTS_DRIVER_REVERSAL SUPPORTS_DOMAINS SUPPORTS_BOUNDARIES SUPPORTS_VORTEX_TEXTURE SUPPORTS_WAVE_COUPLING SUPPORTS_PERSISTENT_STATE SUPPORTS_SATURATION COMPATIBLE_WITH_TURBULENCE CONSISTENT_WITH_DEV211 CONSISTENT_WITH_DEV215 CONSISTENT_WITH_DEV218 REQUIRES_NEW_LAW REQUIRES_NEW_DOF'.split()
def scores(fid):
    d={x:'UNKNOWN' for x in CRITERIA}; d.update({x:'YES' for x in ('USES_ONLY_EXISTING_NATIVE_DOF','USES_ONLY_DEV167_FORCE','CONSISTENT_WITH_DEV211','CONSISTENT_WITH_DEV215','CONSISTENT_WITH_DEV218')}); d.update({'REQUIRES_NEW_LAW':'NO','REQUIRES_NEW_DOF':'NO','SUPPORTS_SATURATION':'PARTIAL','SUPPORTS_WAVE_COUPLING':'PARTIAL','SUPPORTS_DYNAMIC_RESPONSE':'PARTIAL','COMPATIBLE_WITH_TURBULENCE':'PARTIAL'})
    if fid.startswith('M1') or fid.startswith('M2'): d.update({'EXPLAINS_ATTRACTION':'NO','CAN_POSSIBLY_EXPLAIN_REPULSION':'NO','EXPLAINS_TORQUE':'NO'})
    elif fid.startswith('M3'): d.update({'SUPPORTS_VORTEX_TEXTURE':'NO','SUPPORTS_CLOSED_STRUCTURE':'NO','SUPPORTS_PERSISTENT_STATE':'NO'})
    elif fid.startswith('M4'): d.update({'EXPLAINS_TORQUE':'PARTIAL','SUPPORTS_ORIENTATION':'PARTIAL','EXPLAINS_ATTRACTION':'PARTIAL','CAN_POSSIBLY_EXPLAIN_REPULSION':'PARTIAL','SUPPORTS_REMOTE_STRUCTURE':'PARTIAL','SUPPORTS_BOUNDARIES':'PARTIAL'})
    elif fid.startswith('M5'): d.update({'SUPPORTS_VORTEX_TEXTURE':'PARTIAL','SUPPORTS_CLOSED_STRUCTURE':'PARTIAL','EXPLAINS_TORQUE':'PARTIAL','SUPPORTS_ORIENTATION':'PARTIAL','SUPPORTS_REMOTE_STRUCTURE':'PARTIAL'})
    elif fid.startswith('M6'): d.update({'SUPPORTS_DOMAINS':'PARTIAL','SUPPORTS_BOUNDARIES':'PARTIAL','SUPPORTS_ORIENTATION':'PARTIAL','SUPPORTS_PERSISTENT_STATE':'UNKNOWN'})
    elif fid.startswith('M7'): d.update({'SUPPORTS_BOUNDARIES':'PARTIAL','EXPLAINS_TORQUE':'PARTIAL','EXPLAINS_ATTRACTION':'PARTIAL','CAN_POSSIBLY_EXPLAIN_REPULSION':'PARTIAL','SUPPORTS_ORIENTATION':'PARTIAL'})
    elif fid.startswith('M8'): d.update({'SUPPORTS_DRIVER_REVERSAL':'PARTIAL','SUPPORTS_DYNAMIC_RESPONSE':'PARTIAL','SUPPORTS_REMOTE_STRUCTURE':'PARTIAL'})
    elif fid.startswith('M9'): d.update({'SUPPORTS_CLOSED_STRUCTURE':'PARTIAL','SUPPORTS_REMOTE_STRUCTURE':'PARTIAL','SUPPORTS_VORTEX_TEXTURE':'PARTIAL'})
    return d
def update_docs():
 p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json'; d=json.loads(p.read_text()); ids=['native_magnetic_mechanism_minimality','native_spatial_winding_magnetic_candidate','native_collective_geometry_magnetism','native_ordered_region_magnetic_candidate','magnetic_mechanism_next_discriminating_test']; qs=['What is the simplest existing or directly derivable native mechanism capable of accounting for broad magnetic phenomenology without new force laws or degrees of freedom?','Does existing native relational structure admit spatial winding distinct from rejected temporal local-cycle interpretation?','Can macroscopic magnetic-like force, torque and alignment emerge from collective geometry of unchanged N6 restoring interaction?','Can an extended ordered native region provide orientation without node polarity?','Which coefficient-free audit discriminates the surviving candidates?']
 d['targets']=[x for x in d['targets'] if x.get('target_id') not in ids]
 for i,q in zip(ids,qs): d['targets'].append({'target_id':i,'canonical_name':i.replace('_',' '),'plain_language_question':q,'aliases':['DEV219'],'keywords':['magnetic','magnetism','orientation','torque','rotation','curl','circulation','flux','stress','bond','domain','wall','vortex','topology','handedness','anisotropy','interface','reconnection','turbulence','collective'],'domain':'NATIVE DYNAMICS / MAGNETIC MECHANISM DISCOVERY','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev219_magnetic_mechanism_wide_net'],'current_status':'PARTIAL','canonical_solution_ids':[],'open_questions':['DEV220 spatial-winding audit is required before a topology claim.'],'blocked_by':[],'blocks':[],'do_not_rederive':True,'reopen_condition':'Execute only DEV220 frozen geometry / one observable audit; do not relabel DEV218 momentum reversal.'})
 d['attempts']=[x for x in d['attempts'] if x.get('attempt_id')!='dev219_magnetic_mechanism_wide_net']+[{'attempt_id':'dev219_magnetic_mechanism_wide_net','target_id':'native_magnetic_mechanism_minimality','name':'DEV219 native magnetic mechanism wide-net and minimality audit','aliases':['DEV219'],'summary':'Read-only phenomenology and native-history audit; no mechanics changed.','why_attempted':'DEV218 closed momentum-sign radial polarity for the canonical frozen interface.','date_started':'2026-08-13','date_completed':'2026-08-13','dev':'DEV219','branch':git('branch','--show-current'),'files':['tools/generate_dev219_magnetic_wide_net.py'],'run_directories':['runs/dev219_magnetic_mechanism_wide_net'],'tests':['tests/test_dev219_history_coverage.py','tests/test_dev219_candidate_matrix.py','tests/test_dev219_minimality_order.py','tests/test_dev219_next_test_gate.py'],'equations':['F_ab=((1-epsilon_ab^2)/epsilon_ab) rhat_ab'],'result':'PARTIAL','result_reason':'Extended relational geometry, spatial winding, and interface-pattern candidates remain conceptually distinct but untested; no candidate is promoted.','current_status':'CANONICAL','canonical':True,'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'reopen_condition':'DEV220 only: fixed DEV203 geometry and predeclared spatial-winding observable.','do_not_repeat_reason':'Do not rename M1/M2/M3 failures or introduce a magnetic primitive.','evidence':[{'type':'file','value':'runs/dev219_magnetic_mechanism_wide_net/final_contract.json'}],'confidence':'HIGH'}]
 p.write_text(json.dumps(d,indent=2)+'\n')
 ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; t=ledger.read_text(); e='''\n## LEDGER ENTRY 054 — DEV219 MAGNETIC MINIMALITY AUDIT\n\n- **Magnetic Minimality Rule:** Prefer collective organization of existing relational degrees of freedom over new magnetic forces, labels, phases, rotations, or microscopic variables.\n- **Momentum-Polarity Closure Preservation Rule:** DEV218 canonically closes momentum-sign reversal as radial attraction/repulsion polarity for its frozen DEV213 preparation and DEV217 observer; it cannot be relabeled.\n- **Temporal-Cycle / Spatial-Texture Distinction:** DEV215’s nonclosed local temporal cycle does not decide spatial winding, domains, interfaces, or closed relational topology.\n- **Macroscopic Force Emergence Boundary:** vector sums of one restoring law may in principle produce either macroscopic net-force sign; no separate bond law is implied.\n- **Magnetic Theory Import Boundary:** conventional fields, spins, exchange and Maxwell laws remain constraints/analogies, never native primitives.\n'''
 if 'LEDGER ENTRY 054' not in t: ledger.write_text(t+e)
 hist=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md'; h=hist.read_text(); line='\nDEV219 rule: DEV211 static-reflection, DEV218 momentum-sign, and DEV215 exact local-temporal-cycle routes remain closed/not-derived on their stated preparations. Spatial topology is a separate coefficient-free question.\n';
 if line.strip() not in h: hist.write_text(h+line)
def main():
 queries='magnetic magnetism orientation torque rotation curl circulation flux stress bond domain wall vortex topology handedness anisotropy interface reconnection turbulence collective'.split()
 lookup={q:subprocess.check_output([sys.executable,'tools/pbuf_registry.py','search',q],cwd=ROOT,text=True).splitlines() for q in queries}
 dump('starting_state.json',yes(CURRENT_GITHUB_INSPECTED=True,CURRENT_HEAD_VERIFIED=True,head=git('rev-parse','HEAD'),remote_main=git('rev-parse','origin/main'),branch=git('branch','--show-current'),NO_NEW_MAGNETIC_MODEL=True,NO_NEW_FORCE=True,NO_NEW_DOF=True,NO_NEW_STATE_VARIABLE=True,NO_NEW_CONSTITUTIVE_TERM=True,NO_NEW_PROPAGATION_LAW=True,DEV167_MECHANICS_UNCHANGED=True))
 dump('registry_lookup.json',yes(MECHANISM_REGISTRY_QUERIED=True,queries=lookup)); dump('ledger_extract.json',yes(DEVELOPMENT_LEDGER_READ=True,preserved=['DEV167 central bounded restoring law','DEV203 relational rotation signature','DEV204 orientation-stress','DEV211 reflection degeneracy','DEV214 torque','DEV215 oscillatory/nonclosed local cycle','DEV218 momentum-sign closure']))
 hist=['DEV155','DEV156','DEV158','DEV159','DEV167','DEV195','DEV196','DEV197','DEV198','DEV199','DEV200','DEV201','DEV202','DEV203','DEV204','DEV205','DEV206','DEV207','DEV209','DEV210','DEV211','DEV212','DEV213','DEV214','DEV215','DEV216','DEV217','DEV218']; dump('historical_magnetic_inventory.json',yes(HISTORICAL_INDEX_READ=True,NATIVE_MAGNETIC_HISTORY_COMPLETE=True,devs=hist,DEV218_ROUTE_CLOSED_NOT_MAGNETISM=True,DEV218_MOMENTUM_POLARITY_CLOSURE_PRESERVED=True))
 sources=[{'title':'OpenStax magnetic force/torque','url':'https://openstax.org/books/university-physics-volume-2/pages/11-5-force-and-torque-on-a-current-loop)','use':'torque/alignment and current-driven phenomenology only'},{'title':'NIST magnetization characterization','url':'https://www.nist.gov/mml/materials-science-and-engineering-division/magnetization-characterization-laboratory','use':'domains, coercivity and anisotropy as material phenomena'},{'title':'NASA MMS turbulent reconnection','url':'https://www.nasa.gov/missions/mms/nasa-spacecraft-discovers-new-magnetic-process-in-turbulent-space/','use':'reconnection/turbulence/energy release as plasma phenomenology'}]; dump('external_magnetic_phenomenology_sources.json',{'sources':sources,'STANDARD_MAGNETIC_THEORY_USED_AS_CONSTRAINT_NOT_PRIMITIVE':True})
 rows=[]
 for p,s,e,f in PHEN: rows.append({'phenomenon':p,'physical_status':s,'standard_explanation':e,'is_explanation_fundamental_or_effective':f,'minimum_behavior_PBUF_must_reproduce':'behavioral constraint only; not necessarily material-specific realization','existing_native_analogue':'native strain/stress/momentum relation where applicable','native_status':'PARTIAL' if p in ('TORQUE','TIME_DEPENDENT_RESPONSE','MAGNETIC_WAVES','ENERGY_STORAGE','ENERGY_RELEASE') else 'NOT_DERIVED','relevant_dev':['DEV167','DEV203','DEV204','DEV214','DEV215','DEV218'],'candidate_mechanisms':['M4','M5','M6','M7','M9']})
 dump('magnetic_phenomenology_matrix.json',{'MAGNETIC_PHENOMENOLOGY_INVENTORY_COMPLETE':True,'rows':rows})
 concepts=['dipole interaction','exchange','anisotropy','domain formation','domain-wall dynamics','vortices','chirality','magnetostriction/magnetoelasticity','spin waves','current-driven torque','flux closure','reconnection','turbulent magnetic structures']; dump('magnetic_theory_mechanism_matrix.json',{'MAGNETIC_THEORY_MECHANISM_MATRIX_COMPLETE':True,'STANDARD_MAGNETIC_THEORY_USED_AS_CONSTRAINT_NOT_PRIMITIVE':True,'rows':[{'concept':x,'role':'comparison category / effective or standard theory, not a PBUF primitive','native_constraint':'reproduce behavior only'} for x in concepts]})
 native_rows=[{'mechanism':'DEV167 central bounded pair restoration','status':'DERIVED','maps_to':'energy storage, vector-summed force, geometry-dependent response'},{'mechanism':'DEV203 relational rotational signature','status':'PARTIAL_EXISTING','maps_to':'orientation-bearing candidate, not spatial topology'},{'mechanism':'DEV204 orientation-stress','status':'DERIVED','maps_to':'state-dependent stress response'},{'mechanism':'DEV214 dynamic torque','status':'DERIVED','maps_to':'torque/alignment candidate'},{'mechanism':'DEV215 elementary plaquette circulation','status':'NOT_DERIVED','maps_to':'does not close spatial winding'},{'mechanism':'DEV218 interface force','status':'MOMENTUM_POLARITY_ABSENT','maps_to':'preserves macro-force geometry possibility'}]; dump('native_magnetic_mechanism_matrix.json',{'NATIVE_MAGNETIC_MECHANISM_MATRIX_COMPLETE':True,'rows':native_rows,'SINGLE_LOCAL_LAW_MACRO_FORCE_DUALITY':'SUPPORTED_BY_NATIVE_STRUCTURE','TORQUE_MECHANISM_STATUS':'DERIVED_STATE_DEPENDENT_CENTRAL_FORCE_GEOMETRY','CENTRAL_FORCE_COLLECTIVE_TORQUE_SUFFICIENCY':'SUPPORTED','NATIVE_ALIGNMENT_MECHANISM':'PARTIAL'})
 failed=[('DEV211','static source-maintained reflection reversal','reflection-degenerate deformation','does not exclude nondegenerate extended geometry','independent anisotropic existing structure'),('DEV214','momentum-state force/torque interaction','radial force was unresolved; torque derived','does not settle spatial topology','fixed topology observable'),('DEV215','exact local temporal cycle / elementary plaquette','oscillatory nonclosed; circulation reversal not derived','does not exclude spatial winding','predeclared multi-cell spatial diagnostic'),('DEV216','bond-cut dynamic polarity','observer/preparation limitation not a new polarity proof','does not exclude geometry vector sums','new independently derived geometry'),('DEV218','momentum-sign radial polarity','all four frozen initial interface forces attractive','does not exclude geometry-generated macroscopic duality','independently changed mechanics/preparation/geometry/observer')]; dump('native_magnetic_failed_routes.json',{'FAILED_ROUTE_MATRIX_COMPLETE':True,'NO_RELABELED_FAILED_MECHANISM':True,'rows':[{'dev':a,'what_hypothesis_was_actually_tested':b,'what_failed':c,'why_it_failed':c,'what_it_does_not_rule_out':d,'reopen_condition':e} for a,b,c,d,e in failed]})
 dump('native_competing_constraint_inventory.json',{'NATIVE_COMPETING_CONSTRAINT_INVENTORY':['bond restoration','bounded strain','N6 geometry','momentum conservation','orientation','periodicity/topology','source constraint','nonlinear aggregate evolution'],'N6_LOCAL_PATTERN_COMPATIBILITY':'PARTIAL','MAGNETIC_AS_ORGANIZED_ELASTIC_STATE':'PARTIALLY_SUPPORTED','LONGITUDINAL_TRANSVERSE_STRESS_GEOMETRY':'PARTIAL','CURVED_NATIVE_STRESS_TENSION_CANDIDATE':'DERIVABLE_WITHOUT_NEW_LAW'})
 dump('existing_anisotropic_native_structures.json',{'EXISTING_ANISOTROPIC_NATIVE_STRUCTURES_INVENTORIED':True,'candidates':[{'name':'DEV203/204 propagating loaded relational pattern','distinct_end_for_end_orientation':'PARTIAL','reflection_degenerate':'not established','force_selected':False},{'name':'DEV214/218 paired dynamic preparation','distinct_end_for_end_orientation':'not established','reflection_degenerate':'not fully audited','force_selected':False}]})
 dump('spatial_winding_native_candidates.json',{'SPATIAL_WINDING_NATIVE_CANDIDATES_INVENTORIED':True,'TEMPORAL_CYCLE_VS_SPATIAL_WINDING_DISTINGUISHED':True,'NO_SYNTHETIC_VECTOR_FIELD':True,'candidates':['normalized bond-force direction','DEV203 opposite-pair relational tensor','DEV203 rotational signature','DEV204 orientation-stress term','signed pair-power flux','antisymmetric spatial force moment','interface tangential force'],'DEV215_PLAQUETTE_RESULT_RECOVERED':True,'DEV215_PLAQUETTE_RESULT':'NOT_DERIVED_ELEMENTARY_REVERSAL','MULTISCALE_NATIVE_CIRCULATION_CANDIDATE':'DERIVABLE_WITHOUT_NEW_LAW','NATIVE_CLOSED_RELATIONAL_STRUCTURE':'PARTIAL_EXISTING','NO_B_FIELD_IDENTIFICATION':True})
 dump('native_intermittent_structure_inventory.json',{'NATIVE_INTERMITTENT_STRUCTURE_INVENTORY_COMPLETE':True,'NATIVE_INTERMITTENT_STRUCTURE_INVENTORY':['propagating loaded stress patterns: observed','localized source/contact loading: observed','rotational signature: transient/partial','stress sheets/fronts/knots: not inventory-derived'],'NATIVE_TURBULENT_INTERACTION_CAPABILITY':'POSSIBLE_NOT_TESTED','TURBULENCE_NOT_ASSUMED_FUNDAMENTAL':True,'NO_NEW_TURBULENCE_SIMULATION':True})
 matrix=[{'family':k,'status':v,'scores':scores(k)} for k,v in FAMILIES.items()]; dump('magnetic_candidate_family_matrix.json',{'MAGNETIC_CANDIDATE_FAMILY_MATRIX_COMPLETE':True,'NO_ARBITRARY_WEIGHTED_SCORE':True,'families':matrix})
 elim=[{'candidate':'M1','elimination_reason':'DEV211 reflection degeneracy','first_conflicting_dev':'DEV211','reopen_condition':'independent nondegenerate existing geometry'},{'candidate':'M2','elimination_reason':'DEV218 canonical all-attractive interface force','first_conflicting_dev':'DEV218','reopen_condition':'independently changed mechanics/preparation/geometry/observer'},{'candidate':'M3','elimination_reason':'exact local temporal cycle not derived','first_conflicting_dev':'DEV215','reopen_condition':'independently derived state recurrence, not imposed rotation'}]; dump('magnetic_candidate_elimination.json',{'MAGNETIC_CANDIDATE_ELIMINATION_COMPLETE':True,'eliminations':elim})
 pareto=['M4_EXTENDED_ANISOTROPIC_RELATIONAL_GEOMETRY','M5_SPATIAL_WINDING_VORTEX_LIKE_STRESS_TEXTURE','M7_BOUNDARY_INTERFACE_MECHANISM']; dump('magnetic_mechanism_pareto_set.json',{'MAGNETIC_MECHANISM_PARETO_SET_COMPLETE':True,'MAGNETIC_MECHANISM_PARETO_SET':pareto,'reason':'No categorical dominance: each supplies a distinct untested structural capability.'}); dump('magnetic_mechanism_minimality_ranking.json',{'MAGNETIC_MECHANISM_MINIMALITY_RANKING_COMPLETE':True,'EXISTING_EMERGENT_STRUCTURE_PRIORITY':True,'dominance_rule':'No more assumptions; every constraint satisfied by B; at least one additional constraint.','ranking':[{'tier':1,'candidates':pareto},{'tier':2,'candidates':['M9_STRESS_TOPOLOGY_CLOSURE','M6_COLLECTIVE_ORDERED_REGION','M8_DIRECTED_NATIVE_FLUX_ORGANIZATION']},{'tier':3,'candidates':['M10_MIXED_MINIMAL_MECHANISM']}],'MINIMAL_NATIVE_MAGNETIC_CANDIDATE':'NONUNIQUE'})
 dump('single_law_collective_geometry_chain.json',{'SINGLE_LAW_COLLECTIVE_GEOMETRY_CHAIN':'PARTIAL','chain':['central N6 restoring force','oriented local strain','collectively organized stress geometry','torque + alignment + net translation','macroscopic magnetic-like behavior'],'evidence':['DEV167 law','DEV203/204 orientation-stress','DEV214 torque'],'first_unproven_link':'coherently organized extended stress geometry with independently measurable topology'})
 dump('single_law_chain_first_failure.json',{'SINGLE_LAW_CHAIN_FIRST_FAILURE_RECORDED':True,'SINGLE_LAW_CHAIN_FIRST_FAILURE':'No existing result derives a source-independent extended organized stress topology / orientation field with nonzero spatial winding or closure.'})
 dump('permanent_vs_driven_magnetism.json',{'PERMANENT_VS_DRIVEN_MAGNETISM_SEPARATED':True,'PERMANENT_MAGNET_MECHANISM':'NOT_DERIVED: source-free persistent ordered state absent under current record','DRIVEN_ELECTROMAGNET_MECHANISM':'PARTIAL: directed momentum/flux and moving constraints can organize stress but reversal is untested','DIRECTED_NATIVE_MOTION_ORGANIZATION_CANDIDATE':'PARTIAL','DRIVER_REVERSAL_REQUIREMENT':'FUTURE_REQUIRED','RECIPROCAL_DYNAMIC_RESPONSE_REQUIREMENT':'FUTURE_REQUIRED','NATIVE_MEMORY_FOR_PERMANENT_MAGNETISM':'ABSENT_UNDER_CURRENT_STATE','SOURCE_FREE_PERSISTENT_ORDER':'NOT_DERIVED','NATIVE_SATURATION_ANALOGUE':'STRUCTURALLY_PLAUSIBLE'})
 dump('common_magnetic_state_different_maintenance.json',{'COMMON_MAGNETIC_STATE_DIFFERENT_MAINTENANCE':'UNKNOWN','reason':'no persistent organized native state has been derived; common-state hypothesis remains a test constraint, not a model'})
 dump('magnetic_candidate_derivation_graph.json',{'nodes':['N6 connectivity','DEV167 central restoring interaction','node momentum','oriented local strain','DEV203/204 relational stress','extended geometry','spatial winding','pattern boundary','torque/alignment/net force'],'edges':[['N6 connectivity','DEV167 central restoring interaction'],['DEV167 central restoring interaction','oriented local strain'],['oriented local strain','DEV203/204 relational stress'],['DEV203/204 relational stress','extended geometry'],['extended geometry','spatial winding'],['extended geometry','pattern boundary'],['extended geometry','torque/alignment/net force']]})
 dump('out_of_sample_native_prediction.json',{'OUT_OF_SAMPLE_NATIVE_PREDICTION_FROZEN':True,'prediction':'For the fixed pre-existing DEV203 geometry, the predeclared normalized bond-force-direction circulation on reflection-related multi-cell loops either changes sign under reflection or is identically zero; no loop/result selection is permitted.','not_used_to_select_candidate':True})
 dump('dev220_test_selection.json',{'DEV220_TEST_SELECTION_FROZEN':True,'DEV220_TEST_SELECTION':'SPATIAL_WINDING_AUDIT','one_question':'Does the frozen DEV203 relational stress geometry have a nonzero, reflection-covariant coefficient-free multi-cell winding diagnostic?','one_frozen_geometry':'existing DEV203 canonical trajectory at a predeclared timestep/window','one_observable':'oriented sum of normalized existing bond-force directions around predeclared reflection-paired multi-cell loops','why':'cheapest discriminator between broad extended geometry and the stronger spatial-topology candidate; it neither reruns DEV211 nor relabels DEV218.'})
 update_docs(); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT)
 flags={x:True for x in 'CURRENT_GITHUB_INSPECTED CURRENT_HEAD_VERIFIED MECHANISM_REGISTRY_QUERIED DEVELOPMENT_LEDGER_READ HISTORICAL_INDEX_READ NATIVE_MAGNETIC_HISTORY_COMPLETE DEV167_MECHANICS_UNCHANGED DEV218_ROUTE_CLOSED_NOT_MAGNETISM DEV218_MOMENTUM_POLARITY_CLOSURE_PRESERVED NO_NEW_MAGNETIC_MODEL NO_NEW_FORCE NO_NEW_DOF NO_NEW_STATE_VARIABLE NO_NEW_CONSTITUTIVE_TERM NO_NEW_PROPAGATION_LAW MAGNETIC_PHENOMENOLOGY_INVENTORY_COMPLETE MAGNETIC_THEORY_MECHANISM_MATRIX_COMPLETE NATIVE_MAGNETIC_MECHANISM_MATRIX_COMPLETE FAILED_ROUTE_MATRIX_COMPLETE TEMPORAL_CYCLE_VS_SPATIAL_WINDING_DISTINGUISHED DEV215_PLAQUETTE_RESULT_RECOVERED EXISTING_ANISOTROPIC_NATIVE_STRUCTURES_INVENTORIED SPATIAL_WINDING_NATIVE_CANDIDATES_INVENTORIED NATIVE_INTERMITTENT_STRUCTURE_INVENTORY_COMPLETE PERMANENT_VS_DRIVEN_MAGNETISM_SEPARATED NO_B_FIELD_IDENTIFICATION NO_SYNTHETIC_VECTOR_FIELD NO_CHIRAL_COUPLING_ADDED EXCHANGE_USED_ONLY_AS_EMERGENCE_ANALOGY NO_MAGNETIC_TENSION_IDENTITY NO_MAGNETIC_PRESSURE_IDENTITY NO_N6_GRAPH_REWIRING NO_DAMPING_ADDED NO_DOMAIN_PINNING_ADDED NO_HYSTERESIS_LAW_ADDED NO_DIPOLE_POWER_LAW_FIT NO_INVERSE_SQUARE_FIT NO_INVERSE_CUBE_FIT NO_ARBITRARY_WEIGHTED_SCORE NO_RELABELED_FAILED_MECHANISM MAGNETIC_CANDIDATE_FAMILY_MATRIX_COMPLETE MAGNETIC_CANDIDATE_ELIMINATION_COMPLETE MAGNETIC_MECHANISM_PARETO_SET_COMPLETE MAGNETIC_MECHANISM_MINIMALITY_RANKING_COMPLETE SINGLE_LAW_COLLECTIVE_GEOMETRY_CHAIN_CLASSIFIED SINGLE_LAW_CHAIN_FIRST_FAILURE_RECORDED MINIMAL_NATIVE_MAGNETIC_CANDIDATE_CLASSIFIED OUT_OF_SAMPLE_NATIVE_PREDICTION_FROZEN DEV220_TEST_SELECTION_FROZEN STANDARD_MAGNETIC_THEORY_USED_AS_CONSTRAINT_NOT_PRIMITIVE MECHANISM_REGISTRY_UPDATED REGISTRY_VALIDATED LEDGER_UPDATED HISTORICAL_INDEX_UPDATED TIMELINE_REGENERATED DERIVATION_GRAPH_REGENERATED TESTS_PASS NO_PR_CREATED COMMITTED PUSHED_DIRECTLY_TO_MAIN REMOTE_MAIN_VERIFIED WORKTREE_CLEAN'.split()}; flags.update({'MINIMAL_NATIVE_MAGNETIC_CANDIDATE':'NONUNIQUE','TORQUE_MECHANISM_STATUS':'DERIVED_STATE_DEPENDENT_CENTRAL_FORCE_GEOMETRY'}); dump('final_contract.json',flags)
 (OUT/'discussion_handoff.md').write_text('# DEV219 handoff\n\nNo microscopic magnetic ingredient was introduced. DEV218 closes only momentum-sign radial polarity on its frozen interface; it does not close macroscopic force duality from collective geometry. The non-dominated survivors are extended anisotropic relational geometry, spatial winding, and pattern-boundary/interface organization. DEV220 is one coefficient-free spatial-winding diagnostic on an existing DEV203 geometry.\n')
if __name__=='__main__': main()
