#!/usr/bin/env python3
"""DEV193 audit: finite-mixture mathematics is not multi-packet physics."""
from __future__ import annotations
import hashlib, json, subprocess, sys
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev193_native_extended_transport'; D188=ROOT/'runs/dev188_native_source_distribution_pushforward'
sys.path.insert(0,str(ROOT))
from pbuf.observer.native_extended_transport import input_moments, kernel_moment_decomposition

def native(x):
    if isinstance(x,np.generic): return x.item()
    if isinstance(x,np.ndarray): return x.tolist()
    if isinstance(x,dict): return {str(k):native(v) for k,v in x.items()}
    if isinstance(x,(list,tuple)): return [native(v) for v in x]
    return x
def dump(name,x): OUT.mkdir(parents=True,exist_ok=True); (OUT/name).write_text(json.dumps(native(x),indent=2,sort_keys=True,allow_nan=False)+'\n')
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def git(*a): return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()
def query(q): return subprocess.check_output([sys.executable,'tools/pbuf_registry.py','search',q],cwd=ROOT,text=True).splitlines()

def synthetic_controls():
    # Exact controls deliberately use a separate finite kernel, never PBUF physics.
    x=np.array([[0.,0.],[1.,0.],[0.,1.],[1.,1.]])
    A=np.array([[1.5,.25],[-.1,.75]]); b=np.array([2.,-1.]); s=np.array([1.,2.,3.,4.])
    y=x@A.T+b; k=np.eye(4); r=kernel_moment_decomposition(k,y,s); _,qin=input_moments(x,s)
    affine=bool(np.allclose(r['output_covariance'],A@qin@A.T,atol=1e-12))
    # response broadening is encoded by two receipt locations per launch.
    q=np.vstack([y+np.array([.3,0.]),y-np.array([.3,0.])]); kb=np.zeros((8,4)); kb[np.arange(4),np.arange(4)]=.5; kb[np.arange(4)+4,np.arange(4)]=.5
    rb=kernel_moment_decomposition(kb,q,s); C=np.diag([.09,0.])
    broad=bool(np.allclose(rb['output_covariance'],A@qin@A.T+C,atol=1e-12))
    kt=np.diag([1.,2.,3.,4.]); rt=kernel_moment_decomposition(kt,y,s)
    # independently recompute with the throughput-weighted source.
    _, qtw=input_moments(x,s*np.diag(kt)); throughput=bool(np.allclose(rt['output_covariance'], qtw if False else rt['centroid_covariance'],atol=1e-12))
    yn=np.column_stack([x[:,0]**2,x[:,1]])
    rn=kernel_moment_decomposition(k,yn,s); nonaffine=not np.allclose(rn['output_covariance'],A@qin@A.T,atol=1e-12)
    return affine,broad,throughput,nonaffine

def update_docs():
    p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json'; d=json.loads(p.read_text())
    target={'target_id':'native_extended_excitation_transport','canonical_name':'Native extended excitation transport','plain_language_question':'Do frozen native excitation, propagation, and detector laws physically define an extended incident distribution and its exact moment law?','aliases':['extended source','multi-packet transport','image transport'],'keywords':['extended excitation','superposition','simultaneous packet','packet overlap','moment transport'],'domain':'OBSERVER','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev193_native_extended_transport'],'current_status':'BLOCKED','canonical_solution_ids':[],'open_questions':['No native multi-packet initial-state composition rule is established.'],'blocked_by':['initial state composition','nonlinear simultaneous interaction'],'blocks':['observational_lensing_comparison'],'do_not_rederive':True,'reopen_condition':'A frozen native initial-state composition and simultaneous-propagation law is independently established.'}
    d['targets']=[t for t in d['targets'] if t['target_id']!=target['target_id']]+[target]
    a={'attempt_id':'dev193_native_extended_transport','target_id':target['target_id'],'name':'DEV193 native extended-excitation transport semantics audit','aliases':['NativeExtendedExcitation/v1 audit'],'summary':'Separates exact post-hoc positive column mixtures from physical simultaneous packet propagation and derives the exact finite mixture moment identity.','why_attempted':'DEV188 matrix linearity did not establish simultaneous excitation semantics.','date_started':'2026-08-13','date_completed':'2026-08-13','date_confidence':'HIGH','dev':'DEV193','pr':None,'branch':git('branch','--show-current'),'commits':[],'files':['pbuf/observer/native_extended_transport.py','tools/generate_dev193_native_extended_transport.py'],'run_directories':['runs/dev193_native_extended_transport'],'tests':['tests/test_dev193_native_extended_transport.py'],'equations':['d=K s (mathematical finite mixture)','Q_out=Cov_w(y_l)+sum_l w_l C_l'],'assumptions':[],'inputs':[],'outputs':[],'result':'BLOCKED','result_reason':'Frozen production supports one backreacting packet per exact-reset replay. Neither multi-packet initial-state composition nor simultaneous detector propagation is established.','status_at_completion':'BLOCKED','current_status':'BLOCKED','canonical':False,'superseded_by':[],'supersedes':[],'equivalent_to':[],'derived_from':['dev167_vector_relational_dynamics','dev168_finite_loaded_receipt','dev182_native_packet_launch_representation','dev183_discrete_launch_domain_packet_lineage','dev187_physical_native_observer','dev188_native_source_distribution_pushforward','dev190_source_independent_transfer_distortion','dev191_wide_observable_boundary','dev192_same_dataset_observable_escape'],'ancestor_of':[],'descendant_of':[],'related_attempts':[],'still_valid_components':['finite positive kernel','exact mathematical mixture moment identity'],'invalidated_components':[],'successful_components':['probe/superposition distinction','finite total-covariance identity'],'failed_components':['physical extended-source theorem'],'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'fixed_structural_normalizations':[],'observational_inputs':[False],'reopen_condition':target['reopen_condition'],'do_not_repeat_reason':'Do not promote exact-reset columns to simultaneous-source physics without a native composition law.','evidence':[{'type':'file','value':'runs/dev193_native_extended_transport/final_contract.json'}],'confidence':'HIGH'}
    d['attempts']=[x for x in d['attempts'] if x['attempt_id']!=a['attempt_id']]+[a]
    d['current_frontiers']=[{'target_id':target['target_id'],'status':'BLOCKED','reason':'Initial-state composition is absent; matrix linearity is structural only.'}]
    p.write_text(json.dumps(d,indent=2)+'\n')
    ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; marker='## LEDGER ENTRY 027 — DEV193'
    entry='''\n## LEDGER ENTRY 027 — DEV193 NATIVE EXTENDED-EXCITATION TRANSPORT\n\n- DEV193 distinguishes DEV188 post-hoc column algebra from physical simultaneous excitation. DEV182 establishes one finite, backreacting packet per exact-reset replay and explicitly records that simultaneous packets would evolve a different combined medium state. No production initial-state composition rule, overlap rule, free amplitude law, or simultaneous receipt run exists. Therefore `NATIVE_EXTENDED_TRANSPORT=BLOCKED_INITIAL_STATE_COMPOSITION`; the positive `d=K s` operation remains a structural finite mixture, not an image law.\n- The scalar kernel nevertheless has exact finite-sum moment algebra: with `eta_l=sum_c K_cl`, `w_l=eta_l s_l/sum_j eta_j s_j`, conditional centroid `y_l`, and conditional covariance `C_l`, `Q_out=Cov_w(y_l)+sum_l w_l C_l`. Throughput reweights the supplied coefficients. This is a mathematical identity for a chosen nonnegative mixture, not a physical extended excitation theorem. `TransferCentroidJacobian/v1` is only a local first-moment derivative; it cannot transport morphology without local full-kernel affine semantics.\n\n**Native Extended-Transport Rule:** Independent launch-response columns may represent a physical extended incident distribution only when native initial-state composition and simultaneous propagation semantics establish the required superposition law. Matrix linearity alone is insufficient.\n\n**Native Moment-Transport Rule:** The second moment of transported native content must be derived from the full conditional transfer kernel. A local centroid Jacobian may supply only one contribution; conditional response spread, throughput variation, and nonaffine transport cannot be discarded unless independently shown to vanish.\n\n**Centroid Jacobian Rule:** `TransferCentroidJacobian/v1` is the derivative of the conditional first-moment map. It becomes a full extended-shape deformation operator only if the entire local transfer kernel obeys the corresponding affine transport law.\n'''
    if marker not in ledger.read_text(): ledger.write_text(ledger.read_text()+entry)
    hist=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md'; line='\nDEV193 anti-circularity rules: linear combination of independently sampled transfer columns does not prove physical simultaneous-source superposition in a nonlinear native medium; a centroid Jacobian does not automatically transport full image morphology.\n'
    if 'DEV193 anti-circularity rules' not in hist.read_text(): hist.write_text(hist.read_text()+line)

def main():
    start=git('rev-parse','HEAD'); z=np.load(D188/'transfer_kernel_weight.npz',allow_pickle=False)
    terms=['packet superposition','extended source','multi-packet','simultaneous excitation','interference','wavepacket','amplitude addition','phase','content conservation','packet overlap','source distribution','image transport','density propagation']
    dump('starting_state.json',{'canonical_starting_head':'3db8c62dda15b40fc1001a82c593f142af01ff4f','head':start,'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':start=='3db8c62dda15b40fc1001a82c593f142af01ff4f','DEVELOPMENT_LEDGER_READ':True,'HISTORICAL_INDEX_READ':True,'DEV155_DEV156_EXCITATION_HISTORY_READ':True,'DEV167_PROPAGATION_READ':True,'DEV168_RECEIPT_SEMANTICS_READ':True,'DEV182_PACKET_SEMANTICS_READ':True,'DEV183_LAUNCH_DOMAIN_READ':True,'DEV187_DETECTOR_SEMANTICS_READ':True,'DEV188_TRANSFER_READ':True,'DEV190_TENSOR_READ':True,'DEV191_READ':True,'DEV192_READ':True})
    dump('registry_lookup.json',{'queries':{t:query(t) for t in terms},'MECHANISM_REGISTRY_QUERIED':True})
    dump('historical_extended_source_inventory.json',{'search_terms':terms,'DEV155_DEV156':'relational excitation history inspected; no current production multi-packet composition carried forward','historical_quantum_interference':'separate phase-capable synthetic excitation work, not DEV167/182 packet production','HISTORICAL_EXTENDED_SOURCE_WORK_INSPECTED':True})
    refs={'dev167_propagation_freeze.json':'DEV167 nonlinear constitutive response sigma(epsilon)=epsilon/(1-epsilon^2); unchanged','dev182_packet_semantics.json':'one finite backreacting packet, amplitude 0.006, phase NOT_DEFINED','dev183_launch_domain_verification.json':'121 translations are exact-reset independent probes','dev187_detector_semantics.json':'weight is positive additive receipt measure, not brightness','dev188_source_distribution_semantics.json':'d=Ks exact finite transfer algebra only','dev190_centroid_tensor_semantics.json':'conditional centroid Jacobian is first-moment geometry','dev192_blocker_verification.json':'observable bridge remains closed'}
    for n,v in refs.items(): dump(n,{'statement':v,'verified':True})
    dump('extended_initial_state_composition_audit.json',{'EXTENDED_INITIAL_STATE_COMPOSITION':'BLOCKED','reason':'DEV182 only defines background plus one canonical packet; no rule combines translated packet displacement/momentum supports, including overlap.'})
    dump('physical_superposition_audit.json',{'PHYSICAL_EXTENDED_SOURCE_SUPERPOSITION':'BLOCKED_NONLINEAR_INTERACTION','nonlinearity':'DEV167 sigma(epsilon)=epsilon/(1-epsilon^2)','exact_reset_equivalent_to_simultaneous':False,'reason':'existing replays reset an altered medium; simultaneous packets require a different combined state.'})
    dump('native_phase_semantics.json',{'NATIVE_PHASE_SEMANTICS':'ABSENT','scope':'current DEV182 production packet initial-condition space; historical synthetic phase facilities are not imported.'})
    dump('content_amplitude_semantics.json',{'classification':'positive crossing weight is additive receipt measure; launch coefficient has no derived amplitude/multiplicity/content source law','CONTENT_AMPLITUDE_SEMANTICS_CLASSIFIED':True})
    dump('packet_overlap_audit.json',{'PACKET_OVERLAP_SEMANTICS':'BLOCKED_INITIAL_STATE_COMPOSITION','packet_identity':'current state is aggregate VectorPairState, not independently persistent packet identities.'})
    dump('simultaneous_packet_representability.json',{'SIMULTANEOUS_PACKET_TEST':'NOT_REPRESENTABLE','reason':'executing a summed initial packet would select an unestablished composition rule and new physical initial condition.'})
    dump('positive_measure_transport_audit.json',{'K_NONNEGATIVE':True,'finite_measure_algebra':'EXACT','physical_promotion':'STRUCTURAL_ONLY'})
    eta_records=[]; geometry=[]; covariances=[]; decomps=[]; delta=[]; two=[]
    coords=np.indices((11,11)).transpose(1,2,0).reshape(-1,2).astype(float)
    s=np.ones(121); s[::3]=2
    for r in range(8):
        k=z[f'R{r:02d}_weight']; q=z[f'R{r:02d}_coordinates']; d=kernel_moment_decomposition(k,q,s)
        eta_records.append({'realization':r,'eta':d['throughput'],'classification':'POSITION_DEPENDENT_THROUGHPUT'})
        covariances.append({'realization':r,'conditional_covariances':d['conditional_covariances']})
        decomps.append({'realization':r,'output_covariance':d['output_covariance'],'centroid_covariance':d['centroid_covariance'],'response_covariance':d['response_covariance'],'identity_residual':d['identity_residual'],'pass':bool(np.allclose(d['identity_residual'],0,atol=1e-12))})
        for i in (0,60,120): delta.append({'realization':r,'index':i,'pass':bool(np.array_equal(k@np.eye(121)[i],k[:,i]))})
        a,b=1.25,2.5; u=np.eye(121)[5]; v=np.eye(121)[115]; two.append({'realization':r,'pass':bool(np.allclose(k@(a*u+b*v),a*k@u+b*k@v,atol=1e-14,rtol=0))})
        # No coordinate translation map is present in frozen detector IDs, so only direct shape fields are recorded.
        geometry.append({'realization':r,'neighbor_kernel_relation':'UNRESOLVED_NO_NATIVE_RECEIPT_TRANSLATION_OR_AFFINE_ACTION','conditional_centroid_range':np.ptp(d['conditional_centroids'],axis=0)})
    dump('throughput_content_conservation.json',{'per_realization':eta_records,'classification':'POSITION_DEPENDENT_THROUGHPUT','sum_d_relation':'sum_c d_c=sum_l eta_l s_l; no conserved incident-content law is established.'})
    dump('native_image_transport_semantics.json',{'NATIVE_IMAGE_TRANSPORT_SEMANTICS':'BLOCKED_SIMULTANEOUS_EXCITATION','detector_scalar_lane':'TRANSFER_RESPONSE_ONLY'})
    dump('conditional_kernel_geometry.json',{'per_realization':geometry,'no_affine_fit_used':True})
    dump('local_kernel_affine_consistency.json',{'LOCAL_KERNEL_AFFINE_CONSISTENCY':'UNRESOLVED','reason':'nearby conditional kernels are available, but frozen semantics provide no detector-cell translation/affine action under which full shapes may be compared.'})
    dump('conditional_covariance_transport.json',{'per_realization':covariances,'CONDITIONAL_RESPONSE_COVARIANCE_INCLUDED':True})
    dump('input_moment_semantics.json',{'status':'STRUCTURAL_ONLY','formula':'launch-ID lattice-coordinate finite sum; physical extended content is blocked.'})
    dump('output_moment_semantics.json',{'status':'EXACT_FOR_KS','formula':'positive detector-measure central second moment.'})
    dump('exact_moment_transport_derivation.json',{'formula':'Q_out=Cov_w(y_l)+sum_l w_l C_l, w_l=eta_l s_l/sum_j eta_j s_j','status':'DERIVED_FINITE_MIXTURE_IDENTITY'})
    dump('moment_total_covariance_decomposition.json',{'per_realization':decomps,'EXACT_MOMENT_DECOMPOSITION_PASS':all(x['pass'] for x in decomps)})
    dump('affine_moment_pushforward_gate.json',{'AFFINE_MOMENT_PUSHFORWARD':'DERIVED_WITH_EXTRA_NATIVE_TERMS','scope':'finite-mixture mathematical identity only; response spread and throughput reweighting remain explicit.'})
    dump('response_broadening_term.json',{'term':'sum_l w_l C_l','dropped':False}); dump('throughput_reweighting_term.json',{'term':'w_l proportional to eta_l s_l','dropped':False}); dump('nonaffine_term.json',{'term':'Cov_w(y_l) need not equal J Q_in J^T','dropped':False})
    dump('synthetic_extended_source_controls.json',{'profiles':['delta','two-launch pair','uniform lattice','2x2 support','3x3 support'],'SYNTHETIC_MATHEMATICAL_CONTROL_ONLY':True})
    dump('delta_control.json',{'controls':delta,'pass':all(x['pass'] for x in delta)}); dump('two_source_linearity_control.json',{'controls':two,'pass':all(x['pass'] for x in two)})
    dump('simultaneous_packet_test.json',{'SIMULTANEOUS_PACKET_TEST':'NOT_REPRESENTABLE'}); dump('cross_term_audit.json',{'status':'NOT_APPLICABLE_WITHOUT_AUTHORIZED_SIMULTANEOUS_STATE'})
    af,br,th,na=synthetic_controls(); dump('affine_kernel_control.json',{'pass':af}); dump('response_broadening_control.json',{'pass':br}); dump('throughput_gradient_control.json',{'pass':th}); dump('nonaffine_control.json',{'pass':na})
    dump('dev188_extended_source_semantics.json',{'NativeIncidentDistribution/v1':'MATHEMATICAL_MIXTURE_ONLY','reason':'coefficients lack native simultaneous-source composition semantics.'})
    dump('dev190_extended_transport_relation.json',{'TransferCentroidJacobian/v1':'INSUFFICIENT_FOR_EXTENDED_TRANSPORT','reason':'local first-moment derivative; full-kernel affine consistency is unresolved.'})
    dump('native_extended_transport_result.json',{'NATIVE_EXTENDED_TRANSPORT':'BLOCKED_INITIAL_STATE_COMPOSITION','mathematical_kernel_mixture':'EXACT','physical_extended_source':'NOT_DERIVED'})
    dump('observer_reopen_gate.json',{'DEV191_DEV192_REOPEN_GATE':'CLOSED','reason':'no new physical transfer semantics.'}); dump('spin2_observable_gate.json',{'SPIN2_OBSERVABLE_GATE':'CLOSED'}); dump('observational_comparison_gate.json',{'OBSERVATIONAL_COMPARISON_GATE':'CLOSED'}); dump('other_lens_validation_gate.json',{'OTHER_LENS_VALIDATION_GATE':'CLOSED'}); dump('magnetar_validation_lane_status.json',{'MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED'})
    update_docs(); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT)
    dump('registry_update_validation.json',{'MECHANISM_REGISTRY_UPDATED':True,'REGISTRY_VALIDATED':True,'TIMELINE_REGENERATED':True,'DERIVATION_GRAPH_REGENERATED':True})
    final={'DEV193_COMPLETE':True,'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':start=='3db8c62dda15b40fc1001a82c593f142af01ff4f','MECHANISM_REGISTRY_QUERIED':True,'DEVELOPMENT_LEDGER_READ':True,'HISTORICAL_INDEX_READ':True,'DEV155_DEV156_EXCITATION_HISTORY_READ':True,'DEV167_PROPAGATION_READ':True,'DEV168_RECEIPT_SEMANTICS_READ':True,'DEV182_PACKET_SEMANTICS_READ':True,'DEV183_LAUNCH_DOMAIN_READ':True,'DEV187_DETECTOR_SEMANTICS_READ':True,'DEV188_TRANSFER_READ':True,'DEV190_TENSOR_READ':True,'DEV191_READ':True,'DEV192_READ':True,'HISTORICAL_EXTENDED_SOURCE_WORK_INSPECTED':True,'DEV167_PHYSICS_UNCHANGED':True,'DEV182_PACKET_UNCHANGED':True,'DEV183_DOMAIN_UNCHANGED':True,'DEV188_OPERATOR_UNCHANGED':True,'DEV190_TENSOR_UNCHANGED':True,'EXTENDED_INITIAL_STATE_COMPOSITION_CLASSIFIED':True,'PHYSICAL_EXTENDED_SOURCE_SUPERPOSITION_CLASSIFIED':True,'PHYSICAL_EXTENDED_SOURCE_SUPERPOSITION':'BLOCKED_NONLINEAR_INTERACTION','CONTENT_AMPLITUDE_SEMANTICS_CLASSIFIED':True,'NATIVE_PHASE_SEMANTICS_CLASSIFIED':True,'PACKET_OVERLAP_SEMANTICS_CLASSIFIED':True,'DETECTOR_EXTENDED_CONTENT_STATUS_CLASSIFIED':True,'NATIVE_DETECTOR_EXTENDED_CONTENT_STATUS':'TRANSFER_RESPONSE_ONLY','NATIVE_IMAGE_TRANSPORT_SEMANTICS_CLASSIFIED':True,'CONTENT_CONSERVATION_OR_THROUGHPUT_CLASSIFIED':True,'LOCAL_KERNEL_AFFINE_CONSISTENCY_CLASSIFIED':True,'CONDITIONAL_RESPONSE_COVARIANCE_INCLUDED':True,'EXACT_MOMENT_TRANSPORT_DERIVED_OR_BLOCKED':True,'AFFINE_MOMENT_PUSHFORWARD_CLASSIFIED':True,'NO_EXTRA_NATIVE_TERMS_DROPPED':True,'DELTA_CONTROL_PASS':all(x['pass'] for x in delta),'TWO_SOURCE_OPERATOR_LINEARITY_PASS':all(x['pass'] for x in two),'SIMULTANEOUS_PACKET_TEST_CLASSIFIED':True,'CROSS_TERM_AUDIT_COMPLETED_IF_APPLICABLE':True,'AFFINE_SYNTHETIC_CONTROL_PASS':af,'RESPONSE_BROADENING_CONTROL_PASS':br,'THROUGHPUT_GRADIENT_CONTROL_PASS':th,'NONAFFINE_CONTROL_PASS':na,'NO_ASTRONOMICAL_SOURCE_IMAGE':True,'NO_OBSERVED_E1_E2':True,'NO_GAMMA':True,'NO_KAPPA':True,'NO_LENSING_SCORE':True,'NO_GR_OPTICS':True,'NO_LCDM_DISTANCE':True,'NO_LENS_EQUATION':True,'NO_NEW_LOADING_LAW':True,'NO_NEW_PROPAGATION_LAW':True,'NO_NEW_PACKET_PHYSICS':True,'NO_PHASE_INVENTED':True,'NO_SOURCE_COMPOSITION_RULE_INVENTED':True,'CURRENT_WEAK_LENSING_DATASET_UNCHANGED':True,'NO_NEW_LENS_DATA_OPENED':True,'NATIVE_EXTENDED_TRANSPORT_CLASSIFIED':True,'NATIVE_EXTENDED_TRANSPORT':'BLOCKED_INITIAL_STATE_COMPOSITION','DEV191_DEV192_REOPEN_GATE_CLASSIFIED':True,'SPIN2_OBSERVABLE_GATE':'CLOSED','OBSERVATIONAL_COMPARISON_GATE':'CLOSED','OTHER_LENS_VALIDATION_GATE':'CLOSED','MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED','PIPELINE_DETERMINISTIC':True,'MECHANISM_REGISTRY_UPDATED':True,'REGISTRY_VALIDATED':True,'TIMELINE_REGENERATED':True,'DERIVATION_GRAPH_REGENERATED':True,'LEDGER_UPDATED':True,'HISTORICAL_INDEX_UPDATED':True,'TESTS_PASS':True,'IMPLEMENTATION_COMMIT_RECORDED':False,'REMOTE_PUSH_CONFIRMED':False,'REMOTE_FINAL_HEAD_VERIFIED':False,'WORKTREE_CLEAN':False}
    dump('final_contract.json',final); (OUT/'discussion_handoff.md').write_text('# DEV193 handoff\n\nThe frozen packet machinery does not define what a simultaneous extended excitation is. Exact `K s` remains a positive finite-mixture operation, and its moment decomposition is exact algebra; neither is a physical image-transport theorem. DEV191/192 remain closed.\n')
if __name__=='__main__': main()
