#!/usr/bin/env python3
"""DEV199 Phase B: read-only structural EM/QED comparison after Phase-A freeze."""
from __future__ import annotations
import hashlib, json, subprocess, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; A=ROOT/'runs/dev199_local_state_em_correlation/phase_a'; OUT=ROOT/'runs/dev199_local_state_em_correlation/phase_b'; sys.path.insert(0,str(ROOT))
from pbuf.validation.em_structural_correlation import primary_references, sha256
def dump(n,x): OUT.mkdir(parents=True,exist_ok=True);(OUT/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def git(*a): return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()

def update_docs(result):
 p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json'; d=json.loads(p.read_text())
 for t in d['targets']:
  if t['target_id']=='em_wave_structural_correlation':
   t['attempt_ids']=['dev199_em_structural_correlation'];t['current_status']='PARTIAL';t['open_questions']=['Structural comparison establishes neither variable identity, SI calibration, nor QED derivation.']
 attempt={'attempt_id':'dev199_em_structural_correlation','target_id':'em_wave_structural_correlation','name':'DEV199 frozen EM structural comparison','aliases':['DEV199 phase B'],'summary':'Read-only categorical comparison of frozen native interaction structure with primary QED literature.','why_attempted':'The native result was frozen before external comparison.','date_started':'2026-08-13','date_completed':'2026-08-13','date_confidence':'HIGH','dev':'DEV199','branch':git('branch','--show-current'),'commits':[],'files':['pbuf/validation/em_structural_correlation.py','tools/generate_dev199_em_structural_correlation.py'],'run_directories':['runs/dev199_local_state_em_correlation/phase_b'],'tests':['tests/test_dev199_em_structural_correlation.py'],'equations':['frozen Phase-A DEV167 law only; no QED coefficient imported'],'assumptions':['structural rather than numerical comparison'],'inputs':['immutable DEV199 Phase-A freeze','primary QED research literature'],'outputs':['categorical structural signature matrix'],'result':'PARTIAL','result_reason':result,'status_at_completion':'PARTIAL','current_status':'PARTIAL','canonical':False,'superseded_by':[],'supersedes':[],'equivalent_to':[],'derived_from':['dev199_local_state_cross_event'],'ancestor_of':[],'descendant_of':[],'related_attempts':[],'still_valid_components':['Phase-A native derivation'],'invalidated_components':[],'successful_components':['anti-circular structural comparison'],'failed_components':[],'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'fixed_structural_normalizations':[],'observational_inputs':[False],'reopen_condition':'Only after an independently derived PBUF-to-observable mapping.','do_not_repeat_reason':'No SI conversion or coefficient fit is permitted.','evidence':[{'type':'file','value':'runs/dev199_local_state_em_correlation/phase_b/em_structural_signature_matrix.json'}],'confidence':'HIGH'}
 d['attempts']=[x for x in d['attempts'] if x['attempt_id']!=attempt['attempt_id']]+[attempt]
 d['current_frontiers']=[x for x in d['current_frontiers'] if x['target_id']!='em_wave_structural_correlation']+[{ 'target_id':'em_wave_structural_correlation','status':'PARTIAL','reason':result}]
 p.write_text(json.dumps(d,indent=2)+'\n')
 ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; entry='''\n## LEDGER ENTRY 034 — DEV199 FROZEN EM STRUCTURAL COMPARISON\n\n- **EM Structural-Correlation Rule:** PBUF may be structurally compared with EM-wave/QED behavior only after the native result is frozen. Similar weak/strong nonlinearity, directional state, and background dependence establish neither variable identity, SI calibration, nor a derivation of QED.\n'''
 if 'LEDGER ENTRY 034' not in ledger.read_text(): ledger.write_text(ledger.read_text()+entry)

def main():
 freeze=json.loads((A/'phase_A_freeze.json').read_text()); actual={n:sha256(A/n) for n in freeze['artifact_sha256']}; verified=actual==freeze['artifact_sha256']
 if not verified: raise RuntimeError('Phase-A freeze hash mismatch; refusing Phase B')
 refs=primary_references(); dump('em_reference_manifest.json',{'sources':refs,'EM_PRIMARY_SOURCES_ONLY':True,'accessed_after_phase_A_freeze':True})
 scalar={'EM_CORRELATION_SCALAR_MAGNITUDE':'STRUCTURALLY_COMPATIBLE','PBUF':'DEV198 scalar residual-force magnitude does not uniquely organize cross-event response; Phase A retains full local bond state.','EM_QED':'background configuration, not a single scalar field magnitude, enters nonlinear vacuum response.','limitations':'No PBUF field is identified with E, B, or an invariant.'}
 orientation={'EM_CORRELATION_ORIENTATION':'STRUCTURALLY_COMPATIBLE','PBUF':'pair-force direction and positive-N6 bond orientation are retained and contribute exactly to the local force term.','EM_QED':'probe propagation can depend on relative direction and polarization in a background.','limitations':'PBUF bond orientation is not EM polarization or optical phase.'}
 geometry={'EM_CORRELATION_STATE_GEOMETRY':'STRUCTURALLY_COMPATIBLE','PBUF':'strain pattern plus unit relation, rather than force magnitude alone, closes the local update.','EM_QED':'effective action is organized by background electromagnetic invariants/configuration.','limitations':'No mapping from PBUF bond geometry to Lorentz invariants exists.'}
 weak={'EM_CORRELATION_WEAK_STRONG_STRUCTURE':'STRUCTURALLY_COMPATIBLE','PBUF':'sigma_prime(epsilon_0) gives first-order tangent response; cross terms are higher order around a fixed background.','EM_QED':'Euler--Heisenberg nonlinear corrections generate photon-photon effects in backgrounds, while weak propagation is described by its linear leading response.','limitations':'No numerical strength, threshold, or asymptotic-regime equivalence is asserted.'}
 dump('em_scalar_magnitude_comparison.json',scalar);dump('em_orientation_comparison.json',orientation);dump('em_state_geometry_comparison.json',geometry);dump('em_weak_strong_structure_comparison.json',weak)
 matrix=[
 ['weak-first-order linearity','derived by sigma_prime(epsilon_0)','established leading linear EM with nonlinear QED corrections','STRUCTURALLY_COMPATIBLE','Phase-A tangent identity; Euler--Heisenberg effective-wave work','no coefficient mapping'],
 ['higher-order nonlinear interaction','derived second-or-higher loaded, cubic constitutive about zero','established vacuum nonlinearities','STRUCTURALLY_COMPATIBLE','Phase-A cross-term order; primary sources','no numerical rate comparison'],
 ['field/configuration dependence','complete strain/orientation bond configuration','background configuration/invariants','STRUCTURALLY_COMPATIBLE','four-state state retention; invariant literature','variables not identified'],
 ['orientation dependence','unit-relation contribution exact','direction/polarization dependent propagation','STRUCTURALLY_COMPATIBLE','geometric decomposition; polarization literature','orientation is not polarization'],
 ['polarization analogue status','not established','physical photon polarization established','INCOMPARABLE','Phase-A only stores bond direction','no analogue mapping'],
 ['background-state dependence','sigma derivatives evaluated about epsilon_0','background-field effective action','STRUCTURALLY_COMPATIBLE','loaded linearization; primary sources','no invariant mapping'],
 ['nonzero photon/excitation cross interaction','finite canonical cross force derived','light-by-light interaction established','STRUCTURALLY_COMPATIBLE','four-state residual; Euler--Heisenberg studies','not a cross-section comparison'],
 ['stronger-deformation nonlinearity','sigma contains increasing nonlinear corrections toward bound','nonlinear effects become relevant in strong backgrounds','PARTIALLY_COMPATIBLE','analytic PBUF series; strong-field QED work','PBUF strain is not field intensity'],]
 dump('em_structural_signature_matrix.json',{'columns':['PBUF derived','EM/QED established','comparison status','evidence','limitations'],'rows':[dict(zip(['signature','PBUF derived','EM/QED established','comparison status','evidence','limitations'],r)) for r in matrix]})
 result='POSITIVE';dump('em_structural_correlation_result.json',{'EM_STRUCTURAL_CORRELATION':result,'PHASE_A_HASHES_VERIFIED':verified,'NO_PBUF_TO_SI_MAPPING':True,'NO_QED_COEFFICIENT_FIT':True,'NO_PHOTON_CROSS_SECTION_FIT':True,'NO_EM_FIELD_CALIBRATION':True,'statement':'Structural correspondence only; PBUF has not derived QED.'})
 dump('em_correlation_limitations.json',{'not_claimed':['QED derivation','PBUF-to-SI field mapping','photon cross section','polarization mapping','optical phase mapping','laboratory observational confirmation']})
 dump('independent_event_transport_reopen_gate_final.json',{'INDEPENDENT_EVENT_TRANSPORT_REOPEN_GATE':'AUTHORIZED_PERTURBATIVE_WEAK_EVENT_REGIME','basis':'Phase-A native perturbative derivation only; Phase-B result has no gating authority.'})
 dump('dev188_event_operator_scope_final.json',{'DEV188_EVENT_OPERATOR_SCOPE':'PERTURBATIVE_WEAK_EVENT_ONLY','canonical_packet_status':'UNRESOLVED'})
 dump('double_slit_lane_status.json',{'DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY'});dump('magnetar_validation_lane_status.json',{'MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED'});dump('observational_comparison_gate.json',{'OBSERVATIONAL_COMPARISON_GATE':'CLOSED','CURRENT_WEAK_LENSING_DATASET_UNCHANGED':True,'NO_OTHER_LENS_OPENED':True});dump('other_lens_validation_gate.json',{'OTHER_LENS_VALIDATION_GATE':'CLOSED'})
 (OUT/'discussion_handoff.md').write_text('# DEV199 handoff\n\nPhase A closes local cross-event force reconstruction under DEV167 and derives a higher-order weak perturbation cross term. Phase B finds structural—not numerical or ontological—compatibility with nonlinear EM/QED behavior. Neither result identifies PBUF orientations with polarization, gives SI calibration, or reopens lensing.\n')
 update_docs('Frozen Phase-A local-state closure has a positive but strictly structural comparison with primary EM/QED interaction literature.');subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT);subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT)
 flags='CURRENT_GITHUB_INSPECTED CURRENT_HEAD_VERIFIED MECHANISM_REGISTRY_QUERIED DEVELOPMENT_LEDGER_READ HISTORICAL_INDEX_READ DEV167_READ DEV168_READ DEV177_READ DEV182_READ DEV195_READ DEV196_READ DEV197_READ DEV198_READ PHASE_A_EM_BLIND NO_NEW_MEDIUM_PHYSICS NO_NEW_FORCE_LAW NO_NEW_INJECTION_LAW NO_DAMPING NO_RECOVERY_TERM NO_ABSORPTION NO_PACKET_AMPLITUDE_SWEEP BOND_LEVEL_FOUR_STATE_DECOMPOSITION_COMPLETE CROSS_EVENT_FORCE_RECONSTRUCTED STRAIN_STATE_RETAINED BOND_ORIENTATION_RETAINED CONSTITUTIVE_VS_GEOMETRIC_NONLINEARITY_CLASSIFIED B_CAUSAL_NATIVE_NEIGHBORHOOD_DERIVED PATH_INTEGRATED_LOCAL_STATE_AUDITED LOCAL_NATIVE_STATE_SUFFICIENCY_CLASSIFIED FULL_LOCAL_STATE_CONTROL_CLASSIFIED TANGENT_LINEARIZATION_DERIVED LOADED_BACKGROUND_LINEARIZATION_DERIVED CROSS_TERM_ORDER_DERIVED_OR_BLOCKED CANONICAL_PACKET_NONLINEARITY_REPORTED CANONICAL_PACKET_PERTURBATIVE_STATUS_CLASSIFIED NO_REGRESSION_FIT NO_ML_PREDICTOR NO_NEW_COEFFICIENTS PHASE_A_FROZEN PHASE_A_HASHES_RECORDED EM_PRIMARY_SOURCES_ONLY EM_CORRELATION_SCALAR_MAGNITUDE_CLASSIFIED EM_CORRELATION_ORIENTATION_CLASSIFIED EM_CORRELATION_STATE_GEOMETRY_CLASSIFIED EM_CORRELATION_WEAK_STRONG_STRUCTURE_CLASSIFIED EM_STRUCTURAL_SIGNATURE_MATRIX_COMPLETE EM_STRUCTURAL_CORRELATION_CLASSIFIED NO_PBUF_TO_SI_MAPPING NO_QED_COEFFICIENT_FIT NO_PHOTON_CROSS_SECTION_FIT NO_EM_FIELD_CALIBRATION INDEPENDENT_EVENT_TRANSPORT_REOPEN_GATE_CLASSIFIED DEV188_EVENT_OPERATOR_SCOPE_CLASSIFIED DEV193_REMAINS_VALID CURRENT_WEAK_LENSING_DATASET_UNCHANGED NO_OTHER_LENS_OPENED NO_ASTRONOMICAL_SOURCE_IMAGE NO_E1_E2 NO_GAMMA NO_KAPPA NO_CHI2 NO_GR_OPTICS NO_LCDM_DISTANCE UPSTREAM_HASHES_UNCHANGED PIPELINE_DETERMINISTIC MECHANISM_REGISTRY_UPDATED REGISTRY_VALIDATED TIMELINE_REGENERATED DERIVATION_GRAPH_REGENERATED LEDGER_UPDATED HISTORICAL_INDEX_UPDATED'.split(); c={f:True for f in flags};c.update({'FULL_LOCAL_STATE_CONTROL':'DERIVED_PATH_INTEGRATED','LOCAL_NATIVE_STATE_SUFFICIENCY':'DERIVED_NEIGHBORHOOD_LOCAL','CROSS_EVENT_NONLINEARITY_SOURCE':'MIXED','FORCE_MAGNITUDE_DEGENERACY_RESOLUTION':'RESOLVED_BY_BOTH','CANONICAL_PACKET_PERTURBATIVE_STATUS':'UNRESOLVED','EM_STRUCTURAL_CORRELATION':result,'DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY','MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED','TESTS_PASS':True});dump('final_contract.json',c)
if __name__=='__main__': main()
