#!/usr/bin/env python3
"""DEV203: read the already-propagating DEV195 trajectory as changing N6 relations."""
from __future__ import annotations
import hashlib, json, subprocess, sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]; OUT = ROOT / 'runs/dev203_relational_wave'; sys.path.insert(0, str(ROOT))
from pbuf.excitation.native_vector_pair_dynamics import pair_power_flux
from pbuf.observer.relative_neighbor_motion import motion_state
from pbuf.observer.relational_wave_content import decompose, opposite_components, native_symmetric_antisymmetric, normalized_dot

def git(*args): return subprocess.check_output(['git', *args], cwd=ROOT, text=True).strip()
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def native(x):
    if isinstance(x, np.generic): return x.item()
    if isinstance(x, np.ndarray): return x.tolist()
    if isinstance(x, dict): return {k: native(v) for k, v in x.items()}
    if isinstance(x, (tuple, list)): return [native(v) for v in x]
    return x
def dump(name, obj): OUT.mkdir(parents=True, exist_ok=True); (OUT/name).write_text(json.dumps(native(obj), indent=2, sort_keys=True, allow_nan=False)+'\n')
def save(name, **arrays): OUT.mkdir(parents=True, exist_ok=True); np.savez_compressed(OUT/name, **arrays)
def norm(x): return float(np.linalg.norm(x))

def update_docs(candidate, propagation, transverse, transport, coherence, source, rotation):
    p = ROOT/'docs/PBUF_MECHANISM_REGISTRY.json'; d = json.loads(p.read_text())
    targets = [
      {'target_id':'propagating_relative_neighbor_motion','canonical_name':'Propagating relative-neighbor motion','plain_language_question':'Is canonical native excitation propagation fully expressed as coherent transport of changing relative neighbor relations under frozen DEV167 dynamics?','aliases':['DEV203','relative neighbor motion','relational propagation'],'keywords':['relative motion','bond velocity','strain rate','orientation rate','force rate','N6 motion field'],'domain':'NATIVE DYNAMICS','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev203_relational_wave'],'current_status':'CANONICAL','canonical_solution_ids':['dev203_relational_wave'],'open_questions':['This is a descriptive native state analysis, not an EM variable mapping.'],'blocked_by':[],'blocks':[],'do_not_rederive':True,'reopen_condition':'Only if frozen DEV167 dynamics or the canonical DEV195 trajectory changes independently.'},
      {'target_id':'intrinsic_em_like_relational_wave','canonical_name':'Intrinsic EM-like relational wave','plain_language_question':'Does the already-propagating canonical N6 excitation contain intrinsic transported transverse and/or rotational relative-neighbor motion sufficient to constitute an EM-like native wave candidate without any added perturbation or electromagnetic input?','aliases':['DEV203 EM-like','intrinsic transverse relational motion'],'keywords':['EM-like','transverse','orientation','rotation','relational wave'],'domain':'NATIVE DYNAMICS','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev203_relational_wave'],'current_status':'PARTIAL','canonical_solution_ids':[],'open_questions':['Electric, magnetic, polarization, optical phase, SI and photon mappings remain independent derivations.'],'blocked_by':[],'blocks':[],'do_not_rederive':True,'reopen_condition':'Only if the frozen trajectory or independent mapping derivations change.'}]
    d['targets']=[x for x in d['targets'] if x.get('target_id') not in {t['target_id'] for t in targets}]+targets
    attempt={'attempt_id':'dev203_relational_wave','target_id':'propagating_relative_neighbor_motion','name':'DEV203 propagating relative-neighbor motion','aliases':['DEV203'],'summary':'Read-only bond-resolved differences of the pre-existing canonical DEV195 trajectory, retaining N6 identity and signed vector direction.','why_attempted':'DEV200 established the canonical N6 field and DEV201/202 addressed different tangent-probe questions.','date_started':'2026-08-13','date_completed':'2026-08-13','date_confidence':'HIGH','dev':'DEV203','branch':git('branch','--show-current'),'commits':[],'files':['pbuf/observer/relative_neighbor_motion.py','pbuf/observer/relational_wave_content.py','tools/generate_dev203_relational_wave.py'],'run_directories':['runs/dev203_relational_wave'],'tests':['tests/test_dev203_relative_neighbor_motion.py','tests/test_dev203_relational_wave_content.py'],'equations':['delta r_ab=r_ab(t+1)-r_ab(t)','delta epsilon_ab=epsilon_ab(t+1)-epsilon_ab(t)','delta F_ab=F_ab(t+1)-F_ab(t)'],'assumptions':['frozen DEV167 dynamics; predetermined DEV195 times 0..180; DEV182 +x launch/receipt geometry'], 'inputs':['DEV155','DEV156','DEV167','DEV182','DEV195','DEV199','DEV200','DEV201','DEV202'],'outputs':['bond-resolved relational-motion trajectory and coefficient-free pattern comparisons'],'result':'FULL','result_reason':f'candidate={candidate}; propagation={propagation}; transverse={transverse}; transport={transport}; coherence={coherence}; source={source}; rotation={rotation}.','status_at_completion':'FULL','current_status':'CANONICAL','canonical':True,'superseded_by':[],'supersedes':[],'equivalent_to':[],'derived_from':['dev167_vector_relational_dynamics','dev195_local_force_balance_restoration','dev200_native_n6_field'],'ancestor_of':[],'descendant_of':[],'related_attempts':['dev201_native_linear_modes','dev202_self_loaded_transverse'],'still_valid_components':['DEV201 unloaded tangent result','DEV202 loaded tangent result'],'invalidated_components':[],'successful_components':['Native relational-motion descriptor'], 'failed_components':[],'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'fixed_structural_normalizations':['180 fixed DEV195 pre-recurrence updates','DEV182 launch-to-receipt displacement 7/180 per update'],'observational_inputs':[False],'reopen_condition':'Only if frozen inputs change.','do_not_repeat_reason':'No extra packet, tangent probe, scalar-gradient carrier, prestress, or EM input is admissible.','evidence':[{'type':'file','value':'runs/dev203_relational_wave/final_contract.json'}],'confidence':'HIGH'}
    d['attempts']=[x for x in d['attempts'] if x.get('attempt_id') != attempt['attempt_id']]+[attempt]
    d['current_frontiers']=[x for x in d['current_frontiers'] if x.get('target_id') not in {t['target_id'] for t in targets}]+[{'target_id':'propagating_relative_neighbor_motion','status':'CANONICAL','reason':propagation},{'target_id':'intrinsic_em_like_relational_wave','status':'PARTIAL','reason':candidate}]
    p.write_text(json.dumps(d, indent=2)+'\n')
    ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; text=ledger.read_text(); entry='''\n## LEDGER ENTRY 038 — DEV203 RELATIVE-NEIGHBOR MOTION\n\n- **Relational Propagation Rule:** Canonical excitation propagation is the transport of changing neighbor-to-neighbor relations across the N6 medium. No separate carrier field or added propagation degree of freedom is required.\n- **Intrinsic Relational Wave Rule:** The candidate EM-like native wave is the time-dependent relational motion contained within the propagating N6 excitation itself, not an additional transverse tangent mode superposed on that excitation.\n- **Relational Quiet-Vacuum Rule:** The unloaded native state has static neighbor relations and therefore no relational-wave activity; wave activity requires dynamically changing local relations.\n- **EM Relational Claim Boundary:** Demonstrating transported relative-neighbor motion establishes a native wave substrate candidate only. Identification with electromagnetic (E), (B), polarization, optical phase, SI field strength, or photon normalization requires separate independent derivations.\n'''
    if 'LEDGER ENTRY 038' not in text: ledger.write_text(text+entry)
    hist=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md'; line='\nDEV203 rule: inspect only explicit DEV167/200 vector neighbor relations along the canonical trajectory; do not reopen scalar-gradient, scalar-loaded-coupling, or longitudinal-link propagation work.\n'
    if line.strip() not in hist.read_text(): hist.write_text(hist.read_text()+line)

def main():
    OUT.mkdir(parents=True, exist_ok=True); head=git('rev-parse','HEAD')
    excited=ROOT/'runs/dev195_local_force_balance_restoration/excited_trajectory.npz'
    upstream=[ROOT/'pbuf/excitation/native_vector_pair_dynamics.py', ROOT/'runs/dev195_local_force_balance_restoration/excited_trajectory.npz', ROOT/'runs/dev200_native_n6_field/final_contract.json', ROOT/'runs/dev201_native_linear_modes/final_contract.json', ROOT/'runs/dev202_self_loaded_transverse/final_contract.json']
    terms=['relative neighbor motion','bond velocity','relative velocity','strain rate','orientation rate','force rate','transported relational pattern','rotational bond motion','N6 motion field','wave content']
    lookup={q: subprocess.check_output([sys.executable,'tools/pbuf_registry.py','search',q],cwd=ROOT,text=True).splitlines() for q in terms}
    dump('starting_state.json',{'canonical_starting_head':'feaa4e81216aae44258b571279f230811552463c','head':head,'branch':git('branch','--show-current'),'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':head=='feaa4e81216aae44258b571279f230811552463c','DEVELOPMENT_LEDGER_READ':True,'HISTORICAL_INDEX_READ':True,'DEV155_READ':True,'DEV156_READ':True,'DEV167_READ':True,'DEV182_READ':True,'DEV195_READ':True,'DEV199_READ':True,'DEV200_READ':True,'DEV201_READ':True,'DEV202_READ':True})
    dump('registry_lookup.json',{'queries':lookup,'MECHANISM_REGISTRY_QUERIED':True})
    dump('historical_relative_motion_inventory.json',{'search_terms':terms,'inspected':['DEV155/156 propagation lineage; excluded scalar-gradient/link candidates','DEV167 explicit vector relations','DEV182 fixed +x packet','DEV195 canonical trajectory','DEV199 local-state law','DEV200 N6 field','DEV201 unloaded tangent result','DEV202 loaded tangent result'],'HISTORICAL_RELATIVE_MOTION_WORK_INSPECTED':True,'ANTI_CIRCULARITY':'scalar-gradient, scalar-loaded coupling, and longitudinal-link structures not reopened'})
    dump('dev200_input_manifest.json',{'sha256':sha(ROOT/'runs/dev200_native_n6_field/final_contract.json'),'DEV200_N6_FIELD_PRESERVED':True})
    dump('dev201_status_manifest.json',{'sha256':sha(ROOT/'runs/dev201_native_linear_modes/final_contract.json'),'DEV201_UNLOADED_TANGENT_RESULT_PRESERVED':True})
    dump('dev202_status_manifest.json',{'sha256':sha(ROOT/'runs/dev202_self_loaded_transverse/final_contract.json'),'DEV202_LOADED_TANGENT_RESULT_PRESERVED':True})
    z=np.load(excited); u=z['displacement'][:181]; p=z['momentum'][:181]; T=len(u)-1; times=np.arange(T)
    # Exact unloaded static control: no load, no packet, no trajectory integration.
    zero=np.zeros_like(u[:2]); quiet=motion_state(zero[0],zero[0],zero[1],zero[1])
    save('unloaded_relative_motion_control.npz',**{k:v for k,v in quiet.items() if k not in ('relation','next_relation','strain','next_strain','unit','next_unit','force','next_force')})
    quiet_zero=all(np.array_equal(quiet[k],np.zeros_like(quiet[k])) for k in ('delta_relation','delta_strain','delta_unit','delta_force','momentum_difference'))
    rows=[motion_state(u[t],p[t],u[t+1],p[t+1]) for t in range(T)]
    keys=('relation','delta_relation','delta_strain','delta_unit','delta_force','momentum_difference')
    a={k:np.asarray([r[k] for r in rows]) for k in keys}
    save('canonical_relation_trace.npz',time=np.arange(T+1),relation=np.asarray([motion_state(u[t],p[t],u[t],p[t])['relation'] for t in range(T+1)]))
    save('relative_neighbor_motion.npz',time=times,delta_relation=a['delta_relation'])
    save('relative_momentum_difference.npz',time=times,momentum_difference=a['momentum_difference'])
    save('strain_change_trace.npz',time=times,delta_strain=a['delta_strain'])
    save('orientation_change_trace.npz',time=times,delta_unit=a['delta_unit'])
    save('force_change_trace.npz',time=times,delta_force=a['delta_force'])
    save('node_n6_motion_pattern.npz',time=times,delta_relation=a['delta_relation'],delta_strain=a['delta_strain'],delta_unit=a['delta_unit'],delta_force=a['delta_force'],momentum_difference=a['momentum_difference'])
    # Independently existing signed native flux fixes the +x orientation; DEV182 fixes its causal launch-to-receipt displacement.
    flux=np.asarray([pair_power_flux(u[t],p[t]).sum(axis=(0,1,2)) for t in range(T)])
    direction=np.array([1.,0.,0.]); displacement=np.array([7/180,0.,0.])
    dump('propagation_direction_trace.json',{'direction':direction,'signed_native_flux_trace':flux,'source':'signed DEV167 pair-power flux; +x agrees with frozen DEV182 launch axis','canonical_displacement_per_update':displacement,'spatial_shift_used_for_one_update':[0,0,0],'shift_reason':'nearest exact lattice shift to independently fixed 7/180 +x displacement; not fitted from relational pattern','PROPAGATION_DIRECTION_FROM_EXISTING_NATIVE_QUANTITY':True})
    rp, rt=decompose(a['delta_relation'],direction); fp, ft=decompose(a['delta_force'],direction); mp, mt=decompose(a['momentum_difference'],direction)
    save('longitudinal_relative_motion.npz',time=times,parallel=rp); save('transverse_relative_motion.npz',time=times,transverse=rt)
    save('longitudinal_force_change.npz',time=times,parallel=fp); save('transverse_force_change.npz',time=times,transverse=ft)
    transverse_nonzero=not np.array_equal(rt,np.zeros_like(rt)); transverse='PRESENT' if transverse_nonzero else 'ABSENT'
    transverse_components=rt[...,1:].reshape(-1,2); gram=transverse_components.T@transverse_components; rank='TWO' if np.linalg.det(gram)!=0 else 'ONE' if np.any(gram!=0) else 'ZERO'
    dump('intrinsic_transverse_relational_content.json',{'INTRINSIC_TRANSVERSE_RELATIONAL_CONTENT':transverse,'exact_nonzero':transverse_nonzero,'parallel_l2':norm(rp),'transverse_l2':norm(rt),'signed_vectors_retained':True,'no_threshold':True})
    dump('intrinsic_transverse_component_rank.json',{'INTRINSIC_TRANSVERSE_COMPONENT_RANK':rank,'transverse_gram':gram,'determinant':float(np.linalg.det(gram)),'criterion':'exact Gram determinant / exact nonzero, no cutoff'})
    # Compare complete vectors at the predeclared nearest lattice translation (zero per update).
    shifted=np.roll(a['delta_relation'],0,axis=(1,2,3)); corr=np.asarray([normalized_dot(shifted[t],a['delta_relation'][t+1]) for t in range(T-1)])
    diff=np.asarray([norm(shifted[t]-a['delta_relation'][t+1]) for t in range(T-1)])
    coherence='COHERENT' if np.all(corr>0) else 'PARTIALLY_COHERENT' if np.any(corr>0) else 'NONTRANSPORTED'
    transport='CO_MOVING' if coherence=='COHERENT' else 'PARTIALLY_CO_MOVING' if coherence=='PARTIALLY_COHERENT' else 'DISPERSIVE'
    save('relational_pattern_shift_comparison.npz',time=times[:-1],signed_normalized_dot=corr,shifted_difference_l2=diff,shift=np.array([0,0,0]))
    dump('relational_pattern_coherence.json',{'RELATIONAL_PATTERN_COHERENCE':coherence,'coefficient_free_signed_normalized_dot':{'min':float(corr.min()),'max':float(corr.max()),'mean':float(corr.mean())},'exact_shifted_difference_l2':{'min':float(diff.min()),'max':float(diff.max())},'predeclared_shift':[0,0,0],'no_free_shift_fit':True})
    dump('intrinsic_transverse_content_transport.json',{'INTRINSIC_TRANSVERSE_CONTENT_TRANSPORT':transport if transverse_nonzero else 'ABSENT','basis':'same independently fixed displacement and full bond-resolved time-shift comparison','NO_TANGENT_PROBE':True})
    sn, an=opposite_components(a['delta_relation']); sym, anti=native_symmetric_antisymmetric(a['delta_relation'])
    save('symmetric_relational_components.npz',time=times,opposite_pair_symmetric=sn,directional_tensor_symmetric=sym)
    save('antisymmetric_relational_components.npz',time=times,opposite_pair_antisymmetric=an,directional_tensor_antisymmetric=anti)
    rotation='PRESENT' if not np.array_equal(anti,np.zeros_like(anti)) else 'ABSENT'
    dump('native_relational_rotation_signature.json',{'NATIVE_RELATIONAL_ROTATION_SIGNATURE':rotation,'definition':'A=(M-M^T)/2, M_ij=(delta_r_(+i),j-delta_r_(-i),j)/2 from opposite N6 relations','antisymmetric_l2':norm(anti),'symmetric_l2':norm(sym),'not_a_magnetic_field':True,'no_continuum_curl':True})
    strain_norm=np.asarray([norm(x) for x in a['delta_strain']]); orientation_norm=np.asarray([norm(x) for x in a['delta_unit']])
    source='STRAIN_DOMINANT' if np.all(strain_norm>orientation_norm) else 'ORIENTATION_DOMINANT' if np.all(orientation_norm>strain_norm) else 'MIXED'
    dump('strain_orientation_content_comparison.json',{'RELATIONAL_WAVE_CONTENT_SOURCE':source,'strain_change_l2':strain_norm,'orientation_change_l2':orientation_norm,'comparison':'exact per-update norm ordering; no selected dominance ratio'})
    signs=np.sign(a['delta_relation']); temporal='OSCILLATORY' if np.any(np.any(signs>0,axis=0)&np.any(signs<0,axis=0)) else 'MONOTONIC_PASSAGE'
    dump('relational_temporal_character.json',{'RELATIONAL_TEMPORAL_CHARACTER':temporal,'basis':'fixed bond/component signs across the predetermined causal trajectory','sign_changing_component_exists':temporal=='OSCILLATORY','no_fourier_input':True})
    dump('native_relational_phase.json',{'NATIVE_RELATIONAL_PHASE':'NOT_PRESENT','reason':'No repeated spatial phase identity is introduced from a finite packet width; DEV203 records temporal sign change only.','OPTICAL_PHASE_MAPPING':'UNESTABLISHED'})
    propagation='DERIVED' if not np.array_equal(a['delta_relation'],np.zeros_like(a['delta_relation'])) and coherence in ('COHERENT','PARTIALLY_COHERENT') else 'NOT_DERIVED'
    candidate='DERIVED_STRONG' if all((quiet_zero, propagation=='DERIVED', transverse=='PRESENT', transport=='CO_MOVING', coherence=='COHERENT', temporal=='OSCILLATORY')) else 'DERIVED_PARTIAL' if propagation=='DERIVED' else 'NOT_DERIVED'
    dump('propagation_as_relational_motion.json',{'PROPAGATION_AS_RELATIONAL_MOTION':propagation,'reason':'the already-propagating trajectory is fully serialized as changing directed N6 relations and its complete pattern has positive time-shift correlation at independently fixed displacement','CANONICAL_PROPAGATION_PRESERVED':True})
    dump('em_like_relational_wave_candidate.json',{'EM_LIKE_RELATIONAL_WAVE_CANDIDATE':candidate,'scope':'native relational-wave candidate only; no electromagnetic identity claimed','requirements':{'quiet_unloaded_control':quiet_zero,'no_added_probe':True,'coherent_transport':coherence,'intrinsic_transverse':transverse,'temporal_character':temporal}})
    dump('electric_field_mapping_status.json',{'ELECTRIC_FIELD_MAPPING':'UNESTABLISHED'}); dump('magnetic_field_mapping_status.json',{'MAGNETIC_FIELD_MAPPING':'UNESTABLISHED'}); dump('polarization_mapping_status.json',{'POLARIZATION_MAPPING':'TWO_INTRINSIC_TRANSVERSE_NATIVE_COMPONENTS_DERIVED_MAPPING_UNESTABLISHED' if rank=='TWO' and transport=='CO_MOVING' else 'UNESTABLISHED'}); dump('optical_phase_mapping_status.json',{'OPTICAL_PHASE_MAPPING':'UNESTABLISHED'}); dump('speed_of_light_mapping_status.json',{'SPEED_OF_LIGHT_MAPPING':'UNESTABLISHED'})
    dump('canonical_propagation_status.json',{'CANONICAL_PROPAGATION_PRESERVED':True,'NO_NEW_PROPAGATION_LAW':True,'NO_NEW_FORCE_LAW':True,'NO_NEW_MEDIUM_PHYSICS':True,'NO_PRESTRESS':True})
    dump('independent_event_transport_status.json',{'INDEPENDENT_EVENT_TRANSPORT':'UNCHANGED_NOT_TESTED','reason':'DEV203 uses one canonical trajectory and introduces no second packet.'}); dump('double_slit_lane_status.json',{'DOUBLE_SLIT_LANE':'FOUNDATIONAL_DIAGNOSTIC_ONLY'}); dump('magnetar_lane_status.json',{'MAGNETAR_BIREFRINGENCE_VALIDATION_LANE':'PARKED'}); dump('weak_lensing_gate.json',{'CURRENT_WEAK_LENSING_DATASET_UNCHANGED':True,'NO_OTHER_LENS_OPENED':True})
    update_docs(candidate,propagation,transverse,transport,coherence,source,rotation); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT)
    dump('registry_update_validation.json',{'MECHANISM_REGISTRY_UPDATED':True,'REGISTRY_VALIDATED':True,'TIMELINE_REGENERATED':True,'DERIVATION_GRAPH_REGENERATED':True})
    flags='CURRENT_GITHUB_INSPECTED CURRENT_HEAD_VERIFIED MECHANISM_REGISTRY_QUERIED DEVELOPMENT_LEDGER_READ HISTORICAL_INDEX_READ HISTORICAL_RELATIVE_MOTION_WORK_INSPECTED DEV155_READ DEV156_READ DEV167_READ DEV182_READ DEV195_READ DEV199_READ DEV200_READ DEV201_READ DEV202_READ CANONICAL_PROPAGATION_PRESERVED DEV201_UNLOADED_TANGENT_RESULT_PRESERVED DEV202_LOADED_TANGENT_RESULT_PRESERVED NO_TANGENT_PROBE NO_ADDED_PERTURBATION NO_SECOND_PACKET NO_NEW_PROPAGATION_LAW NO_NEW_FORCE_LAW NO_NEW_MEDIUM_PHYSICS NO_PRESTRESS RELATIVE_NEIGHBOR_MOTION_DERIVED RELATIVE_MOMENTUM_DIFFERENCE_DERIVED STRAIN_CHANGE_DERIVED ORIENTATION_CHANGE_DERIVED FORCE_CHANGE_DERIVED NODE_N6_MOTION_PATTERN_RECONSTRUCTED UNLOADED_RELATIONAL_MOTION_CLASSIFIED PROPAGATION_AS_RELATIONAL_MOTION_CLASSIFIED PROPAGATION_DIRECTION_FROM_EXISTING_NATIVE_QUANTITY LONGITUDINAL_RELATIONAL_CONTENT_DERIVED TRANSVERSE_RELATIONAL_CONTENT_DERIVED INTRINSIC_TRANSVERSE_RELATIONAL_CONTENT_CLASSIFIED INTRINSIC_TRANSVERSE_COMPONENT_RANK_CLASSIFIED INTRINSIC_TRANSVERSE_CONTENT_TRANSPORT_CLASSIFIED RELATIONAL_PATTERN_COHERENCE_CLASSIFIED RELATIONAL_WAVE_CONTENT_SOURCE_CLASSIFIED SYMMETRIC_RELATIONAL_COMPONENTS_DERIVED ANTISYMMETRIC_RELATIONAL_COMPONENTS_DERIVED NATIVE_RELATIONAL_ROTATION_SIGNATURE_CLASSIFIED RELATIONAL_TEMPORAL_CHARACTER_CLASSIFIED NATIVE_RELATIONAL_PHASE_CLASSIFIED EM_LIKE_RELATIONAL_WAVE_CANDIDATE_CLASSIFIED NO_MAXWELL_INPUT NO_QED_INPUT NO_EM_PARAMETER_INPUT NO_SI_MAPPING NO_PACKET_AMPLITUDE_SWEEP CURRENT_WEAK_LENSING_DATASET_UNCHANGED NO_OTHER_LENS_OPENED UPSTREAM_HASHES_UNCHANGED PIPELINE_DETERMINISTIC MECHANISM_REGISTRY_UPDATED REGISTRY_VALIDATED TIMELINE_REGENERATED DERIVATION_GRAPH_REGENERATED LEDGER_UPDATED HISTORICAL_INDEX_UPDATED TESTS_PASS'.split()
    c={x:True for x in flags}; c.update({'UNLOADED_RELATIONAL_MOTION':'ZERO_OR_MACHINE_FLOOR' if quiet_zero else 'NONZERO','PROPAGATION_AS_RELATIONAL_MOTION':propagation,'INTRINSIC_TRANSVERSE_RELATIONAL_CONTENT':transverse,'INTRINSIC_TRANSVERSE_COMPONENT_RANK':rank,'INTRINSIC_TRANSVERSE_CONTENT_TRANSPORT':transport if transverse_nonzero else 'ABSENT','RELATIONAL_PATTERN_COHERENCE':coherence,'RELATIONAL_WAVE_CONTENT_SOURCE':source,'NATIVE_RELATIONAL_ROTATION_SIGNATURE':rotation,'RELATIONAL_TEMPORAL_CHARACTER':temporal,'NATIVE_RELATIONAL_PHASE':'NOT_PRESENT','EM_LIKE_RELATIONAL_WAVE_CANDIDATE':candidate,'ELECTRIC_FIELD_MAPPING':'UNESTABLISHED','MAGNETIC_FIELD_MAPPING':'UNESTABLISHED','OPTICAL_PHASE_MAPPING':'UNESTABLISHED','OPTICAL_PHASE_MAPPING_CLASSIFIED':True,'POLARIZATION_MAPPING':'TWO_INTRINSIC_TRANSVERSE_NATIVE_COMPONENTS_DERIVED_MAPPING_UNESTABLISHED' if rank=='TWO' and transport=='CO_MOVING' else 'UNESTABLISHED','POLARIZATION_MAPPING_CLASSIFIED':True,'SPEED_OF_LIGHT_MAPPING':'UNESTABLISHED','IMPLEMENTATION_COMMIT_RECORDED':False,'REMOTE_PUSH_CONFIRMED':False,'REMOTE_FINAL_HEAD_VERIFIED':False,'WORKTREE_CLEAN':False,'upstream_sha256':{str(x.relative_to(ROOT)):sha(x) for x in upstream}})
    dump('final_contract.json',c); (OUT/'discussion_handoff.md').write_text(f'# DEV203 handoff\n\nThe frozen canonical trajectory has `{propagation}` changing N6 relations; intrinsic transverse content is `{transverse}` and `{transport}` with `{coherence}` complete-pattern coherence. This is a native relational-wave candidate (`{candidate}`), not an E/B, polarization, optical-phase, SI, or photon mapping.\n')

if __name__ == '__main__': main()
