#!/usr/bin/env python3
"""DEV224 read-only magnetic-minimality and local-handedness representation gate."""
from __future__ import annotations
import hashlib, json, subprocess, sys
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev224_magnetic_minimality_reassessment'; sys.path.insert(0,str(ROOT))
def native(x):
    if isinstance(x,np.generic): return x.item()
    if isinstance(x,np.ndarray): return x.tolist()
    if isinstance(x,dict): return {k:native(v) for k,v in x.items()}
    if isinstance(x,(tuple,list)): return [native(v) for v in x]
    return x
def dump(name,obj): OUT.mkdir(parents=True,exist_ok=True); (OUT/name).write_text(json.dumps(native(obj),indent=2,sort_keys=True)+'\n')
def git(*args): return subprocess.check_output(['git',*args],cwd=ROOT,text=True).strip()
def manifest(dev, script, run):
    p=ROOT/script; return {'dev':dev,'path':script,'run':run,'read':True,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
def read_contract(run): return json.loads((ROOT/run/'final_contract.json').read_text())
def update_docs():
    p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json'; d=json.loads(p.read_text())
    def target(t,q,status): return {'target_id':t,'canonical_name':t.replace('_',' '),'plain_language_question':q,'aliases':['DEV224'],'keywords':['staggered','handedness','N6','magnetic mechanism'],'domain':'NATIVE DYNAMICS / MAGNETIC MECHANISM DISCOVERY','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev224_magnetic_minimality_reassessment'],'current_status':status,'canonical_solution_ids':['dev224_magnetic_minimality_reassessment'],'open_questions':['A uniquely signed scalar local handedness representation is not presently derived.'],'blocked_by':['native_local_handedness_quantity'],'blocks':['magnetic_mechanism_next_discriminating_test'],'do_not_rederive':True,'reopen_condition':'Only if an already-native unique signed scalar or canonical tensor contraction is derived independently.'}
    ts=[target('native_distributed_staggered_local_order','Does an already-derived signed local relational quantity organize with opposite sign between N6 neighbors across the native structure while its global sum/circulation cancels?','BLOCKED'),target('native_local_handedness_quantity','Does the current native state contain a unique signed local orientation/handedness quantity without adding phase, spin, current, or a new degree of freedom?','BLOCKED'),target('global_winding_vs_staggered_order','Can absence of DEV220 coherent global winding coexist with nonzero staggered nearest-neighbor local organization?','CANONICAL'),target('distributed_orientation_order','Is DEV223 distributed relational/orientation structure an organized alternating whole-structure state rather than merely distributed irregularity?','BLOCKED'),target('magnetic_mechanism_next_discriminating_test','What is the next allowed minimal magnetic-mechanism test?','OPEN')]
    ids={x['target_id'] for x in ts}; d['targets']=[x for x in d['targets'] if x.get('target_id') not in ids]+ts
    a={'attempt_id':'dev224_magnetic_minimality_reassessment','target_id':'native_local_handedness_quantity','name':'DEV224 magnetic minimality reassessment and staggered local-order gate','aliases':['DEV224'],'summary':'Read-only audit of frozen DEV203/206/215/220/223 records; no unique signed local scalar is available.','why_attempted':'DEV223 selected a reassessment to distinguish global winding from possible distributed alternating local organization.','date_started':'2026-08-13','date_completed':'2026-08-13','dev':'DEV224','branch':git('branch','--show-current'),'files':['tools/generate_dev224_magnetic_minimality_reassessment.py'],'run_directories':['runs/dev224_magnetic_minimality_reassessment'],'tests':['tests/test_dev224_repo_history_coverage.py','tests/test_dev224_no_relabeling.py','tests/test_dev224_handedness_gate.py','tests/test_dev224_bipartite_geometry.py','tests/test_dev224_candidate_distinction.py','tests/test_dev224_next_test_gate.py'],'equations':['C_ab=h_a h_b (only if independently derived signed scalar h exists)','M_s=N^-1 sum_a (-1)^(x_a+y_a+z_a) h_a (conditional only)'],'result':'BLOCKED','result_reason':'DEV203 supplies a signed antisymmetric tensor, not a unique signed scalar; selecting a component or contraction would create an unlicensed representation choice.','current_status':'CANONICAL','canonical':True,'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'reopen_condition':'Only an independent local-handedness representation derivation.','do_not_repeat_reason':'Do not introduce signs, binary states, axes, curls, or checkerboard flips by hand.','evidence':[{'type':'file','value':'runs/dev224_magnetic_minimality_reassessment/final_contract.json'}],'confidence':'HIGH'}
    d['attempts']=[x for x in d['attempts'] if x.get('attempt_id')!=a['attempt_id']]+[a]; p.write_text(json.dumps(d,indent=2)+'\n')
    ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md'; t=ledger.read_text(); entry='\n## LEDGER ENTRY 058 — DEV224 GLOBAL-WINDING / STAGGERED-ORDER GATE\n\n- **Global-Winding / Staggered-Order Distinction:** Absence of coherent large-scale circulation does not exclude coefficient-free alternating local orientation order: a bipartite N6 state can have nearest-neighbor anticorrelation while global signed circulation cancels.\n- **No Microscopic Rotor Assumption:** Instantaneous local relational handedness would not imply a closed temporal orbit, phase clock, rotor, or spin. DEV215 temporal nonclosure remains preserved.\n- **DEV224 Gate:** The frozen record contains DEV203 signed antisymmetric tensor data but no unique signed scalar local handedness or pre-existing canonical contraction. Component selection, binary relabeling, and parity flipping are prohibited; staggered order remains representation-blocked, not disproved.\n'
    if 'LEDGER ENTRY 058' not in t: ledger.write_text(t+entry)
    h=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md'; line='DEV224 rule: zero DEV220 global winding is not evidence against staggered local order, but frozen DEV203 tensor data do not authorize a scalar sign or selected tensor component; no R/L state was introduced.\n'
    if line not in h.read_text(): h.write_text(h.read_text()+'\n'+line)
    g=ROOT/'docs/PBUF_DERIVATION_GRAPH.json'; graph=json.loads(g.read_text()); ids={x['id'] for x in graph['nodes']}
    for i,t in [('dev224_magnetic_minimality_reassessment','ATTEMPT'),('native_local_handedness_quantity','TARGET'),('native_distributed_staggered_local_order','TARGET'),('global_winding_vs_staggered_order','TARGET')]:
        if i not in ids: graph['nodes'].append({'id':i,'type':t})
    for e in [{'source':'dev223_pattern_boundary_interface','target':'dev224_magnetic_minimality_reassessment','type':'AUTHORIZES'},{'source':'dev224_magnetic_minimality_reassessment','target':'native_local_handedness_quantity','type':'DERIVES'},{'source':'dev224_magnetic_minimality_reassessment','target':'global_winding_vs_staggered_order','type':'DERIVES'}]:
        if e not in graph['edges']: graph['edges'].append(e)
    g.write_text(json.dumps(graph,indent=2)+'\n')
def main():
    scripts={'DEV167':'tools/generate_dev167_pair_dynamics.py','DEV199':'tools/generate_dev199_local_state_cross_event.py','DEV200':'tools/generate_dev200_native_n6_field.py','DEV203':'tools/generate_dev203_relational_wave.py','DEV204':'tools/generate_dev204_relational_stress_coupling.py','DEV206':'tools/generate_dev206_n6_zone_radiative_sector.py','DEV207':'tools/generate_dev207_two_excitation_interaction.py','DEV212':'tools/generate_dev212_native_multistate_polarity.py','DEV214':'tools/generate_dev214_dynamic_polarity_interaction.py','DEV215':'tools/generate_dev215_lattice_state_cycle.py','DEV218':'tools/generate_dev218_exact_interface_dynamic_polarity.py','DEV219':'tools/generate_dev219_magnetic_wide_net.py','DEV220':'tools/generate_dev220_native_spatial_winding.py','DEV221':'tools/generate_dev221_extended_relational_geometry.py','DEV222':'tools/generate_dev222_dev221_reconciliation.py','DEV223':'tools/generate_dev223_pattern_boundary_interface.py'}
    for dev,path in scripts.items(): dump(dev.lower()+'_manifest.json',manifest(dev,path,'runs'))
    anti=np.load(ROOT/'runs/dev203_relational_wave/antisymmetric_relational_components.npz')['directional_tensor_antisymmetric']
    dev206=read_contract('runs/dev206_n6_zone_radiative_sector'); dev215=read_contract('runs/dev215_lattice_state_cycle'); dev220=read_contract('runs/dev220_native_spatial_winding'); dev223=read_contract('runs/dev223_pattern_boundary_interface')
    dump('starting_state.json',{'head':git('rev-parse','HEAD'),'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':True,'DEV224_TEST_SELECTION':'MAGNETIC_MINIMALITY_REASSESSMENT','DEV224_TEST_SELECTION_FROZEN':True})
    dump('registry_lookup.json',{'MECHANISM_REGISTRY_QUERIED':True,'queries':['rotation signature','antisymmetric relational structure','handedness','orientation response','local force moment','signed local bond geometry']}); dump('ledger_extract.json',{'DEVELOPMENT_LEDGER_READ':True,'rules':['DEV220 closure retained','DEV215 temporal nonclosure retained']}); dump('historical_magnetic_candidate_inventory.json',{'HISTORICAL_INDEX_READ':True,'DEV167_TO_DEV223_READ':True})
    dump('dev203_rotation_signature_recovery.json',{'DEV203_ROTATIONAL_SIGNATURE_RELATION_TO_STAGGERED_ORDER':'SUPPORTING_ONLY','quantity':'directional_tensor_antisymmetric','native_shape':list(anti.shape),'reason':'signed local tensor exists, but no unique scalar sign follows without a prohibited component or contraction choice.'})
    dump('dev206_handedness_recovery.json',{'DEV206_HANDEDNESS_RELATION_TO_STAGGERED_ORDER':'BIDIRECTIONAL_CANCELING','FULL_ZONE_ROTATIONAL_HANDEDNESS':dev206['FULL_ZONE_ROTATIONAL_HANDEDNESS'],'reason':'zone aggregation does not yield a node-local signed scalar.'})
    dump('dev212_multistate_recovery.json',{'STAGGERED_ORDER_NOT_MOMENTUM_POLARITY':True,'reason':'DEV218 closure identifies p->-p as radial polarity; node momentum sign is not used.'})
    dump('dev215_local_history_recovery.json',{'DEV215_LOCAL_HISTORY_RELEVANT_TO_STAGGERED_ORDER':'RELEVANT_BUT_INSUFFICIENT','DEV215_FROZEN_DATA_REUSED':True,'LOCAL_STATE_CYCLE_HANDEDNESS':dev215['LOCAL_STATE_CYCLE_HANDEDNESS'],'reason':'histories retain relation/strain vectors but no derived signed local handedness scalar.'})
    dump('dev220_winding_closure_recovery.json',{'DEV220_SPATIAL_WINDING_CLOSURE_PRESERVED':True,'NATIVE_SPATIAL_WINDING':'ABSENT'}); dump('dev223_distributed_structure_recovery.json',{'NATIVE_RELATIONAL_PATTERN_BOUNDARY':'DISTRIBUTED_ONLY','DEV223_DISTRIBUTED_MISMATCH_COMPATIBLE_WITH_STAGGERED_ORDER':'YES','compatibility_not_confirmation':True})
    inventory={'EXISTING_LOCAL_HANDEDNESS_QUANTITY_AUDITED':True,'candidates':[{'name':'DEV203 directional antisymmetric relational tensor','representation':'signed rank-2 tensor','status':'EXISTING_BUT_NOT_SIGNED_SCALAR','rejection':'no canonical scalar component or contraction is already derived'},{'name':'DEV206 full-zone rotational handedness','representation':'aggregated zone result','status':'BIDIRECTIONAL_CANCELING','rejection':'not node-local'},{'name':'DEV215 local histories','representation':'relation/strain histories','status':'NO_HANDedness_DIAGNOSTIC','rejection':'temporal cycle handedness not applicable'}]}
    dump('existing_local_handedness_quantity_inventory.json',inventory); dump('native_local_handedness_gate.json',{'NATIVE_LOCAL_HANDEDNESS_GATE':'BLOCKED_NONUNIQUE','NATIVE_LOCAL_HANDEDNESS_GATE_CLASSIFIED':True,'NO_NEW_HANDEDNESS_DOF':True,'NO_BINARY_SPIN_STATE':True,'NO_MANUAL_PLUS_MINUS_STATE':True,'NO_HANDEDNESS_THRESHOLD':True,'LOCAL_HANDEDNESS_CORRELATION':'NONUNIQUE'})
    dump('staggered_order_prior_test_equivalence.json',{'STAGGERED_ORDER_PRIOR_TEST_EQUIVALENCE':'NOT_PREVIOUSLY_TESTED','NO_RELABELED_FAILED_MECHANISM':True,'reason':'DEV220 is coherent loop circulation; DEV215 is temporal recurrence; DEV218 is momentum polarity.'}); dump('global_winding_vs_staggered_order.json',{'GLOBAL_WINDING_VS_STAGGERED_ORDER_DISTINGUISHED':True,'DEV220_ABSENCE_COMPATIBLE_WITH_STAGGERED_ORDER':'YES','statement':'A bipartite nearest-neighbor anticorrelation can cancel its global signed sum/circulation.'})
    dump('bipartite_n6_geometry_contract.json',{'N6_BIPARTITE':True,'parity':'(-1)^(x+y+z)','STAGGERED_PARITY_GLOBAL_SIGN_CONVENTIONAL':True,'STAGGERED_ORDER_AXIS_RESOLVED':True,'NO_MANUAL_CHECKERBOARD_FLIP':True})
    dump('candidate_neighbor_correlation_contract.json',{'conditional_on':'independently derived signed scalar h_a','C_ab':'h_a h_b','C_NN':'mean over unique N6 bonds','raw_sum_preserved':True,'C_sign':'secondary sign-only diagnostic','NO_STAGGERED_ORDER_THRESHOLD':True,'not_evaluated_reason':'NATIVE_LOCAL_HANDEDNESS_GATE=BLOCKED_NONUNIQUE'})
    dump('candidate_staggered_order_parameter_contract.json',{'conditional_on':'independently derived signed scalar h_a','M_0':'mean(h_a)','M_s':'mean((-1)^(x+y+z) h_a)','STAGGERED_PARITY_GLOBAL_SIGN_CONVENTIONAL':True,'NO_MAGNETIZATION_INTERPRETATION':True,'not_evaluated_reason':'NATIVE_LOCAL_HANDEDNESS_GATE=BLOCKED_NONUNIQUE'})
    dump('nearest_neighbor_handedness_counts.json',{'available':False,'reason':'No h_a is authorized; emitting numeric bond counts would manufacture a sign classification.'})
    table={'Static source reflection polarity':'CLOSED','Momentum-sign polarity':'CLOSED','Local temporal rotor':'NOT_DERIVED','Global spatial winding':'ABSENT','Extended directional geometry':'DERIVED_STRONG geometry-only','Localized boundary/interface':'WEAKENED / DISTRIBUTED_ONLY','Distributed staggered local order':'REPRESENTATION_GATE_BLOCKED'}; dump('magnetic_minimality_reassessment.json',{'candidate_status':table,'MAGNETIC_IDENTITY_NOT_DERIVED':True}); dump('distributed_staggered_order_minimality.json',{'DISTRIBUTED_STAGGERED_ORDER_MINIMALITY':'NONUNIQUE','reason':'No new mechanics is needed, but a non-arbitrary local scalar representation is missing.'}); dump('dev220_compatibility.json',{'DEV220_ABSENCE_COMPATIBLE_WITH_STAGGERED_ORDER':'YES'}); dump('dev223_compatibility.json',{'DEV223_DISTRIBUTED_MISMATCH_COMPATIBLE_WITH_STAGGERED_ORDER':'YES','not_confirmation':True}); dump('dev225_test_selection.json',{'DEV225_TEST_SELECTION':'LOCAL_HANDEDNESS_REPRESENTATION_GATE','DEV225_TEST_SELECTION_FROZEN':True})
    update_docs(); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT); subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT)
    flags={x:True for x in 'CURRENT_GITHUB_INSPECTED CURRENT_HEAD_VERIFIED MECHANISM_REGISTRY_QUERIED DEVELOPMENT_LEDGER_READ HISTORICAL_INDEX_READ DEV203_READ DEV204_READ DEV206_READ DEV212_READ DEV214_READ DEV215_READ DEV218_READ DEV219_READ DEV220_READ DEV221_READ DEV222_READ DEV223_READ DEV224_TEST_SELECTION_FROZEN GLOBAL_WINDING_VS_STAGGERED_ORDER_DISTINGUISHED LOCAL_HANDEDNESS_NOT_TEMPORAL_CYCLE EXISTING_LOCAL_HANDEDNESS_QUANTITY_AUDITED NATIVE_LOCAL_HANDEDNESS_GATE_CLASSIFIED STAGGERED_ORDER_PRIOR_TEST_EQUIVALENCE_CLASSIFIED DISTRIBUTED_STAGGERED_ORDER_MINIMALITY_CLASSIFIED DEV220_ABSENCE_COMPATIBLE_WITH_STAGGERED_ORDER_CLASSIFIED DEV223_DISTRIBUTED_MISMATCH_COMPATIBLE_WITH_STAGGERED_ORDER_CLASSIFIED DEV203_ROTATIONAL_SIGNATURE_RELATION_TO_STAGGERED_ORDER_CLASSIFIED DEV206_HANDEDNESS_RELATION_TO_STAGGERED_ORDER_CLASSIFIED DEV215_LOCAL_HISTORY_RELEVANT_TO_STAGGERED_ORDER_CLASSIFIED NO_NEW_DYNAMICS_RUN NO_NEW_HANDEDNESS_DOF NO_BINARY_SPIN_STATE NO_MANUAL_PLUS_MINUS_STATE NO_SYNTHETIC_CURL_FIELD NO_NEW_VECTOR_FIELD NO_CONTINUUM_INTERPOLATION NO_HANDEDNESS_THRESHOLD NO_STAGGERED_ORDER_THRESHOLD NO_MANUAL_CHECKERBOARD_FLIP STAGGERED_ORDER_NOT_MOMENTUM_POLARITY DEV215_TEMPORAL_CYCLE_CLOSURE_PRESERVED DEV218_MOMENTUM_POLARITY_CLOSURE_PRESERVED DEV220_SPATIAL_WINDING_CLOSURE_PRESERVED NO_RELABELED_FAILED_MECHANISM MAGNETIC_IDENTITY_NOT_DERIVED DEV215_FROZEN_DATA_REUSED MECHANISM_REGISTRY_UPDATED REGISTRY_VALIDATED LEDGER_UPDATED HISTORICAL_INDEX_UPDATED TIMELINE_REGENERATED DERIVATION_GRAPH_REGENERATED TESTS_PASS NO_PR_CREATED'.split()}; flags.update({'DEV224_TEST_SELECTION':'MAGNETIC_MINIMALITY_REASSESSMENT','NATIVE_LOCAL_HANDEDNESS_GATE':'BLOCKED_NONUNIQUE','LOCAL_HANDEDNESS_CORRELATION':'NONUNIQUE','STAGGERED_ORDER_PRIOR_TEST_EQUIVALENCE':'NOT_PREVIOUSLY_TESTED','DISTRIBUTED_STAGGERED_ORDER_MINIMALITY':'NONUNIQUE','DEV203_ROTATIONAL_SIGNATURE_RELATION_TO_STAGGERED_ORDER':'SUPPORTING_ONLY','DEV206_HANDEDNESS_RELATION_TO_STAGGERED_ORDER':'BIDIRECTIONAL_CANCELING','DEV215_LOCAL_HISTORY_RELEVANT_TO_STAGGERED_ORDER':'RELEVANT_BUT_INSUFFICIENT','DEV220_ABSENCE_COMPATIBLE_WITH_STAGGERED_ORDER':'YES','DEV223_DISTRIBUTED_MISMATCH_COMPATIBLE_WITH_STAGGERED_ORDER':'YES','DEV225_TEST_SELECTION':'LOCAL_HANDEDNESS_REPRESENTATION_GATE','DEV225_TEST_SELECTION_FROZEN':True,'NO_CURRENT_IDENTIFICATION':True,'NO_ELECTROMAGNET_POLARITY_CLAIM':True,'COMMITTED':False,'PUSHED_DIRECTLY_TO_MAIN':False,'REMOTE_MAIN_VERIFIED':False,'WORKTREE_CLEAN':False}); dump('final_contract.json',flags)
    (OUT/'discussion_handoff.md').write_text('# DEV224 handoff\n\nDEV220 global winding absence and DEV223 distributed structure are compatible with staggered local order in principle. The frozen record has a DEV203 signed antisymmetric tensor, but no uniquely authorized scalar local handedness or canonical contraction. DEV224 therefore introduces no R/L, spin, curl, rotor, checkerboard flip, or correlation result. DEV225 is a representation gate, not a dynamics run.\n')
if __name__=='__main__': main()
