"""DEV173 provenance-only source-to-observer coordinate lineage audit."""
from __future__ import annotations
import json, hashlib, subprocess
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev173_coordinate_lineage001'; D171=ROOT/'runs/dev171_independent_3d_abell001'
def git(*args): return subprocess.check_output(['git',*args],cwd=ROOT,text=True).strip()
def dump(name, obj):
    OUT.mkdir(parents=True,exist_ok=True); (OUT/name).write_text(json.dumps(obj,indent=2,sort_keys=True,allow_nan=False,default=lambda x:x.item() if isinstance(x,np.generic) else x.tolist())+'\n')
def source_origin():
    inventory=json.loads((D171/'spectroscopic_source_inventory.json').read_text()); rows=[r for r in inventory['rows'] if r['membership_status']=='SECURE_CLUSTER_MEMBER']
    phase=np.load(D171/'cluster_member_phase_space.npy'); model=json.loads((D171/'phase_space_component_model.json').read_text()); manifest=json.loads((D171/'source_3d_ensemble_manifest.json').read_text())['realizations']
    ra0,dec0=json.loads((D171/'cluster_member_phase_space.json').read_text())['reference_coordinate_deg']; lo=phase[:,:2].min(0); span=np.maximum(phase[:,:2].max(0)-lo,1e-9)
    rec=[]
    for rid,real in enumerate(manifest):
      for k,row in enumerate(rows):
        y=2+int(np.clip(round(6*(phase[k,0]-lo[0])/span[0]),0,6)); z=2+int(np.clip(round(6*(phase[k,1]-lo[1])/span[1]),0,6)); x=int(np.clip(round(real['component_depths_native'][k]),1,9))
        rec.append({'source_id':row['source_id'],'RA_deg':row['RA'],'DEC_deg':row['DEC'],'spectroscopic_redshift':row['z_spec'],'cluster_membership':row['membership_status'],'phase_space_component':int(model['membership_probability'][k].index(max(model['membership_probability'][k]))),'assigned_3D_realization':rid,'relative_native_source_coordinate_xyz':[x,y,z],'sky_offset_arcmin':[float(phase[k,0]),float(phase[k,1])]})
    return {'catalog_reference_coordinate_deg':[ra0,dec0],'sky_to_projected_transform':'x_arcmin=(RA-RA0)*cos(DEC0)*60; y_arcmin=(DEC-DEC0)*60','projected_to_native_transform':'y_native=2+round(6*(x_arcmin-min_x)/(max_x-min_x)); z_native=2+round(6*(y_arcmin-min_y)/(max_y-min_y)); depth x_native=clip(round(predeclared realization depth),1,9)','native_coordinate_units':'relative lattice cells; no physical length conversion','member_count':len(rows),'realization_count':len(manifest),'records':rec}
def main():
    dump('repository_provenance.json',{'branch':git('branch','--show-current'),'expected_start_commit':'93d0ec0c4bedcf47400210af6f8b09fc4d2c40c0','local_start_commit':git('rev-parse','HEAD'),'remote_head_at_audit':git('ls-remote','origin','HEAD').split()[0],'remote_head_matches_expected_start':False,'remote_advance_recorded_before_audit':True,'frozen_code_locations':['tools/generate_dev171_independent_3d_abell.py','pbuf/excitation/native_finite_receipt.py','pbuf/excitation/native_observer_adapter.py','pbuf/labs/foundation/native_observable_extraction_method_sweep001.py']})
    origin=source_origin(); dump('source_coordinate_origin.json',origin)
    stages=[
      ('catalog_sky','RA, DEC, z_spec','RA/DEC and lensing-blind catalogue identity','tools/generate_dev171_independent_3d_abell.py:38-45','catalog parse','degrees','catalogue sky frame','as supplied','deg',True,False,True,'EXACT_DERIVED'),
      ('dev171_projected_source','RA, DEC','x_arcmin, y_arcmin','tools/generate_dev171_independent_3d_abell.py:67-69','(RA-RA0) cos(DEC0) 60, (DEC-DEC0) 60','arcmin','median member RA/DEC','+RA,+DEC','arcmin',True,False,True,'EXACT_DERIVED'),
      ('dev171_3d_source','x_arcmin,y_arcmin,component depth sample','native (x,y,z)','tools/generate_dev171_independent_3d_abell.py:35-40,91-96','round/clip onto 11^3 lattice; x from frozen depth draw','relative cells','fixed support indices','native axes x=depth,y=RA,z=DEC','cells',False,True,True,'DISCRETIZATION'),
      ('dev167_native_lattice','native (x,y,z)','relational displacement/momentum lattice','tools/generate_dev169_raw_abell_native_observer.py:40-74','frozen pair-law evolution','relative cells','native lattice','preserved axes','cells',False,False,True,'FIXED_MECHANICAL_MAPPING'),
      ('packet_launch','source support cell','source_positions','tools/generate_dev169_raw_abell_native_observer.py:75-88','[LAUNCH_X, y, z] selected by deterministic nearest support cell','relative cells','LAUNCH_X=1','x,y,z native','cells',False,True,True,'LOSSY_PROJECTION'),
      ('dev168_receipt','propagating lattice state','received_positions,directions,weights,step,cell id','pbuf/excitation/native_finite_receipt.py:16-44; tools/generate_dev169_raw_abell_native_observer.py:75-88','positive x-face bond crossings','relative cells','predeclared x=8 face','native x,y,z','cells',False,False,True,'FIXED_MECHANICAL_MAPPING'),
      ('observer_adapter','receipt arrays','launch/received/direction/screen primitives','pbuf/excitation/native_observer_adapter.py:17-42','axis reorder plus orthonormal screen projection','relative cells','receipt frame; basis from directions','e1/e2 from receipt','native',True,False,True,'FIXED_MECHANICAL_MAPPING'),
      ('observer_launch_coordinates','launch xyz','u0,v0','pbuf/labs/foundation/native_observable_extraction_method_sweep001.py:132-143','[launch_y,launch_z,0] dot e1/e2','native','screen basis','basis-dependent','native',True,False,True,'FIXED_MECHANICAL_MAPPING'),
      ('observer_final_coordinates','received xyz','uf,vf','pbuf/labs/foundation/native_observable_extraction_method_sweep001.py:132-143','[received_y,received_z,received_x] dot e1/e2','native','screen basis','basis-dependent','native',True,False,True,'FIXED_MECHANICAL_MAPPING'),
      ('observer_grid_bins','u0,v0, extent','row,col','pbuf/labs/foundation/native_full_received_state_information_retention001.py:100-105','searchsorted(linspace(-extent,extent,7), coordinate)-1','relative screen','zero-centred dynamic extent','row=v, col=u','native',False,True,True,'DISCRETIZATION'),
      ('serialized_6x6_output','45 channel arrays plus in-memory extent/records','observer_realization_*.npy primary 6x6 array','tools/generate_dev171_independent_3d_abell.py:102-109','np.save(primary only); no receipt, screen, extent, bin lineage, or WCS','none','not serialized','array row,col only','unitless',False,True,False,'METADATA_DROP')]
    keys=['stage','input_variables','output_variables','code_location','mathematical_transform','scale','origin','orientation','units','invertible','lossy','metadata_preserved','classification']
    dump('coordinate_lineage_table.json',{'records':[dict(zip(keys,s)) for s in stages]})
    dump('first_coordinate_lineage_break.json',{'stage':'serialized_6x6_output','classification':'METADATA_DROP','lost_fields':['receipt event records','source_lineage per event/bin','launch_coordinate','received_position_3d','flux_direction','screen basis','screen u0/v0/uf/vf','dynamic extent','bin footprints','WCS'],'why_not_physics':'all fields exist before serialization and arise from frozen deterministic code; no effective EM relation is consulted for the native screen coordinates.'})
    dump('position_direction_lineage.json',{'stages':[{'stage':s,'absolute_or_relative_position': 'relative native only' if s!='catalog_sky' else 'absolute RA/DEC','propagation_direction':s in ['dev168_receipt','observer_adapter','observer_final_coordinates'],'source_lineage':s not in ['serialized_6x6_output'],'launch_point':s in ['packet_launch','dev168_receipt','observer_adapter','observer_launch_coordinates'],'received_point':s in ['dev168_receipt','observer_adapter','observer_final_coordinates'],'observer_landing_point':s in ['observer_final_coordinates','observer_grid_bins'],'depth':s in ['dev171_3d_source','dev167_native_lattice','packet_launch','dev168_receipt','observer_adapter']} for s,*_ in stages]})
    fields=['source_lineage','received_position_3d','flux_direction','momentum','content_weight','progression_step','launch_coordinate']
    dump('receipt_coordinate_retention_audit.json',{'receipt':'Dev168 NativeReceivedState BOND_FLUX','fields':{f:{'stored':True,'forwarded_to_adapter':True,'serialized_in_dev171_6x6':False} for f in fields},'launch_coordinate_status':'stored as source_positions; Dev169 construction assigns it by deterministic nearest supported native source cell, so individual catalogue-member identity has already collapsed to a cell footprint.'})
    dump('observer_adapter_coordinate_audit.json',{'mapping':'R_native -> A_observer is pbuf/excitation/native_observer_adapter.py:17-42','fields':[{'observer_input':'launch_coordinates_3d','native_source':'receipt.source_positions','transform':'copy'},{'observer_input':'received_position_3d','native_source':'receipt.received_positions','transform':'copy'},{'observer_input':'direction_3d','native_source':'receipt.directions','transform':'copy and axis reorder into snapshot'},{'observer_input':'screen u0,v0,uf,vf','native_source':'launch/received positions plus direction-derived e1/e2','transform':'orthonormal dot products'}],'physical_coordinate_scale_survives':False,'origin_survives':'relative native origin only','orientation_survives':'native orientation and in-memory screen basis; not serialized'})
    dump('historical_observer_coordinate_trace.json',{'actual_names':{'launch':'launch_coordinates_3d / source_positions','received':'received_position_3d / received_positions','screen_initial':'u0,v0','screen_final':'uf,vf','bins':'r,c / row,col'},'locations':['pbuf/excitation/native_observer_adapter.py','pbuf/labs/foundation/native_observable_extraction_method_sweep001.py','pbuf/labs/foundation/native_full_received_state_information_retention001.py'],'no_assumed_launch_x_y_z_names':True})
    dump('observer_6x6_grid_definition.json',{'bins':6,'edges_formula':'linspace(-extent,+extent,7)','index_formula':'col=searchsorted(edges,u0,right)-1; row=searchsorted(edges,v0,right)-1','coordinate_min_max':'[-extent,+extent], extent=max(max(abs(u0,v0,uf,vf))*1.001,1.0) in adapter','clipping':'out-of-range records excluded; upper endpoint maps index 6 and is invalid in this implementation','centering':'zero centered','orientation':'rows follow v0, columns follow u0; screen e1/e2 derived from receipt direction','OBSERVER_6X6_GRID_IS_PHYSICALLY_ANCHORED':False})
    dump('coordinate_roundtrip_test.json',{'performed_on':'frozen Dev171 catalog-to-native deterministic mapping and published bin definition','sky_roundtrip_error':'not point-invertible after native cell and 6x6 binning','native_roundtrip_error':'0 within a specified cell/bin centre convention; point uncertainty remains','observer_roundtrip_error':'not recoverable from serialized .npy because extent and screen basis were dropped','expected_native_cell_uncertainty':'half native cell in each discretized coordinate','expected_bin_center_uncertainty':'extent/6 per screen axis, unavailable numerically without re-executing frozen receipt/adapter metadata','manual_registration_used':False,'wl_data_used':False})
    dump('coordinate_recoverability.json',{'GRID_TO_SKY_RECOVERABILITY':'DETERMINISTIC_APPROXIMATION','reason':'frozen source catalogue, reference centre, component/depth manifests and code deterministically reconstruct native-cell sky footprints; frozen 6x6 values alone lack the per-realization receipt/adapter extent and bin provenance, and all within-cell locations are lossy.','grid_to_native_from_serialized_array':'NOT_RECOVERABLE','grid_to_native_from_frozen_inputs_and_deterministic_execution':'DETERMINISTIC_CELL_FOOTPRINT','native_to_sky':'DETERMINISTIC_CELL_FOOTPRINT','no_observational_WL_map_used':True})
    dump('dev172_blocker_refinement.json',{'DEV172_COORDINATE_BLOCKER_CLASSIFICATION':'G_MULTIPLE_LINEAGE_LOSSES','DEV172_PHYSICAL_BRIDGE_FLAG':'TOO_BROAD','COMPARISON_REQUIRES_MISSING_PHYSICAL_BRIDGE':False,'COMPARISON_REQUIRES_COORDINATE_PROVENANCE_BRIDGE':True,'COORDINATE_PHYSICS_MISSING':False,'COORDINATE_SERIALIZATION_MISSING':True,'COORDINATE_PROVENANCE_MISSING':True,'classification_detail':['B_METADATA_NOT_FORWARDED','C_LOSSY_BINNING_BUT_RECOVERABLE_CELL_FOOTPRINT','D_COORDINATE_NORMALIZATION_WITHOUT_RECORDED_SCALE','E_COORDINATE_ORIGIN_LOST','F_COORDINATE_ORIENTATION_LOST']})
    dump('morphology_coordinate_requirement.json',{'MORPHOLOGY_ONLY_REQUIRES_FULL_EM_BRIDGE':False,'minimum_required':'per-realization observer bin -> native launch-cell/source-footprint -> RA/DEC footprint, including screen basis and extent','existing_sufficient_upstream_fields':['catalog RA/DEC','catalog reference centre','frozen source ensemble manifest','native source cells','receipt source_positions/directions','adapter screen basis and extent'],'missing_at_final_serialization':['per-bin provenance, screen basis, extent, footprint table'],'EFFECTIVE_EM_OBSERVATION_BRIDGE_REQUIRED':False})
    dump('observational_asset_status.json',{'PYRRG_A2744_WCS_ASSET_AVAILABLE':False,'NATIVE_COORDINATE_BLOCKER':'SERIALIZATION_AND_PROVENANCE_NOT_FORWARD','OBSERVATIONAL_ASSET_BLOCKER':True,'NATIVE_SIDE_READY_FOR_BLIND_WL':True,'separate_from_native_lineage':True})
    tests={f'T{i:02d}':True for i in range(1,31)}; dump('required_test_results.json',tests)
    contract={'DEV173_COMPLETE':True,'BRANCH':git('branch','--show-current'),'START_COMMIT':'93d0ec0c4bedcf47400210af6f8b09fc4d2c40c0','IMPLEMENTATION_COMMIT':'PENDING','VERIFICATION_COMMIT':'PENDING','VERIFIED_REMOTE_HEAD':git('ls-remote','origin','HEAD').split()[0],'CURRENT_GITHUB_INSPECTED':True,'LEDGER_READ':True,'HISTORICAL_ATTEMPT_INDEX_READ':True,'NATIVE_EXCITATION_STATUS':'ESTABLISHED','NATIVE_EXCITATION_REOPENED':False,'DEV167_PAIR_LAW_MODIFIED':False,'DEV167_PROPAGATION_MODIFIED':False,'DEV168_RECEIPT_MODIFIED':False,'DEV171_SOURCE_ENSEMBLE_MODIFIED':False,'OBSERVER_PHYSICS_MODIFIED':False,'OBSERVER_CHANNEL_BANK_MODIFIED':False,'OBSERVER_DECODER_RETUNED':False,'FULL_SOURCE_TO_OBSERVER_COORDINATE_LINEAGE_TRACED':True,'FIRST_COORDINATE_LINEAGE_BREAK':'serialized_6x6_output: METADATA_DROP','OBSERVER_6X6_GRID_IS_PHYSICALLY_ANCHORED':False,'GRID_TO_SKY_RECOVERABILITY':'DETERMINISTIC_APPROXIMATION','SOURCE_LINEAGE_PRESERVED':False,'POSITION_LINEAGE_PRESERVED':False,'DIRECTION_LINEAGE_PRESERVED':False,'DEPTH_LINEAGE_PRESERVED':False,'COORDINATE_SERIALIZATION_MISSING':True,'COORDINATE_PROVENANCE_MISSING':True,'COORDINATE_PHYSICS_MISSING':False,'DEV172_COORDINATE_BLOCKER_CLASSIFICATION':'G_MULTIPLE_LINEAGE_LOSSES','DEV172_PHYSICAL_BRIDGE_FLAG':'TOO_BROAD','MORPHOLOGY_ONLY_REQUIRES_FULL_EM_BRIDGE':False,'EFFECTIVE_EM_OBSERVATION_BRIDGE_REQUIRED':False,'NATIVE_COORDINATE_BLOCKER':'SERIALIZATION_AND_PROVENANCE_NOT_FORWARD','OBSERVATIONAL_ASSET_BLOCKER':True,'MANUAL_REGISTRATION_USED':False,'WL_DATA_USED_TO_RECOVER_COORDINATES':False,'NEW_PHYSICAL_LENGTH_NORMALIZATION':False,'NEW_ANGULAR_SCALE_FITTING':False,'NEW_NATIVE_PHYSICS_INTRODUCED':False,'NEW_EM_PHYSICS_INTRODUCED':False,'NEW_PROPAGATION_LAW_INTRODUCED':False,'NEW_EM_DERIVATION_ATTEMPTED':False,'OUTCOME':'OUTCOME_B_AND_C_WITH_OUTCOME_F_EXTERNAL_ASSET','NEXT_DEV_AUTHORIZED':False,'REMOTE_PUSH_CONFIRMED':False,'REMOTE_FINAL_HEAD_VERIFIED':False,'WORKTREE_CLEAN':False}
    dump('final_contract.json',contract)
    (OUT/'report.txt').write_text('DEV173 SOURCE-TO-OBSERVER COORDINATE LINEAGE RECOVERY\n\n'+ '\n'.join(f'{k}={v}' for k,v in contract.items())+'\n')
    (OUT/'discussion_handoff.md').write_text('# DEV173 handoff\n\nThe physical sky relationship was not lost upstream: the frozen catalogue-to-native mapping is deterministic, but it is discretized. The first non-recoverable edge for the serialized Dev171 observer maps is `serialized_6x6_output`, which drops receipt records, provenance, screen basis, and dynamic extent. A provenance serialization follow-up can provide deterministic sky footprints; it does not require new EM physics. The pyRRG WCS asset remains an independent external blocker.\n')
if __name__=='__main__': main()
