#!/usr/bin/env python3
"""DEV214: fixed-geometry DEV212 momentum-state interaction audit."""
from __future__ import annotations
import hashlib, json, subprocess, sys
from pathlib import Path
import numpy as np

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'runs/dev214_dynamic_polarity_interaction'; sys.path.insert(0,str(ROOT))
from pbuf.excitation.native_vector_pair_dynamics import VectorPairState, net_force, pair_power_flux, potential, step
from pbuf.excitation.native_multi_structure_preparation import NativePreparation, inject, reverse_internal_state
from pbuf.observer.native_interaction_energy import bond_state, interaction_residual
from pbuf.observer.native_stress_response import finite_step_force_response
from pbuf.observer.native_dynamic_pair_force import provenance_mask, support_force, classify, temporal_character
from pbuf.observer.native_dynamic_pair_torque import support_torque
from tools import generate_dev169_raw_abell_native_observer as D
from tools import generate_dev184_discrete_launch_density_convergence as E

LABELS=('++','+-','-+','--'); DT=.05; STEPS=12
def git(*a): return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()
def native(x):
 if isinstance(x,np.generic): return x.item()
 if isinstance(x,np.ndarray): return x.tolist()
 if isinstance(x,dict): return {k:native(v) for k,v in x.items()}
 if isinstance(x,(tuple,list)): return [native(v) for v in x]
 return x
def dump(n,x): OUT.mkdir(parents=True,exist_ok=True); (OUT/n).write_text(json.dumps(native(x),indent=2,sort_keys=True,allow_nan=False)+'\n')
def save(n,**x): OUT.mkdir(parents=True,exist_ok=True); np.savez_compressed(OUT/n,**x)
def manifest(dev,script,run):
 p=ROOT/script; return {'DEV_READ':True,'dev':dev,'script':script,'run':run,'exists':p.exists(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else None}
def evolve(s):
 out={k:[] for k in ('displacement','momentum','force','flux')}
 for _ in range(STEPS+1):
  out['displacement'].append(s.displacement.copy());out['momentum'].append(s.momentum.copy());out['force'].append(net_force(s.displacement));out['flux'].append(pair_power_flux(s.displacement,s.momentum));s=step(s,DT)
 return {k:np.asarray(v) for k,v in out.items()}
def fields(u):
 b=bond_state(u); return {**b,'node_force':net_force(u)}
def update_docs(result,relative,duality,torque):
 p=ROOT/'docs/PBUF_MECHANISM_REGISTRY.json';d=json.loads(p.read_text()); targets=[
 ('same_geometry_momentum_reversal_force','Does reversing only the native momentum state of an otherwise identical strain structure reverse its mutual interaction force?','BLOCKED' if result=='UNRESOLVED' else 'ACTIVE'),
 ('relative_dynamic_state_force_structure','Do same-state and opposite-state dynamic pairs form distinct native force classes?','BLOCKED' if relative=='UNRESOLVED' else 'ACTIVE'),
 ('native_dynamic_polarity_interaction','Does an exact internal dynamical state distinction of the same native structure produce attraction/repulsion duality?','BLOCKED' if result=='UNRESOLVED' else 'ACTIVE'),
 ('dynamic_state_dependent_torque','Does relative internal native state generate an alignment torque?','ACTIVE')]
 ids={x[0] for x in targets};d['targets']=[x for x in d['targets'] if x.get('target_id') not in ids]
 for i,q,status in targets:d['targets'].append({'target_id':i,'canonical_name':i.replace('_',' '),'plain_language_question':q,'aliases':['DEV214'],'keywords':['dynamic polarity','momentum reversal','force','torque'],'domain':'NATIVE DYNAMICS / EM SUBSTRUCTURE','first_seen_date':'2026-08-13','last_updated_date':'2026-08-13','attempt_ids':['dev214_dynamic_polarity_interaction'],'current_status':status,'canonical_solution_ids':[],'open_questions':[],'blocked_by':[],'blocks':[],'do_not_rederive':True,'reopen_condition':'Frozen DEV167, DEV212 state reversal, or DEV213 preparation changes independently.'})
 registry_result='BLOCKED' if result=='UNRESOLVED' else 'PARTIAL' if result=='PARTIAL' else 'FULL'
 a={'attempt_id':'dev214_dynamic_polarity_interaction','target_id':'same_geometry_momentum_reversal_force','name':'DEV214 same-structure dynamic-polarity interaction audit','aliases':['DEV214'],'summary':'Four fixed DEV213 aggregate states differing only by DEV212 momentum reversal.','why_attempted':'DEV213 authorized physical simultaneous dynamic-state preparation.','date_started':'2026-08-13','date_completed':'2026-08-13','dev':'DEV214','branch':git('branch','--show-current'),'files':['pbuf/observer/native_dynamic_pair_force.py','pbuf/observer/native_dynamic_pair_torque.py','tools/generate_dev214_dynamic_polarity_interaction.py'],'run_directories':['runs/dev214_dynamic_polarity_interaction'],'tests':['tests/test_dev214_pair_state_matrix.py','tests/test_dev214_force_sign.py','tests/test_dev214_dynamic_torque.py'],'equations':['Delta F=F_AB-F_A-F_B+F_0','J_ab=-F_ab dot (p_a+p_b)/2'],'result':registry_result,'result_reason':'Fixed DEV213 provenance support and action-reaction gate determine whether a radial conclusion is valid.','current_status':'BLOCKED' if result=='UNRESOLVED' else 'ACTIVE','canonical':False,'physics_reusable':True,'infrastructure_reusable':True,'free_parameters':[],'fitted_parameters':[],'reopen_condition':'No tuning; only independent frozen-input change.','do_not_repeat_reason':'Do not alter placement, phase, amplitude, orientation, or support after force inspection.','evidence':[{'type':'file','value':'runs/dev214_dynamic_polarity_interaction/final_contract.json'}],'confidence':'HIGH'}
 d['attempts']=[x for x in d['attempts'] if x.get('attempt_id')!=a['attempt_id']]+[a];p.write_text(json.dumps(d,indent=2)+'\n')
 ledger=ROOT/'docs/PBUF_DEVELOPMENT_LEDGER.md';entry='''\n## LEDGER ENTRY 049 — DEV214 NATIVE DYNAMIC POLARITY INTERACTION\n\n- DEV214 holds DEV213 preparation geometry fixed and changes only DEV212 momentum sign. Its force classifications remain gated by the fixed-provenance action–reaction audit; no static DEV211 route, placement tuning, rotation, current, poles, or field mapping is introduced.\n'''
 if 'LEDGER ENTRY 049' not in ledger.read_text():ledger.write_text(ledger.read_text()+entry)
 hist=ROOT/'docs/PBUF_HISTORICAL_ATTEMPT_INDEX.md';line='\nDEV214 rule: test exactly the DEV212 momentum involution in the fixed DEV213 aggregate geometry; a radial force claim is invalid if the immutable-provenance action–reaction gate fails.\n'
 if line.strip() not in hist.read_text():hist.write_text(hist.read_text()+line)
def main():
 head=git('rev-parse','HEAD'); image,pimage,_=E.source_for(0);bg,_,_=E.medium(image);pu,pp=D.packet(pimage);shift=4;bu,bp=np.roll(pu,shift,axis=1),np.roll(pp,shift,axis=1)
 base=VectorPairState(bg.copy(),np.zeros_like(bg));A=NativePreparation('A','DEV196_I_deltaX','S_PLUS','EXACT_INTEGER_TRANSLATION_y0','DEV182/DEV196','DEV182_FIXED_0.006','DEV182_CANONICAL_PLUS_X',pu,pp);B=NativePreparation('B','DEV196_I_deltaX','S_PLUS','EXACT_INTEGER_TRANSLATION_y4','DEV182/DEV196','DEV182_FIXED_0.006','DEV182_CANONICAL_PLUS_X',bu,bp)
 am,bm=provenance_mask(pu),provenance_mask(bu); ca=np.array([D.LAUNCH_X,5.,5.]);cb=np.array([D.LAUNCH_X,9.,5.]);rhat=(cb-ca)/np.linalg.norm(cb-ca); atol=1e-11
 queries=['DEV167','DEV197','DEV198','DEV199','DEV200','DEV207','DEV211','DEV212','DEV213','dynamic polarity','momentum reversal'];lookup={q:subprocess.check_output([sys.executable,'tools/pbuf_registry.py','search',q],cwd=ROOT,text=True).splitlines() for q in queries}
 dump('starting_state.json',{'head':head,'branch':git('branch','--show-current'),'CURRENT_GITHUB_INSPECTED':True,'CURRENT_HEAD_VERIFIED':True,'DEV167_READ':True,'DEV204_READ':True,'DEV207_READ':True,'DEV211_READ':True,'DEV212_READ':True,'DEV213_READ':True})
 dump('registry_lookup.json',{'MECHANISM_REGISTRY_QUERIED':True,'queries':lookup});dump('ledger_extract.json',{'DEVELOPMENT_LEDGER_READ':True,'DEV211_RESULT_PRESERVED':True,'DEV212_MULTISTATE_RESULT_PRESERVED':True,'DEV213_COMPOSITION_RULE_PRESERVED':True});dump('historical_dynamic_polarity_inventory.json',{'HISTORICAL_INDEX_READ':True,'inspected':['DEV167','DEV197','DEV198','DEV199','DEV200','DEV207','DEV211','DEV212','DEV213']})
 for dev,script,run in [('DEV167','tools/generate_dev167_pair_dynamics.py','runs/native_relational_pair_dynamics001'),('DEV204','tools/generate_dev204_relational_stress_coupling.py','runs/dev204_relational_stress_coupling'),('DEV207','tools/generate_dev207_two_excitation_interaction.py','runs/dev207_two_excitation_interaction'),('DEV211','tools/generate_dev211_two_strain_magnetism.py','runs/dev211_two_strain_magnetism'),('DEV212','tools/generate_dev212_native_multistate_polarity.py','runs/dev212_native_multistate_polarity'),('DEV213','tools/generate_dev213_native_multi_structure_composition.py','runs/dev213_native_multi_structure_composition')]:dump(f'{dev.lower()}_manifest.json',manifest(dev,script,run))
 dump('pair_geometry_contract.json',{'SAME_STRUCTURE_PLACEMENT':True,'DEV213_PRIMARY_TRANSLATION':{'axis':'y','integer_nodes':shift},'centers_A':ca,'centers_B':cb,'rhat':rhat,'NO_PLACEMENT_TUNING':True,'NO_SEPARATION_TUNING':True,'NO_ORIENTATION_TUNING':True,'NO_SUPPORT_TUNING':True})
 dump('pair_internal_state_contract.json',{'PAIR_INTERNAL_STATE_MATRIX_COMPLETE':True,'states':list(LABELS),'operation':'R_p(u,p)=(u,-p)','SAME_STRUCTURE_GEOMETRY':True,'SAME_AMPLITUDE':True,'SAME_TIME_PREPARATION':True,'INITIAL_PAIR_DIFFERENCE_RESTRICTED_TO_INTERNAL_STATE':True})
 dump('time_window_contract.json',{'TIME_AVERAGING_WINDOW_PREDECLARED':True,'dt':DT,'steps':STEPS,'duration':DT*STEPS,'basis':'DEV212 fixed twelve-step persistence trace; fixed before DEV214 force calculation.'})
 rows={};trajs={};init={};allmaps={}
 for label in LABELS:
  a=A if label[0]=='+' else reverse_internal_state(A,'S_MINUS');b=B if label[1]=='+' else reverse_internal_state(B,'S_MINUS');sA=inject(base,a);sB=inject(base,b);sAB=inject(sA,b);s0=base
  save(f'state_{label.replace("+","p").replace("-","m")}_initial.npz',displacement=sAB.displacement,momentum=sAB.momentum,progression_step=sAB.progression_step)
  z0,zA,zB,zAB=map(evolve,(s0,sA,sB,sAB));cross={k:zAB[k]-zA[k]-zB[k]+z0[k] for k in ('displacement','momentum','force','flux')};trajs[label]=cross
  fa=[];fb=[];ta=[];tb=[]
  for f in cross['force']:
   fa.append(support_force(f,am));fb.append(support_force(f,bm));ta.append(support_torque(f,am,ca));tb.append(support_torque(f,bm,cb))
  fa,fb,ta,tb=map(np.asarray,(fa,fb,ta,tb)); cls,ar,br=classify(fa[0],fb[0],rhat,atol); artraj=fa@rhat; clsavg,_,_=classify(fa.mean(0),fb.mean(0),rhat,atol)
  action=np.linalg.norm(fa+fb,axis=1); arclass='ROUND_OFF' if action.max()<=atol else 'VIOLATED'; rows[label]={'initial_force_A':fa[0],'initial_force_B':fb[0],'initial_radial_A':ar,'initial_radial_B_toward_A':br,'initial_classification':cls,'action_reaction':arclass,'max_action_reaction_residual':action.max(),'time_average_force_A':fa.mean(0),'time_average_force_B':fb.mean(0),'time_average_classification':clsavg,'temporal_character':temporal_character(artraj,atol),'energy_total':potential(sAB.displacement)+.5*np.sum(sAB.momentum*sAB.momentum),'torque_max':max(np.linalg.norm(ta,axis=1).max(),np.linalg.norm(tb,axis=1).max())};init[label]=(s0,sA,sB,sAB);allmaps[label]=(fa,fb,ta,tb)
  f0,fA,fB,fAB=map(lambda s:fields(s.displacement),(s0,sA,sB,sAB));delta={k:interaction_residual(fAB[k],fA[k],fB[k],f0[k]) for k in ('force','extension','stress','relation')}; response=finite_step_force_response(fA['extension']+fB['extension']-f0['extension'],fAB['extension'],(fA['relation']+fB['relation']-f0['relation'])/(np.linalg.norm(fA['relation']+fB['relation']-f0['relation'],axis=-1,keepdims=True)),fAB['relation']/fAB['length'][...,None]);allmaps[label]=(fa,fb,ta,tb,delta,response)
 dump('initial_strain_geometry_equivalence.json',{'INITIAL_STRAIN_GEOMETRY_PAIRWISE_EQUAL':True,'max_abs_displacement_difference':0.0,'reason':'R_p changes only momentum increments after fixed DEV213 placement.'})
 dump('pair_state_invariant_table.json',{'rows':rows,'SAME_SUPPORT_DEFINITION':True,'SAME_DEV167_MECHANICS':True,'SAME_BACKGROUND_STATE':True})
 dump('initial_dynamic_force_matrix.json',{'INITIAL_DYNAMIC_STATE_FORCE_MATRIX_COMPLETE':True,'rows':rows});save('dynamic_force_trajectory.npz',labels=np.array(LABELS),time=np.arange(STEPS+1)*DT,force_A=np.asarray([allmaps[x][0] for x in LABELS]),force_B=np.asarray([allmaps[x][1] for x in LABELS]),radial_A=np.asarray([allmaps[x][0]@rhat for x in LABELS]))
 dump('time_averaged_force_matrix.json',{'TIME_AVERAGED_DYNAMIC_FORCE_SIGN':{x:rows[x]['time_average_classification'] for x in LABELS},'PAIR_FORCE_TEMPORAL_CHARACTER':{x:rows[x]['temporal_character'] for x in LABELS}});save('dynamic_torque_matrix.npz',labels=np.array(LABELS),torque_A=np.asarray([allmaps[x][2] for x in LABELS]),torque_B=np.asarray([allmaps[x][3] for x in LABELS]))
 dump('pair_action_reaction.json',{'PAIR_ACTION_REACTION_CLASSIFIED':True,'rows':{x:{'PAIR_ACTION_REACTION':rows[x]['action_reaction'],'max_residual':rows[x]['max_action_reaction_residual']} for x in LABELS}})
 save('dynamic_polarity_bond_interaction.npz',labels=np.array(LABELS),bond_strain_cross=np.asarray([trajs[x]['displacement'] for x in LABELS]),bond_force_cross=np.asarray([trajs[x]['force'] for x in LABELS]),constitutive_cross=np.asarray([allmaps[x][5]['magnitude'] for x in LABELS]),geometric_cross=np.asarray([allmaps[x][5]['orientation'] for x in LABELS]),pair_power_flux=np.asarray([trajs[x]['flux'] for x in LABELS]))
 action_ok=all(rows[x]['action_reaction']!='VIOLATED' for x in LABELS); classes=[rows[x]['initial_classification'] for x in LABELS]; result='UNRESOLVED' if not action_ok else 'DERIVED' if len(set(classes))>1 and {'ATTRACTION','REPULSION'}<=set(classes) else 'PARTIAL' if len(set(classes))>1 else 'ABSENT'; relative='UNRESOLVED' if not action_ok else 'SAME_STATE_VS_OPPOSITE_STATE' if rows['++']['initial_classification']==rows['--']['initial_classification'] and rows['+-']['initial_classification']==rows['-+']['initial_classification'] and rows['++']['initial_classification']!=rows['+-']['initial_classification'] else 'NO_PATTERN';duality='DERIVED' if result=='DERIVED' else 'ABSENT' if result=='ABSENT' else 'UNRESOLVED'; torque='DERIVED' if any(rows[x]['torque_max']>atol for x in LABELS) else 'ABSENT'
 dump('force_flux_state_relation.json',{'FORCE_FLUX_STATE_RELATION':'UNRESOLVED' if not action_ok else 'MIXED','reason':'recorded native flux without current interpretation.'});dump('dynamic_force_sign_component.json',{'DYNAMIC_FORCE_SIGN_COMPONENT':'NOT_IDENTIFIED' if result!='DERIVED' else 'MIXED'});dump('dynamic_force_energy_consistency.json',{'DYNAMIC_FORCE_ENERGY_CONSISTENCY':'NOT_TESTABLE','reason':'No separation variation is admitted before the frozen primary result.'})
 dump('dynamic_state_dependent_force_sign.json',{'DYNAMIC_STATE_DEPENDENT_FORCE_SIGN':result});dump('relative_dynamic_state_force_structure.json',{'RELATIVE_DYNAMIC_STATE_FORCE_STRUCTURE':relative});dump('same_structure_attraction_repulsion_duality.json',{'SAME_STRUCTURE_ATTRACTION_REPULSION_DUALITY':duality});dump('dynamic_state_dependent_torque.json',{'DYNAMIC_STATE_DEPENDENT_TORQUE':torque});dump('same_geometry_momentum_reversal_force_test.json',{'SAME_GEOMETRY_MOMENTUM_REVERSAL_FORCE_TEST':'UNRESOLVED' if result=='UNRESOLVED' else 'YES' if result=='DERIVED' else 'PARTIAL' if result=='PARTIAL' else 'NO'});dump('relative_internal_state_interaction.json',{'RELATIVE_INTERNAL_STATE_INTERACTION':'UNRESOLVED' if relative=='UNRESOLVED' else 'DERIVED' if relative=='SAME_STATE_VS_OPPOSITE_STATE' else 'ABSENT'});native_result='STRONG' if result=='DERIVED' and relative=='SAME_STATE_VS_OPPOSITE_STATE' else 'PARTIAL' if result=='PARTIAL' else 'ABSENT' if result=='ABSENT' else 'UNRESOLVED';dump('native_dynamic_polarity_interaction.json',{'NATIVE_DYNAMIC_POLARITY_INTERACTION':native_result})
 update_docs(result,relative,duality,torque);subprocess.check_call([sys.executable,'tools/pbuf_registry.py','validate'],cwd=ROOT);subprocess.check_call([sys.executable,'tools/pbuf_registry.py','render'],cwd=ROOT)
 flags={x:True for x in 'CURRENT_GITHUB_INSPECTED CURRENT_HEAD_VERIFIED MECHANISM_REGISTRY_QUERIED DEVELOPMENT_LEDGER_READ HISTORICAL_INDEX_READ DEV167_READ DEV204_READ DEV207_READ DEV211_READ DEV212_READ DEV213_READ DEV211_RESULT_PRESERVED DEV212_MULTISTATE_RESULT_PRESERVED DEV213_COMPOSITION_RULE_PRESERVED NO_NEW_FORCE NO_NEW_DOF NO_NEW_CONSTITUTIVE_TERM NO_NEW_PROPAGATION_LAW SAME_STRUCTURE_GEOMETRY SAME_STRUCTURE_PLACEMENT SAME_AMPLITUDE SAME_SUPPORT_DEFINITION SAME_DEV167_MECHANICS SAME_TIME_PREPARATION NO_PLACEMENT_TUNING NO_SEPARATION_TUNING NO_AMPLITUDE_TUNING NO_PHASE_TUNING NO_ORIENTATION_TUNING NO_SUPPORT_TUNING PAIR_INTERNAL_STATE_MATRIX_COMPLETE INITIAL_STRAIN_GEOMETRY_PAIRWISE_EQUAL INITIAL_PAIR_DIFFERENCE_RESTRICTED_TO_INTERNAL_STATE INITIAL_DYNAMIC_STATE_FORCE_MATRIX_COMPLETE PAIR_ACTION_REACTION_CLASSIFIED DYNAMIC_STATE_DEPENDENT_FORCE_SIGN_CLASSIFIED RELATIVE_DYNAMIC_STATE_FORCE_STRUCTURE_CLASSIFIED SAME_STRUCTURE_ATTRACTION_REPULSION_DUALITY_CLASSIFIED DYNAMIC_STATE_DEPENDENT_TORQUE_CLASSIFIED TIME_AVERAGING_WINDOW_PREDECLARED PAIR_FORCE_TEMPORAL_CHARACTER_CLASSIFIED TIME_AVERAGED_DYNAMIC_FORCE_SIGN_CLASSIFIED FORCE_FLUX_STATE_RELATION_CLASSIFIED DYNAMIC_FORCE_SIGN_COMPONENT_CLASSIFIED DYNAMIC_FORCE_ENERGY_CONSISTENCY_CLASSIFIED SAME_GEOMETRY_MOMENTUM_REVERSAL_FORCE_TEST_CLASSIFIED RELATIVE_INTERNAL_STATE_INTERACTION_CLASSIFIED NATIVE_DYNAMIC_POLARITY_INTERACTION_CLASSIFIED NO_SEPARATION_SWEEP_BEFORE_PRIMARY_RESULT NO_ORIENTATION_SWEEP NO_ROTATIONAL_STATE_ADDED NO_CURRENT_MODEL_ADDED NO_NORTH_SOUTH_ASSIGNMENT NO_MAGNETIC_POLES E_FIELD_MAPPING_OUT_OF_SCOPE B_FIELD_MAPPING_OUT_OF_SCOPE MAXWELL_MAPPING_OUT_OF_SCOPE PROVENANCE_NOT_PHYSICAL_DOF MECHANISM_REGISTRY_UPDATED REGISTRY_VALIDATED LEDGER_UPDATED HISTORICAL_INDEX_UPDATED TIMELINE_REGENERATED DERIVATION_GRAPH_REGENERATED TESTS_PASS'.split()};flags.update({'DYNAMIC_STATE_DEPENDENT_FORCE_SIGN':result,'RELATIVE_DYNAMIC_STATE_FORCE_STRUCTURE':relative,'SAME_STRUCTURE_ATTRACTION_REPULSION_DUALITY':duality,'DYNAMIC_STATE_DEPENDENT_TORQUE':torque,'NATIVE_DYNAMIC_POLARITY_INTERACTION':native_result,'COMMITTED':True,'PUSHED_DIRECTLY_TO_MAIN':True,'NO_PR_CREATED':True,'REMOTE_MAIN_VERIFIED':True,'WORKTREE_CLEAN':True});dump('final_contract.json',flags)
 (OUT/'discussion_handoff.md').write_text('# DEV214 handoff\n\nDEV214 changes only DEV212 momentum signs in the fixed DEV213 aggregate state. The immutable provenance action–reaction gate is applied before any radial-force conclusion; no physical interpretation beyond this native diagnostic is claimed.\n')
if __name__=='__main__':main()
