"""Canonical equations executed by the current native system."""
from __future__ import annotations

def equations():
    return [
      {"equation_id":"E01","name":"A8 N6 mean","latex":r"\bar u_a=\frac16\sum_{b\in N_6(a)}u_b","code_location":"pbuf/models/a8_state.py:40-77","variables":["u"],"status":"ESTABLISHED","first_dev":"historical A8","last_verified_dev":154,"assumptions":["unit Cartesian N6 grid"]},
      {"equation_id":"E02","name":"fast update","latex":r"u_f'=clip[u_f+0.03((\bar u_f-u_f)+0.5(u_s-u_f)),-5,5]","code_location":"pbuf/models/a8_state.py:101-112","variables":["u_fast","u_slow"],"status":"ESTABLISHED","first_dev":"historical A8","last_verified_dev":154,"assumptions":["160 iterations"]},
      {"equation_id":"E03","name":"slow update","latex":r"u_s'=clip[u_s+0.003((\bar u_s-u_s)+0.5(u_f-u_s)),-5,5]","code_location":"pbuf/models/a8_state.py:101-112","variables":["u_fast","u_slow"],"status":"ESTABLISHED","first_dev":"historical A8","last_verified_dev":154,"assumptions":["simultaneous increments from old fields"]},
      {"equation_id":"E04","name":"combined loading state","latex":r"c_{state}=(u_s+u_f)/2","code_location":"pbuf/models/a8_state.py:89-114","variables":["c_state","u_fast","u_slow"],"status":"ESTABLISHED","first_dev":"historical A8","last_verified_dev":154,"assumptions":[]},
      {"equation_id":"E05","name":"bond strain","latex":r"\epsilon_{ab}=(u_b-u_a)/\Delta x","code_location":"pbuf/labs/foundation/c_state_bounded_strain_bridge001.py:128-133","variables":["epsilon","u"],"status":"ESTABLISHED","first_dev":143,"last_verified_dev":154,"assumptions":["axis-aligned positive bonds"]},
      {"equation_id":"E06","name":"bounded energy","latex":r"W=-\frac{K\epsilon_{max}^2}{2}\ln(1-\epsilon^2/\epsilon_{max}^2)","code_location":"pbuf/wl/native_incremental_elastic_energy.py:18-26","variables":["W","epsilon","K"],"status":"ESTABLISHED","first_dev":143,"last_verified_dev":154,"assumptions":["|epsilon|<epsilon_max"]},
      {"equation_id":"E07","name":"bounded stress","latex":r"\sigma=K\epsilon/(1-\epsilon^2/\epsilon_{max}^2)","code_location":"pbuf/wl/native_incremental_elastic_energy.py:29-33","variables":["sigma","epsilon","K"],"status":"ESTABLISHED","first_dev":143,"last_verified_dev":154,"assumptions":["|epsilon|<epsilon_max"]},
      {"equation_id":"E08","name":"tangent stiffness","latex":r"K_{tan}=K(1+q)/(1-q)^2,\ q=(\epsilon/\epsilon_{max})^2","code_location":"pbuf/wl/native_incremental_elastic_energy.py:36-41","variables":["K_tangent","epsilon","K"],"status":"ESTABLISHED","first_dev":143,"last_verified_dev":154,"assumptions":["equals W''"]},
      {"equation_id":"E09","name":"nonlinear equilibrium","latex":r"A(u)_a=\Delta x^{-2}\sum_{b\in N_6(a)}K\frac{u_a-u_b}{1-\epsilon_{ab}^2/\epsilon_{max}^2}=c_{state,a}","code_location":"pbuf/labs/foundation/c_state_bounded_strain_bridge001.py:136-220","variables":["u","c_state","epsilon"],"status":"ESTABLISHED","first_dev":145,"last_verified_dev":154,"assumptions":["zero Dirichlet accumulation boundary","Picard+CG"]},
      {"equation_id":"E10","name":"packet initialization","latex":r"X_a=A\exp[-\tfrac12((a-a_0)/w)^2]\,p/\|p\|","code_location":"pbuf/excitation/native_excitation_state.py:24-32","variables":["X1","X2"],"status":"ESTABLISHED","first_dev":148,"last_verified_dev":154,"assumptions":["node state","no carrier phase"]},
      {"equation_id":"E11","name":"free progression","latex":r"X_a^{n+1}=X_{(a-d)\bmod N}^{n},\ d\in\{-1,+1\}","code_location":"pbuf/excitation/native_excitation_transfer.py:24-37","variables":["X1","X2"],"status":"ESTABLISHED","first_dev":148,"last_verified_dev":154,"assumptions":["1D periodic support","no branching"]},
      {"equation_id":"E12","name":"frame-aware progression","latex":r"X_j^{n+1}=R_{ij}X_i^n,\ j=(i+1)\bmod N","code_location":"pbuf/foundation/native_neighbor_mixed_state.py:17-33","variables":["X1","X2","R_ij"],"status":"ESTABLISHED","first_dev":152,"last_verified_dev":154,"assumptions":["one outgoing neighbor"]},
      {"equation_id":"E13","name":"orthogonal frame map","latex":r"R_{ij}=UV^T,\quad B_{ij}=E_{\perp,j}E_{\perp,i}^T=U\Sigma V^T","code_location":"pbuf/foundation/native_neighbor_state.py:48-52","variables":["R_ij"],"status":"ESTABLISHED","first_dev":152,"last_verified_dev":154,"assumptions":["nearest orthogonal polar factor"]},
      {"equation_id":"E14","name":"excitation norm","latex":r"N_X=\sum_a(X_{1,a}^2+X_{2,a}^2)","code_location":"pbuf/excitation/native_excitation_invariants.py:7-15","variables":["N_X","X1","X2"],"status":"ESTABLISHED","first_dev":148,"last_verified_dev":154,"assumptions":[]},
      {"equation_id":"E15","name":"excitation density","latex":r"\rho_{X,a}=X_{1,a}^2+X_{2,a}^2","code_location":"pbuf/foundation/native_neighbor_mixed_observer.py:6-9","variables":["rho_X","X1","X2"],"status":"DERIVED","first_dev":149,"last_verified_dev":154,"assumptions":["diagnostic, not probability"]},
      {"equation_id":"E16","name":"packet centroid","latex":r"\bar r_n=\sum_a a\rho_{X,a}^{(n)}/\sum_a\rho_{X,a}^{(n)}","code_location":"pbuf/foundation/native_neighbor_mixed_observer.py:6-9","variables":["rbar","rho_X"],"status":"DERIVED","first_dev":149,"last_verified_dev":154,"assumptions":["linear centroid; packet must not cross periodic seam"]},
      {"equation_id":"E17","name":"FFT wavelength","latex":r"m_n=argmax_{m\ge1}|FFT(X_1)_m|^2,\ \lambda_n=N/max(m_n,1)","code_location":"pbuf/foundation/native_neighbor_mixed_observer.py:10-12","variables":["lambda_n","X1"],"status":"DIAGNOSTIC","first_dev":149,"last_verified_dev":154,"assumptions":["first transverse component only"]},
      {"equation_id":"E18","name":"unified state","latex":r"\mathcal S=(L,X_1,X_2)","code_location":"pbuf/foundation/native_neighbor_state.py:54-70","variables":["L","X1","X2"],"status":"REPRESENTATIONAL","first_dev":151,"last_verified_dev":154,"assumptions":["L is audit longitudinal array, not c_state primitive"]},
    ]
