"""Structured D01-D30 inventory reconstructed from executable source."""
from __future__ import annotations

NAMES=["native spatial topology","node/link representation","static loading input","local medium loading/state","neighbor equilibrium","bounded strain","accumulated deformation response","dynamic excitation state","excitation initialization","excitation neighbor transfer","two transverse modes","excitation norm","spatial wavelength","native k","interference","polarization","handedness","rank-3 unified neighbor representation","local frames","frame transport","mixed loaded+excited state","currently absent cross-effect","excitation density","packet evolution","packet centroid","native trajectory","native direction","native curvature","historical geometric trajectory machinery","weak-lensing propagation machinery"]
STATUS=["ESTABLISHED","REPRESENTATIONAL","ESTABLISHED","ESTABLISHED","ESTABLISHED","ESTABLISHED","ESTABLISHED","ESTABLISHED","ESTABLISHED","ESTABLISHED","ESTABLISHED","ESTABLISHED","DIAGNOSTIC","UNRESOLVED","ESTABLISHED","ESTABLISHED","ESTABLISHED","REPRESENTATIONAL","REPRESENTATIONAL","ESTABLISHED","REPRESENTATIONAL","UNRESOLVED","DERIVED","ESTABLISHED","DERIVED","DIAGNOSTIC","UNRESOLVED","UNRESOLVED","HISTORICAL","ESTABLISHED"]
PURPOSE=["Provide Cartesian nearest-neighbor support","Distinguish node arrays from audit link state","Turn rho into fast/slow initialization","Store fast, slow, and combined scalar response","Solve discrete nonlinear force balance","Bound bond deformation constitutively","Produce long-range u from local c_state","Store two signed components per site","Create a localized Gaussian vector packet","Move all state to one periodic neighbor","Represent independent transverse coordinates","Audit the quadratic invariant","Estimate spatial periodicity from X1","Record a wave-number quantity","Demonstrate signed linear superposition","Select a normalized two-vector orientation","Represent phase-quadrature sign classes in audit packets","Place L and X in one rank-3 record","Construct deterministic link triads","Map transverse coordinates between frames","Run L and X together without backreaction","Record failure to derive C(L)","Measure packet morphology","Apply permutation and optional frame map","Locate density-weighted packet center","Store centroid sequence as diagnostic path","Would derive motion direction","Would derive turning of direction","Analyze pre-excitation geometric path state","Propagate geometric optical rays/bundles"]
MATH=[r"N_6=\{\pm\hat x,\pm\hat y,\pm\hat z\}",r"u,c: grid scalars; \mathcal S_i=(L_i,X_{1i},X_{2i})",r"u_s^0=u_f^0=\rho;\ c=(u_s+u_f)/2",r"c_{state}=(u_s+u_f)/2",r"A(u)=c_{state}",r"\epsilon=(u_b-u_a)/\Delta x;\ W,\sigma,K_{tan}\text{ as E06--E08}",r"u=A^{-1}_{bounded}(c_{state})",r"X\in\mathbb R^{N\times2}",r"X_a=Ae^{-((a-a_0)/w)^2/2}\hat p",r"X_a^{n+1}=X_{(a-d)\bmod N}^n\text{ or }R X",r"X=(X_1,X_2)",r"N_X=\sum_a\|X_a\|^2",r"\lambda=N/argmax_{m\ge1}|FFT(X_1)_m|^2",r"NO\ IMPLEMENTED\ k_n\ IN\ CANONICAL\ OBSERVER",r"P(a+b)=P(a)+P(b)",r"\hat p=p/\|p\|;\ X\mapsto QX",r"X_2=\pm\,env\sin(ka)\text{ in Dev152 fixtures}",r"\mathcal S=(L,X_1,X_2)",r"E=(e_\parallel,e_1,e_2)",r"R=UV^T,\ R^TR=I",r"L^{n+1}=L^n;\ X_j^{n+1}=R_{ij}X_i^n",r"\mathcal C_{ij}=I\text{ is the established null}",r"\rho_X=X_1^2+X_2^2",r"X^{n+1}=P_R X^n",r"\bar r=\sum a\rho_a/\sum\rho_a",r"\Gamma=(\bar r_0,\ldots,\bar r_N)",r"NO\ EXCITATION\ DIRECTION\ ESTIMATOR",r"NO\ EXCITATION\ CURVATURE\ ESTIMATOR",r"\kappa=\Delta\theta/\Delta s\text{ for geometric paths}",r"r_{n+1}=G(r_n,d_n,medium)\text{ in separate WL stack}"]
CODE=["pbuf/core/conventions.py:177-191; pbuf/models/a8_state.py:40-77","pbuf/excitation/native_excitation_state.py:34-47; pbuf/foundation/native_neighbor_state.py:54-70","pbuf/models/a8_state.py:117-136","pbuf/models/a8_state.py:80-114","pbuf/labs/foundation/c_state_bounded_strain_bridge001.py:128-220","pbuf/wl/native_incremental_elastic_energy.py:18-41","pbuf/labs/foundation/c_state_bounded_strain_bridge001.py:223-230","pbuf/excitation/native_excitation_state.py:34-47","pbuf/excitation/native_excitation_state.py:24-32","pbuf/excitation/native_excitation_transfer.py:24-37; pbuf/foundation/native_neighbor_mixed_state.py:17-33","pbuf/excitation/native_excitation_invariants.py:24-26","pbuf/excitation/native_excitation_invariants.py:7-15","pbuf/foundation/native_neighbor_mixed_observer.py:10-12","NO_CANONICAL_SYMBOL / no current implementation","pbuf/excitation/native_excitation_invariants.py:16-19","pbuf/excitation/native_excitation_state.py:24-32","pbuf/foundation/native_neighbor_loaded_excitation.py:10-21","pbuf/foundation/native_neighbor_state.py:54-70","pbuf/foundation/native_neighbor_state.py:26-32","pbuf/foundation/native_neighbor_state.py:48-52","pbuf/foundation/native_neighbor_mixed_state.py:17-33","pbuf/foundation/native_loaded_link_response.py:52-64","pbuf/foundation/native_neighbor_mixed_observer.py:6-9","pbuf/foundation/native_neighbor_mixed_state.py:17-33","pbuf/foundation/native_neighbor_mixed_observer.py:6-9","pbuf/foundation/native_neighbor_mixed_observer.py:6-9","NO CURRENT EXCITATION IMPLEMENTATION","NO CURRENT EXCITATION IMPLEMENTATION","pbuf/wl/trajectory_state.py:100-148","pbuf/wl/propagation.py; pbuf/wl/trajectory_state.py"]

def domains():
    out=[]
    for i,name in enumerate(NAMES):
      absent=i in (13,26,27)
      out.append({"id":f"D{i+1:02d}","Name":name,"Status":STATUS[i],"Purpose":PURPOSE[i],
       "Physical meaning":"Implementation-level native quantity or diagnostic; not an identification with established external physics.",
       "Stored variables":"none" if absent else ("X arrays/history" if 7<=i<=27 else "scalar grid fields or geometric records"),
       "Units/dimensional status":"native dimensionless/index units; absolute physical closure unresolved",
       "Mathematical definition":MATH[i],"Update/evolution equation":MATH[i] if not absent else "None implemented",
       "Inputs":"upstream quantities listed in dependency graph","Outputs":PURPOSE[i],"Code implementation":CODE[i],
       "Upstream dependencies":"See native_dependency_graph.json","Downstream consumers":"See native_dependency_graph.json",
       "Conservation/invariants":"Quadratic X norm for dynamic permutation/orthogonal transport; static solver residual for equilibrium",
       "Known controls/tests":f"Dev145-153 contracts and Dev154 source reconstruction; domain {i+1}",
       "What it DOES establish":PURPOSE[i],"What it DOES NOT establish":"New cross-coupling, absolute units, or identification with gravity/EM/QM",
       "PLAIN_LANGUAGE":("The code does not currently calculate this quantity for excitation packets." if absent else PURPOSE[i]+" using the concrete code path cited above."),
       "CARPET_FIBER_ANALOGY":"A grid bond may be pictured as a fiber connection; this is analogy only, not an ontological claim."})
    return out

def variables():
    rows=[("c","c_state","float64 ndarray","(Nz,Ny,Nx)","grid","static","scalar","native","unresolved","mean fast/slow state"),("u","field","float64 ndarray","(N,N,N)","grid","static","scalar","native","unresolved","accumulated equilibrium field"),("epsilon","bond_strains","float64 ndarrays","three staggered grids","link","static","scalar","derived","dimensionless","finite difference of u"),("sigma","bounded_strain_stress","float64 ndarray","bond grids","link","static","scalar","derived","K units","constitutive stress"),("W","bounded_strain_energy","float64 ndarray","bond grids","link","static","scalar","derived","K units","constitutive energy density"),("K","K0","float","scalar","global","static","scalar","native","normalization","1.0"),("K_tan","bounded_strain_tangent","float64 ndarray","bond grids","link","static","scalar","derived","K units","stress derivative"),("L","longitudinal","float64 ndarray","(N,)","link audit","static","scalar","representational","dimensionless","Dev151 profile, not c_state"),("X_1","values[...,0]","float64 ndarray","(N,)","node/link audit","dynamic","scalar component","native","dimensionless","first transverse component"),("X_2","values[...,1]","float64 ndarray","(N,)","node/link audit","dynamic","scalar component","native","dimensionless","second transverse component"),("R_ij","frame_overlap","float64 ndarray","(2,2)","link pair","dynamic","tensor","derived","dimensionless","orthogonal frame map"),("theta_ij","rotation_angle","float","scalar","link pair","diagnostic","scalar","derived","radian","angle extracted from R"),("rho_X","amp","float64 ndarray","(steps,N)","node","diagnostic","scalar","derived","X squared","density observable"),("r_a","idx","integer ndarray","(N,)","node","static","vector/index","representational","index units","site coordinate"),("rbar","centroid","float64 ndarray","(steps,)","global","diagnostic","scalar","derived","index units","density weighted mean"),("NO_CANONICAL_SYMBOL","direction","absent","absent","global","diagnostic","vector","unresolved","unresolved","not implemented for excitation"),("NO_CANONICAL_SYMBOL","curvature","absent","absent","global","diagnostic","scalar","unresolved","unresolved","not implemented for excitation"),("lambda_n","wavelength","float64 ndarray","(steps,)","global","diagnostic","scalar","derived","site units","FFT-bin wavelength"),("NO_CANONICAL_SYMBOL","k_n","absent","absent","global","diagnostic","scalar","unresolved","unresolved","not emitted by canonical observer"),("N_X","excitation_norm","float64 ndarray","(steps,)","global","diagnostic","scalar","derived","X squared","global quadratic norm")]
    keys=["symbol","code_name","data_type","shape/rank","location","static/dynamic","scalar/vector/tensor","native/derived/diagnostic","dimensionless/dimensional/unresolved","definition"]
    return [dict(zip(keys,r)) for r in rows]
